### ISSUE TITLE
RStan Compilation ERROR, function(s)/method(s) not created!

### ISSUE THREAD

**Issue by TL000003** [stan-dev/rstan#1004]
#### Summary:
RStan can't fit the model.

## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 
# predict voting leave with a simple logistic regression using STAN
# drop people who don't intend to vote in the referendum
dt =dt[which(dt$brexit_V!="novote"),]
# synthesize past turnout in a single variable with past vote
dt$V_pastGE = 
ifelse(is.na(dt$V_pastGE) & dt$T_pastGE==0,
       "novote",
       as.character(unlist(dt$V_pastGE)))
dt$V_pastGE = as.factor(dt$V_pastGE)
# make outcome dichotomous
dt$leave = ifelse(dt$brexit_V=="leave",1,0)
# make dt only with variables we need
dt.sub = dt[,c("leave",
               "V_pastGE",
               "gender","age","region","ethnicity","edu","tenure",
               "UKIP15","c11PopulationDensity","c11PassportEU","c11Christian",
               "c11Muslim","c11IndustryAgriculture","c11Degree","c11Retired",
               "c11EthnicityAsian","c11EthnicityBlack","c11Employed",
               "c11NSSECLongtermUnemployed","c11Deprived4")]
# focus on complete cases
dt.sub.complete = dt.sub[complete.cases(dt.sub),]
# one-hot factors to feed it to STAN
X = one_hot(dt = dt.sub.complete,dropCols = T,dropUnusedLevels = T)
# drop one level for each variable to put in the baseline and have dentifiable coefficients
# also drop leave from the covariates - it's the outcome
X = X[,!c("leave",
          "V_pastGE_conservative","gender_Male","region_London","ethnicity_White","edu_Level 4/5","tenure_Owns")]
# drop covariates which have no variance (all)
X = X[,!apply(X,2,function(x){sd(x)<0.1}),with=F]
# scale the covariates - makes effects comparable and speeds up estimation
X.raw = X
X = scale(X)
X.center =  attributes(X)$`scaled:center` 
X.sd = attributes(X)$`scaled:scale` 
X = as.matrix(cbind(intercept=1,X))

# leave 15% of the dataset for test 
train_id = sample(1:dim(X)[1],size = 0.85*dim(X)[1])

# put data together a list to give 
data_list = list(y = dt.sub.complete$leave[train_id],
                 n = dim(X[train_id,])[1],
                 X = X[train_id,],
                 p = dim(X[train_id,])[2])

## define model 
model_logit = "data{
   int<lower = 1> n; // total number of observations
   int<lower = 1> p; // number of covariates in design matrix
int<lower = 0> y[n]; // vector of outcomes
     matrix[n, p] X; // design matrix
}

parameters{
       vector[p] beta;
}

transformed parameters{
vector[n] mu;
vector<lower = 0,upper = 1>[n] pi;

mu =  X * beta; 
pi = inv_logit(mu);
}

model{
// likelihood
y ~ bernoulli(pi);
}
"

# # # parameters to monitor
pars_logit = c('beta','pi')

library(rstan)
library(StanHeaders)
library(ggplot2)
#install.packages("benchmarkme")
#library(benchmarkme)
#get_cpu()$no_of_cores
# # # fit the model 
fit_object <-stan(model_code = model_logit, 
                  data = data_list, 
                  iter = 200,
                  warmup = 100,
                  thin = 4,
                  cores = 4,
                  chains = 4,
                #  control = list(max_treedepth = 10, adapt_delta = 0.8),
                  verbose = T)

#### Current Output:
Compilation ERROR, function(s)/method(s) not created!
Error in compileCode(f, code, language = language, verbose = verbose) : 
  D:\Program Files (x86)\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file1cbc28a5354e.o:file1cbc28a5354e.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'D:\Program Files (x86)\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file1cbc28a5354e.o:file1cbc28a5354e.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'D:\Program Files (x86)\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file1cbc28a5354e.o:file1cbc28a5354e.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x3a): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'D:\Program Files (x86)\rtools42\x86_64-w64-mingw32.static.pos

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
2.21.5’

#### R Version:
"R version 4.2.0 

#### Operating System:
Win 10

**Comment by rajesh06** [comment]
I get the same error when running: 
`example(stan_model, package = "rstan", run.dontrun = TRUE)`

Any ideas?

**Comment by andrjohns** [comment]
See the [Getting Started guide](https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows#rstan-compatibility)

**Comment by rajesh06** [comment]
RStudio and R are not installing the preview version of Rstan (2.26). Here is my output.

`install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
Installing package into ‘C:/Users/rajesh.sahasrabuddhe/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mc-stan.org/r-packages/src/contrib:
  cannot open URL 'https://mc-stan.org/r-packages/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
  cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mc-stan.org/r-packages/bin/windows/contrib/4.3:
  cannot open URL 'https://mc-stan.org/r-packages/bin/windows/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://cloud.r-project.org/bin/windows/contrib/4.3:
  cannot open URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES'
Warning message:
package ‘rstan’ is not available for this version of R`

Are others having this issue?
