### ISSUE TITLE
Cannot sample [1] "Error in sampler$call_sampler(args_list[[i]]) : "                       [2] "  Must use algorithm=\"Fixed_param\" for model that has no parameters." [1] "error occurred during calling the sampler; sampling not done"

### ISSUE THREAD

**Issue by navgo98** [stan-dev/rstan#1014]
#### Summary: Cannot sample for models (possibly the model is wrong?)
Please provide a short summary (no more than a sentence or two).

#### Description: I tried to fit an SEEIIR model in R but it is not working for me. I followed https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html   . But their codes were not working as well,  the error is
 SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
[1] "Error in sampler$call_sampler(args_list[[i]]) : "                      
[2] "  Must use algorithm=\"Fixed_param\" for model that has no parameters."
[1] "error occurred during calling the sampler; sampling not done"
Describe the issue as clearly as possible.

#### Reproducible Steps: Attached file of Model specifications (seeiir.stan) and dataset (covid_ cases.cvs)
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output: SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
[1] "Error in sampler$call_sampler(args_list[[i]]) : "                      
[2] "  Must use algorithm=\"Fixed_param\" for model that has no parameters."
[1] "error occurred during calling the sampler; sampling not done"
If applicable, any relevant output from RStan.

#### Expected Output: Working...
If applicable, the output you expected from RStan.
[seeiir_text_stan.txt](https://github.com/stan-dev/rstan/files/8735613/seeiir_text_stan.txt)

#### RStan Version:  latest versio
[seeiir_R_code.txt](https://github.com/stan-dev/rstan/files/8735630/seeiir_R_code.txt)
n "2.26.1"
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version: 4.2.0
The version of R you are running (e.g., from `R.version.string`)

#### Operating System: Windows [10]([url]([url]([url](url))))
Your operating system (e.g., OS X 10.11.3)

**Comment by andrjohns** [comment]
Closing this issue for now, feel free to reopen if there's still a prolem
