### ISSUE TITLE
Configuring C++ Toolchain for Ubuntu 20.04.02 Fails

### ISSUE THREAD

**Issue by eweiss99** [stan-dev/rstan#1015]
#### Summary:
Trying to add repositories to configure toolchain from Ubuntu terminal fails.

#### Reproducible Steps:
**sudo add-apt-repository ppa:marutter/rrutter4.0**
_Cannot add PPA: 'ppa:~marutter/ubuntu/rrutter4.0'.
ERROR: '~marutter' user or team does not exist._

**sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+**
_Cannot add PPA: 'ppa:~c2d4u.team/ubuntu/c2d4u4.0+'.
ERROR: '~c2d4u.team' user or team does not exist._

As a result, cannot install RStan

**Comment by SteveBronder** [comment]
These look like issues with rrutter's ubuntu repository add on and not with rstan
