### ISSUE TITLE
rstan without v8 dependency

### ISSUE THREAD

**Issue by barracuda156** [stan-dev/rstan#1019]
Is there a current version without a dependency on `v8`? 
@andrjohns had a fork earlier: https://discourse.mc-stan.org/t/override-dependency-on-v8-or-make-v8-build-on-powerpc-mac-r-4-1-2/25432/5 (which still failed to build the last time I tried).

I want to fix `rstan` for MacOS PPC. The major issue, as of now, is a lack of Darwin PPC support in `v8`. There is some version of `v8` for PPC, perhaps dated, but it is for AIX – rewriting it for Darwin may be feasible, but far from trivial: https://github.com/ibmruntimes/v8ppc

P. S. For the context, we have the latest `cmake`, `gcc11` with `gfortran` and the latest `R` working on MacOS PPC. Many `R` packages build, some fail. There is no `qt5` for PPC, so RStudio does not build, but I have fixed a reasonable recent version of R GUI app.

**Comment by andrjohns** [comment]
The V8 dependency can now be replaced by the `QuickJSR` package, a PR is currently in progress: #1058

**Comment by barracuda156** [comment]
> QuickJSR

@andrjohns Thank you very much, sounds great. I will try building `QuickJSR` now.

By the way, we have `rstan` in Macports now, and it builds and works on MacOS PowerPC!
https://ports.macports.org/port/R-rstan
