### ISSUE TITLE
Cannot find g++ with RTools on Windows 10

### ISSUE THREAD

**Issue by JuleWolf36** [stan-dev/rstan#1021]
#### Summary:
I am trying to run a brm ordinal regression but fail to use rstan

#### Description:
I am rather new to R so I am sorry if my issue is basic. I have tried to check other issues here but could not solve the problem.

I ran a brm model which resulted in an error.
I then discovered the following help page and went through all of the steps thus **configuring C toolchain** : https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows
However, when I try to run an example model as suggested (example(stan_model, package = "rstan", run.dontrun = TRUE)) I receive the following errors:

#### Current Output:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  /bin/sh: line 1: C:/rtools42/usr/mingw_64/bin/g++: No such file or directorymake: *** [C:/PROGRA~1/R/R-42~1.1/etc/x64/Makeconf:260: file378cdb016a3.o] Error 127
Error in sink(type = "output") : invalid connection

#### Expected Output:
Running the brm model

#### RStan Version:
2.21.5

#### R Version:
R 4.2.1.
Using RStudio

#### Operating System:
Win10

Unfortunately, I am stuck here not knowing what else to try. Would be super happy about some hints

**Comment by andrjohns** [comment]
You've followed the instructions for R3.6 instead of R4.2, which has set your R installation to looking for the installed compilers in the wrong place. Try the instructions for removing old RStan configurations, uninstall all versions of RTools, then reinstall RTools42

**Comment by JuleWolf36** [comment]
Thank you so much. Might have been an easy issue for you but for me it was of great help!
