### ISSUE TITLE
Rstan crashes R session on load

### ISSUE THREAD

**Issue by afstam** [stan-dev/rstan#1022]
#### Summary:
My R session immediately hard crashes after running `library(rstan)`.

#### Description:
I have just installed rstan, but my R session hard crashes when I load it. I've tried downloading rstan from CRAN, from the location mentioned here in the readme, and as source. The result is always the same: hard crash on load.

#### RStan Version:
2.26.13

#### R Version:
R version 4.2.1 (2022-06-23 ucrt)

#### Operating System:
Windows 11

**Comment by PYB-SU** [comment]
Same here with Windows 11, R 4.2.1 (patched) ; rstan 2.26.13, StanHeaders 2.26.13 and Rtools 4.2

I had it working again by reinstalling some libraries required by rstan. I don't know which did the trick.

reinstalled : 
install.packages("RcppParallel")
install.packages("RcppEigen")
install.packages("inline")
install.packages("Rcpp")
install.packages("pkgbuild")
install.packages("BH")

**Comment by tspeidel-ey** [comment]
Same here with:

**RStudio**: 2022.07.2 Build 576  
**R**: 4.2.1  
**OS**: Windows 10 Enterprise v 21H2  
**rtools**: C:\rtools42  
**rstan**: 2.21.1 and 2.26.x  

as soon as I load `library(rstan)` R hard crashes.

**Comment by tspeidel-suncor** [comment]
> 

This did it for me. Thanks for sharing.

**Comment by tspeidel-ey** [comment]
> Same here with Windows 11, R 4.2.1 (patched) ; rstan 2.26.13, StanHeaders 2.26.13 and Rtools 4.2
> 
> I had it working again by reinstalling some libraries required by rstan. I don't know which did the trick.
> 
> reinstalled : install.packages("RcppParallel") install.packages("RcppEigen") install.packages("inline") install.packages("Rcpp") install.packages("pkgbuild") install.packages("BH")

This did it for me. Thanks for sharing!
