### ISSUE TITLE
Declaring multiple variables at once is not supported at rstan2.26?

### ISSUE THREAD

**Issue by perlatex** [stan-dev/rstan#1028]
Hi ,

I follow reference-manual [declaring-multiple-variables-at-once](https://mc-stan.org/docs/reference-manual/declaring-multiple-variables-at-once.html)

it works
```
parameters {
  real x; 
  real y;
}
model {
  x ~ normal(0, 1);
  y ~ exponential(1);

}
```

but, it does not work
```
parameters {
  real x, y; 
}
model {
  x ~ normal(0, 1);
  y ~ exponential(1);

}
```

error information
```
Syntax error in 'string', line 2, column 8 to column 9, parsing error:

";" is expected after a top-level variable declaration.
```

#### RStan Version:
> packageVersion("rstan")
[1] ‘2.26.13’

#### R Version:
> R.version.string
[1] "R version 4.2.0 (2022-04-22 ucrt)"

#### Operating System:
windows 11

**Comment by bob-carpenter** [comment]
This issue will be fixed when RStan catches up to Stan.  Until then, there's really nothing we can do, so I'm going to close this issue.

The problem you're facing is that Rstan 2.26 is behind Stan at 2.30.  We added multiple declarations after 2.26, but our reference manual doesn't indicate that:

* https://mc-stan.org/docs/reference-manual/declaring-multiple-variables-at-once.html

An even bigger problem going forward is that we're going to start removing deprecated syntax from Stan like our old array declaration style, which will exacerbate the incompatibilities.

As of now, the only way to get an up-to-date version of Stan through R is with [cmdstanr](https://mc-stan.org/cmdstanr/).  It has very limited functionality compared to RStan, but it can fit models and you can extract draws (in a more limited unstructured way) and summarize fits.  And it keeps up with improvements to the Stan language and math library.

**Comment by WardBrian** [comment]
A reference manual for 2.26 is still available at https://mc-stan.org/docs/2_26/reference-manual/index.html, if you're interested in documentation from that version.
