### ISSUE TITLE
rstan installation

### ISSUE THREAD

**Issue by johnsonrd58** [stan-dev/rstan#1029]
#### Summary:
i cant seem to compile rstan with either r 4.2.2 or 4.2.2 and am getting a compellation error.  I have rtools 4.2 (4.2.0.1) installed

#### Description:
Compilation ERROR, function(s)/method(s) not created!
Error in compileCode(f, code, language = language, verbose = verbose) : 
  C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file63436163ef8.o:file63436163ef8.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file63436163ef8.o:file63436163ef8.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file63436163ef8.o:file63436163ef8.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x3a): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file63436163ef8.o:file63436163ef8.cpp:(.text$_ZN3tbb10interface623task_

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by andrjohns** [comment]
See the [Getting Started Guide](https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows#r-42)
