### ISSUE TITLE
Is the R package V8 still a denpendency?

### ISSUE THREAD

**Issue by waynelapierre** [stan-dev/rstan#1030]
When I installed rstan on Fedora Linux a while ago, I had to install v8-devel. According to rstan's CRAN page, the R package V8 seems no longer a dependency. 
I would like some clarification on this issue because I need to install rstan on another computer. 
https://cran.r-project.org/web/packages/rstan/index.html

**Comment by andrjohns** [comment]
The V8 package is temporarily no longer a dependency for the CRAN version of rstan, but it will be for the next version

**Comment by waynelapierre** [comment]
V8 is a huge dependency. If rstan can work without it, why add it back?

**Comment by andrjohns** [comment]
Because the next version of rstan can't work without it. Since Stan 2.21, the Stan-to-C++ parser was rewritten in Ocaml ([repo here](github.com/stan-dev/stanc3/)). R does not (currently) have the capacity to compile Ocaml during package installation, so the current workaround is to transpile the Ocaml code to javascript, which is then run using the V8 engine.

Not an ideal solution by any means, but it's the best we have at the moment

**Comment by waynelapierre** [comment]
Now I understand it. By the way, why not use C++ for the parser? OCaml seems a really weird choice.

**Comment by bob-carpenter** [comment]
@waynelapierre:  OCaml is the standard language for building compilers in programming language classes.  Our original parser was in C++ based on Boost's Spirit Qi package, but it was so clunky and complicated doing this in C++ with lazy evaluation and sequential accessor interfaces that we gave up and rebuilt the whole thing in OCaml a few years ago.

**Comment by barracuda156** [comment]
> Because the next version of rstan can't work without it. Since Stan 2.21, the Stan-to-C++ parser was rewritten in Ocaml ([repo here](github.com/stan-dev/stanc3/)). R does not (currently) have the capacity to compile Ocaml during package installation, so the current workaround is to transpile the Ocaml code to javascript, which is then run using the V8 engine.
> 
> Not an ideal solution by any means, but it's the best we have at the moment

@andrjohns Could we think of some alternative? `v8` is broken for a number of platforms (while `OCaml` works at least in bytecode).
Making `v8` a required dep gonna essentially kill `rstan` for some platforms and users.

**Comment by barracuda156** [comment]
@andrjohns By the way, can we run tests for the current version of Rstan without v8? I would like to run test suite, but fixing v8 “over a weekend” is not an option :)

**Comment by barracuda156** [comment]
> @andrjohns By the way, can we run tests for the current version of Rstan without v8? I would like to run test suite, but fixing v8 “over a weekend” is not an option :)

Answering to myself: no, `v8` can be thrown away, and tests pass:
```
--->  Testing R-rstan
* using log directory ‘/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-rstan/R-rstan/work/rstan/rstan.Rcheck’
* using R version 4.2.2 (2022-10-31)
* using platform: powerpc-apple-darwin10.8.0 (32-bit)
* using session charset: UTF-8
* checking for file ‘rstan/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘rstan’ version ‘2.21.8’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rstan’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  7.7Mb
  sub-directories of 1Mb or more:
    lib    1.0Mb
    libs   3.9Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'rstan.Rd':
  ‘[rstanarm]{rstanarm-package}’

See section 'Cross-references' in the 'Writing R Extensions' manual.
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking R/sysdata.rda ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... NOTE
GNU make is a SystemRequirements.
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘doRUnit.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘SBC.Rmd’ using ‘UTF-8’... OK
  ‘external.Rmd’ using ‘UTF-8’... OK
  ‘rstan.Rmd’ using ‘UTF-8’... OK
  ‘stanfit-objects.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 WARNING, 2 NOTEs
```
