### ISSUE TITLE
Linking against sundialr package

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/rstan#1033]
@hsbadr 

Now that [this PR](https://github.com/sn248/sundialr/pull/6) has been merged, `rstan` should be able to link against the `sundialr` package rather than bundling/building the sources itself - which should hopefully simplify the install/build process

**Comment by hsbadr** [comment]
Hi @andrjohns This can simplify the build process, but it'll require all dependencies to link to `sundialr` as well.

**Comment by andrjohns** [comment]
Ahh of course
