### ISSUE TITLE
"Getting started" wiki link to openBUGS site leads to Mostbet casino website

### ISSUE THREAD

**Issue by koenderks** [stan-dev/rstan#1039]
#### Summary:
Please provide a short summary (no more than a sentence or two).

In the "RStan Getting started" page on the wiki, clicking the link (https://www.openbugs.net) to the openBUGS website (at https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#references) leads me to the website for something called "Mostbet casino".

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25059399/221116213-a6d95923-7c89-4b48-95d5-aaf05dbe3deb.png">

#### Description:
I don't think this is the correct website to be linked to.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

See above.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by koenderks** [comment]
The Wikipedia entry for openBUGS at https://en.wikipedia.org/wiki/OpenBUGS provides the same link.

The footnote on this page says "On 1.December 2021 openbugs.net was offline", but I guess the domain has been bought by someone else

**Comment by andrjohns** [comment]
Thanks for letting us know. It looks like the domain has been sold/bought/discontinued. I've updated the link to point to the MRC website: https://www.mrc-bsu.cam.ac.uk/software/bugs/openbugs/

**Comment by koenderks** [comment]
Perhaps you also noticed this, but on the same page the BUGS link leads to a 'Page not found" on the MRC website:

http://www.mrc-bsu.cam.ac.uk/bugs/

This should be 

https://www.mrc-bsu.cam.ac.uk/software/bugs/

I'll make a new issue for this
