### ISSUE TITLE
"Getting started" BUGS link

### ISSUE THREAD

**Issue by koenderks** [stan-dev/rstan#1040]
#### Summary:
Please provide a short summary (no more than a sentence or two).

In the "RStan Getting started" page on the wiki, clicking the link (http://www.mrc-bsu.cam.ac.uk/bugs/) to the BUGS page (from https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#references) results in a page not found. The correct link is https://www.mrc-bsu.cam.ac.uk/software/bugs/.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by andrjohns** [comment]
Resolved

**Comment by andrjohns** [comment]
For any more link issues, please comment/re-open this issue

**Comment by koenderks** [comment]
It is probably best to change those links in the translated versions of the getting started pages as well.

- https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-(Français)
- https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-(Japanese)
- https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-(繁體中文)
- https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-(Português)

It does not seem like I can reopen this issue?
