### ISSUE TITLE
Installing the preview version of RStan

### ISSUE THREAD

**Issue by rajesh06** [stan-dev/rstan#1065]
RStudio and R are not installing the preview version of Rstan (2.26). Here is my output.

`install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))`

`Installing package into ‘C:/Users/rajesh.sahasrabuddhe/AppData/Local/R/win-library/4.3’ (as ‘lib’ is unspecified) Warning: unable to access index for repository https://mc-stan.org/r-packages/src/contrib: cannot open URL 'https://mc-stan.org/r-packages/src/contrib/PACKAGES' Warning: unable to access index for repository https://cloud.r-project.org/src/contrib: cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES' Warning: unable to access index for repository https://mc-stan.org/r-packages/bin/windows/contrib/4.3: cannot open URL 'https://mc-stan.org/r-packages/bin/windows/contrib/4.3/PACKAGES' Warning: unable to access index for repository https://cloud.r-project.org/bin/windows/contrib/4.3: cannot open URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/PACKAGES' Warning message: package ‘rstan’ is not available for this version of R`

Are others having this issue?

**Comment by andrjohns** [comment]
That output indicates that your R installation is not able to access the internet, because it is unable to connect to both the standard repositories `https://cloud.r-project.org` and the stan repository.

Are you able to install any other packages? For example:
```r
install.packages("Rcpp", type="source")
```

**Comment by rajesh06** [comment]
Thanks. I can download from CRAN, just not other sources (including github, etc.) My IT department is looking into this, as it appears to be a firewall issue. You can close the issue.
