### ISSUE TITLE
Update link to MAC toolchain

### ISSUE THREAD

**Issue by tfjaeger** [stan-dev/rstan#1073]
#### Summary:
Perhaps consider updating this page https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Mac to point to the coatless-mac/macrtools library (https://github.com/coatless-mac/macrtools) since the Mac c++ toolchain installer is not maintained anymore, and does not work. Thanks!

**Comment by bob-carpenter** [comment]
Thanks, @tfjaeger.  There's been a renewed burst of activity on RStan and there should be updates soon to bring it up to date with Stan itself.  Hopefully the doc like this can also get updated.

**Comment by jgabry** [comment]
> Perhaps consider updating this page https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Mac to point to the coatless-mac/macrtools library

Updated to point to macrtools, thanks!
