### ISSUE TITLE
Update link for macOS C Toolchain installation in wiki

### ISSUE THREAD

**Issue by rdboyes** [stan-dev/rstan#1074]
#### Summary:
The link to the macOS toolchain installer on the wiki is outdated.

#### Description:
On the wiki page [Configuring C Toolchain for Mac](https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Mac), there is a link to the [macOS toolchain installer](https://github.com/coatless-mac/r-macos-rtools#how-do-i-use-the-installer). This linked site is out of date and doesn't work. On the linked page, it states that the tool has been superceded by the R package [macrtools](https://github.com/coatless-mac/macrtools). Suggest that the link should go directly to this package. 

#### Reproducible Steps:
Not applicable

#### Current Output:
Not applicable

#### Expected Output:
Not applicable

#### RStan Version:
Not applicable

#### R Version:
4.3.0

#### Operating System:
macOS monterey (12.4)

**Comment by jgabry** [comment]
Thanks! Just updated the instructions to point to macrtools.
