### ISSUE TITLE
Cannot install Stan with OS X.10

### ISSUE THREAD

**Issue by avecchiato** [stan-dev/rstan#109]
Hey folks, I get this weird error when I try to install stan on a Macbook Air with Yosemite. I followed the procedure and I have everything up to date. Any hint?

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
/bin/sh: llvm-g++-4.2: command not found
make: **\* [file83b127be515.o] Error 127 In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file83b127be515.cpp 2> file83b127be515.cpp.err.txt' had status 1

**Comment by jpcsoup** [comment]
I'm running into a similar problem, but I'm unsure about how to change the configuration for my default C++ compiler.  Any help?

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! /bin/sh: llvm-g++-4.2: command not found
make: **\* [filec26b62b5fdfd.o] Error 127
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB filec26b62b5fdfd.cpp 2> filec26b62b5fdfd.cpp.err.txt' had status 1 
Called from: cxxfunction(body = src, includes = "", plugin = "Rcpp", verbose = FALSE)

**Comment by maverickg** [comment]
What are the versions of your OS, Xcode, and R?

If everything on Mac is updated to the latest versions, there should be no problem.

**Comment by avecchiato** [comment]
For me it happened when I updated to Yosemite and kept the old version of R. When I reinstalled R with the latest it worked out without changing any configuration.

**Comment by jpcsoup** [comment]
Reinstalling R seemed to do the trick.  Thank you so much for the help!
