### ISSUE TITLE
Unable to install rstan on Mac M1 with R 4.1

### ISSUE THREAD

**Issue by ischmidt20** [stan-dev/rstan#1090]
#### Summary:
`install.packages(rstan)` fails. The error occurs after compilation.

#### Current Output:

I can try to post the whole compilation log but it is too long to fit in a single Markdown post. Here is the final bit which describes the error:

```
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘rstan’:
 .onLoad failed in loadNamespace() for 'rstan', details:
  call: NULL
  error: Evaluating JS code failed!
Error: loading failed
Execution halted
ERROR: loading failed
```

#### Expected Output:
Package installs as expected (note that all dependencies were able to install successfully).

#### R Version:
4.1.2

#### Operating System:
OS X 12.6.7
Apple M1 Pro chip

**Comment by andrjohns** [comment]
Can you try the following:
```r
install.packages(c("rstan","StanHeaders"), type ="source")
```

**Comment by ischmidt20** [comment]
StanHeaders installed fine but even after doing so and restarting R session, I still see the same error for rstan.

**Comment by andrjohns** [comment]
How about if you try installing the current github version:
```r
remotes::install_github("stan-dev/rstan", subdir="rstan/rstan")
```

**Comment by ischmidt20** [comment]
Thanks, this worked!

It failed the first time but at least revealed that I was missing the V8 namespace. Simply ran `install.packages('V8')` and then tried to install rstan from GitHub again, and this time, succeeded.

I was able to load the package with `library(rstan)` and didn't see any errors—haven't tried to actually use it yet but things look good for now.

Edit: Actually started using `rstan` (via `rstanarm`) and have experienced no issues thus far. Installation worked!
