### ISSUE TITLE
exec/stanc.js contains compressed JS without source

### ISSUE THREAD

**Issue by tillea** [stan-dev/rstan#1102]
#### Summary:
The tarball that can be downloaded from `https://cran.r-project.org/package=rstan` includes the file `exec/stanc.js` which contains compressed JavaScript.

#### Description:
In Debian we need the uncompressed JavaScript.  The first line of the affected file is

    // Generated by js_of_ocaml 3.4.0

We just need the source file and the command line to convert the source to the result.

#### RStan Version:
2.32.3

**Comment by WardBrian** [comment]
I believe this is a duplicate of https://github.com/stan-dev/rstan/issues/1079

The source is implemented in OCaml in https://github.com/stan-dev/stanc3

**Comment by tillea** [comment]
Closing this duplicate of https://github.com/stan-dev/rstan/issues/1079
