### ISSUE TITLE
Editing privilege for RStan-Getting-Started-(Japanese)

### ISSUE THREAD

**Issue by MatsuuraKentaro** [stan-dev/rstan#1106]
I was one of the authors of the following page:
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started-(Japanese)
I don't seem to have the editing privilege right now, so if it is possible, could someone please give me it? I will update the page.

P.S. Sorry if I shouldn't have written this in issues.

**Comment by bob-carpenter** [comment]
Can you not just edit the Wiki?  If not, making a PR for RStan is probably the best thing to do.  

It'd be great to have something like this for CmdStanR, too.

**Comment by MatsuuraKentaro** [comment]
There is no edit button on the Wiki. I will make a PR for RStan.

**Comment by MatsuuraKentaro** [comment]
I could not run the git clone. Any ideas? (`?` in the filename might be the cause.)

```
$ git clone https://github.com/stan-dev/rstan.wiki.git
Cloning into 'rstan.wiki'...
remote: Enumerating objects: 1624, done.
remote: Total 1624 (delta 0), reused 0 (delta 0), pack-reused 1624
Receiving objects: 100% (1624/1624), 615.80 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (1025/1025), done.
error: invalid path 'How-to-Work-with-the-Stan-Submodule-in-rstan-Repo?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by bob-carpenter** [comment]
Are you on Windows?  I don't have any problem checking out the Wiki.

```
~/github/stan-dev$ git clone https://github.com/stan-dev/rstan.wiki.git 
Cloning into 'rstan.wiki'...
remote: Enumerating objects: 1624, done.
remote: Total 1624 (delta 0), reused 0 (delta 0), pack-reused 1624
Receiving objects: 100% (1624/1624), 615.80 KiB | 5.55 MiB/s, done.
Resolving deltas: 100% (1025/1025), done.
```

It does generate a file `How-to-build-rstan-package?.md`.

**Comment by bob-carpenter** [comment]
To cut out all the back and forth, I just gave you write permission for this repo: https://github.com/stan-dev/rstan

You can edit the wiki, but please don't push unreviewed code.  Thanks.

**Comment by MatsuuraKentaro** [comment]
Yes, I use Windows 11. Thank you for the permission!
I understand that I don't push unreviewed code.
