### ISSUE TITLE
Lookup function doesn't return Stan function names

### ISSUE THREAD

**Issue by ian-coccimiglio** [stan-dev/rstan#1110]
#### Summary:
The lookup function in R does not return Stan function names anymore, instead it only returns the name of the input R function.

#### Description
I think the issue is either in the rosetta formatting or the matching of the lookup function. The function uses rosetta[matches, -1, drop = FALSE] and drops the first column of the output, which are the Stan function names, rather than dropping the second column of R function names.

#### Reproducible Steps:
Use `lookup(dnorm)` or `lookup("dnorm")` using rstan v2.32.5 (or any other R function).

#### Current Output:
```
> lookup(dnorm)
    RFunction                                                                    Arguments ReturnType
415     dnorm (real, matrix, real, vector, T);(vector, row_vector, vector, vector, vector)     T;real
418     dnorm                                     (real, real, T);(vector, vector, vector)     T;real
419     dnorm                                     (real, real, T);(vector, vector, vector)     T;real
553     dnorm                                                                 (T);(vector)     T;real
```

#### Expected Output:

See [here](https://pluto.coe.fsu.edu/svn/common/rgroup-shiny/Bayesian/Schools8Stan.nb.html) for the original return value of the function.

<img width="945" alt="image" src="https://github.com/stan-dev/rstan/assets/62724583/141df80e-c9e3-4f48-8088-673bca332e5d">

#### RStan Version:
Rstan v2.32.5

#### R Version:
R version 4.3.0 

#### Operating System:
Both macOSX and Manjaro linux.

**Comment by jgabry** [comment]
> I think the issue is either in the rosetta formatting or the matching of the lookup function. The function uses rosetta[matches, -1, drop = FALSE] and drops the first column of the output, which are the Stan function names, rather than dropping the second column of R function names.

@ian-coccimiglio thanks for bringing this to our attention. That's strange! @bgoodri I guess the columns in `rosetta` changed order by mistake at some point? Simplest solution seems to be to just change to `rosetta[matches, -2, drop = FALSE]` (or better yet, drop using the column name).

**Comment by jgabry** [comment]
I made a PR: https://github.com/stan-dev/rstan/pull/1113
