### ISSUE TITLE
rstan dependent package compilation failures on CRAN

### ISSUE THREAD

**Issue by sbfnk** [stan-dev/rstan#1127]
#### Summary:
Quite a few packages that depend on rstan currently error on some platforms during compilation on CRAN.

#### Description:
A few examples (the first ones when going through alphabetically) are

https://cran.r-project.org/web/checks/check_results_baggr.html
https://cran.r-project.org/web/checks/check_results_bakR.html
https://cran.r-project.org/web/checks/check_results_baldur.html

The final line in the log is
```
make[1]: *** [/home/hornik/tmp/R.check/r-patched-gcc/Work/build/etc/Makeconf:200: stanExports_logit.o] Terminated
```
No error is reported, and we have been unable to reproduce this locally using the same r-patched revision for [EpiNow2](https://cran.r-project.org/web/checks/check_results_EpiNow2.html). Perhaps a memory issue?

If this remains it is likely to cause issues for CRAN submission of packages that depend on `rstan`

**Comment by WardBrian** [comment]
Related: https://github.com/stan-dev/rstan/issues/1122
https://github.com/stan-dev/rstan/pull/1124#issuecomment-2075003911

I believe that these are most likely out-of-memory issues in the compiler (`Terminated` is distinct from an error and usually means the OS killed the process). If that's the case, it is unclear what we can do about it.

**Comment by sbfnk** [comment]
Seems to have been a transient issue that has resolved itself.
