### ISSUE TITLE
the latest rstan could not be installed on FreeBSD 

### ISSUE THREAD

**Issue by jszhao** [stan-dev/rstan#1128]
#### Summary:
rstan imports QuickJSR, [and the latter could not be installed on FreeBSD](https://github.com/andrjohns/QuickJSR/issues/53), thus rstan could not be installed on FreeBSD too.

#### R Version:
```
> R.version.string
[1] "R version 4.4.0 (2024-04-24)"
```

#### Operating System:
```
% uname -a
FreeBSD xw6600 14.1-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC amd64
```

**Comment by andrjohns** [comment]
Please don't open issues for problems in other packages. You've already opened an issue in QuickJSR, please wait until that is resolved before opening more issues for the same problem.
