### ISSUE TITLE
chain=0 in Rstan quick start

### ISSUE THREAD

**Issue by gemcavoy** [stan-dev/rstan#124]
The quick start guide for Rstan includes an example for parallel processing in the which  "chain=0" is used in the compiling stage. If "iter=0" is the preferred call, the document should probably be changed.

From Quick Start:

######
library(parallel)
library(rstan)

foo_data <- ...;
rng_seed <- ...;
foo <- stan("foo.stan", data = foo_data, chains = 0)  #######HERE IS THE CALL
sflist <- 
  mclapply(1:4, mc.cores = 2, 
           function(i) stan(fit = foo, data = foo_data, 
                            seed = rng_seed, 
                            chains = 1, chain_id = i, 
                            refresh = -1))
Greg

**Comment by maverickg** [comment]
nothing is preferred; just use what works better for you.  I am closing this.
