### ISSUE TITLE
`init_r` control parameter is ignored.

### ISSUE THREAD

**Issue by skparkes** [stan-dev/rstan#125]
This probably isn't the best example, but here is the default example for `stan()` adapted to show this control parameter being ignored:

```R
library(rstan)
scode <- "
parameters {
real y[2]; 
} 
model {
y[1] ~ normal(0, 1);
y[2] ~ double_exponential(0, 2);
} 
"
fit1 <- stan(model_code = scode, iter = 10, verbose = FALSE) 
attr(fit1@sim$samples[[1]],'args')$init_radius
fit2 <- stan(fit=fit1, iter = 10, verbose = FALSE, control=list(init_r=1))
attr(fit2@sim$samples[[1]],'args')$init_radius
```

The attributes to both `fit1` and `fit2` both show the `init_radius=2`.

**Comment by maverickg** [comment]
I am closing this as `control` is used for arguments only for the sampler.  There are other parameters needed to be in `...`.
