### ISSUE TITLE
split into headers-only package and rstan user interface

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/rstan#126]
It will soon be feasible to use stan as a library, https://github.com/stan-dev/stan/issues/1175

We plan to use stan headers as part of http://openmx.psyc.virginia.edu/

Can you split rstan into two separate packages? RStanHeaders should only contain the headers and not depend on any other package. It should be similar to RcppEigen, but actually RcppEigen's dependency on Rcpp is troublesome and unnecessary. We much prefer if RStanHeaders contains only the headers and nothing else. The current rstan package can remain as is, but simple add a linkto dependency against RStanHeaders.

Thank you

**Comment by maverickg** [comment]
this should be discussed on stan.  In other words, do we need an R package that only distribute stan source?  I think we could.

**Comment by jpritikin** [comment]
"this should be discussed on stan." -- What needs to be discussed?

**Comment by syclik** [comment]
I think Maverick was suggesting we have the discussion on the stan-dev
mailing list rather than the issue.

**Comment by syclik** [comment]
Since this discussion has moved to the email list and there isn't action to be done on RStan itself (at the moment), I'm closing this issue.
