### ISSUE TITLE
Report ESS/s in print()

### ISSUE THREAD

**Issue by gregorgorjanc** [stan-dev/rstan#128]
For comparisons of different models and general understanding on the quality of the fit the ESS per time would be very useful to have in print() method of the stanfit object..

**Comment by maverickg** [comment]
rstan does not have that info passed in as numbers.  besides, it would make the output too wide.

**Comment by gregorgorjanc** [comment]
Since HMC behaves differently than MCMC a common metric to compare the two is via ESS/time and this is why I propose to add another column. One might argue that perhaps this is even more important than having so many quantiles reported. Anyhow, having somewhere such information in the RStan object would be interesting, given that this information is already collected by stan - it only needs to be captured and transferred to RStan or make ESS/time a common additional metric for all stan interfaces. Just my 2 cents.

**Comment by maverickg** [comment]
Though I don't like print out everything by default, having this information available is nice.  But currently it's not available to rstan as stan controls the output.

**Comment by bob-carpenter** [comment]
You just want to divide n_eff by number of seconds to get
n_eff/second.   

Andrew's got a whole new scheme for output he's playing
with, so maybe holding off on this for a bit is a good idea.

CmdStan reports this in its output, but it
reports it dovides by SAMPLING TIME ONLY (not warmup time).
Reporting for sampling gives you the ESS/rate going forward,
whereas including warmup might be seen as more "fair".

- Bob

**Comment by maverickg** [comment]
> You just want to divide n_eff by number of seconds to get
n_eff/second.

I was trying to say rstan does not get the time information as rstan gives an output stream to stan and stan prints the time out after the progression of sampling. 

>
Andrew's got a whole new scheme for output he's playing
with, so maybe holding off on this for a bit is a good idea.

ok

**Comment by jgabry** [comment]
It's not the same thing as n_eff/second, but shinyStan has a plot of n_eff/N (where N is the total number of draws) as well as a threshold you can set so it warns you if any parameters have n_eff/N below the threshold value.
