### ISSUE TITLE
remove dependencies on Google Code

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#13]
- [ ] distribution of RStan, which is still from http://wiki.stan.googlecode.com/git/R
- [ ] RStan getting started Wiki

There are also Stan issues for which there is a separate issue on the stan issue tracker:

https://github.com/stan-dev/stan/issues/229

When both are cleared, we can

- [ ] shut down Google Code site

**Comment by jgabry** [comment]
closing outdated issue
