### ISSUE TITLE
Memory leak in multi_normal

### ISSUE THREAD

**Issue by jhjourdan** [stan-dev/rstan#130]
Hello,

The following R script is a much simplified version of our application:

```
library(rstan)

model = stan_model(model_code=
"data {
}
transformed data {
  matrix[1, 1] V;
  vector[1] S;
  vector[1] mu;

  V[1, 1] <- 1;
  S[1] <- 1;
  mu[1] <- 0;
}
parameters {
  vector[1] x;
}
model {
  x ~ multi_normal(mu, V);
  //x ~ normal(mu, S);
}")

for(i in 1:1000) {
  s = sampling(model, data=list(), chains=1, refresh=-1, iter=10000, warmup=10000)
  if(i %% 20) {
    gc()
  }
}
```

When executed, R allocates more and more memory, and it is not possible to free it. In our application, this is a problem, because then the size of the heap reaches more than 8GB, which is too much for our computers.

It seems like when replacing the multi_normal distribution by a normal distribution, the problem disappears.

Thanks,

JH

**Comment by syclik** [comment]
I just verified this behavior in RStan v2.5.0.

Memory definite grows between runs with multi_normal, but not with normal.

I don't know enough of how the sampling() call in RStan is written to know
whether this is actually a bug in Stan itself.

**Comment by bob-carpenter** [comment]
I could not recreate a leak in CmdStan under develop.

My only guess is that the object created by sampling()
to hold the sample is not being freed when s is
reassigned.

- Bob

**Comment by bob-carpenter** [comment]
The memory needs be recovered in the same way in RStan
as in CmdStan.  The multi_normal is using the LDLT
object that goes on its own memory stack.  

This may be fixed for RStan with the current develop
branch of Stan.

- Bob

**Comment by jhjourdan** [comment]
Indeed, it is fixed with current develop version of stan, sorry for the noise.

Thanks,

JH

**Comment by bob-carpenter** [comment]
We'd much rather be informed twice about a bug than 
zero times.  We find it hard ourselves to search the 
issue tracker to figure out what's been done already.

- Bob
