### ISSUE TITLE
RStan dump truncating integers with scientific notation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#14]
Reported by Kevin S Van Horn on stan-users list:

<blockquote>
I had a variable n with value 1234567890123456. This was written to the dump file as 1.234568e+15, which avoids the  problem of it being interpreted as an integer, but loses everything after the first 7 digits.
</blockquote>

What should we do for this?   Issues are that

- it's larger than a 32-bit int
- it's an integer that's getting written out in scientific notation, which we reserve for double values

Seems to me we do one of the following

- fix the I/O in Stan so that it can read long integers and store them and then raise an error if you try to get them as an int and they overflow;  this also requires forcing R not to write out scientific notation for integer values
- include type information in the rstan_dump output, and if we see a value larger than 2^32 - 1, raise some kind of error from rstan_dump

It seems to do this right, we also need to allow

- [ ] control number of significant digits in dump output

**Comment by jgabry** [comment]
closing outdated issue
