### ISSUE TITLE
RStan installation failure, R 3.1.2 on 64-bit Windows 7 Professional

### ISSUE THREAD

**Issue by TMKAIG1** [stan-dev/rstan#141]
Hi!  I'm not sure if this is the right place to report, but I tried to install RStan on R 3.1.2 on 64-bit Windows 7 Professional, and I got the same error on both 32-bit and 64-bit versions of R.  I sure would appreciate any assistance / advice.  I used the PA1 CRAN site and ran the commands:

> source('http://mc-stan.org/rstan/install.R', echo = TRUE, max.deparse.length = 2000)
> install_rstan()
> which resulted in the following error messages:

**\* arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="Rcpp.dll" OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o"' had status 127
ERROR: compilation failed for package 'Rcpp'
- removing 'C:/Users/tkatz/Documents/R/win-library/3.1/Rcpp'
- restoring previous 'C:/Users/tkatz/Documents/R/win-library/3.1/Rcpp'

The downloaded source packages are in
        ‘C:\Users\tkatz\AppData\Local\Temp\RtmpCOILlY\downloaded_packages’

Attaching package: ‘Rcpp’

The following object is masked from ‘package:inline’:

```
registerPlugin
```

Warning message:
running command 'make -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2adc784666ab.dll" OBJECTS="file2adc784666ab.o"' had status 127 

ERROR(s) during compilation: source code errors or compiler configuration errors!

...

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2adc784666ab.dll" OBJECTS="file2adc784666ab.o"' had status 127 
In addition: Warning messages:
1: running command '"C:/PROGRA~1/R/R-31~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\tkatz\Documents\R\win-library\3.1" C:\Users\tkatz\AppData\Local\Temp\RtmpCOILlY/downloaded_packages/Rcpp_0.11.5.tar.gz' had status 1 
2: In install.packages("Rcpp", type = "source") :
  installation of package ‘Rcpp’ had non-zero exit status
3: running command 'C:/PROGRA~1/R/R-31~1.2/bin/i386/R CMD SHLIB file2adc784666ab.cpp 2> file2adc784666ab.cpp.err.txt' had status 1 

THANKS!

**Comment by bob-carpenter** [comment]
Reporting as an issue is fine with us.

Your install is failing to install Rcpp, which is a pre-requisite
to install RStan. 

From the 127 return code, it looks like you don't have a C++ 
compiler installed on your path.  Have you installed the latest Rtools 
for Windows?  It will give you the C++ toolchain you need.
- Bob

**Comment by TMKAIG1** [comment]
Hi bob-carpenter!  Thank you for responding.  I took your hint about Rtools and downloaded Rtools32.exe from http://cran.r-project.org/bin/windows/Rtools/ because that looked like the recommended version for R 3.1.2.  I ran Rtools32.exe with all its default choices, and it appeared to succeed.  Then I retried installing RStan and got the same error as before.  In the Rtools installation there was a point where you could edit the path and the registry, and the default was to edit only the registry, so I reran the Rtools32.exe, this time adding the path edit option.  When I ran the RStan installation after that... success!  It installed both the 32-bit and 64-bit versions.  Thanks so much!!!

**Comment by bob-carpenter** [comment]
You need to put a program on your PATH in order for other programs to be able to find it just using its name, which is what Rcpp requires of the C++ compiler.

For future reference, the RStan getting started page points to this page as a pre-req for Windows installs, and the page pointed to takes pains to point out you need to use the path option:

https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

We don't know how to make this much clearer, but lots of people run into problems, so you're not alone.

**Comment by TMKAIG1** [comment]
Ah, now I see that all the information was there all along!  And I see why I went wrong.  It wasn't obvious to me that the "Toolchain" section was a prerequisite.  In the "R" section of the prerequisites it says "R version 2.15.1 or later is required..."  The "Toolchain" section doesn't explicitly say that Rtools is required.  The next section is entitled "How to Install RStan," so that wasn't part of the prerequisites; was "Toolchain?"  Now I can see that the bold title fonts are different sizes, but it's kind of a subtle difference to my eye.  I'm not saying that there's anything wrong that needs to be changed, and perhaps it is obvious to everybody else, but I think if it had been spelled out a bit more on the https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started page that Rtools was a requirement, I might have gotten through this by myself.  Anyway, thanks for your patient assistance!!!

**Comment by kwathen** [comment]
Hi I am new to STAN (have been using winbugs and JAGS) and am trying to get it setup.    I followed the instructions at https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started.  I currently am on Windows 10, using R Studio 1.1.419 and R version 3.6.   I installed rtools.   When I run the command pkgbuild::has_build_tools(debug = TRUE) I get a return value of TRUE.   When I run the example  example model the  line

fit <- stan(file = '8schools.stan', data = schools_dat)

gives me the error below.   Any ideas when I need to do to to fix this?


Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/R-3.6.0/library/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from C:/R-3.6.0/library/BH/include/boost/random/detail/int_float_pair.hpp:26,
                 from C:/R-3.6.0/library/BH/include/boost/random/exponential_distribution.hpp:27,
                 from C:/R-3.6.0/library/BH/include/boost/random/gamma_distribution.hpp:25,
                 from C:/R-3.6.0/library/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
                 from C:/R-3.6.0/library/StanHeaders/include/stan/math/prim/mat.hpp:292,
                 from C:/R-3.6.0/library/StanHeaders/include/stan/math/rev/mat.hpp:12,
                 from C:/R-3.6.0/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/R-3.6.0/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file13383e1530f1.cpp:8:
C:/R-3.6.0/library/BH/include/boost/pending/integer_lo
Error in sink(type = "output") : invalid connection

**Comment by bgoodri** [comment]
Just do

install.packages("
https://win-builder.r-project.org/OP272u474CMQ/rstan_2.19.1.zip", repos =
NULL)

**Comment by kwathen** [comment]
Thanks @bgoodri  that worked for me!
