### ISSUE TITLE
output the chain ID

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#142]
This is related to stan-dev/stan#1348. 
From @bgoodri 

Currently, when you do chains in parallel the progress report does not look so good

Iteration:    1 / 2000 [  0%](Warmup)
Iteration:    1 / 2000 [  0%](Warmup)
Iteration:    1 / 2000 [  0%](Warmup)
Iteration:    1 / 2000 [  0%](Warmup)
Iteration:    1 / 2000 [  0%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)
Iteration:  500 / 2000 [ 25%](Warmup)

And it is even worse if the chains are not progressing at the same rate. It would be better if it said

Chain #, iteration: ...

but print_progress() currently does not have an argument to accept the chain ID.

**Comment by maverickg** [comment]
taken care of by https://github.com/stan-dev/rstan/pull/143
