### ISSUE TITLE
add doc about using function log_prob on stanfit object from parallel 

### ISSUE THREAD

**Issue by maverickg** [stan-dev/rstan#148]
In the case of using parallel multiple chains, the `log_prob` function cannot be used.  Where to doc this?

**Comment by bgoodri** [comment]
Probably would need to document it in a lot of places. But why can't the resulting multichain stanfit object copy whatever is necessary to do `log_prob` etc. from the first stanfit object?

**Comment by maverickg** [comment]
Technically it's doable: it needs to create a new c++ stan_fit object with the data for the multichain stanfit object.

**Comment by bgoodri** [comment]
Did I get it right in e8b3676 ?

**Comment by bgoodri** [comment]
Assuming it is right.
