### ISSUE TITLE
Documentation needs updating: rstan now requires a higher version of R than listed

### ISSUE THREAD

**Issue by mkosmala** [stan-dev/rstan#152]

**Comment by bob-carpenter** [comment]
Thanks for reporting.

Is there a way to update RStan without continually requiring R to
be updated?  
- Bob

**Comment by maverickg** [comment]
rstan should be fine for any version of R where Rcpp is installed.  Currently Rcpp requires R >= 3.0.0.  So sometimes, for convenience, updating R is needed.

**Comment by ariddell** [comment]
I think `devtools` might also have to be installed. I wasn't able to install `devtools` with stock Ubuntu 14.04 today because it requires rversions (or maybe xml2) which requires a more recent version of R.

**Comment by bgoodri** [comment]
devtools is only needed temporarily to install the previous version of BH.
The imminent rstan works with the current BH.

**Comment by ariddell** [comment]
Good news!
