### ISSUE TITLE
Error compiling rstan 2.6.0 with BH 1.58.0-1

### ISSUE THREAD

**Issue by brabes** [stan-dev/rstan#163]
Hello!

I was trying to install rstan as per the getting started guide on FreeBSD 9.1, using clang and R 3.2.0

```
% uname -a
FreeBSD localhost.localdomain 9.1-RC2 FreeBSD 9.1-RC2 #0 r241106: Mon Oct  1 18:26:44 UTC 2012     root@farrell.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64

% clang++ -v
FreeBSD clang version 3.1 (branches/release_31 156863) 20120523
Target: x86_64-unknown-freebsd9.0
Thread model: posix

> version
               _
platform       x86_64-unknown-freebsd9.1
arch           x86_64
os             freebsd9.1
system         x86_64, freebsd9.1
status
major          3
minor          2.0
year           2015
month          04
day            16
svn rev        68180
language       R
version.string R version 3.2.0 (2015-04-16)
nickname       Full of Ingredients

```

With BH 1.58.0-1 installed, compilation fails on `gm__grammars__term_grammar_inst.o` - unfortunately, as is often the case with C++ template related errors, the error message is a several hundred lines, but seems to come from

```
../inst/include/stansrc/stan/gm/grammars/term_grammar_def.hpp:649:9
```

I also tried compiling using gcc 4.2.1 but compilation also failed in `gm__grammars__term_grammar_inst.o` with a similar (though even less comprehensible) error message. I have also tried compiling on my Windows machine with BH 1.58.0-1 and compilation fails in the same place.

I was able to resolve the issue by downgrading BH to 1.55.0-3 on both FreeBSD and Windows platforms. In R 3.2.0 it attempts to upgrade to BH 1.58.0-1 when installing rstan, and so I had to manually disable dependencies when installing.

This table shows the different combinations that I tried; as you can see, the version of BH seems to be the determining factor.

| Platform | R | Compiler | rstan | BH | Outcome |
| --- | --- | --- | --- | --- | --- |
| FreeBSD 9.1 x86_64 | 3.2.0 | gcc 4.2.1 | 2.6.0 | 1.58.0-1 | Fails |
| FreeBSD 9.1 x86_64 | 3.2.0 | clang 3.1 | 2.6.0 | 1.58.0-1 | Fails |
| FreeBSD 9.1 x86_64 | 3.2.0 | clang 3.1 | 2.6.0 | 1.55.0-3 | Works |
| Windows 8.1 (x64) | 3.2.0 | gcc 4.6.3 | 2.6.0 | 1.58.0-1 | Fails |
| Windows 8.1 (x64) | 3.1.3 | gcc 4.6.3 | 2.6.0 | 1.55.0-3 | Works |

Thanks,

**Comment by syclik** [comment]
Hi, we're in the middle of fixing this compiler error. It is issue
stan-dev/stan#1457.

Hopefully we'll have that resolved soon.

**Comment by brabes** [comment]
Thanks! :+1: Sorry I only searched in the rstan issues to see if it was a known bug!

**Comment by bob-carpenter** [comment]
This will be solved in stan-dev/stan issue https://github.com/stan-dev/stan/issues/1457
