### ISSUE TITLE
Failed installation of Rstan on Ubuntu 15.04

### ISSUE THREAD

**Issue by chrmei** [stan-dev/rstan#164]
Hello,

during installation for rstan I get a compilation error. I used the standard installation script from your site. I tried 
Sys.setenv(MAKEFLAGS = "") and Sys.setenv(MAKEFLAGS = "-j1") and "-j4", but it was everytime the same.
It seems similar to this post ( https://github.com/stan-dev/rstan/issues/6 ), but a little bit different, cause my files are not "too big".
I'm using Ubuntu 15.04, R 3.2, build essentials installed and my g++ is std=c11. My Makeconf on line 142/143:

> .cpp.o:
>   $(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -c $< -o $@

and the lines for:

> CPPFLAGS = 
> CXXFLAGS = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security ->D_FORTIFY_SOURCE=2 -g $(LTO)

and here is my error-output from the installation:

---

> /usr/local/lib/R/site-library/BH/include/boost/phoenix/core/detail/preprocessed/actor_operator_10.hpp:557:9: note: template<class A0, class A1, class A2, class A3, class A4, class A5, class A6, class A7, class A8, class A9> typename boost::phoenix::result_of::actor<typename boost::mpl::eval_if_c<boost::mpl::or_<boost::phoenix::is_custom_terminal<Expr>, mpl_::bool_boost::is_placeholder<Expr::value> >::value, boost::proto::terminal<Expr>, boost::mpl::identity<T> >::type::proto_base_expr, const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&, const A8&, const A9&>::type boost::phoenix::actor<Expr>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&, const A8&, const A9&) const [with A0 = A0; A1 = A1; A2 = A2; A3 = A3; A4 = A4; A5 = A5; A6 = A6; A7 = A7; A8 = A8; A9 = A9; Expr = boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval, boost::proto::argsns_::list7<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<stan::gm::add_var>, 0l>, boost::phoenix::actorboost::spirit::attribute<0 >, boost::phoenix::actorboost::spirit::argument<0 >, boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<stan::gm::variable_map> >, 0l> >, boost::phoenix::actorboost::spirit::local_variable<0 >, boost::phoenix::actorboost::spirit::attribute<2 >, boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<std::basic_stringstream<char> > >, 0l> > >, 7l>]
>          operator()(A0 const& a0 , A1 const& a1 , A2 const& a2 , A3 const& a3 , A4 const& a4 , A5 const& a
>          ^
> /usr/local/lib/R/site-library/BH/include/boost/phoenix/core/detail/preprocessed/actor_operator_10.hpp:557:9: note:   template argument deduction/substitution failed:
> In file included from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi/action/action.hpp:21:0,
>                  from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi/action.hpp:14,
>                  from /usr/local/lib/R/site-library/BH/include/boost/spirit/home/qi.hpp:14,
>                  from /usr/local/lib/R/site-library/BH/include/boost/spirit/include/qi.hpp:16,
>                  from ../inst/include/stansrc/stan/gm/grammars/var_decls_grammar_def.hpp:4,
>                  from ../inst/include/stansrc/stan/gm/grammars/var_decls_grammar_inst.cpp:1,
>                  from gm__grammars__var_deccls_grammar_inst.cpp:2:
> /usr/local/lib/R/site-library/BH/include/boost/spirit/home/support/action_dispatch.hpp:178:39: note:   candidate expects 10 arguments, 3 provided
>              f(attr_wrap, context, pass);
>                                        ^
> /usr/lib/R/etc/Makeconf:143: recipe for target 'gm__grammars__var_deccls_grammar_inst.o' failed
> make: **\* [gm__grammars__var_deccls_grammar_inst.o] Error 1
> ERROR: compilation failed for package ‘rstan’
> - removing ‘/usr/local/lib/R/site-library/rstan’
>   The downloaded source packages are in
>   ‘/tmp/RtmpNsmW71/downloaded_packages’
>   Error in library(rstan) : there is no package called ‘rstan’
>   In addition: Warning message:
>   In install.packages("rstan", type = "source") :
>   installation of package ‘rstan’ had non-zero exit status
>   _____________________________________________________________________

The "candidate expects 10 arguments, 3 provided" warning is occuring more than only once, but i don't know, if this is important.
Hope, there is a solution. Last time on Ubuntu 14.04 it worked perfect. You need more information of anything else?

Cheers and thanks

**Comment by maverickg** [comment]
https://groups.google.com/d/msg/stan-users/lGIMXJf5P04/zZqOUsjlc1QJ

https://github.com/stan-dev/rstan/issues/163

**Comment by chrmei** [comment]
Thanks a lot! So, they're building a fix. I think, this issue here can be closed?
