### ISSUE TITLE
fix the problem after making stan math a library

### ISSUE THREAD

**Issue by maverickg** [stan-dev/rstan#166]
Current building of rstan is broken now due to making stan math a library.  How to fix it?  Fix it in StanHeaders or rstan? Make another R package for stan math?

**Comment by syclik** [comment]
@maverickg, what's going to be easiest?

I think both @jpritikin and @bob-carpenter agreed it'd be good to have a
separate math library R package. Is that going to be hard?

**Comment by maverickg** [comment]
I think all are easy.  It is easy to have a separate R package for stan math too.  If we make stan math a package, do we need make the rest of stan an R package (or do we need "StanHeaders without stan math")?

**Comment by bgoodri** [comment]
I was thinking StanHeaders would include the Stan Math Library.

**Comment by bgoodri** [comment]
The bigger issue is that the 100 byte threshold is exceeded again for some files

```
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/fwd/mat/fun/multiply_lower_tri_self_transpose.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/prim/mat/fun/multiply_lower_tri_self_transpose.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/prim/scal/meta/contains_nonconstant_struct.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/prim/scal/prob/double_exponential_ccdf_log.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/prim/scal/prob/scaled_inv_chi_square_ccdf_log.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/prim/scal/prob/scaled_inv_chi_square_cdf_log.hpp’
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  ‘StanHeaders/inst/include/lib/stan_math_2.6.3/stan/math/rev/mat/fun/multiply_lower_tri_self_transpose.hpp’
```

**Comment by bgoodri** [comment]
I can get around this by changing the directory stan_math_2.6.3 to stan_math but we are really close to the limit.

**Comment by bob-carpenter** [comment]
I think StanHeaders should include Stan Math, either directly
or by dependency.  

If we had separate headers for Stan Math, that'd be great.

If CRAN would let us have separate headers for Stan Math and
include them in StanHeaders, I think that'd be even better.
- Bob

**Comment by bgoodri** [comment]
Is the fwd stuff eventually going to be in the Stan Math Library? Or will
it have its own library?

**Comment by syclik** [comment]
It'll be in the math library.

**Comment by bgoodri** [comment]
Were we supposed to get rid of pure include files that did not involve math/ like mcmc.hpp? Should we change the interfaces to include every .hpp file under mcmc/?

**Comment by syclik** [comment]
Sorry, I reread that a few times and I don't get it.

I think we should either include:
- just stan/math.hpp
  Or
- the minimum set of header files directly

(That answers what I think you asked, but I'm not sure.)

**Comment by maverickg** [comment]
The issue with including stan math lib inside StanHeaders is that another package needs to explicitly add the path of stan math lib.  For a typical R package including header files, one only need to add the package to Suggests in the DESCRIPTION file as we do for Rcpp and BH.

**Comment by bgoodri** [comment]
I actually had to flip it around to get the function formerly known as
testify to work, which is arguably a better setup now:

```
goodrich@T540p:/opt/rstan/StanHeaders/inst/include$ ls -l -h
total 4.0K
lrwxrwxrwx 1 goodrich goodrich   13 Jun 13 03:20 src -> upstream/src/
lrwxrwxrwx 1 goodrich goodrich   34 Jun 13 03:18 stan ->
upstream/lib/stan_math_2.6.3/stan/
drwxr-xr-x 6 goodrich goodrich 4.0K Jun 12 16:18 upstream
```

So if another package only wants to use the Stan Math Library, then putting
StanHeaders under LinkingTo in their DESCRIPTION is sufficient. If they
want to use the optimization, MCMC, etc. algorithms in StanHeaders like
RStan does, then they have to also put

```
-I`"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" -e "cat(system.file('include',
'src', package = 'StanHeaders'))"`
```

in their PKG_CFLAGS.

**Comment by maverickg** [comment]
I see.  Nice flip.
