### ISSUE TITLE
Using Rstan with Packrat

### ISSUE THREAD

**Issue by DocLabyrinth** [stan-dev/rstan#168]
We are currently in the process of adopting [Packrat](https://github.com/rstudio/packrat) for our dependency management. So far I haven't found a way to make RStan work reliably with Packrat. The usual workflow is to install packages as normal then run packrat::snapshot() to add them to the packrat bundle.

Unforunately the way Packrat is implemented means it tries to reload the packages from CRAN somehow when making a snapshot, and it fails when it reaches Rstan. Packrat does provide the option to use external packages, but in on our server this seems to fail when Packrat loses the site packages path. [This seems to be a known issue](https://github.com/rstudio/packrat/blob/1a91cdb290795c24cc0fda94177588b605525674/R/library-support.R#L101), so it's unlikely to have a concrete solution anytime soon.

Is there a known way to make Rstan work with Packrat either inside the bundle or as an external package?

**Comment by bob-carpenter** [comment]
We're working on getting RStan on CRAN.  

If I read your note correctly, that's the only way
to make this other package work.  

Otherwise, if there's an RStudio-style GitHub install
option, we could use that.
- Bob

**Comment by DocLabyrinth** [comment]
Thanks for the reply, in the end there were too many issues with Packrat and we decided to code our own solution so I'll close this issue for now.

**Comment by bgoodri** [comment]
You could try again now that rstan is on CRAN.
