### ISSUE TITLE
command to just compile model & reuse without fit object

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#17]
From Kevin van Horn on stan-users:

Is there any way to evaluate the log joint probability of a data set and its gradient in rstan without creating a stan_fit object? It seems awkward that I have to do this

```
    sf <- sampling(my_stan_model, data=data, init=0, chains=1, iter=2)
```

just so that I can evaluate log_prob for various parameter vectors (via `log_prob(sf, parameter_vector)`).

Jiqiang wrote back:

No.  One reason is that we added these functions later and a natural place to add is for stanfit object as the data have been read (and a model instance in terms of C++ that using Rcpp is created in memory, which is needed for these two functions).

This should be doable with some code re-org on the R side.  There are a few other modularity issues like this I'd also like to address, but I'll put them in separate feature requests.

**Comment by jgabry** [comment]
Closing this since there's not a specific plan here and this will be subsumed into the changes from https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers anyway.
