### ISSUE TITLE
support variational inference

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstan#171]
I'm hesitant to add a new method with a `stanmodel` in its signature for variational inference just to take it away in 3.0 but we should do something to get Alp and Dustin's work into 2.7.0

**Comment by akucukelbir** [comment]
i'd be happy to help in any way, though my R knowledge is dismal.

**Comment by maverickg** [comment]
We need to remove this std::cout first: 

https://github.com/stan-dev/stan/blob/develop/src/stan/variational/advi.hpp#L326

**Comment by akucukelbir** [comment]
good catch. removed as of https://github.com/stan-dev/stan/commit/6ae949d55504b5185c89d18af042a2556b14de6a

**Comment by maverickg** [comment]
@akucukelbir 

I took a look and my understanding is that the Variational Bayes component in Stan writes everything to, say, the standard output.  Am I correct?  If so, it's not possible to get the values into R.

**Comment by bob-carpenter** [comment]
It's not tied into std::cout directly, but may go through
output streams.  

If that's the case, then it probably just requires a little refactoring
along the lines of the writer refactor Michael's doing.  Any chance we
could piggyback on that?
- Bob

**Comment by bgoodri** [comment]
Is it not possible to do whatever is the R equivalent of the CmdStan syntax

./bernoulli variational data file=bernoulli.data.R output file=v.csv

and then read_stan_csv("v.csv") ?

**Comment by maverickg** [comment]
Of course, that's doable.  It's just....

By the way, read_stan_csv need to be updated for the output of vb.

**Comment by bob-carpenter** [comment]
> On Jul 10, 2015, at 3:04 PM, maverickg notifications@github.com wrote:
> 
> Of course, that's doable. It's just....

I'm not too shy to say it ... a nasty hack that'll be slow!  

But given that it's not a user facing hack, we could probably live
with it temporarily.

> By the way, read_stan_csv need to be updated for the output of vb.

Is this an RStan or Stan thing?  If so, can you open a relevant issue if
it's not an RStan issue that can be dealt with as part of this issue.

Thanks,
- Bob

**Comment by akucukelbir** [comment]
sorry, i'm a bit lost. (blame post-ICML exhaustion.) can i help with something here?

**Comment by bgoodri** [comment]
As far as I understand it, the 2.7.0 release is stuck due to
- ADVI apparently doesn't lend itself to transferring the samples to the
  interface via memory. This is not the worst thing in the world right now
  because the interface can still write to a temporary csv file and read that.
- But the csv writer for ADVI puts zeros into the "lp" column to a hack
  around the fact that the writer function expects lp__ (
  https://github.com/stan-dev/stan/issues/1538 ) and people don't want to
  release 2.7.0 with this hack and take it away for 2.8.0
- This is apparently already (going to be) fixed in the writer refactor
  but it is not clear what parts of the writer refactor can be merged when.

**Comment by maverickg** [comment]
I added a method for stanmodel with name `vb` in rstan's branch advb.  For now, the output is read into R as it is by using `read.csv`.  This method is not exported.

**Comment by betanalpha** [comment]
There is no reason RStan needs to support ADVI in 2.7
and we should not hold up the release for it.  In particular,
because the algorithm is experimental having extraneous
zeroes and awkward I/O should not be a hold up.

**Comment by bob-carpenter** [comment]
I agree with Michael here --- no need to get variational
inference out in RStan 2.7, and if you do, no big deal
if the back end isn't perfect or some of the output's off.
- Bob

**Comment by andrewgelman** [comment]
I think it’s better to release with awkward i/o then not at all.  Once it’s in Rstan, people can play with it!

**Comment by bgoodri** [comment]
this was done for 2.9.0
