### ISSUE TITLE
rstan install hangs / crashes (NFS home directory?)

### ISSUE THREAD

**Issue by dlakelan** [stan-dev/rstan#172]
I'm trying to install rstan using the directions given: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

the process gets to installing BH and hangs forever, with 0.5% of the CPU being used by R and nothing else going on. If I kill it, it will complain about 00LOCK-BH, if I remove this directory the whole saga starts all over again.

when the process is hung, I can't C-c the R process but I can C-z and kill % it.

If it makes any difference, my home directory is an NFS v4 mount using Kerberos security, this might affect file-locking?

The BH directory is in ~/R/x86_64-pc-linux-gnu-library/3.2/ so if I comment out the BH install and continue along I get a similar hang for install of Rcpp. Continuing past in the same way I get failed compile of rstan, with complaints about boost macros.

I'm running a relatively current Debian testing/stable mix and I have installed rstan before though not in the last few months.

Any ideas?

**Comment by dlakelan** [comment]
Installing on my laptop, which has a local home directory, it flashes through the BH install in a few seconds (Ubuntu 14.10, local home directory).

**Comment by bob-carpenter** [comment]
Have you tried just installing BH 1.58 first before
installing RStan?

Can you install any packages in the R on that system?
- Bob

**Comment by dlakelan** [comment]
Yes I can install other packages, in fact for example RCppEigen which is the first thing the rstan installer tries to install does install just fine. installing BH by itself from the commandline just hangs as before. (Also, the Rstan install script doesn't check whether it's installed, so it always tries to install RCppEigen, BH, etc). As I said, my laptop installs things fine. I suspect because it hangs without any CPU usage involved, it's probably something to do with NFS file locking. DANGIT.

**Comment by dlakelan** [comment]
BTW: the rstan install instructions are somewhat incomplete, in particular rstan wants devtools which then wants the R packages curl and xml2 and git2r and whatnot which then requires you to install other linux packages like libxml2... libssl-dev, git, curl, and whatnot.

I realize you probably mostly expect people to figure that stuff out, but a slightly more complete list might help some newbies.

**Comment by bob-carpenter** [comment]
I think we've assumed Linux users are hardier than
Mac or Windows users when it comes to installs, but no reason
to make anyone's life difficult.

If someone has a list, we can add a linux pre-reqs section.
Or do they all come with devtools in R?
- Bob

**Comment by dlakelan** [comment]
On 07/10/2015 12:31 PM, Bob Carpenter wrote:

> I think we've assumed Linux users are hardier than
> Mac or Windows users when it comes to installs, but no reason
> to make anyone's life difficult.
> 
> If someone has a list, we can add a linux pre-reqs section.
> Or do they all come with devtools in R?

They all seem to come as a consequence of devtools, but they're not all 
installed by R, they include regular OS packages that the R packages 
depend on. At a minimum: libxml2, libssl-dev, curl, and git. I am not 
sure if there are additional ones

On the rstan quickstart page you could probably make the following change:
- For Linux, use your package manager to install build-essential and a 
  recent version of either g++ or clang++.
- For Linux, use your package manager to install build-essential, curl, 
  git, libxml2, libssl-dev and a recent version of either g++ or clang++, 
  then use the R function install.packages to install the CRAN package 
  "devtools".

**Comment by bob-carpenter** [comment]
Thanks --- I'll add that.
- Bob

**Comment by bgoodri** [comment]
Can you try installing rstan again from CRAN this time? The devtools package is no longer required.
