### ISSUE TITLE
instance of traceplot being masked

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#174]
@bgoodri, is there any way to check if `traceplot` is masked by a different library? This came up today.

**Comment by bgoodri** [comment]
It says so when you load the coda package

```
> library(coda)

Attaching package: ‘coda’

The following object is masked from ‘package:rstan’:

    traceplot
```

**Comment by syclik** [comment]
Ah. A user must have had that in a startup script. Never saw that warning.
What's the best advice to work around it?

**Comment by bgoodri** [comment]
load rstan after coda

**Comment by syclik** [comment]
Thanks. And there's no way to make R dispatch properly on a stanfit object?

**Comment by bgoodri** [comment]
Maybe we can change traceplot to an S3 method

**Comment by jgabry** [comment]
If `traceplot` is masked then `stan_trace` or `rstan::traceplot` can be used.
