### ISSUE TITLE
 no 'nobs' method is available when trying to compare Rstan models

### ISSUE THREAD

**Issue by mauritsvzb** [stan-dev/rstan#178]
Dear all,

I'm trying to compare the dWAIC and weight of different models using the RStan package v 2.6.0. However, when I try to execute the command "models <- compare(m3,m4,m5,m6,m7,m8))", I get the following error message returned: 

"Error in nobs.default(X[[i]], ...) : no 'nobs' method is available"

Any suggestions to how to solve this issue is greatly appreciated.

Thank you,
Maurits

**Comment by bgoodri** [comment]
There is no `compare` function, so you must be getting that from some other package. It is true that there is no `nobs` method available for `stanfit` objects but that is because there is no way of telling how many observations you have for an arbitrary model. Finally, although I doubt it would overcome this problem, you should really use rstan >= 2.7.0 rather than 2.6.0.

**Comment by jgabry** [comment]
There's a compare function in the loo package. Is that what you're using? It works differently than the way you seem to be using it though. If you're indeed using the function in the loo package let us know and we can give more specific advice.

**Comment by mauritsvzb** [comment]
Thank you both for your responses. I just updated to the latest version of RStan, and as predicted it does not solve the problem.

I'm not using the LOO package, but is it also able to provide me with dWAIC and weights ? The compare() function I tried to use is based on a university lecture on statistics.

Best, 
Maurits

**Comment by bgoodri** [comment]
I don't think LOO does weights yet (although it should) but it does
everything else. If you are referring to the compare() function in the
rethinking package, then you should ask Richard or have Richard talk with
us.

**Comment by mauritsvzb** [comment]
It may actually be the compare function in my OP may be referring to the rethinking package. I just sent Richard a personal email to ask for his help. Thank you.
