### ISSUE TITLE
Function to read command-line .csv files into simpler object than stan-fit

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#18]
It would be nice to be able to read command-line output into RStan for plotting and analysis.  This would need to read multiple .csv files as produced by Stan command line.  

This should also make it easy to read in data produced by JAGS or other programs so that we can use our own split-R-hat and n_eff calculations.  

Basically, what I'm saying is that it'd be nice to be able to use a part of RStan like Coda.  In fact, it might make sense breaking it out into a separate package and then have RStan depend on the Coda-like package.

This will probably require re-organizing the way that stan-fit is put together (I don't know the internals), so that an object just holding the samples can be isolated.  Then functions like traceplots should be based on the contained object, since they shouldn't need access to the model.  (One issue is where the names come from --- that may be from the model at this point, in which case they'll have to be finagled into the separate fit object.)

**Comment by jgabry** [comment]
Closing this old issue since we now do have a way of reading cmd line csv files into R for plotting, etc.
