### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by JuliaPalacios** [stan-dev/rstan#182]
Hi,

I just installed rstan following the instructions on (https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#how-to-install-rstan) on Mac OS X 10.9.5. After trying to attempt the schools example, I get:

schools_fit<-stan(file="schools.stan",data=c("J","y","sigma"),iter=1000,chains=1)
COMPILING THE C++ CODE FOR MODEL 'schools' NOW.
clang: error: unknown argument: '-ffat-lto-objects' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: **\* [file6d97f1eff65.o] Error 1 

------487 more lines-------
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! clang: error: unknown argument: '-ffat-lto-objects' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: **\* [file6d97f1eff65.o] Error 1
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file6d97f1eff65.cpp 2> file6d97f1eff65.cpp.err.txt' had status 1 

Any help would be much appreciated. 

Julia Palacios

**Comment by maverickg** [comment]
it looks like that you are careful enough of following the instruction.  The instruction says do the following for gcc 4.9 or higher:

```
cat("\nCXXFLAGS+=-flto -ffat-lto-objects", 
    file = M, sep = "\n", append = TRUE)
```

But you have clang on Mac.  So you should undo this step if I am right.

**Comment by JuliaPalacios** [comment]
It looks like it! Thank you
