### ISSUE TITLE
Draw separate trace plots for each chain

### ISSUE THREAD

**Issue by dvukcevic** [stan-dev/rstan#184]
It would be useful to have the `traceplot()` function be able to draw separate plots for each chain.  At the moment all of the chains are overplotted, which makes it hard to see if specific chains are behaving differently to the rest.

I think one good approach would be to have a grid of plots, with one row per parameter and one column per chain.  That lets you easily compare across chains for the same parameter, and across parameters for the same chain.  For example, you could easily see where chains get stuck by inspecting down a column and seeing all the parameters flatline at the same place.

**Comment by bob-carpenter** [comment]
Thanks for filing this as an issue --- it makes it much
easier for us to keep track of.

Have you tried shinyStan?  It allows all kinds of flexiblity, including
this, for exploring posteriors.  The new version that Jonah's about
to release will also allow exporting of all the graphs as ggplot2
code.

Andrew's been rethinking all of the output we produce, and I
think a lot of it will be rewritten for Stan 3.  But that's not
going to be out for quite a while, so it's not going to help right
away.

It'd be easy to make these plots yourself using ggplot2.  If
you do that, feel free to post your code back here so other people
(including us) can use it.
- Bob

**Comment by bgoodri** [comment]
I would echo Bob's comment to just use ShinyStan for pretty much everything, which allows you to select chains and zoom in on a subwindow of the iterations. Or do `arr <- as.array(stanfit)` and call `lines()` on its second and third dimensions. Or do `As.mcmc.list(stanfit)` and use coda's traceplot, which does each parameter and chain separately. If someone wanted to add options like this to rstan's traceplot() function I would merge them, but in light of the alternatives, I don't think it is enough of a priority for me to do personally.
