### ISSUE TITLE
thinning a fit object

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#187]
I don't even know if this will be relevant going forward, but it'd be nice to be able to thin an existing fit object.  Cameron Bracken requested this functionality on the dev list.

Feel free to just kill this issue if you don't want to do it or there's already an easy way to do it.

**Comment by bgoodri** [comment]
Jonah had a solution

```
sub_sample <- function(stanfit, n, keep_warmup = TRUE) {
  sim <- stanfit@sim
  samp <- sim$samples
  W <- sim$warmup
  I <- sim$iter
  sel <- c(if (keep_warmup) 1:W, sample((W + 1):I, size = n))
  subsamp <- lapply(samp, function(chain_samp) {
    lapply(chain_samp, function(x) x[sel])
  })
  stanfit@sim$samples <- subsamp
  stanfit
}
```

but I don't think we want to encourage thinning by actually implementing it in rstan.
