### ISSUE TITLE
allow data to be passed to init function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#19]
Suggestion from Jo(h)n Smith on stan-users:

Pass the data in as an argument to the initialization function.  

I don't know how easy that will be to do and maintain backward compatibility.  

If it's too hard, there are two workarounds:

* just make sure the data is in scope for the function

* write a higher-order function that takes the data as an argument and returns an init function

In fact, I like the second approach enough that it probably makes this feature request redundant.  Maybe we could add an example to the doc and just close this issue.

**Comment by jgabry** [comment]
closing outdated issue
