### ISSUE TITLE
remove -mtune=core2 and -arch x86_64

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#196]
This is what a user reported RStan doing:  

```
CXXFLAGS = -Wall -mtune=core2 -O3 $(LTO)  #set_by_rstan
```

whereas here's what I have in my ./R/Makevars after 2.7.0 install:

```CXX=g++ -arch x86_64 -ftemplate-depth-256 -stdlib=libstdc++
CXXFLAGS= -O3 $(LTO)     #set_by_rstan
R_XTRA_CPPFLAGS =  -I$(R_INCLUDE_DIR)      #set_by_rstanCC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256
CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256
CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256

CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256

CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256

CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256

CXXFLAGS=-O3

```

So it looks like installs are trailing lots of previous settings behind them.  I also don't think

But we do not want to hard code the `-mtune=core2` thing because many of us are not using core2 CPUs.  I have a quad-core i7, for example.
```

**Comment by aadler** [comment]
When you install a package from CRAN (at least on Windows), unless you have your own Makevars, the installer tends to copy over the EOPTS that were set when R was compiled. The default EOPTS for R (at least in Windows) is mtune=core2. That's probably where it is coming from. If you build R from source, on any platform, you'll probably have already substituted a different mtune/march already.

**Comment by bob-carpenter** [comment]
Is there a way to fix it without having my install R from source?
I have enough build headaches already in my life.
- Bob

**Comment by jgabry** [comment]
Thanks Avi, I hadn't thought of that but I think that's probably what's
going on.

Bob, I don't see where RStan is imposing core2 anywhere, so Avi's
explanation makes sense. I hope Ben or Mav can tell us if I'm wrong about
that.

**Comment by bob-carpenter** [comment]
I don't care where it's coming from --- can you get rid of it?
Or do we need to go back to instructions where people edit their
Makevars by hand?

**Comment by maverickg** [comment]
If you have it, it was from previous installation from rstan: it's mostly copied from the file installed by R.  So if you don't touch file ``R RHOME``/etc/Makeconf file, having them in ~/.R/Makevars as what you have now is no different than not having them.

**Comment by aadler** [comment]
In the old days (pre-CRAN stan) installing rstan created one and took the CFLAG/CXXFLAGS from my src/gnuwin32/Mkrules.local but if I had one, it didn't touch it. Perhaps on the original user's operating system, the check for Makevars is broken and rstan is automatically pulling from one of the Makefiles?

**Comment by bob-carpenter** [comment]
OK, but if I have it, lots of people may have it. 

I can update and see if it makes a difference in speed.
I the Makevars what gets used for building a model?
- Bob

**Comment by aadler** [comment]
Yes, on Windows, HOME/.R/Makevars is the file you use for C/PP/XXFLAGS, FFLAGS, and other variables (JAGS_HOME, NLOPT_HOME, etc.)

**Comment by bgoodri** [comment]
I don't think rstan is adding `-mtune=core2` anywhere and it isn't in the wiki. Although `-mtune=native` is usually a better choice anyway. My impression was that the "-arch x86_64 -ftemplate-depth-256" was necessary on Macs (at least at one point).

**Comment by bgoodri** [comment]
I'm not sure this ever constituted an issue. Closing.
