### ISSUE TITLE
RStan 2.7 Getting started guide links to v2.6 reference manual

### ISSUE THREAD

**Issue by seanpor** [stan-dev/rstan#198]
At the bottom of the page
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

The reference "The Stan Development Team (2014). Stan Modeling Language User's Guide and Reference Manual." links to 
https://github.com/stan-dev/stan/releases/download/v2.6.0/stan-reference-2.6.0.pdf
where it should probably link to
https://github.com/stan-dev/stan/releases/download/v2.7.0/stan-reference-2.7.0.pdf
with a revised year to 2015 above

**Comment by jgabry** [comment]
Thanks. Should be fixed now.
