### ISSUE TITLE
rstan segfault after Debian upgrade

### ISSUE THREAD

**Issue by tpapp** [stan-dev/rstan#203]
Today I upgraded quite a few packages on my Debian system (`dist-upgrade`), including the c++ compiler. RStan now segfaults with the message `address 0x20, cause 'memory not mapped'`.

I removed rstan and installed from CRAN, does not help. The whole R session transcription is in this gist:
https://gist.github.com/tpapp/bfb17b0a44f845ccaf14

g++ version 4:5.2.1-4.

**Comment by bgoodri** [comment]
Yeah, I have experienced the same thing on my Debian unstable system. I am currently leaning toward thinking it is a Debian bug rather than a rstan bug because things seem to be fine with my r-devel compiled from the subversion sources. Also, I have been able to use rstan with the r-base-core if I reinstall Rcpp and make sure rstan and the .stan program are compiled with the same settings. But any additional information as to what does or does not work for you would certainly be appreciated.

**Comment by syclik** [comment]
Have you restarted R in between the uninstall and install? Have you also
reinstalled the dependencies, especially Rcpp and RcppEigen?

I see those issues when there's an incompatible built library somewhere on
my system. Sometimes the uninstall process doesn't actually remove the
libraries if the R process has a hold of it, so I tend to close R at nearly
every step, but you might have better luck than I do.

And... what version of g++ is that? I don't understand the colon.

**Comment by tpapp** [comment]
@syclik: Yes, I did restart, and did reinstall everything. This does not help. The version is `5.2.1`.

@bgoodri: The following is a workaround:
1. install all the 4.9 packages (`cpp-4.9`,`g++-4.9`, `gcc-4.9`, `gfortran-4.9`)
2. use the following `~/.R/Makevars`:

``` bash
CC=gcc-4.9
CXX=g++-4.9
CXXFLAGS=-O3
CXXFLAGS+=-flto -ffat-lto-objects
```
1. remove `Rcpp`,`RcppEigen`, and `rstan`, then reinstall all three.

But this is just a workaround. 5.2 is in `debian/testing`, which many people use (Debian releases are infrequent), so it would be great to find the source of this — let me know if I can supply more debugging info.

**Comment by bgoodri** [comment]
This is real bad, but I do not yet have any reason to believe it is an rstan bug. My guess is that some libfoo is not transitioned to the g++-5 ABI yet. Or it could be a bug in Rcpp that was exposed by the transition.

I can also get it to work with clang++ using the libc++ library from testing (but not unstable).

**Comment by tpapp** [comment]
@bgoodri: I was not implying that there is a bug in rstan, but even if it is somewhere else, tracking it down and reporting it at the right place is beyond my skills. If your guess is correct, it would make sense to try again in a few months once things settle down in Debian/testing.

In the meantime, if someone finds this issue and wants to use my workaround, the following `.R/Makevars` is better as it allows the compilation of both `rstan` and other libraries:

``` bash
CC=gcc-4.9 -std=gnu99
CXX=g++-4.9
CXXFLAGS+=-O3
CXXFLAGS+=-flto -ffat-lto-objects
FC=gfortran-4.9
F77=gfortran-4.9
```

Note that in contrast to the rstan wiki, I have an `+=` before the `-O3`, so that R's default flags do not get overwritten; the last `-O` should be effective.

**Comment by bgoodri** [comment]
My latest push to the development branch seems to help somewhat. Can you try it with g++-5 on your system, although you will probably have to reinstall Rcpp, RcppEigen, and rstan?

**Comment by tpapp** [comment]
Sorry for the delay, I had something that had a deadline and did not want to risk my toolchain. I tried 776e4f45e097e265d0289187c850df4810b3c2c6 today and it works fine — I am using `.R/Makevars`

``` bash
CXXFLAGS += -O3 -pipe   $(LTO)     #set_by_rstan
R_XTRA_CPPFLAGS =  -I$(R_INCLUDE_DIR)      #set_by_rstan
```

and did recompile `Rcpp`, `RcppEigen`, and of course `rstan`.

I think that you can close the issue. Thanks for the quick fix!

**Comment by bgoodri** [comment]
You have it working with g++-5? I can't even do that, although my unstable is complicated by multilibness.

**Comment by tpapp** [comment]
Yes, everything works fine with

``` bash
tamas@tamas:~$ dpkg -l g++ g++-5 cpp gfortran gcc
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-================================================================================
ii  cpp                                   4:5.2.1-4               amd64                   GNU C preprocessor (cpp)
ii  g++                                   4:5.2.1-4               amd64                   GNU C++ compiler
ii  g++-5                                 5.2.1-16                amd64                   GNU C++ compiler
ii  gcc                                   4:5.2.1-4               amd64                   GNU C compiler
ii  gfortran                              4:5.2.1-4               amd64                   GNU Fortran 95 compiler
```

**Comment by bgoodri** [comment]
I think this can be closed.
