### ISSUE TITLE
Compiler problem after installation on windows

### ISSUE THREAD

**Issue by cgettings** [stan-dev/rstan#208]
@bgoodri (This is @jgabry writing from one of Andrew's student's accounts) We're installing Stan and getting a very strange error when trying to compile the 8 schools model on Windows after rstan installation:

Error in .Call(Module__classes_info, xp) : 
  cannot allocate vector of length 1790997162
In addition: Warning message:
running command '"C:/PROGRA~1/R/R-32~1.0/bin/i386/R" CMD config CXX' had status 2

Have you seen this error before? Thanks!

**Comment by bgoodri** [comment]
No, but it seems to have run out of RAM. Make sure there is no -g or
anything like that in the ~/.R/Makevars file.

**Comment by cgettings** [comment]
Thanks. Unfortunately nothing like that in the Makevars file. And there seems to be at least 3 or 4 gigs of RAM available before trying to compile the eight schools model

**Comment by bgoodri** [comment]
The mingw compiler for Windows can consume a lot more memory than one would
expect. Can your provide some virtual memory (swap space) or try to close
anything else that may be running? You can also watch what used to be
called Task Monitor on Windows to see it approach the memory limit.

**Comment by syclik** [comment]
Is that a 32 bit machine?

**Comment by bgoodri** [comment]
Yes; see the OP

**Comment by jgabry** [comment]
We tried freeing up memory, as well as switching to g++ but kept getting
the same error.

The machine doesn't have an enormous amount of memory but if I recall
correctly it has 6 gigs and more than half was free after we closed a bunch
of other things.

**Comment by bgoodri** [comment]
This is the CRAN version of rstan or the development one?

**Comment by jgabry** [comment]
Cran at first, then I tried the development version.

**Comment by jgabry** [comment]
Actually no, I was going to try the development version but I think we
didn't end up installing it.

**Comment by jgabry** [comment]
So if I remember correctly it's still the CRAN version. Christopher (or do
you prefer Chris?) can you double check? You can just look at the version
number of the rstan package by looking in the rstudio packages window (or
packageVersion('rstan')).

There were several installation issues we were dealing with so I can't
quite remember where we left it.

**Comment by jgabry** [comment]
Fortunately there were only a handful of students who were having
installation trouble, so that's good (and most we were able to sort out I
think).

Unless many of them hadn't tried to install it yet and didn't say anything
when he asked.

**Comment by bgoodri** [comment]
Try putting

CXXFLAGS = -Os -g0

into Makevars

**Comment by cgettings** [comment]
I have rstan version 2.7.0-1

**Comment by cgettings** [comment]
Alright, so: I edited the Makevars file, put it in my home directory, and it worked. To further test the solution I removed the Makevars file from 'home', exited and relaunched RStudio, and then ran the model again and... it worked, still. 

I _was_ able to recreate the problem, however. During some tests I included `options(mc.cores = parallel::detectCores())` (from the [RStan Getting Started](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) guide), and this gave me the original error message 

`Error in .Call(Module__classes_info, xp) : 
    cannot allocate vector of length 1790997162`    

Looking back through my history, I see that every unsuccessful attempt today has included setting this `mc.cores` option. Every successful attempt has left it out.

For the record, I've done simulations in parallel using `doSnow` and `doParallel`, so I'm fairly certain that the problem is not with my machine's RAM or reluctance to engage in parallel processing. I do know that `parallel` doesn't work in Windows, though, which is why I've used the alternatives.

So I wonder if there's something about RStan's `mc.cores` options that, when set with `parallel`, just doesn't get along with Windows?

Thanks very much to Jonah and Ben for the help!

Edit: FYI:
I _am_ still getting the `'"C:/PROGRA~1/R/R-32~1.0/bin/i386/R" CMD config CXX' had status 2` warning message.

**Comment by bgoodri** [comment]
That warning is a harmless bug that got fixed since then I think. Windows gives us more problems that any other operating system, but many people have used Windows (usually 64bit) to run `stan` in parallel. Like the startup message says, parallel is more situations with excess RAM, and with a 32bit system it is always going to be a bit tight since it can't have objects that are more than 4GB. I wouldn't think that would be a problem with the eight schools example, but maybe there is an instant where it makes a copy and needs more RAM than that.

**Comment by jgabry** [comment]
Thanks Ben
