### ISSUE TITLE
'dotlist' not found error when sampling in parallel

### ISSUE THREAD

**Issue by enbrown** [stan-dev/rstan#209]
I'm not sure if this has been found before, but compiling with the most recent development version (commit 7e6f5395dafd1bdb6559906bc9ef3f9d6926956a) gives me an error when running rstan in parallel:

> Error in checkForRemoteErrors(val) : 
>  2 nodes produced errors; first error: object 'dotlist' not found

I think that this is related to line 416 in stanmodel-class.R which was:

`if(is.list(.dotlist$init)) dotlist$init <- dotlist$init[i]` and probably should be `if(is.list(.dotlist$init)) .dotlist$init <- .dotlist$init[i]`

**Comment by bgoodri** [comment]
This was fixed by bc98f46b a long time ago. Sorry to not mention it at the time. Thanks for reporting.
