### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by adjidieng** [stan-dev/rstan#211]
Hi,

Operating System: OS X Yosemite 10.10.5
StanHeaders version: 2.8.0
rstan version: 2.7.0.1

When I run stan(arguments), I get the following compilation error:

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! clang: warning: optimization flag '-ffat-lto-objects' is not supported
clang: warning: argument unused during compilation: '-ffat-lto-objects'
In file included from file91515d85a54.cpp:316:
In file included from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rstan/include/rstan/stan_fit.hpp:80:
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rstan/include/rstan/io/rlist_ref_var_context_factory.hpp:4:10: fatal error: 'stan/interface/var_context_factory/dump_factory.hpp' file not found
# include <stan/interface/var_context_factory/dump_factory.hpp>

```
     ^
```

1 error generated.
make: **\* [file91515d85a54.o] Error 1
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file91515d85a54.cpp 2> file91515d85a54.cpp.err.txt' had status 1 

I think there is one header file that is not being linked properly. 

Thank you for any help on this!

**Comment by jgabry** [comment]
StanHeaders 2.8.0 isn't compatible with RStan < 2.8.0. I believe RStan
2.8.0 will be submitted to CRAN today, which should solve this problem.
Until then you could try installing the previous StanHeaders:

```
library(devtools)
install_url("https://cran.rproject.org/src/contrib/Archive/StanHeaders/StanHeaders_2.7.0.tar.gz")
install.packages("rstan", dependencies = TRUE) # from CRAN`
```

 Alternatively, you could keep the new StanHeaders and try installing RStan
from GitHub:

```
library(devtools)
install.packages("StanHeaders") # from CRAN
install_github("stan-dev/rstan", subdir = "rstan/rstan", ref = "develop")
```

**Comment by jgabry** [comment]
Thanks for posting the details. If the solutions I suggested don't work let us know.

**Comment by adjidieng** [comment]
Thanks a lot! The last solution worked perfectly...

**Comment by jgabry** [comment]
Ok great, glad it works.
