### ISSUE TITLE
`expose_stan_functions` is exposing all but one function

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#214]
@bgoodri I have several functions in the `functions` block of a Stan program that compiles and runs fine. However, when I call  `expose_stan_functions` all of the functions are exposed to R except for one of them. The function that's missing is this one:

```
real[] lagged_y(int[] y, int[] id, int[] t) {
  real out[size(y)];
  out[1] <- 0.5;
  for (n in 2:size(out)) {
    if (id[n-1] == id[n] && t[n-1] == (t[n] - 1))
      out[n] <- y[n-1];
    else
      out[n] <- 0.5;
  }
  return out;
}
```

Any reason you know of why `expose_stan_functions` wouldn't work for this particular function?

**Comment by bgoodri** [comment]
It looks as if the export statements do not get inserted correctly

Warning message:
In Rcpp::sourceCpp(code = paste(lines, collapse = "\n")) :
  No Rcpp::export attributes or RCPP_MODULE declarations found in source

I'll try to fix it tonight.

**Comment by bob-carpenter** [comment]
If I were to add something that generated a double-based version of
the function in the model without template params, would that be sufficient?
I can mangle the name to prevent any kind of compiler conflict, but that
shouldn't be necessary.

If that's not enough, what else needs to be done?  I remember something about
std::vector vs. Eigen::Matrix, or was that for Python?

Anyway, if one of you guys wants to start an issue for stan-dev/stan and assign
it to me (for next release --- I don't want this to drop out of sight before
I do it), I can get the code generation done so we don't need to monkey
with syntactic transforms via string manipulation.
- Bob

**Comment by jgabry** [comment]
On Wednesday, September 23, 2015, bgoodri notifications@github.com wrote:

> Warning message:
> In Rcpp::sourceCpp(code = paste(lines, collapse = "\n")) :
> No Rcpp::export attributes or RCPP_MODULE declarations found in source

Should I be seeing these warnings too or are they typically suppressed
internally? I don't actually get any warnings from expose_stan_functions.

**Comment by jgabry** [comment]
Bob, I don't understand the source of the problem well enough to say. Ben
knows what's going on with expose_stan_functions much better than I do (he
wrote it) so hopefully he will know.

**Comment by bgoodri** [comment]
I think this particular thing will be easy enough to fix. The longer term
plan of having outside-the-namespace versions of the user-defined functions
that are specialized for doubles and just call the inside-the-namespace
versions is more complicated because Rcpp::sourceCpp would have to be
capable of compiling a whole .stan file, which would require some clever
stuff because Rcpp::sourceCpp doesn't do -I or -isystem to look for header
files in directories.
