### ISSUE TITLE
include in stan() not passed to sampling()

### ISSUE THREAD

**Issue by ihrke** [stan-dev/rstan#215]
The argument `include=TRUE` is not passed through to the call to `sampling()` in the `stan()` function.
This means, that the following call

``` R
stan(model.fname, pars=c("ignored.par"), include=FALSE)
```

will sample only `ignored.par`. According to the documentation, it should sample all variables _except_ `ignored.par`.
Here is the relevant snippet from the current version of `rstan` (taken from the current master branch):

``` R
stan <- function(file, model_name = "anon_model", 
# ...
                 verbose = FALSE, include = TRUE,
# ...
                 eigen_lib = NULL) {
# ...
  sampling(sm, data, pars, chains, iter, warmup, thin, seed, init, 
           check_data = TRUE, sample_file = sample_file, 
           diagnostic_file = diagnostic_file,
           verbose = verbose, algorithm = match.arg(algorithm), 
           control = control, check_unknown_args = FALSE, 
           cores = cores, open_progress = open_progress, ...)
} 
```

**Comment by jgabry** [comment]
@ihrke Thanks for reporting. Should be fixed now in the `develop` branch.
