### ISSUE TITLE
bug in unconstrain_pars?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#217]
On stan-users Sebastian Weber [reported a bug](https://groups.google.com/forum/#!topic/stan-users/t3EwilLYfSs) in `traceplot`, but it seems to be a bug in `unconstrain_pars`. 

The error seems to happen with vectors of length 1. I was able to replicate the error with this simple example:

```
stancode <- "
parameters {
  vector<lower=0>[1] tau;
}
model {
  tau ~ exponential(1);
}"
fit <- stan(model_code = stancode)
pars <- extract(fit, permuted = FALSE, inc_warmup = TRUE)
skeleton <- get_inits(fit)[[1L]]
upars <- apply(pars, 1:2, FUN = function(theta) {
  unconstrain_pars(fit, relist(theta, skeleton))
})

Error: mismatch in number dimensions declared and found in context; processing stage=initialization; variable name=tau; dims declared=(1); dims found=()
Called from: object@.MISC$stan_fit_instance$unconstrain_pars(pars)
```

**Comment by maverickg** [comment]
When the data are passed from R to the C++ part, if you want to specify an array of length 1, it needs to be done explicitly at R side.  Using the following code would fix the problem here

```

skeleton <- rstan:::create_skeleton(fit@model_pars, fit@par_dims)['tau']
upars <- apply(pars, 1:2, FUN = function(theta) {
  unconstrain_pars(fit, rstan:::rstan_relist(theta, skeleton))
})
```

**Comment by jgabry** [comment]
Ok, I see. Thanks.

**Comment by maverickg** [comment]
Note that `unconstrain_pars` can not be even applied in some cases:

What I can think of for now are:
-  when a stanfit object is created from reading csv file

```
> traceplot(fit, unconstrain = TRUE)
Error in get_inits(object)[[1L]] : subscript out of bounds
```
- when a stanfit is created from reading a saved stanfit, 

```
> library(rstan)
> b <- readRDS('a.rds')
>
> traceplot(b, unconstrain = TRUE)
Error in .local(object, ...) :
  the model object is not created or not valid
```

**Comment by jgabry** [comment]
Thanks Mav, very helpful.
