### ISSUE TITLE
File connections not being cleaned

### ISSUE THREAD

**Issue by wesleyburr** [stan-dev/rstan#219]
I'm not sure exactly what combination of things has led to this, and I have a work-around, but I thought I'd make you aware of something I came across today. I am fitting 208 versions of the same model (compile once, run many). I have a for loop that runs through 8 different variations, each of which consists of 26 different subsets. After the first ~ 50 or so such subsets have been run, R kills the loop because it is unable to open a temporary file handler, error:

```
Error in file(file, "r") : all connections are in use
```

Doing `showConnections()` indicates that there are a very large number of temporary file connections open. Doing a `closeAllConnections()` at the end of the inside of the

``` R
   for(j in 1:8) { } 
```

loop corrects the crash and allows the entire loop through the cases to complete. So, something inside rstan is creating temporary files, but isn't doing effective garbage collection and closing them, which eventually causes R to run out of file connections, and terminate the process. Obviously this can't be happening all the time, or everyone who tried to run a bunch of models would be experiencing it, so here's my system details which might help narrow it down.

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 20 (Heisenbug)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       
```

My processor: i7-3740QM, running "8 cores" for R's parallel options. 

Sorry I can't be more precise than this on the error: I've only come across it once (today, with this data), and I can't share the data freely for replication. The model is shown below.

``` stan
data {
  int<lower=0> J;
  real samSE[J];
  real betahat[J];
}
parameters {
  real Mu;
  real<lower=0> Sigma;  
  real citybeta[J];
}
model {
  Mu ~ normal(0, 100);
  Sigma ~ uniform(0, 1);

  for(j in 1 : J) {
    citybeta[j] ~ normal(Mu, Sigma);
    betahat[j] ~ normal(citybeta[j], samSE[j]);
  }
}
```

**Comment by bob-carpenter** [comment]
Thanks --- this indeed looks like a bug.  Presumably it'll
be easy to fix in R.
- Bob

**Comment by mkuhn** [comment]
Hi Bob, I created a pull request that fixes this bug a few days ago: #218

**Comment by bob-carpenter** [comment]
Thanks for linking.  When that gets merged we should close this issue.  One of the RStan devs will have to review it, though.

**Comment by jgabry** [comment]
Thanks. Will definitely take a look at the PR and get this taken care
of before the next release.

**Comment by maverickg** [comment]
code to replicate this error

```
library(rstan)
fit <- stan(model_code = "parameters { real<lower=0, upper=1> y; } model { }", chains = 1)
for (i in 1:10000) stan(fit = fit, chains = 1)
```

I don't understand why #218 adds prefix to the temporary file.   so for now, I am gonna borrow part of  #218 to fix this issue: https://github.com/stan-dev/rstan/commit/ea076596f4d49bd92a72bc045053f7ce4597461e.

**Comment by mkuhn** [comment]
I added prefixes to all temp files to be able to check with showConnections
which part of the code had the problem.

**Comment by maverickg** [comment]
@mkuhn I see.  Thanks a lot.
