### ISSUE TITLE
RStan reliably crashes R on Windows 7 when reusing a previously compiled model

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#221]
I haven't tried this in Rstan 2.8 yet, but RStan 2.7 reliably crashes R on Windows 7 if you reuse a precompiled model. In particular, if you call

  fit <- stan(model_code = model, ...)

and then later call stan() again with the same model code string, it causes R to crash. The only way to avoid this is to tweak the model code string (say, add or remove some white space) to force stan() to recompile the model.

**Comment by maverickg** [comment]
Can you please try 2.8?

**Comment by bgoodri** [comment]
Yes, this was a known problem with 2.7.

**Comment by ksvanhorn** [comment]
I verified that it's no longer a problem in 2.8. Thanks.
