### ISSUE TITLE
in DESCRIPTION, the version of StanHeaders should be EQUAL to that of rstan

### ISSUE THREAD

**Issue by jhjourdan** [stan-dev/rstan#224]
Using rstan with a different version of StanHeaders seems not supported. So, It would be good to force the versions of rstan and StanHeaders to be equal in the DESCRIPTION file.

**Comment by bgoodri** [comment]
rstan MAJOR.MINOR needs to have at least StanHeaders MAJOR.0. In other words, rstan 2.8.1 from GitHub does work with StanHeaders 2.8.0 from CRAN, but there is no way to specify that condition. But rstan 2.8.x does not work with StanHeaders 2.7.0.
