### ISSUE TITLE
Accumulated warnings are printed to stdout instead of stderr

### ISSUE THREAD

**Issue by mkuhn** [stan-dev/rstan#226]
The following code in [stanmodel-class.R](https://github.com/stan-dev/rstan/blob/ea076596f4d49bd92a72bc045053f7ce4597461e/rstan/rstan/R/stanmodel-class.R#L535) prints the accumulated warnings to stdout, instead of stderr (like `message`). It would be nicer to have both `msg` and `mat` in the same stream.

```
                  if (.Platform$OS.type == "windows") print(msg)
                  else message(msg)
                  mat <- as.matrix(tab)
                  colnames(mat) <- "count"
                  print(mat)
                  if (.Platform$OS.type == "windows") print(end)
                  else message(end)
```

**Comment by bgoodri** [comment]
I think I tried using `message` to output the contents of `mat` and it didn't work so well when `mat` had more than 1 row. Suggestions?

**Comment by mkuhn** [comment]
It's a bit ugly, but this might do the job:

```
message(paste(capture.output(print(mat)), collapse = "\n"))
```

**Comment by bgoodri** [comment]
OK, I'm putting this in. It seems to look fine on my laptop.
