### ISSUE TITLE
fix travis for Linux

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstan#229]
it looks as if it got a new version of git or something

**Comment by maverickg** [comment]
it looks like that an older version of git than before was used.

**Comment by maverickg** [comment]
Changed to use dist trusty, but it still fails for a problem of setting the environment for building R package.  Report this problem to https://github.com/travis-ci/travis-ci/issues/5086

**Comment by maverickg** [comment]
There is no problem with dist trusty after a fix on travis.  Close this now.
