### ISSUE TITLE
rstan 2.8.2 problems running in parallel : Error in list.files(lib, pattern = paste0("^", pkg, "$"), full.names = TRUE) : invalid 'pattern' regular expression

### ISSUE THREAD

**Issue by gsb2** [stan-dev/rstan#244]
Hello:

I recently upgraded to rstan 2.8.2 and successfully ran the 8schools
example with one chain.

When I attempted to run multiple chains (in parallel), I got the
following error at the R console:

Error in list.files(lib, pattern = paste0("^", pkg, "$"), full.names =
TRUE) :  invalid 'pattern' regular expression

Here is the R feedback:

> options(mc.cores = parallel::detectCores())
> fit <- stan(file = '8schools.stan', data = schools_dat, iter = 1000, chains = 3)
> cygwin warning:
>   MS-DOS style path detected: C:/WORKSP~1/R-31~1.3/etc/x64/Makeconf
>   Preferred POSIX equivalent is: /cygdrive/c/WORKSP~1/R-31~1.3/etc/x64/Makeconf
>   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
>   Consult the user's guide for more details about POSIX paths:
>     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
> Error in list.files(lib, pattern = paste0("^", pkg, "$"), full.names = TRUE) :
>   invalid 'pattern' regular expression
> 
> traceback()
> 12: list.files(lib, pattern = paste0("^", pkg, "$"), full.names = TRUE)
> 11: find.package(package, lib.loc, quiet = TRUE)
> 10: system.file(package = d)
> 9: dirname(system.file(package = d))
> 8: FUN(c("Rcpp", "rstan", "rstanarm", "methods", "stats4", "inline",
>    "gridExtra (>= 2.0.0)", "Rcpp (>=", "0.11.0)")[[8L]], ...)
> 7: lapply(X = X, FUN = FUN, ...)
> 6: sapply(dependencies, FUN = function(d) {
>        dirname(system.file(package = d))
>    })
> 5: unique(sapply(dependencies, FUN = function(d) {
>        dirname(system.file(package = d))
>    }))
> 4: .local(object, ...)
> 3: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,
>        check_data = TRUE, sample_file = sample_file, diagnostic_file =
> diagnostic_file,
>        verbose = verbose, algorithm = match.arg(algorithm), control = control,
>        check_unknown_args = FALSE, cores = cores, open_progress = open_progress,
>        include = include, ...)
> 2: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,
>        check_data = TRUE, sample_file = sample_file, diagnostic_file =
> diagnostic_file,
>        verbose = verbose, algorithm = match.arg(algorithm), control = control,
>        check_unknown_args = FALSE, cores = cores, open_progress = open_progress,
>        include = include, ...)
> 1: stan(file = "8schools.stan", data = schools_dat, iter = 1000,
>        chains = 3)
> sessionInfo()
> R version 3.1.3 (2015-03-09)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rstan_2.8.2   ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] codetools_0.2-14 colorspace_1.2-6 digest_0.6.8     grid_3.1.3
 [5] gridExtra_2.0.0  gtable_0.1.2     inline_0.3.14    magrittr_1.5
 [9] MASS_7.3-44      munsell_0.4.2    parallel_3.1.3   plyr_1.8.3
[13] proto_0.3-10     Rcpp_0.12.2      reshape2_1.4.1   scales_0.3.0
[17] stats4_3.1.3     stringi_1.0-1    stringr_1.0.0    tools_3.1.3

After searching for messages related to this error, I tried the steps
listed here: https://github.com/stan-dev/stan/issues/1712 with no
success.

Best Regards,

**Comment by bgoodri** [comment]
I think this was fixed by d980de76f6906057d129d0eebf83b000f484db63
