### ISSUE TITLE
getting compiler error on rstan 

### ISSUE THREAD

**Issue by johnsonrd58** [stan-dev/rstan#249]
In file included from C:/Users/johnson.rd.1/Documents/johnson.rd.1/R/win-library/3.2/rstan/include/rstan/rstaninc.hpp:3:0,
                 from file88462ab3e15.cpp:444:
C:/Users/johnson.rd.1/Documents/johnson.rd.1/R/win-library/3.2/rstan/include/rstan/stan_fit.hpp:69:45: fatal error: stan/services/init/init_adapt.hpp: No such file or directory
compilation terminated.
make: **\* [file88462ab3e15.o] Error 1
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-32~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file88462ab3e15.dll" WIN=64 TCLBIN=64 OBJECTS="file88462ab3e15.o"' had status 2 

ERROR(s) during compilation: source code errors or compiler configuration errors!

[8Schools.docx](https://github.com/stan-dev/rstan/files/79034/8Schools.docx)

**Comment by bgoodri** [comment]
This is due to version mismatch. See 
https://groups.google.com/forum/#!topic/stan-users/JI7xPUcKvM4
