### ISSUE TITLE
vb incorrectly assigns samples to parameters

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstan#251]
After the release of rstan 2.9.0, I have been testing some models using vb and came across the following issue.

For some models, it happens that samples are not correctly assigned to their corresponding parameters. Instead, two parameters may have the exact same samples and (possibly as a result) the assignment between parameter names and samples is incorrect.

I have attached a reproducible example using a simple regression model.
[rstan_vb_bug.zip](https://github.com/stan-dev/rstan/files/81605/rstan_vb_bug.zip)

**Comment by syclik** [comment]
Thanks for reporting the issue. The link is dead. Would you be able to
provide a new link?

**Comment by paul-buerkner** [comment]
Hmm, the link works for me... Lets try again:
[rstan_vb_bug.zip](https://github.com/stan-dev/rstan/files/81623/rstan_vb_bug.zip)

**Comment by bgoodri** [comment]
This is most likely in the post-processing of the CSV file rather than the CSV file itself. I'll look at it.

**Comment by bgoodri** [comment]
There is a bug where one parameter name is a prefix of another parameter name (e.g. `b` and `b_intercept`)
