### ISSUE TITLE
cannot install arules package.please help me to install the package

### ISSUE THREAD

**Issue by Rahuldebchakladar** [stan-dev/rstan#253]
**\* arch - i386
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" SHLIB="arules.dll" OBJECTS="arrayIndex.o bitmat.o istree.o listops.o matrix.o nstats.o params.o ptree.o rapriori.o reclat.o scan.o similarity.o symtab.o tfscan.o tid_count.o tract.o vecops.o warm.o"' had status 127
ERROR: compilation failed for package 'arules'
- removing 'C:/Users/Rahul Deb Chakladar/Documents/R/win-library/3.2/arules'
  Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\Rahul Deb Chakladar\Documents\R\win-library\3.2" "C:/Users/RAHULD~1/Desktop/arules_1.3-1.tar.gz"' had status 1
  Warning in install.packages :
  installation of package ‘C:/Users/RAHULD~1/Desktop/arules_1.3-1.tar.gz’ had non-zero exit status

**Comment by bgoodri** [comment]
As far as I can tell, this installation issue with the arules package has nothing to do with the rstan package, in which case you should be asking the maintainer of arules.
