### ISSUE TITLE
expose_stan_functions bug with error handling

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#259]
original reported through twitter: https://twitter.com/vianey_lb/status/692766634784661504/photo/1

Using rstan 2.9.0.

Here's a minimal example (from within R):

```
library(rstan)
s <- '
functions {
  real foo() {
     reject("rejection message");
     return 0;
  }
}
model { }
'
expose_stan_functions(stanc(model_code = s))
```

The output is:

```
> foo()
Error: *** IF YOU SEE THIS, PLEASE REPORT A BUG ***
```

**Comment by bgoodri** [comment]
Yeah, I need to replace that with "AN EXCEPTION OCCURRED" or something.

**Comment by syclik** [comment]
Can we not bubble up the actual message?
