### ISSUE TITLE
Ability to add "generated quantity" after the fact

### ISSUE THREAD

**Issue by colinorourke** [stan-dev/rstan#262]
Maybe there's already a straightforward way to do this, but it sometimes happens to me that after waiting for a model to run I realize I want to make inferences about some transformation of a parameter, say, exp(p) and I've modelled p in STAN.  If I'd planned ahead I'd have added this to the generated quantities block.  But re-running the model with a new generated quantities block to get such a simple transformation would take a long time.  And extracting the samples, dealing with arrays, transforming them, and then summarizing the posterior samples by hand is very inconvenient.

It would be nice if there was an easy way to add at least simple generated quantities to an existing stanfit object so that they could be summarized, etc. using the readymade functions in rstan.  If there already is functionality to do this I apologize—I couldn't find reference to it by looking through the rstan help or on Google.

**Comment by bgoodri** [comment]
There is not really a good way to do this currently, as it would require recompiling the model. There has been some talk of being able to recompile a second program that basically inputs parameter draws and outputs generated quantities, but that is not implemented yet and is more of a Stan thing than an rstan thing. The best way of doing this currently is to implement your model with user-defined Stan functions as much as possible, export those to R using `expose_stan_functions`, and call those with your posterior draws. If you generated quantity can be represented as a three dimensional array with draws as rows, chains as columns, and generated quantities as the third dimension, then the `monitor` function will summarize them like `summary` does for a `stanfit` object. Just be sure to call `monitor` with `warmup = 0`.
