### ISSUE TITLE
warning: unknown warning option '-Wno-unused-local-typedefs' [-Wunknown-warning-option]

### ISSUE THREAD

**Issue by richardneu** [stan-dev/rstan#269]
#### Summary:

Every time I fit a model using rstan, I get the following warning message:
“warning: unknown warning option '-Wno-unused-local-typedefs' [-Wunknown-warning-option]”
#### Description:

I assume this is a C++ compiler issue.  This guy has it, too:

http://www.psychologie.uni-heidelberg.de/ae/meth/team/mertens/oneway.html
#### RStan Version:

 2.9.0-3
#### R Version:

3.2.3
#### Operating System:

OS X 10.11.3

**Comment by bob-carpenter** [comment]
Do you know which C++ compiler you're using?  

I'm not seeing that on my Mac (OS X 10.10.5, R 3.1.3, clang++
Apple LLVM version 7.0.2), but it's a completely different setup
in terms of versions.
- Bob

**Comment by richardneu** [comment]
Hi Bob,

To be honest, I don’t.  How can I figure that out?  My XCode version is 6.1, if that helps.

Best,

Richard

> Am 25.02.2016 um 14:50 schrieb Bob Carpenter notifications@github.com:
> 
> Do you know which C++ compiler you're using? 
> 
> I'm not seeing that on my Mac (OS X 10.10.5, R 3.1.3, clang++
> Apple LLVM version 7.0.2), but it's a completely different setup
> in terms of versions.
> - Bob
>

**Comment by bob-carpenter** [comment]
It's partly configured through R, but if you haven't changed
that, then it's probably just what you get in a terminal
from 

> clang++ --version

But if you're only on XCode 6.1, that's probably the issue.  I'm
up to 7.2.1.  So it sounds like they introduced that warning
config flag -Wno-unused-local-typedefs later.
- Bob

**Comment by richardneu** [comment]
Hi Bob,

This is what I get:

Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

I’ll try upgrading XCode.

Thanks.

Best,

Richard

> Am 25.02.2016 um 15:12 schrieb Bob Carpenter notifications@github.com:
> 
> It's partly configured through R, but if you haven't changed
> that, then it's probably just what you get in a terminal
> from 
> 
> > clang++ --version
> 
> But if you're only on XCode 6.1, that's probably the issue. I'm
> up to 7.2.1. So it sounds like they introduced that warning
> config flag -Wno-unused-local-typedefs later.
> - Bob
>

**Comment by bob-carpenter** [comment]
It's just a warning about an unknown compiler option.  And
that option's just there to prevent other compiler warnings.
You can safely ignore all of them.

In the meantime, I think we may be able to fix it on our side
by branching on compiler versions.
- Bob

**Comment by richardneu** [comment]
Sounds good, thanks.

Best regards,

Richard

On 25.02.2016, at 17:02, Bob Carpenter notifications@github.com wrote:

It's just a warning about an unknown compiler option. And
that option's just there to prevent other compiler warnings.
You can safely ignore all of them.

In the meantime, I think we may be able to fix it on our side
by branching on compiler versions.
- Bob

**Comment by bgoodri** [comment]
You can delete -Wno-unused-local-typedefs from whatever directory

```
file.path(Sys.getenv("HOME"), ".R", "Makevars")
```

evaluates to.
