### ISSUE TITLE
Issue with running RStan with Windows

### ISSUE THREAD

**Issue by Lichen2016** [stan-dev/rstan#271]
#### Summary:

I installed RTools and RStan and I am trying to run the 8schools example. But I am not able to obtain results but the following error message. Have tried all I can found on the web but still no clue.
#### Description:

Describe the issue as clearly as possible.
#### Reproducible Steps:

Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.
#### Current Output:

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! clang++.exe: error: unknown argument: '-ffat-lto-objects'
make: **\* [file2d8c30375702.o] Error 1
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-32~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" -f "C:/Users/Lichen/Documents/.R/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2d8c30375702.dll" WIN=64 TCLBIN=64 OBJECTS="file2d8c30375702.o"' had status 2 
In addition: Warning message:
running command 'C:/PROGRA~1/R/R-32~1.3/bin/x64/R CMD SHLIB file2d8c30375702.cpp 2> file2d8c30375702.cpp.err.txt' had status 1 
#### Expected Output:

If applicable, the output you expected from RStan.
#### RStan Version:

The version of RStan you are running (e.g., from `packageVersion("rstan")`)
#### R Version:

R 3.2.3
#### Operating System

Windows10

**Comment by bob-carpenter** [comment]
There's nothing in this issue.  I'm going to close it if it remains just a title.  @Lichen2016, please complete the issue's text before creating it; we get emails with the issue and all the updates one by one otherwise.

**Comment by bgoodri** [comment]
You should not have `-ffat-lto-objects` in CXXFLAGS on Windows if using RTools <= 3.2. Nor should CXX be `clang++`.

**Comment by Lichen2016** [comment]
Hi bgoodri,

Thank you for you reply ! Could you please let me know what should I do to fix the problem?

Thank you very much !

**Comment by Lichen2016** [comment]
By the way, I am using R 3.2.3 and Rtools33

**Comment by bgoodri** [comment]
Uninstall Rtools33; use Rtools32. Then do

file.remove(file.path(Sys.getenv("HOME"), ".R", "Makevars"))

Then follow the first part of the instructions at

https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuration

and do not do the commands that are marked "for OSX only" or for g++
version 4.9 or higher.

**Comment by Lichen2016** [comment]
Hi @bgoodri , I followed your instructions and it works !!!

Thank you so much !!! I just couldn't imagine how I would figure this out without your helps !
