### ISSUE TITLE
Print statements in model block produce no output if error occurs LATER

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#274]
#### Summary:

If an error occurs in the model block, print statements PRECEDING the error never produce any output.
#### Description:

Originally, I was trying to debug a Stan program and scattered print statements all throughout the model block, but I got no output from any of them, even though a print statement in the transformed data block did produce output. I eventually pared it down to a very small program and verified that the error occurs on a specific line. However, the print statements on the lines preceding the error never produce any output.
#### Reproducible Steps:

The following code illustrates the problem. If you comment out the assignment to z_lo, it runs and the print statements produce output. If you leave in the assignment to z_lo, you get the error 

"Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value."

multiple times, and there is no output from the print statements.

```
model_code <- '
data {
}
transformed data {
  real lo;
  lo <- negative_infinity();
  print("Finished transforming data.");
}
parameters {
  real scale;
}
model {
  print("Starting model.");
  scale ~ normal(0, 1);
  print("A");
  {
    real z_lo;
    print("B");
    z_lo <- lo * scale;
  }
}
'

sm <- stan_model(model_code = model_code)
fit <- vb(sm, data=list())
```
#### Current Output:

Error in eval(expr, envir, enclos) : Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated at the initial value is not finite.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Gradient evaluated
#### Expected Output:

Expect to see the print statements

```
Starting model.
A
B
```
#### RStan Version:

2.9.0
#### R Version:

3.2.1
#### Operating System:

Mac OS X El Capitan

**Comment by bgoodri** [comment]
Closing so that followups go to stan-dev/stan#1789.
