### ISSUE TITLE
wrong arguments in control (stan()) are only noticed after the whole sampling is finished

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/rstan#277]
#### Summary:

If one makes a mistake in argument of the list that goes in "control" when using stan(), the error only appears after the whole sampling. It would be good to have an error immediately that stops the sampling.
#### Description:

 I wrote already step_size instead of stepsize a couple of times, and I noticed it only two days later when the model was done. And this is specially confusing since it is _adapt_delta_ and not _adaptdelta_
The following line should throw an error immediatly.
`stan(file="file.stan",data=datastan , control=list(adapt_delta=.999,max_treedepth=12,`_step_size_`=0.01)
`
#### Reproducible Steps:

`stan(file="file.stan",data=datastan , control=list(adapt_delta=.999,max_treedepth=12,`_step_size_`=0.01)
`
#### Current Output:

`Warning message:
'control' list contains unknown members of names: step_size.`
#### Expected Output:

Some type of error that stops the sampling
#### RStan Version:

2.9.0
#### R Version:

3.2.3
#### Operating System:

Ubuntu 15.04

**Comment by jgabry** [comment]
Thanks for the suggestion. We should definitely verify that the names are valid before sampling and throw an error if not.

**Comment by bgoodri** [comment]
2.10.0 is throwing an error in these situations
