### ISSUE TITLE
Update files to build for stanc

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#279]
#### Summary:

The pull request stan-dev/stan#1799 introduced different files for compiling stanc. RStan's build process will need to build the new file in order to compile the stanc compiler.
#### Description:

RStan doesn't match files based on a wildcard, so the files being built need to be set by hand.

These are the files that need to be built now:
- stan/lang/ast_def.cpp
- stan/lang/grammars/semantic_actions_def.cpp
- stan/lang/grammars/bare_type_grammar_inst.cpp
- stan/lang/grammars/expression07_grammar_inst.cpp
- stan/lang/grammars/expression_grammar_inst.cpp
- stan/lang/grammars/functions_grammar_inst.cpp
- stan/lang/grammars/indexes_grammar_inst.cpp
- stan/lang/grammars/program_grammar_inst.cpp
- stan/lang/grammars/statement_2_grammar_inst.cpp
- stan/lang/grammars/statement_grammar_inst.cpp
- stan/lang/grammars/term_grammar_inst.cpp
- stan/lang/grammars/var_decls_grammar_inst.cpp
- stan/lang/grammars/whitespace_grammar_inst.cpp

**Comment by bgoodri** [comment]
This will have been fixed in c974892cb85bcbd9c98b83986a595341eb5fc1f9
