### ISSUE TITLE
Issue compiling (schools or any example)

### ISSUE THREAD

**Issue by TMSweet** [stan-dev/rstan#283]
If this information would be useful to others:
I updated my operating system to OS X 10.11  Updated Xcode.  Continued to get errors.  Had to reinstall Stan (as well as update Makevars again) - even though both were updated.  Then restarted R for the 3rd time and schools example works.  
#### Summary:

I've read through all of the threads regarding this issue, but I can't seem to fix it.  Used rstan last year (for teaching) without issue.  Updated rstan to version 2.9.0.3 and getting compiling issues.  I have tried to install following directions exactly.  

A file called string is missing and that's correct.  If I go to the StanHeaders/include/stan/math/version.hpp file, the file says "include string" and there isn't something called string there.  (Should there be?)
#### Description:

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file155c65e6f0c17.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.2/Resources/library/StanHeaders/include/stan/math.hpp:4:
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/StanHeaders/include/stan/math/version.hpp:4:10: fatal error: 'string' file not found
# include <string>

```
     ^
```

1 error generated.
make: **\* [file155c65e6f0c17.o] Error 1
In addition: Warning message:
running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file155c65e6f0c17.cpp 2> file155c65e6f0c17.cpp.err.txt' had status 1
#### RStan Version:

2.9.0.3
#### R Version:

3.2.4
#### Operating System:

OS X 10.10.5

**Comment by bgoodri** [comment]
This should be unnecessary if you have StanHeaders and rstan in sync, which is now possible for 2.11.x on CRAN
