### ISSUE TITLE
CVODES

### ISSUE THREAD

**Issue by wds15** [stan-dev/rstan#286]
#### Summary:

Switch from CVODE to CVODES integrator for greater robustness and speed for mostly large ODE systems.
#### Description:

Remove integrate_ode_cvode function and replace with

integrate_ode_cvodes and integrate_ode_cvodes_stiff

each in two variants, i.e. a simple one and one which exposes the options abs+rel tol and maximum number of steps
#### Reproducible Steps:

Performance tests for stiff ODE integrator in stan-math fail with CVODE, but not with CVODES.
#### Current Output:

Stan freezes with old CVODE system on some ODE systems (see the test).
#### Expected Output:

Just return the solution.
#### Additional Information:

This requires to distribute CVODES instead of CVODE with StanHeaders.
#### RStan Version:

develop
#### R Version:

The version of R you are running (e.g., from `R.version.string`)

**Comment by bgoodri** [comment]
done
