### ISSUE TITLE
Seg fault trying code from forthcoming ADVI paper

### ISSUE THREAD

**Issue by elbamos** [stan-dev/rstan#287]
#### Summary:

Please provide a short summary (no more than a sentence or two).

Trying out Stan after seeing Kucukelbir's talk last night, I get a seg fault running a simple example taken from the appendix to the ADVI paper.
#### Description:

Describe the issue as clearly as possible.

```
 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: .Call(Module__functions_names, xp)
 2: Module(module, mustStart = TRUE)
 3: .getModulePointer(x)
 4: <S4 object of class "Module">$stan_fit4model4256601dbeeb_ae60a1c7b6f22f02799050eb171d0c04
 5: <S4 object of class "Module">$stan_fit4model4256601dbeeb_ae60a1c7b6f22f02799050eb171d0c04
 6: eval(expr, envir, enclos)
 7: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
 8: object@mk_cppmodule(object)
 9: .local(object, ...)
10: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
11: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
12: stan(data = dat, iter = 1000, chains = 4, model_code = "data { \n    int<lower=0> N; // number o f da ta i tem s\n    int<lower=0> D; // dimen si on o f i n pu t f e a t u r e s\n    matrix[N,D] x; // in p u t m a t rix\n    vector[N] y; // output v e c t o r\n    real<lower=0> a0;\n    real<lower=0> b0;\n    real<lower=0> c0;\n    real<lower=0> d0;\n}\nparameters {\n    vector[D] w; \n    real<lower=0> sigma; \n    vector<lower=0>[D] alpha; \n}\ntransformed parameters {\n    vector[D] one_over_sqrt_alpha;\n    for (i in 1:D) {\n        one_over_sqrt_alpha[ i ] <- 1 / sqrt ( alpha [ i ] ) ;\n    }\n}\nmodel {\n// alph a : hyper - p r i o r on w ei g h t s\n    alpha ~ gamma( c0 , d0 ) ;\n// sigma : p r i o r on s t and a rd d e vi a t i o n\n    sigma ~ inv_gamma ( a0 , b0 ) ;\n// w: p r i o r on w ei g h t s\n    w ~ normal ( 0 , sigma * one_over_sqrt_alpha ) ;\n// y : l i k e l i h o o d\n    y ~ normal ( x * w, sigma ) ;\n}")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```
#### Reproducible Steps:

Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

```
library(rstan)
Loading required package: ggplot2
rstan (Version 2.9.0-3, packaged: 2016-02-11 15:54:41 UTC, GitRev: 05c3d0058b6a)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

Attaching package: ‘rstan’

The following object is masked from ‘package:magrittr’:

    extract

The following object is masked from ‘package:tidyr’:

    extract

> dat <- list(y = rnorm(100), x = matrix(rnorm(1000), nrow = 100))
> fit <- stan(data = dat,iter = 1000, chains = 4, model_code="data { 
...     int<lower=0> N; // number o f da ta i tem s
...     int<lower=0> D; // dimen si on o f i n pu t f e a t u r e s
...     matrix[N,D] x; // in p u t m a t rix
...     vector[N] y; // output v e c t o r
...     real<lower=0> a0;
...     real<lower=0> b0;
...     real<lower=0> c0;
...     real<lower=0> d0;
... }
... parameters {
...     vector[D] w; 
...     real<lower=0> sigma; 
...     vector<lower=0>[D] alpha; 
... }
... transformed parameters {
...     vector[D] one_over_sqrt_alpha;
...     for (i in 1:D) {
...         one_over_sqrt_alpha[ i ] <- 1 / sqrt ( alpha [ i ] ) ;
...     }
... }
... model {
... // alph a : hyper - p r i o r on w ei g h t s
...     alpha ~ gamma( c0 , d0 ) ;
... // sigma : p r i o r on s t and a rd d e vi a t i o n
...     sigma ~ inv_gamma ( a0 , b0 ) ;
... // w: p r i o r on w ei g h t s
...     w ~ normal ( 0 , sigma * one_over_sqrt_alpha ) ;
... // y : l i k e l i h o o d
...     y ~ normal ( x * w, sigma ) ;
... }")
```
#### Current Output:

If applicable, any relevant output from RStan.

See above. 
#### Expected Output:

If applicable, the output you expected from RStan.

I expected it to produce a very poor fit. 
#### RStan Version:

The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.9.0-3
#### R Version:

The version of R you are running (e.g., from `R.version.string`)
3.2.4-Revised
#### Operating System:

Your operating system (e.g., OS X 10.11.3)
Ubuntu 16.04 Development

**Comment by bgoodri** [comment]
I think you need to ensure that Rcpp, RcppEigen, and rstan are all installed with the same compiler (settings). You may have r-cran-rcpp from the Ubuntu repository, which could have been compiled with different settings than whatever you have in ~/.R/Makevars.

**Comment by elbamos** [comment]
I just tried it immediately after reinstalling Rcpp, RcppEigen and stan together in a single session, same result.  Also, since this is linux, all of them were just compiled in the last hour with exactly the same compiler and libraries.

**Comment by bgoodri** [comment]
Hmm. I had it working Friday on Xenial. What compiler version are you using?

**Comment by elbamos** [comment]
```
:/mnt/hfsshare/LIBRARIES/TMBP/DocNADE$ sudo update-alternatives --config gcc
There are 2 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path              Priority   Status
------------------------------------------------------------
* 0            /usr/bin/gcc-4.9   60        auto mode
  1            /usr/bin/gcc-4.9   60        manual mode
  2            /usr/bin/gcc-5     50        manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

Actually, its kind of funny on a level, because a couple of the programs crashed-out during Kucukelbir's talk :p  

But I was actually really impressed by STAN as a concept and I'm eager to try it out.

**Comment by bgoodri** [comment]
I just got an example to run using g++-4.9 as the compiler on Debian
unstable and Ubuntu Xenial prerelease.

I assume that the error you are getting is not specific to Alp's example;
e.g.

```
library(rstan)
stan_demo("blocker")
```

fails in the same way?

**Comment by syclik** [comment]
Alp told me the problems with his examples during his talk were due to CMake. That's not Stan related at all, so no need to worry about Alp's example.

**Comment by elbamos** [comment]
@bgoodri Yes, `stan_demo("blocker")` fails in the same way.

**Comment by bgoodri** [comment]
Is this a fresh Ubuntu install or an upgrade from a previous version? Can
you try with g++-5 and / or a recent clang++?

**Comment by elbamos** [comment]
It's an upgrade from 15.10.  How about, if you tell me exactly what you'd like me to try, that's what I'll do.

**Comment by bob-carpenter** [comment]
That doesn't look like an ADVI-related example (it calls `stan()`) and from the error, it looks like the example was cut out of a PDF (tell-tale bad spacing). We are not getting any other reports from anybody about RStan failing on Linux, so I'm wondering if it's the example.  Could you try a simple example:

```
stan(model_code="parameters { real y; } model { y ~ normal(0, 1); }");
```

**Comment by bgoodri** [comment]
The particular example doesn't matter too much. These things happen from
time to time. Try

```
cat("\nCXX=g++-5", file = "~/.R/Makevars", sep = "\n", append = TRUE)

install.packages(c("Rcpp", "RcppEigen", "rstan"))

library(rstan)

blocker <- stan_demo("blocker")
```

**Comment by elbamos** [comment]
@bob-carpenter  Your example worked.
@bgoodri Your example did not - same result as before.

**Comment by bgoodri** [comment]
So, it segfaults when you pass a Stan program's path to `file` but does not segfault when passing a string to `model_code`?

**Comment by elbamos** [comment]
No. That's not it. In my first example it seg faulted on model code.

**Comment by elbamos** [comment]
Just following-up about this.  Was really looking forward to trying it out.

**Comment by bob-carpenter** [comment]
@bgoodri Any idea what's going on here?  

Will any model that's not passed in as a string work?  I don't know enough about RStan's internals to really help here.

**Comment by bgoodri** [comment]
I am pretty sure it is a toolchain issue but the toolchain stuff has gotten more flaky recently.

**Comment by elbamos** [comment]
Today I upgraded R to 3.2.5, and the segfault is gone.  

Demos now run fine, but when I try code from the ADVI paper, I get:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
ERROR at line 16
 14:    vector<lower=0>[D] alpha; 
 15:    }
 16:    transformed_parameters {
                             ^
 17:    vector[D] one_over_sqrt_alpha;
PARSER EXPECTED: "parameters"
```

(The caret should be under the _ in transformed_parameters.)

Is this the expected result?

**Comment by betanalpha** [comment]
The block is "transformed parameters", no underscore.

**Comment by elbamos** [comment]
Thanks!   Whatever this was, I guess it was related to the version of R that was released and quickly replaced a few weeks ago.  Anyway its resolved now.

**Comment by bob-carpenter** [comment]
Thanks much for following up and closing the issue.
