### ISSUE TITLE
print statements written out as numerical problems

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#288]
#### Summary:

When I have print statements in Stan programs I don't see them until the end and then it puts them in the numerical problems summary.
#### Description:

I'd like to see the prints on a per-iteration basis, or at least if they all have to come at the end without iteration ID, I'd like to see them without numerical problems.  They don't throw exceptions -- they just print to the output stream.
#### Reproducible Steps:

I had these print statements in a Stan program

```
  print("log poisson(0 | 9) = ", poisson_log(0, 9));
  print("log1m_exp(possion_cdf(0 | 9)) = ", log1m_exp(poisson_cdf_log(0, 9)));
  print("log poisson_ccdf(0 | 9) = ", poisson_ccdf_log(0, 9));
  print("log poisson_ccdf(1 | 9) = ", poisson_ccdf_log(1, 9));
```
#### Current Output:

```
The following numerical problems occured the indicated number of times after warmup on chain 4
                                             count
log poisson_ccdf(0 | 9) = -0.000123417        8538
log poisson_ccdf(1 | 9) = -0.00123486         8538
log poisson(0 | 9) = -9                       8538
log1m_exp(possion_cdf(0 | 9)) = -0.000123417  8538
When a numerical problem occurs, the Metropolis proposal gets rejected.
However, by design Metropolis proposals sometimes get rejected even when there are no numerical problems.
Thus, if the number in the 'count' column is small, do not ask about this message on stan-users.
```
#### Expected Output:

Anything that doesn't say it's an error.
#### Session Info

```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.11.3   rstan_2.9.0   ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] codetools_0.2-10 colorspace_1.2-4 digest_0.6.4     grid_3.1.3       gridExtra_2.0.0 
 [6] gtable_0.1.2     inline_0.3.13    labeling_0.2     munsell_0.4.2    plyr_1.8.1      
[11] scales_0.3.0     stats4_3.1.3     tools_3.1.3     
```

**Comment by bgoodri** [comment]
I think this is already fixed for 2.10 as long as print statements are going to stdout, now that exceptions are going to stderr again.

**Comment by bgoodri** [comment]
Upon further review, this doesn't appear as if it is already fixed for 2.10 because print statements are going to stderr.

**Comment by bgoodri** [comment]
@syclik This should really be on this issue. For 2.10, this R script

```
library(rstan)

mc <- '
parameters {real<lower=-1,upper=1> theta;}
model {print("theta = ", theta);}
'
sm <- stan_model(model_code = mc)
post <- sampling(sm, show_messages = FALSE)
```

only prints this progress because the print statements are going to stderr and end up as "messages" in R, which are not shown when `show_messages = FALSE`. But the better behavior would be to flood stdout with the print messages and only use stderr for exceptions (including reject statements).

**Comment by bgoodri** [comment]
this was fixed at some point
