### ISSUE TITLE
Sqrt of integer fails on solaris x86

### ISSUE THREAD

**Issue by JohnReid** [stan-dev/rstan#289]
#### Summary:

Stan generates code with sqrt(3) which won't compile on the solaris compiler
#### Description:

This is the error message that shows the problem:
Compilation ERROR, function(s)/method(s) not created! file15b48b260bb.cpp: In function ‘typename boost::math::tools::promote_args<RT1, RT2>::type model15b324e3bc0_simplest_model_namespace::matern32_cov(const T0__&, const T1__&, std::ostream*)’:
file15b48b260bb.cpp:104:42: error: call of overloaded ‘sqrt(int)’ is ambiguous
             stan::math::assign(x, (sqrt(3) \* fabs((r / l))));
                                          ^
file15b48b260bb.cpp:104:42: note: candidates are:
In file included from /opt/csw/lib/gcc/i386-pc-solaris2.10/4.9.2/include-fixed/math.h:26:0,
                 from /opt/csw/include/c++/4.9.2/cmath:44,
                 from /opt/csw/include/c++/4.9.2/complex:44,
                 from /home/ripley/R/Lib32/RcppEigen/include/Eigen/Core:28,
                 from /home/ripley/R/Lib32/RcppEigen/include/Eigen/Dense:1,
                 from /home/ripley/R/Lib32/StanHeaders/include/stan/math/prim/m
#### Reproducible Steps:

I discovered this issue due to the checks that CRAN ran when I submitted by DeLorean package that uses Stan. Building the vignette triggers the above problem. Brian Ripley pointed it out to me. I believe any model that includes `sqrt(3)` will fail.
#### Current Output:

https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/DeLorean-00check.html
#### R Version:

3.3.0 beta
#### Operating System:

Solaris x86

**Comment by bob-carpenter** [comment]
It's pretty clear from this report that the complex lib shouldn't
be included.  Which makes the name "include-fixed" rather ironic.
Is this some customization thing on your end, part of RStan, or
what?

In any case, are all the double-based functions broken under Solaris?

The only fix for this would be to generate explicit static
casts for function arguments that need to be double and are
integer.
- Bob

**Comment by JohnReid** [comment]
All I know is that it isn't a customisation thing at my end. Neither am I sure about all the double based functions as I haven't used Solaris for a long time. This is one of the default checks that CRAN makes. I don't even have access to this machine. My memory is that Solaris is fussy but that was a long time ago.

**Comment by bob-carpenter** [comment]
That's not so much fussy as just misimplementing the spec.
I'm not sure we'll be able to deal with this.

It's not an RStan issue in any case --- it's something that
would need to be addressed in either the math library or
in the code generator for Stan.
- Bob

**Comment by bgoodri** [comment]
Can we first include our own complex.hpp that has nothing but a header guard?

**Comment by bgoodri** [comment]
I think you can work around this by putting `sqrt(3.0)` or `sqrt(5.0)` in your Stan programs instead of `sqrt(3)` or `sqrt(5)`.

```
./inst/Stan/simple-model.stan:        x <- sqrt(3) * fabs(r / l);
./inst/Stan/simple-model.stan:        x <- sqrt(5) * fabs(r / l);
./inst/Stan/lowrank.stan:        x <- sqrt(3) * fabs(r / l);
./inst/Stan/lowrank.stan:        x <- sqrt(5) * fabs(r / l);
./inst/Stan/simplest-model.stan:        x <- sqrt(3) * fabs(r / l);
./inst/Stan/simplest-model.stan:        x <- sqrt(5) * fabs(r / l);
```

**Comment by bgoodri** [comment]
Or really just replace `sqrt(3)` with `1.7320508075688771932` and replace `sqrt(5)` with `2.2360679774997898051`.

**Comment by JohnReid** [comment]
Yes thanks that is what I have done.
