### ISSUE TITLE
get_sampler_params gives error when called on value returned by vb

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#292]
#### Summary:

If fit is the stanfit object return by rstan::vb(), then get_sampler_params(fit) results in an error.
#### Description:

Calling get_stampler_params() on the stanfit object returned by rstan::vb() gives the following error:

```
Error in do.call(cbind, attr(x, "sampler_params")) : 
  second argument must be a list
```
#### Reproducible Steps:

The following steps produce the error
    sm <- stan_model(model_code = 'parameters {real y;} model {y ~ normal(0,1);}')
    fit <- vb(sm)
    get_sampler_params(fit)
#### RStan Version:

2.9.0.3
#### R Version:

3.2.4
#### Operating System:

Windows 7

**Comment by jgabry** [comment]
Thanks @ksvanhorn. Informative message added saying that `get_sampler_params` is not available for meanfield and fullrank algorithms, at least for now.
