### ISSUE TITLE
Cannot link models with clang++-3.8

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstan#298]
#### Summary:

clang++3.8 (at least) yields a linker error when compiling a model
#### Description:

You can an undefinied symbol from the mangled version of
`std::ios_base::failure::failure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

This is likely a problem in rethrow_located.hpp but @bob-carpenter would know better than I.
#### Reproducible Steps:

Call `stan_model` on anything when clang++-3.8 is the compiler
#### Current Output:

```
Error in dyn.load(libLFile) : 
  unable to load shared object '/tmp/Rtmp3EYkrl/filebab4ea0765b.so':
  /tmp/Rtmp3EYkrl/filebab4ea0765b.so: undefined symbol: _ZNSt8ios_base7failureC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
#### Expected Output:

None
#### RStan Version:

2.9.0-3
#### R Version:

3.3.0
#### Operating System:

Debian

**Comment by bob-carpenter** [comment]
Is there a reason this is an RStan issue and not just a Stan issue?

**Comment by bgoodri** [comment]
Not that I know of but I can only trigger it in R because the error appears
when you try to load the DSO into R.

**Comment by bob-carpenter** [comment]
It looks like it's tryign to load some kind of C++11 thing:

std::ios_base::failure::failure(std::__cxx11::basic_string
                                ^^^^^^^^^^^^

Could that be the problem?  Maybe you just need to include
an instantiation of this somewhere (but I'd have thought just
calling it would do that).

**Comment by bgoodri** [comment]
Yes, recent versions of clang++ use libc++, which is basically the C++11
standard library whether the C++11 standard is enforced or not.

**Comment by bob-carpenter** [comment]
@bgoodri Can you try editing out lines 120 and 121 of `stan/src/stan/lang/rethrow_located.hpp and see if the problem goes away?  That's:

```
     if (is_type<std::ios_base::failure>(e))
        throw std::ios_base::failure(s);
```

We can just default to a generic exception if we can't detect this one, so it's no big deal getting rid of it.

**Comment by bgoodri** [comment]
I commented out those two lines for the StanHeaders on CRAN but we need to transfer this issue to the Stan repository.

**Comment by bgoodri** [comment]
Will fix upstream in Stan.
