### ISSUE TITLE
optimizing() infinite loop of "Error evaluating model log probability: Non-finite gradient."

### ISSUE THREAD

**Issue by randel** [stan-dev/rstan#299]
#### Summary:

This is an example for the error reported in [the Google user group](https://groups.google.com/forum/#!topic/stan-users/HOd-kPsb7l4).
#### Description:

`optimizing()` would report the following error message in an infinite loop.
`Error evaluating model log probability: Non-finite gradient.`
#### Reproducible Steps:

The model file (`stan.txt`) and example data (`dat.rdata`) can be found [here](https://github.com/randel/code).

```
library(rstan)

source('stan.txt')
m <- stan_model(model_code = m_code_sm_hete)

load('dat.rdata')
set.seed(-46587504)
system.time(f <- optimizing(m, data=dat, hessian = TRUE, iter=1e4, algorithm='BFGS'))

```
#### RStan Version:

rstan_2.9.0-3
#### R Version:

R Under development (unstable) (2016-04-04 r70420)
R version 3.2.4 Revised (2016-03-16 r70336)
#### Operating System:

Windows 7 x64 (build 7601) Service Pack 1

**Comment by bob-carpenter** [comment]
Thanks for reporting. Can someone check if this is a general Stan algorithms issue or belongs in RStan?

**Comment by bgoodri** [comment]
I think it is just numerical instability rather than a bug. Changing the parameter declaration from `cov_matrix[npep] sigma` to `cholesky_factor_cov[npep] L_sigma;` and making the corresponding change in the first line of the model block from `b ~ multi_normal(zeros, sigma);` to `b ~ multi_normal_cholesky(zeros, L_sigma);` gets it to work.

**Comment by bob-carpenter** [comment]
Bug or missing feature, we don't really want to let things run away into infinite loops.  This is something that needs to be fixed on the Stan services side, not in RStan, so I'm closing.  The new issue for Stan is here:

https://github.com/stan-dev/stan/issues/1896

**Comment by bgoodri** [comment]
It wasn't an infinite loop. It was a loop that was only terminated by
Optimization terminated with error:
  Line search failed to achieve a sufficient decrease, no more progress can
be made

**Comment by bob-carpenter** [comment]
Ah, I see.  OK, I'll close the Stan issue I just opened, then!
