### ISSUE TITLE
Suggstion to improve an error message

### ISSUE THREAD

**Issue by MMargolis** [stan-dev/rstan#301]
#### Summary:

When Mac users have not approved the Xcode license (which we must do after some upgrades, which we may not even have been aware of) Rstan gives a rather unhelpful message. 
#### Description:

The function get_CXX fails, informing us that a command to the OS has failed with error 69. It would be useful to suggest that perhaps the Xcode license needs reapproval.
#### RStan Version:

The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.9.0.3
#### R Version:

The version of R you are running (e.g., from `R.version.string`)
3.3.0
#### Operating System:

Your operating system (e.g., OS X 10.11.3)
OSX

**Comment by bob-carpenter** [comment]
Thanks for filing an issue.  Do you know how we can query for that during the R install?

Having just helped a bunch of people get RStan installed, the other issue like this to add is not having recent enough versions of other libraries like Rcpp.

**Comment by MMargolis** [comment]
I don't know for use, but it occurs to me you could try running the same system command inside "try" or "tryCatch". Something like

tryC <- try(system2(file.path(R.home(component = "bin"), "R"), args = paste("CMD config", "CXX"), stdout = TRUE, stderr = FALSE))
if (!is.null(attr(tryC, 'status')){
     cat('There is problem with your C compiler \n')
    if (attr(tryC, 'staus') == 69) cat('It may be you did not approve your XCode your license after an update \n')
}

I can't quite test that now, since I have approved my license, but 69 is pretty memorable error code.

**Comment by bgoodri** [comment]
We put something like this into 2.11.1
