### ISSUE TITLE
Ambiguous installation instructions

### ISSUE THREAD

**Issue by RossBoylan** [stan-dev/rstan#302]
#### Summary:

Unclear if some instructions apply just for OS-X, or more generally.
#### Description:

The installation instructions include instructions about `Makevars` that apply only to OS-X, and then some instructions that apply to g++ 4.9+, which is noted to be rare on a Mac.    It is unclear if the second set  of instructions are for OS-X only.
#### Current Text

[https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuration](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuration)

> In addition, on OS X only you should (unless you do not have clang++ installed) execute in R
> 
> cat("\nCC=clang", "CXX=clang++ -arch x86_64 -ftemplate-depth-256", 
>     file = M, sep = "\n", append = TRUE)
> 
> If using g++ version 4.9 or higher (which is rare on a Mac), we recommend executing in R
> 
> cat("\nCXXFLAGS+=-flto -ffat-lto-objects  -Wno-unused-local-typedefs", 
>     file = M, sep = "\n", append = TRUE)

The reference "which is rare on the Mac" contributes to my uncertainty about whether this is a Mac only instruction.
#### Possible Fix

Move the second set of instructions above the first if they apply generally.

**Comment by bgoodri** [comment]
Done. Thanks.
