### ISSUE TITLE
Stan breaking a loop in R

### ISSUE THREAD

**Issue by bracyknight** [stan-dev/rstan#309]
#### Summary:

Hi there. I setup for loop in R that calls stan. After running analysis, my code is supposed to record the results as a line in a data frame. When I run the loop, it does the stan bayesian fun stuff, but it halts the loop. It does not record the results and it does not do another iteration.
#### Description:

I just updated rstan today (version: ). I have multiple analyses (for model selection/comparison) set to run in a loop: 

for(i in 1:9){
  fn <- paste('01_R/02_Rphys/m',i,'.R', sep = "")
  source(fn)
  phys.res[i,] <- c(names(x3),nrow(d),i,round(waic_fit[[3]],2),round(loo_fit[[3]],2))
}

In this case, I'm just trying to run models m1.R through m9.R in a set folder. Each model calls a stan script and runs it. It also calculates the WAIC and LOO from the log likelihood. Then, I just shove a few things into the i line of a results data frame (pays.res). 

When I run this loop, it will call up stan and do the analysis no problem. It even calculates the WAIC and LOO (these are stored as variables). But, it doesn't populate the data frame. I can manually run the line that fills in the data frame and it works just fine.

Running m1.R manually works perfectly, but this doesn't fill in the data frame.

I ran these codes a few days ago, and it looped just fine and dandy. Am I doing something wrong? Is there a better solution? Or, is this a bug?
#### RStan Version:

2.10.1
#### R Version:

R version 3.3.1 (2016-06-21)
#### Operating System:

 OS X 10.11.6

**Comment by bgoodri** [comment]
Is there an error message?

**Comment by bracyknight** [comment]
No error at all. The stan code runs fine and then the loop just doesn’t continue past that part of the loop.

**Comment by bgoodri** [comment]
I don't know what to say. I don't think there is anything in Stan that would cause this, but I can't imagine what would cause this under any circumstances. You might try converting your loop to a sapply call, like

```
phys.res <- t(sapply(1:9, FUN = function(i) {
  fn <- paste('01_R/02_Rphys/m',i,'.R', sep = "")
  source(fn, local = TRUE)
  return(c(names(x3),nrow(d),i,round(waic_fit[[3]],2),round(loo_fit[[3]],2))) 
}))
```

to see if you get an error message or possibly results.

**Comment by davharris** [comment]
@bracyknight Maybe the script you're sourcing in redefines `i` or has a `break` statement?

**Comment by bracyknight** [comment]
Doh! That was it. Thanks

Kevin

—
Kevin Bracy Knight
PhD Candidate
McCain Lab
University of Colorado Boulder
