### ISSUE TITLE
clarify doc for stan() on whether Stan or R does random initialization

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#31]
An issue came up from Ryan Brackney on stan-users about which seed controls the initialization if `init="random"` is specified in  a call to `stan()`.

Also, the "One of" to start the comment on `init` is confusing because it can actually be a positive double value other than 0, as you indicate later in the doc with `init_r`.

* [ ] clarify whether R/Stan does random init
* [ ] reword init doc to make it clearer that you can use a positive double value

**Comment by jgabry** [comment]
closing outdated issue
