### ISSUE TITLE
`print` method errors when using a saved stanfit object 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#313]
#### Summary

After saving a stanfit object and opening a new R session the `print` method throws an error when it tries to print the BFMI. 

@bgoodri are you aware of this? 
#### Reproducible steps

``` r
library("rstan")
fit <- stan_demo("eight_schools")
print(fit) # this works fine
save(fit, file = "fit.rda")

#### Now start a new R session  ####
library("rstan")
load("fit.rda")
print(fit)

# some printed output comes out and then:
Error in .local(object, ...) : 
  the model object is not created or not valid
```

The printed output that does come out is everything except for the BFMI and when it gets to where that would be printed it throws the error above. 
#### RStan Version:

2.10.1
#### R Version:

3.3.1
#### Operating System:

OS X 10.11.5

**Comment by jgabry** [comment]
Actually you don't need to even start a new R session. You can reproduce it just be saving, removing, and reloading within the same R session: 

#### Reproducible steps

``` r
library("rstan")
fit <- stan_demo("eight_schools")
print(fit) # this works fine
save(fit, file = "fit.rda")

rm(fit)
load("fit.rda")
print(fit) # error
```

**Comment by jgabry** [comment]
I assume this is because `is_sfinstance_valid` is `FALSE`

**Comment by bgoodri** [comment]
I think this is already fixed in develop.

**Comment by jgabry** [comment]
Ah ok, I might not have pulled recently. I'll do that and close this if
it's fixed.

**Comment by jgabry** [comment]
closing this, as it's related to #306 and does appear to be fixed on the develop branch.
