### ISSUE TITLE
cannot install rstan via install.packages("http://win-builder.r-project.org/Z1N0He79FT3r/rstan_2.10.1-1.zip", repos = NULL, dependencies = TRUE) 

### ISSUE THREAD

**Issue by XiaoqiJiang** [stan-dev/rstan#319]
#### Summary:

Cannot install rstan via install.packages("http://win-builder.r-project.org/Z1N0He79FT3r/rstan_2.10.1-1.zip", repos = NULL, dependencies = TRUE) 
#### Description:

The path to my R libraries contians a space, so according to the hint "How to Install RStan" I tried to insall rstan via http://win-builder.r-project.org/Z1N0He79FT3r/rstan_2.10.1-1.zip. But this file seems to be not exist anymore. Due to restirictions of administartion on my company's computer, I cannot also change the path to R libraries. 
#### Current Output:

Warning in install.packages :
cannot open: HTTP status was '404 Not Found'
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://win-builder.r-project.org/Z1N0He79FT3r/rstan_2.10.1-1.zip'
#### Expected Output:

the link http://win-builder.r-project.org/Z1N0He79FT3r/rstan_2.10.1-1.zip works again
#### RStan Version:

2.10.1
#### R Version:

3.2.0
#### Operating System:

Windows 8

**Comment by jgabry** [comment]
Hi @XiaoqiJiang, can you try running these two lines instead?

``` r
install.packages("http://win-builder.r-project.org/s056FJOB6dWm/StanHeaders_2.11.0.zip", repos = NULL)

install.packages("http://win-builder.r-project.org/y6g7YWaKlG60/rstan_2.11.1.zip", repos=NULL, dependencies = TRUE)
```

**Comment by bob-carpenter** [comment]
Given that this is a known issue, can you put that in the doc somewhere and then close this issue?  Thanks.

**Comment by jgabry** [comment]
I actually just copied that from the [RStan wiki](https://github.com/stan-dev/rstan/wiki/RStan-Transition-Periods). Should have just pointed there. 

@XiaoqiJiang I'm going to close this issue but if the correct commands that I posted earlier don't work for you please do open another issue about that so we can help you get it sorted out.
