### ISSUE TITLE
R2WinBUGS compatible output

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#32]
From Sebastian Weber:

I would love to get an objects which has the same entries as defined here:

http://www.inside-r.org/packages/cran/R2WinBUGS/docs/bugs

for the case when codaPkg=FALSE, check the section "Value".

I know that I could use these helper functions extract and as.array, but the library I am currently intending to use stan instead of WinBUGS simply used the structure as returned by R2WinBUGS::bugs described above. There is no extra output, just the same stuff which rstan reports already in a different format. Nothing really complicated.

**Comment by jgabry** [comment]
closing outdated issue
