### ISSUE TITLE
transition period instructions not working??

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#320]
@bgoodri at least for me, following the instructions on the transition period wiki and installing RStan from source via github + devtools still results in version 2.10 being installed instead of 2.11

``` r
devtools::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan", dependencies = TRUE)
```

And when I go to the DESCRIPTION file on the develop branch it still says it's version 2.10.1, which is probably why it's installing that version, but where did 2.11 go? 

To install 2.11 I ended up having to do this:

```
install.packages("rstan", repos = "https://cloud.r-project.org", type = "source", dependencies = TRUE)
```

**Comment by bgoodri** [comment]
I think I forgot to push.

**Comment by bgoodri** [comment]
We're past the transition period now, except for R 3.2.x on Windows.
