### ISSUE TITLE
Odd description of methods in documentation.

### ISSUE THREAD

**Issue by rpruim** [stan-dev/rstan#322]
In the documentation for `sampling()` and `optimizing()` you have 

> This method is a generic function of the S4 class stanmodel.

I think that isn't quite the right description.  Methods are not generic functions and don't belong to objects/classes.  You are defining methods that dispatch on signatures that include a stanmodel object.

**Comment by jgabry** [comment]
Thanks, yeah the current description doesn't make sense. I think
that language has been there for ages and I must not have noticed it when I
went through and corrected and cleaned up the documentation before version
2.10. We'll update it before the next release.

**Comment by rpruim** [comment]
That's pretty much what I figured.

By the way, I'm enjoying both `stan` and `rstan`.  (The `rethinking` package is also interesting.)

**Comment by jgabry** [comment]
I just removed those lines from the descriptions in the doc for `sampling` and `optimizing`. I don't even think they need to be replaced by corrected versions as the doc makes sense without them. Thanks for pointing it out and glad you're enjoying Stan!
