### ISSUE TITLE
Warning Message: running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX 2>/dev/null' had status 1 

### ISSUE THREAD

**Issue by DrBlade** [stan-dev/rstan#325]
#### Summary:

Please provide a short summary (no more than a sentence or two).
I have installed Rstan and it shows up as a package in my Rstudio.  However, when I run an example from the package, I get an error message that it cannot call the Stan command.  Am I missing a prerequisite install?
#### Description:

Describe the issue as clearly as possible.
#### Reproducible Steps:

Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.
# Not run:

stanmodelcode <- "
data {
  int<lower=0> N;
  real y[N];
} 

parameters {
  real mu;
} 

model {
  target += normal_lpdf(mu | 0, 10);
  target += normal_lpdf(y  | mu, 1);
} 
"

y <- rnorm(20) 
dat <- list(N = 20, y = y); 
fit <- stan(model_code = stanmodelcode, model_name = "example", 
            data = dat, iter = 2012, chains = 3, sample_file = 'norm.csv',
            verbose = TRUE) 
#### Current Output:

If applicable, any relevant output from RStan.

TRANSLATING MODEL 'example' FROM Stan CODE TO C++ CODE NOW.
successful in parsing the Stan model 'example'.
Error in if (nchar(CXX) == 0) { : argument is of length zero
In addition: Warning message:
running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CXX 2>/dev/null' had status 1 
#### Expected Output:

If applicable, the output you expected from RStan.
#### RStan Version:

The version of RStan you are running (e.g., from `packageVersion("rstan")`)

Package:    rstan
Version:    2.10.0
Date:   June 20, 2016
License:    GPL-3
#### R Version:

The version of R you are running (e.g., from `R.version.string`)
"R version 3.2.3 (2015-12-10)"
#### Operating System:

Your operating system (e.g., OS X 10.11.3)
OSX El Capitan 10.11.15

**Comment by bob-carpenter** [comment]
We don't mind answering questions on our users group, but please don't file issues without reproducible examples.  We don't know what else you have installed in R, what your C++ toolchain looks like, or how you tried to install Stan, so there's very little we can do with this report other than guess what went wrong.   I'll let the  R devs answer the actual question, which is fine to do here along with an issue close.  Thanks.

**Comment by bgoodri** [comment]
I think you need to accept the Xcode license. Also, install rstan 2.11.x, which has a better error message in this case.

**Comment by DrBlade** [comment]
Thank you.  I will try that.
