### ISSUE TITLE
Out of date version of rtools.R produces spurious warning message

### ISSUE THREAD

**Issue by jonathan-g** [stan-dev/rstan#327]
#### Summary:

After upgrading rtools from rtools33 to rtools34, a warning message appears when compiling stan models. This warning seems to be spurious and may have to do with rstan::find_rtools not having been updated to deal with rtools34.
#### Description:

After upgrading from rtools33 to rtools34, stan models compile successfully with stan_model(), but produce a nonfatal warning 

```
Warning message:
In find_rtools() :
  WARNING: Rtools 3.4 found on the path at g:/Rtools is not compatible with R 3.3.1.

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().
```

Despite the warning, the stan model runs properly and produces sensible results.
#### Reproducible Steps:

```
model <- 'data {
  int<lower=0> J;          // number of schools 
  real y[J];               // estimated treatment effects
  real<lower=0> sigma[J];  // s.e. of effect estimates 
}
parameters {
  real mu; 
  real<lower=0> tau;
  vector[J] eta;
}
transformed parameters {
  vector[J] theta;
  theta = mu + tau * eta;
}
model {
  target += normal_lpdf(eta | 0, 1);
  target += normal_lpdf(y | theta, sigma);
}
'

schools_data <- list(
  J = 8,
  y = c(28,  8, -3,  7, -1,  1, 18, 12),
  sigma = c(15, 10, 16, 11,  9, 11, 10, 18)
)

library(rstan)
rstan_options(auto_write = FALSE) # so I force it to re-compile the model each time

# The warning appears after the call to stan_model
sm <- stan_model(model_code = model, model_name = 'eight_schools', auto_write = FALSE)

fit1 <- sampling(sm, 
  data = schools_data,    # named list of data
  chains = 4,             # number of Markov chains
  warmup = 1000,          # number of warmup iterations per chain
  iter = 2000,            # total number of iterations per chain
  cores = parallel::detectCores(),
  refresh = 1000          # show progress every 'refresh' iterations
)
```
#### Current Output:

```
Warning message:
In find_rtools() :
  WARNING: Rtools 3.4 found on the path at g:/Rtools is not compatible with R 3.3.1.

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().
```
### Relevant information

See https://github.com/hadley/devtools/commit/a909176daf282d41a388bcab6a0030d60226fb24
#### Session Info

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.11.1       StanHeaders_2.11.0 ggplot2_2.1.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6      codetools_0.2-14 grid_3.3.1       plyr_1.8.4       gtable_0.2.0     stats4_3.3.1     scales_0.4.0     rstudioapi_0.6   tools_3.3.1      munsell_0.4.3    parallel_3.3.1  
[12] rsconnect_0.4.3  inline_0.3.14    colorspace_1.2-6 gridExtra_2.2.1 
```

**Comment by jonathan-g** [comment]
Is there a reason to have rtools.R in rstan, rather than calling `devtools::find_rtools()` ?

**Comment by bob-carpenter** [comment]
@jonathan-g Thanks for filing the careful issue report.  We appreciate it.

**Comment by bgoodri** [comment]
Just to not put devtools in Imports for one function, but it means we have to deal with things like this.

**Comment by juanpide** [comment]
I have the same problem.
I'm using R 3.3.1 on Windows 10 x64.
I'm unable to run rstan.
I've tried with rstan 2.11.1 and rtools 3.4 and I get the warning
 WARNING: Rtools 3.4 found on the path at g:/Rtools is not compatible with R 3.3.1.
I've also tried with Rtools 3.3
And then I get the error
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:/Rtools/mingw_64/bin/g++: not found  
(Even if that folder exists and it contains g++.exe)
I've also tried with rstan 2.10.0 and even installing from github with no luck.
Other packages don't complain about Rtools.

**Comment by bgoodri** [comment]
This is supposedly fixed in the next version of rstan. You can do

devtools::install_github("stan-dev/rstan", subdir = "rstan/rstan", ref =
"develop")

**Comment by juanpide** [comment]
When running the simple example

> fit <- stan(file = '8schools.stan', data = schools_dat, iter = 100, chains = 4)

I get this error:

> Error in compileCode(f, code, language = language, verbose = verbose) : 
>   Compilation ERROR, function(s)/method(s) not created! In file included from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat.hpp:36:0,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/rev/mat.hpp:9,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math.hpp:4,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
>                  from file2654158e2944.cpp:8:
> C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat/err/check_positive_ordered.hpp: In function 'bool stan::math::check_positive_ordered(const char_, const char_, const Eigen::Matrix<Scalar, -1, 1>&)':
> C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat/err/check_positive_ordered.hpp:39:67: warning: typedef 'size_type' locally defined but not used [-Wunused-local-typede
> In addition: Warning message:
> In find_rtools() :
>   WARNING: Rtools 3.4 found on the path at c:/Rtools is not compatible with R 3.3.1.
> 
> Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().

But when I install 3.3 I get other errors.

**Comment by bgoodri** [comment]
Does devtools::find_rtools() tell you anything different?

**Comment by juanpide** [comment]
devtools::find_rtools()  says  TRUE

**Comment by bgoodri** [comment]
Try installing from GitHub again.

**Comment by juanpide** [comment]
Hello.
I've tried again with the latest github and Rtools 3.4

I get a lot of messages but the last one is:

> C:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o rstan.dll tmp.def chains.o init.o lang__ast_def.o lang__grammars__bare_type_grammar_inst.o lang__grammars__expression07_grammar_inst.o lang__grammars__expression_grammar_inst.o lang__grammars__functions_grammar_inst.o lang__grammars__indexes_grammar_inst.o lang__grammars__program_grammar_inst.o lang__grammars__semantic_actions.o lang__grammars__statement_2_grammar_inst.o lang__grammars__statement_grammar_inst.o lang__grammars__term_grammar_inst.o lang__grammars__var_deccls_grammar_inst.o lang__grammars__whitespace_grammar_inst.o misc.o sparse_extractors.o stanc.o -LC:/swarm/workspace/External-R-3.3.1/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.3.1/vendor/extsoft/lib -LC:/PROGRA~1/MIE74D~1/MRO-33~1.1/bin/x64 -lR
> Cannot export __gnu_lto_v1: symbol not defined
> collect2.exe: error: ld returned 1 exit status
> no DLL was created
> ERROR: compilation failed for package 'rstan'
> - removing 'C:/Program Files/Microsoft/MRO-3.3.1/library/rstan'
>   Installation failed: Command failed (1)
>   Warning message:
>   GitHub repo contains submodules, may not function as expected!

**Comment by juanpide** [comment]
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
installs properly but later it doesn't work
when running the example
fit <- stan(file = '8schools.stan', data = schools_dat, iter = 1000, chains = 4)
it says

> C:/Rtools/mingw_64/lib/gcc/x86_64-w64-mingw32/4.9.3/include/tmmintrin.h:188:32: error: '__builtin_ia32_palignr128' needs isa option -m32 -mssse3
>             (__v2di)__Y, __N \* 8);
>                                 ^
> lto-wrapper: C:\Rtools\mingw_64\bin\g++.exe returned 1 exit status
> C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: lto-wrapper failed
> collect2.exe: error: ld returned 1 exit status
> 
> ERROR(s) during compilation: source code errors or compiler configuration errors!
> 
> Error in compileCode(f, code, language = language, verbose = verbose) : 
>   Compilation ERROR, function(s)/method(s) not created! In file included from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat.hpp:36:0,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/rev/mat.hpp:9,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math.hpp:4,
>                  from C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
>                  from file1a5453437ef8.cpp:8:
> C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat/err/check_positive_ordered.hpp: In function 'bool stan::math::check_positive_ordered(const char_, const char_, const Eigen::Matrix<Scalar, -1, 1>&)':
> C:/Program Files/Microsoft/MRO-3.3.1/library/StanHeaders/include/stan/math/prim/mat/err/check_positive_ordered.hpp:39:67: warning: typedef 'size_type' locally defined but not used [-Wunused-local-typede
> In addition: Warning message:
> In find_rtools() :
>   WARNING: Rtools 3.4 found on the path at c:/Rtools is not compatible with R 3.3.1.
> 
> Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().

**Comment by bgoodri** [comment]
That is a different problem. With a text editor, try taking "-flto
-ffat-lto-objects" out of CXXFLAGS in the result of

normalizePath("~/.R/Makevars")

**Comment by juanpide** [comment]
Oh, yes, I added that options because it was suggested in the help.
I've removed it and now it works with the stan version "https://cloud.r-project.org/"
You can delete my last messages to clean the thread.

Regards
