### ISSUE TITLE
***caught segfault*** rstan2.11 in ubuntu16.04

### ISSUE THREAD

**Issue by lionel68** [stan-dev/rstan#333]
R session abort when trying to fit a model using rstan and return:  **\* caught segfault ***
address 0x20, cause 'memory not mapped'

Example with minimal regression model:
m<-"data{
 int N;
 real x;
 real y;
}
parameters{
 vector[2] beta;
 real<lower=0> sigma;
}
model{
 y ~ normal(beta[1]+beta[2]*x,sigma);
}"

R code:
N<-100
x<-runif(N,-2,2)
y<-rnorm(N,1+2*x,1)
library(rstan)
mf<-stan(model_code=m)

Here is the output of sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8  
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.11.1       StanHeaders_2.11.0 ggplot2_2.1.0

**Comment by bob-carpenter** [comment]
It doesn't segfault for me, but it also doesn't run.
You need to declare 

vector[N] x;
vector[N] y;

I also never use the default I/O because it won't work depending
on what's already in your environment;  I'd recommend always passing
the data in as an argument, at least by name (see the RStan manual).

You also need to declare the scale parameter properly as

  real<lower=0> sigma;

When you fix those two bugs in your model, it works fine:

```
      mean se_mean   sd   2.5%    25%    50%    75%  97.5% n_eff Rhat
```

beta[1]   1.00    0.00 0.11   0.78   0.93   1.00   1.07   1.21  3215    1
beta[2]   1.97    0.00 0.09   1.80   1.92   1.97   2.04   2.15  3290    1
sigma     1.08    0.00 0.08   0.94   1.02   1.07   1.13   1.24  3331    1
lp__    -56.54    0.03 1.22 -59.61 -57.12 -56.21 -55.64 -55.19  2128    1

here's the whole thing:

m<-"data{
int N;
vector[N] x;
vector[N] y;
}
parameters{
vector[2] beta;
real<lower=0> sigma;
}
model{
y ~ normal(beta[1]+beta[2]*x,sigma);
}"

N<-100
x<-runif(N,-2,2)
y<-rnorm(N,1+2*x,1)
library(rstan)
mf<-stan(model_code=m)

I'd suggest reading the regression chapter of the manual.

Why Ubuntu version would segfault is beyond my knowledge of R and Linux
together.
- Bob

P.S.  Here's what I got

> source('norm.R')
> Loading required package: ggplot2
> Loading required package: StanHeaders
> rstan (Version 2.11.1, packaged: 2016-07-28 18:19:31 UTC, GitRev: 85f7a56811da)
> For execution on a local, multicore CPU with excess RAM we recommend calling
> rstan_options(auto_write = TRUE)
> options(mc.cores = parallel::detectCores())
> Error in eval(expr, envir, enclos) : 
>   mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=x; dims declared=(); dims found=(100)
> In addition: Warning messages:
> 1: package ‘rstan’ was built under R version 3.2.5 
> 2: package ‘StanHeaders’ was built under R version 3.2.5 
> failed to create the sampler; sampling not done
>

**Comment by bgoodri** [comment]
Does not segfault for me either on Xenial. We have occasionally run into problems with the computer has a mix of US and German locales though.

**Comment by lionel68** [comment]
Thanks for your swift reply, applying the corrections did not change the results, R still abort, here is the complete output:

m<-stan(file="Documents/PhD/Herbivory_Stuff/Analysis/STAN/minimal.stan",data=list(N=N,x=x,y=y))

 **\* caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: .Call(Module__classes_info, xp)
 2: Module(module, mustStart = TRUE)
 3: .getModulePointer(x)
 4: <S4 object of class "Module">$stan_fit4model1668235a932e_minimal
 5: <S4 object of class "Module">$stan_fit4model1668235a932e_minimal
 6: eval(expr, envir, enclos)
 7: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
 8: object@mk_cppmodule(object)
 9: .local(object, ...)
10: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
11: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
12: stan(file = "Documents/PhD/Herbivory_Stuff/Analysis/STAN/minimal.stan",     data = list(N = N, x = x, y = y))

I do have Ubuntu set up in English but am sitting in Germany ...

Just to be sure here is the model code:
data{
 int N;
 vector[N] x;
 vector[N] y;
}
parameters{
 vector[2] beta;
 real<lower=0> sigma;
}
model{
 y ~ normal(beta[1]+beta[2]*x,sigma);
}

**Comment by bgoodri** [comment]
Might as well try rstan 2.12.1 at this point. I'm concerned about the error messages that say "rstan was built under R 3.2.5", although that hasn't been a problem before.

**Comment by lionel68** [comment]
Updated to rstan2.12.1, still getting the same error message ...

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8  
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.12.1       StanHeaders_2.12.0 ggplot2_2.1.0

**Comment by bgoodri** [comment]
I haven't seen any error messages like this in months, but a while ago, it was possible to get something like that if Rcpp, RcppEigen, and the Stan program were compiled with different compilers or different compiler options. Could that possibly be an issue in your case?

**Comment by lionel68** [comment]
I followed the instructions given here: https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux, everything runs fine even if I get some warnings during rstan installation (see below), but I still get the same error message (also tried the 8school example but it did not work either). How can I see compiler settings for Rcpp, RcppEigen and rstan?

Message I get during rstan installation:
g++ -I/usr/share/R/include -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12  -I"/home/lionel/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/lionel/R/x86_64-pc-linux-gnu-library/3.3/RcppEigen/include" -I"/home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include" -I"/home/lionel/R/x86_64-pc-linux-gnu-library/3.3/StanHeaders/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -c stanc.cpp -o stanc.o
In file included from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/detail/resolve.hpp:26,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/detail/push.hpp:24,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/stream_buffer.hpp:22,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/iostreams/stream.hpp:21,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/spirit/home/qi/stream.hpp:15,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/spirit/home/qi.hpp:30,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/spirit/include/qi.hpp:16,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/StanHeaders/include/src/stan/lang/parser.hpp:9,
                 from /home/lionel/R/x86_64-pc-linux-gnu-library/3.3/StanHeaders/include/src/stan/lang/compiler.hpp:6,
                 from stanc.cpp:22:
/home/lionel/R/x86_64-pc-linux-gnu-library/3.3/BH/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")

**Comment by bgoodri** [comment]
Rcpp and RcppEigen may have been installed from the Ubuntu archives or CRANdebs, in which case I don't know how you figure out what the settings were. It is easiest to just try

``` R
install.packages(c("Rcpp", "RcppEigen", "StanHeaders"))
```

**Comment by lionel68** [comment]
Well re-installing all four packages in this order (Rcpp, RcppEigen, StanHeaders and rstan) fom R solved the problem. Thank you for your time!
