### ISSUE TITLE
Issue with parallel::detectCores()

### ISSUE THREAD

**Issue by andreeleuterio** [stan-dev/rstan#335]
Description:
I am able to run the Eight Schools example, but when I set options(mc.cores = parallel::detectCores()), it freezes. Not setting the option gives me the expected output.
Here are the commands that I ran. I stopped the execution after about 20 minutes of it being stuck on 
`Rscript execution error: No such file or directory`

```
`> library(rstan)
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.11.1, packaged: 2016-07-28 18:19:31 UTC, GitRev: 85f7a56811da)
> rstan_options(auto_write = TRUE)
> options(mc.cores = parallel::detectCores())
> schools_dat <- list(J = 8,
+                     y = c(28,  8, -3,  7, -1,  1, 18, 12),
+                     sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
> fit <- stan(file = 'eightschools.stan', data = schools_dat, iter = 1000, chains = 4)
DIAGNOSTIC(S) FROM PARSER:
Warning (non-fatal): assignment operator <- deprecated in the Stan language; use = instead.

In file included from /pathto/rstan/include/rstan/stan_fit.hpp(62),
                 from /pathto/rstan/include/rstan/rstaninc.hpp(3),
                 from file2a3f3e88421b.cpp(462):
/pathto/StanHeaders/include/src/stan/optimization/bfgs.hpp(113): warning #858: type qualifier on return type is meaningless
        const size_t iter_num() const { return _itNum; }
        ^

In file included from /pathto/rstan/include/rstan/stan_fit.hpp(103),
                 from /pathto/rstan/include/rstan/rstaninc.hpp(3),
                 from file2a3f3e88421b.cpp(462):
/pathto/rstan/include/rstan/sum_values.hpp(79): warning #858: type qualifier on return type is meaningless
      const size_t called() const {
      ^

In file included from /pathto/rstan/include/rstan/stan_fit.hpp(103),
                 from /pathto/rstan/include/rstan/rstaninc.hpp(3),
                 from file2a3f3e88421b.cpp(462):
/pathto/rstan/include/rstan/sum_values.hpp(83): warning #858: type qualifier on return type is meaningless
      const size_t recorded() const {
      ^

Rscript execution error: No such file or directory
^C`
```

I'm running RStan 2.11 on a RedHat 6.7 node. 
Thank you in advance

**Comment by bgoodri** [comment]
I am guessing there is some permission setting in place that prevents you from executing multiple threads. What does `parallel::detectCores()` return? Can you run `example(parLapplyLB, package = "parallel")`?

**Comment by andreeleuterio** [comment]
@bgoodri, here are the outputs:

```
> parallel::detectCores()
[1] 32
> example(parLapplyLB, package = "parallel")

prLpLB> ## No test:
prLpLB> ## Use option cl.cores to choose an appropriate cluster size.
prLpLB> cl <- makeCluster(getOption("cl.cores", 2))
Rscript execution error: No such file or directory

```

It seems like it detects the cores correctly but freezes on the same point where the Eight Schools example did. It's worth noting that the environment I'm working on has no Internet connection so I can't run scripts that fetch data from the internet

**Comment by bgoodri** [comment]
If

cl <- makeCluster(getOption("cl.cores", 2))

fails in isolation, then it is not a rstan problem and there is not
anything rstan can do about it. I think there is some problem with your
setup.

**Comment by andreeleuterio** [comment]
@bgoodri indeed I get
`Rscript execution error: No such file or directory`
What is odd is that parallel::detectCores() worked on RStan 2.9.0, which is why I thought the issue could be with the new version instead of the system

**Comment by bgoodri** [comment]
I think you need to talk to the system administrator for your server.
