### ISSUE TITLE
Error in stan_plot with dev version of ggplot2 (2.1.0.9001)

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstan#337]
#### Summary:

`stan_plot` fails with `Error in if (e1$inherit.blank) return(e2) else return(e1) : 
  argument is of length zero` when using **ggplot2** dev version 2.1.0.9001.
#### Description:

I am not sure whether this ends up being a problem in **rstan** or **ggplot2**, but you may understand this faster than me.
#### Reproducible Steps:

fit any model with `rstan::sampling` (e.g. the one from the main **rstan** doc page)
and run `stan_plot(<stanfit object>)` while having **ggplot2** version 2.1.0.9001 installed.
#### Current Output:

`Error in if (e1$inherit.blank) return(e2) else return(e1) : 
  argument is of length zero`
#### Expected Output:

A `ggplot` object
#### RStan Version:

2.12.1
#### R Version:

R version 3.3.1 (2016-06-21)
#### Operating System:

Windows 10, 64bit

**Comment by jgabry** [comment]
Thanks Paul. Do you still get that error if you use the develop branch of
rstan?

**Comment by paul-buerkner** [comment]
It seems to be fixed on the develop branch. Thanks Jonah!

**Comment by karchjd** [comment]
I receive exactly the same error and do not use any development versions. That is, when I run `plot` on any object of class `"stanfit"` I get the output message:

```ci_level: 0.8 (80% intervals)
outer_level: 0.95 (95% intervals)
Error in if (e1$inherit.blank) return(e2) else return(e1) : 
  argument is of length zero
```


I have updated R as well as both packages  to their most recent CRAN version. My R version is 3.3.2, my ggplot version is `ggplot2_2.2.0`,  and my `rstan` version is  `rstan_2.12.1`

This code produces the error for example. But so far the error occurred with every stanfit object I have tried

```library(rstan)
ocode <- "
  data {
    int<lower=1> N;
    real y[N];
  } 
  parameters {
    real mu;
  } 
  model {
    mu ~ normal(0, 100);
    target += normal_lpdf(y | mu, 1);
  } 
"
y2 <- rnorm(20)
sm <- stan(model_code = ocode,data = list(y = y2, N = length(y2)))
print(plot(sm))
```

**Comment by jgabry** [comment]
The development version of ggplot2 referred to is now the released version
so that's why it's still an issue. We haven't had an rstan release since
then but the bug is fixed on the rstan develop branch and a release is
imminent (this week I think).

Jonah

P.S. I recommend trying out our new bayesplot package if you haven't
already. That should be fully compatible with the latest ggplot2.
