### ISSUE TITLE
Stan manual. Vector of integers or reals?

### ISSUE THREAD

**Issue by juanpide** [stan-dev/rstan#348]
Hello.

I'm starting to read the Stan manual

In page 36 (if vesion 2.12) in the Upper and Lower Bounds section you can read:

`vector<lower=-1,upper=1>[3,3] corr;`

It doesn't explain if the vector is a vector of integers or real numbers.
Though later in the manual it's said that vectors and matrices cannot be typed to return integer values.

And I think the structured vectors definition is not clear.
#### Version:

It happens in several versions, included the 2.12

**Comment by bgoodri** [comment]
Comments about the Stan manual should go to https://github.com/stan-dev/stan but a `vector` type in Stan only holds real numbers. An `array` can be either `int` or `real`.

**Comment by jgabry** [comment]
Thanks. That's a typo in the manual. Seems like it should be a matrix (of reals) not a vector. I added it to the manual issue here: https://github.com/stan-dev/stan/issues/2051
