### ISSUE TITLE
Bug in warning of numerical problems

### ISSUE THREAD

**Issue by stijnmasschelein** [stan-dev/rstan#350]
#### Summary:

A bug in the warning of numerical problems reports numerical problems from _during_ warmup as being _after_ warmup.
#### Description:

Rstan reports multiple numerical problems for a chain even when there is only one sampling iteration. 
#### Reproducible Steps:

The [R file](https://github.com/stan-dev/rstan/files/560467/rgithub.txt) generates data. If you rename [this stan file](https://github.com/stan-dev/rstan/files/560468/stangithub.txt) to 'econ_group.stan' then the R file will also run my stan model. The stan model contains print statements that will print when the offending parameter is nan or inf. The print statement only happen at the start of warmup and not later. Rstan does report numerical problems after warmup.
#### Current Output:

Eg of one of the chains.

```
The following numerical problems occured the indicated number of times after warmup on chain 3
                                                                                                     count
Exception thrown at line 88: binomial_logit_log: Probability parameter[145] is nan, but must be fini    12
Exception thrown at line 88: binomial_logit_log: Probability parameter[17] is nan, but must be finit     6
Exception thrown at line 88: binomial_logit_log: Probability parameter[177] is nan, but must be fini     5
```
#### Expected Output:

A maximum of 1 in the count column as long as iter = 201 and warmup = 200.
#### RStan Version:

2.12.1
#### R Version:

R version 3.3.1 (2016-06-21)
#### Operating System:

OS X 10.12.1

**Comment by jgabry** [comment]
Thanks for reporting this. We'll confirm the bug and try to get it fixed
for the next release.
