### ISSUE TITLE
RGui for Windows buffers output until very end

### ISSUE THREAD

**Issue by syclik** [stan-dev/rstan#351]
#### Summary:
Running a Stan program in the RGUI for Windows buffers all output until the very end. There's no progress that's output.

#### Description:
I'm finding lots of different suggestions on StackOverflow for this. Perhaps we need to judiciously use `flush.console()`?
https://stat.ethz.ch/R-manual/R-devel/library/utils/html/flush.console.html

How do we flush output for `Rcpp::Rcout`?

#### Reproducible Steps:
```R
library(rstan)
fit <- stan(model_code = "parameters { real<lower = 0, upper = 1> theta; } model {}")
```
#### Current Output:
While running:
```
```
(nothing; no compiler warnings, no progress)

#### Expected Output:
While running: everything should happen as it occurs.

#### RStan Version:
2.12.1

#### R Version:
 "R version 3.3.0 (2016-05-03)"

but really, the RGui (64-bit) R Console.

#### Operating System:
Windows 7.

**Comment by bgoodri** [comment]
You have to hit Control-W or uncheck Misc -> Buffer output.

**Comment by syclik** [comment]
Thanks! I can't believe I didn't know about that.
