### ISSUE TITLE
need a function that will extract a suitable initialization list from a stanfit

### ISSUE THREAD

**Issue by dlakelan** [stan-dev/rstan#352]
It can be useful to run stan and get some results, and then want to start your next more substantial run from a position informed by the previous results.

foo <- stan(...)

foo2 <- stan( init=extract.init(foo,33))

that is, foo2 starts its run at the location determined by the 33rd sample from earlier run foo

I realize this doesn't imply the same mass matrix and that you'd still need to do warmup and so this doesn't mean you are just continuing as if you'd never stopped, but particularly for problems where random starting points in high-dimensional models eventually converge to fairly tightly constrained intervals in each dimension, just doing an initial short run or a short optimization and then running a long run including warmups from a "good" starting point can be a great thing.

In any case, for high dimensional models, it's a pain to specify a particular starting point, and letting stan find you one and then extracting it would be a big step in the right direction for controlling initialization. Of course, each person can implement this in a buggy way in their own code, but it seems like something rstan should support.

**Comment by jgabry** [comment]
Hi Daniel,

So the only change would be the addition of  a convenience function that
formats a single posterior draw of the parameters in an acceptable way to
pass to the init argument, right?

Jonah

**Comment by dlakelan** [comment]
Hi, yes, I think this would be a good function to have, and having everyone do it on their own introduces bugs, inefficiencies, and general silliness, and since there might be some wrangling that is specific to the way stanfit objects work, it makes sense to include in rstan once and for all. 

Also, a little mention in the rstan manual and an example of how it could be useful for starting from an informed initialization point would be good for users.

Finally, I'd also say it might make sense to have the index argument also take the string "mean" which would then extract the mean value for all the parameters from the previous stanfit, and maybe have this be the default if nothing is specified.

**Comment by bob-carpenter** [comment]
> On Nov 4, 2016, at 5:57 PM, Jonah Gabry notifications@github.com wrote:
> ...
> So the only change would be the addition of a convenience function that
> formats a single posterior draw of the parameters in an acceptable way to
> pass to the init argument, right?

:-)  Agreed.  That's what I wrote in the blog comment, when I
should've been putting it on the issue.

**Comment by bob-carpenter** [comment]
> On Nov 4, 2016, at 6:07 PM, Daniel Lakeland notifications@github.com wrote:
> 
> Hi, yes, I think this would be a good function to have, and having everyone do it on their own introduces bugs, inefficiencies, and general silliness, and since there might be some wrangling that is specific to the way stanfit objects work, it makes sense to include in rstan once and for all.

You don't need to convince us that it's better to put commonly used
functionality in (R)Stan than have users reimplement them.  It'll be
better tested with more eyes on it and in some cases we can get inside
structures and make it faster.

> Also, a little mention in the rstan manual and an example of how it could be useful for starting from an informed initialization point would be good for users.

Agreed.  In general, it's always nice to have an example.

> Finally, I'd also say it might make sense to have the index argument also take the string "mean" which would then extract the mean value for all the parameters from the previous stanfit, and maybe have this be the default if nothing is specified.

I'd prefer a separate function for this.  But you have to again
be careful, because the posterior mean's another value that might
not be in the typical set.   A 50-dimensional normal is a simple example
of where the posterior mean's not in the typical set.
- Bob

**Comment by dlakelan** [comment]
Bob: yes in high dimensions the average can be weird. But there are several notions of how far you are from the typical set. In particular the one that matters for Stan users is how much computing time via HMC movements does it take before you get in the typical set? The mean value could be "close" in this metric while still being far in the euclidean metric for example. 

Also, there's the question of what's the alternative? It's not necessarily the case that the Stan "random" initializer would produce a "better" init. 

I think maybe making the "mean" be the default might be the wrong idea though, perhaps the default should be "random" where one of the previous samples is chosen uniformly at random?

**Comment by dlakelan** [comment]
ok, now I'm thinking the following text options should be available: "random", "mean", "first" and "last" with "random" or "last" being the default, not sure which.

**Comment by betanalpha** [comment]
As Bob notes the mean is not helpful and will do nothing but cause trouble.
If people want to do that on their own that’s fine, but we shouldn’t facilitate it.

Restarting from a previous mixing chain is fine, but it probably won’t help
much.  HMC converges very quickly — it’s the adaptation that’s slow, and
we can’t reuse previous adaptation info yet.

**Comment by dlakelan** [comment]
Michael, the motivation for all of this arises in a problem I'm working on right now in which there are 3 vectors of 6000 or so parameters. Each one has a cauchy prior with a small scale around zero, and there are basically a few of these parameters where the likelihood is going to pick out a point far from zero (let's say somewhere between 100 and 300 of them and they will be 10 or 20 scale distances from the zero point). I've done some of the reparameterization tricks in the manual, and that's helping, but in adjusting the model I've got a suspicion that things go awry in warmup. The model takes a long time to run, and I suspect that random starting vectors don't get anywhere near the typical set in say 20 or 30 warmup steps. Since these 20 or 30 steps take an hour... it's worth it to me to start somewhere "reasonable" because I can't afford a ton of warmup, especially during the model adjustment phase. I'd be fine with running 2000 samples over a full weekend in the end... but not while I'm debugging and trying to determine if there are facts that I've left out of my model (such as prior information I need to supply but haven't really thought much about yet) or different parameterizations that work better etc.

The main time you're going to want this is during the model-building and model-tuning phase I think, where you'd like to use the partial/not-quite-correct information gleaned in earlier expensive runs with non-optimal models to at least make it so your next run after tuning does better than it would if you started at the default random initialization.
