### ISSUE TITLE
rstan is leaving empty tmp files behind

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstan#358]
#### Summary:
For each chain rstan is leaving one empty tmp file in tmp directory

#### Description:
After runnning rstan and results have been returned to R, there  are one empty tmp file for each chain

  /tmp/RtmpPG5v3y:
  total used in directory 1284 available 12337076
  drwx------  2 ave  ave     4096 Nov 30 13:54 .
  -rw-rw-r--  1 ave  ave        0 Nov 30 13:54 file507f1695a5aa
  -rw-rw-r--  1 ave  ave        0 Nov 30 13:54 file507f565dc053
  -rw-rw-r--  1 ave  ave        0 Nov 30 13:54 file507f63b30f98
  -rw-rw-r--  1 ave  ave        0 Nov 30 13:54 file507f10473610

This becomes annoying when running rstan many times. I'm running rstan more than one million times, which is leaving more than four million empty files in tmp directory.

When making minimal reproducible example, I noticed that when running with model_code option, also am tmp file with model code string is left behind.

#### Reproducible Steps:
code<-"parameters { real t;} model { t ~ normal(0,1);}"
model<-stan(model_code=code)

check the latest files in tmp directory, repeat to generate more tmp files

#### RStan Version:
[1] ‘2.12.1’

#### R Version:
[1] "R version 3.2.3 (2015-12-10)"

#### Operating System:
Ubuntu 16.04

**Comment by bgoodri** [comment]
OK. I'll try to delete unneeded files.
