### ISSUE TITLE
stan_model calls readRDS rather than load

### ISSUE THREAD

**Issue by stephenweigand** [stan-dev/rstan#364]
#### Summary:
It looks like `stan_model()` is calling `readRDS()` rather than `load()` on an .rda file. 

#### Description:
`stan_model()` will look for an existing model fit saved out as an .rda file but calls `readRDS()` rather than `load()` to retrieve it. 

#### Reproducible Steps:

```R
## Code to save to file called `issue.R`
library(rstan)
scode <- "
     parameters {
       real y[2]; 
     } 
     model {
       y[1] ~ normal(0, 1);
       y[2] ~ double_exponential(0, 2);
     } 
     "
writeLines(scode, "mymodel.stan")

mymodel <- stan("mymodel.stan", iter = 10, verbose = FALSE) 
save(mymodel, file = "mymodel.rda")
```
Steps

1. From the shell do `R CMD BATCH issue.R`

2. Everything should be fine as shown in `issue.Rout`

3. There should be a file called `mymodel.rda` in the directory

4. Now do `R CMD BATCH issue.R` again

I get this error:

```R
R> mymodel <- stan("mymodel.stan", iter = 10, verbose = FALSE) 
Error in readRDS(file.rda) : unknown input format
Calls: stan -> stan_model -> is -> readRDS
Execution halted
```
#### RStan Version:

2.12.1

#### R Version:

R version 3.2.0 (2015-04-16)

#### Operating System:

Linux CentOS

**Comment by bgoodri** [comment]
You shouldn't do 
```
save(mymodel, file = "mymodel.rda")
```
Just first do
```
rstan_options(auto_write = TRUE)
```
and it will be fine, although we are currently using the file extensions in a weird way. See
https://github.com/stan-dev/rstan/issues/361

**Comment by stephenweigand** [comment]
Thanks for the quick response. What I was doing was saving multiple objects to a file called `mymodel.rda` and then later `load()`ing along the lines of:
```R
R> save(mymodel, mydata, mythis, mythat, file = "mymodel.rda")
## And in a new session ...
R> load("mymodel.rda", verbose = TRUE)
Loading objects:
  mymodel
  mydata
  mythis
  mythat
```
But it's easy for the user to treat `mydata.rda` or `mydata.rds` as "reserved."
