### ISSUE TITLE
Problem when passing data list to stan

### ISSUE THREAD

**Issue by ppernot** [stan-dev/rstan#374]
#### Summary:
Since version 2.13 `stan` returns an error when elements of the data list
are not exposed in the environment.

#### Description:
In `R` interactive mode, the example below returns the following error message 
> failed to get names of data from the model; sampling not done

```
stan_model = "
data {
    int N;
    vector[N] x;
    vector[N] y;
    vector[N] uy;
}
parameters {
  real a;
  real b;
}
model {
  for (i in 1:N) {
    y[i] ~ normal(a+b*x[i], uy[i]);
  }
}
"

# Generate data
get_ref_data = function(N) {
  x <- as.numeric(1:N)
  y <- x+rnorm(N)
  uy<- x/x
  return(list(N=N, x=x, y=y, uy=uy))
}
stan_data = get_ref_data(10)

# with(stan_data,
# {
  fit = stan(model_code = stan_model, model_name = 'test',
           data = stan_data,
           pars = c("a","b"),
           iter = 1000, chains = 1, warmup = 100, verbose=FALSE)
  print(fit)
# }
# )
```

The sampling is done without error if the `with` structure is uncommented,
whereby the elements of the list become visible to `stan`.   

Note that the error does not occur if the script is run in BATCH mode,
or if the `stan_data` list is built directly, without using the `get_ref_data()`
function.

__It looks like `stan` does not get the data values from the list's content,
but from the (global ?) environment, which seems abnormal (to me). 
The present behaviour is in conflict with earlier versions of rstan.__

#### Operating System: CentOS Version 7 (Core) 64-bit

**Comment by jgabry** [comment]
Hmm, I'm not seeing the problematic behavior when I run your code. I'm on Mac but I doubt the OS difference should matter for something like this. @bgoodri Can you replicate this on whatever linux you're using? 

@ppernot Using a fresh R session can you confirm that the code below results in the same kind of error? Thanks!

```r
library("rstan")
prog <- "data {int N; vector[N] x;} parameters {vector[N] y;} model {y ~ normal(x,1);}"
f <- function() list(N = 1, x = array(1))
fit <- stan(model_code = prog, data = f())
```

**Comment by bgoodri** [comment]
I am not getting this error either. RStan 2.13.1 did change the behavior
but it was ostensibly for the better.

**Comment by ppernot** [comment]
@jgabry: your code runs smoothly. If I run mine in the same session, I get the error...

The full error message is:
> Error in get(x, envir = env, inherits = inherits) : 
>  la promesse est déjà en cours d'évaluation : référence récursive d'argument par défaut ou problème antérieur ?
> failed to get names of data from the model; sampling not done

**Comment by bgoodri** [comment]
I'm not getting an error message in either case. @ppernot can you post the output of `traceback()` after your error occurs?

**Comment by ppernot** [comment]
> traceback()
Pas d'historique des fonctions appelées ('traceback') disponible

**Comment by bgoodri** [comment]
OK. Maybe do `options(error = recover)` first and then cause the error message?

**Comment by ppernot** [comment]
Sorry. No effect....

**Comment by bgoodri** [comment]
Does this work
`with(stan_data, stan(model_code = stan_model, model_name = 'test', pars = c("a","b"), chains = 1))`

**Comment by ppernot** [comment]
Yep!

**Comment by bgoodri** [comment]
What version of R do you have?

**Comment by ppernot** [comment]
3.3.2 (2016-10-31)

**Comment by ppernot** [comment]
This is very weird:
1/ if I run the stan command at the prompt after sourcing the code and getting an error, this second command runs OK
2/ if I double the command in the script and source it, both calls return the error
3/ if I copy/paste the script to run it (instead of sourcing it), both calls run OK
I am going  NUTS ;-)

**Comment by ppernot** [comment]
@jgabry 
If I save your small code in a file and source it, I get the error
If I run it at the R prompt (as I did above), it runs OK

**Comment by jgabry** [comment]
This is very strange indeed. I'm still not sure what's going on here.

**Comment by bgoodri** [comment]
It seems to work if you rename the `x` object in your Stan program to anything else. The `source()` call seems to insert something named `x` into the call stack that causes the error.

**Comment by ppernot** [comment]
@bgoodri : yes, this seems to avoid the problem...
I assume you were able to reproduce it on your side ?

**Comment by bgoodri** [comment]
yeah, I'm going to try to work around it

**Comment by bgoodri** [comment]
This was fixed in 2.14.1

**Comment by ppernot** [comment]
@bgoodri : Thanks and Happy New Year !

Just for my intellectual rest, what caused this funny behavior ?

**Comment by bgoodri** [comment]
The source() function put a non-numeric object called x that was being
found first
