### ISSUE TITLE
expose functions returning integer arrays again

### ISSUE THREAD

**Issue by wds15** [stan-dev/rstan#375]
#### Summary:
exposing functions returning int arrays currently does not work

#### Description:
in rstan 2.12 it was possible to export functions which returned arrays of integers. This stopped working with 2.13 and 2.14.

#### Reproducible Steps:
Here is a small stan file which triggers the problem:

```
functions {
  // count number times elem appears in test set
  int count_elem(int[] test, int elem) {
    int count;
    count = 0;
    for(i in 1:num_elements(test))
      if(test[i] == elem)
        count = count + 1;
    return(count);
  }
  // find elements in test which are equal to elem
  int[] which_elem(int[] test, int elem) {
    int res[count_elem(test, elem)];
    int ci;
    ci <- 1;
    for(i in 1:num_elements(test))
      if(test[i] == elem) {
	res[ci] <- i;
	ci <- ci + 1;
      }
    return(res);
  }

}
data {
  int y[10];
}
transformed data {
  print("zero data items: ", count_elem(y, 0));
  print("zero data item indices: ", which_elem(y, 0));
}
parameters {
  real mu;
}
model {
  target += normal_lpdf(mu| 0, 1);
}
```

When calling expose_stan_function("model.stan"), then the which_elem function is not exported.

#### Current Output:
The function which_elem is not exported to R as it is stripped off from the C++ file.

#### Expected Output:
function which_elem should be exported.

#### RStan Version:
2.14.1

#### R Version:
3.3.1

#### Operating System:
macOS sierra

**Comment by wds15** [comment]
The problem can be fixed with this change in `expose_stan_functions.R`:

replace

```
  ints <- grep("^int$", lines)
```

with

```
  ints <- c(grep("^int$", lines), grep("^std::vector<int>$", lines))
```

I have this change on a branch, but I am not sure if this is really an appropiate fix - what about arrays of int`s being returned of higher dimension? Maybe the regex should be made more general.

**Comment by bob-carpenter** [comment]
We really need to code generate proper versions of all
these.  Patching regexes is not optimal.  I'll try to
do this soon as it seems to keep coming up:

https://github.com/stan-dev/stan/issues/2196

- Bob

**Comment by wds15** [comment]
Latest develop fixes this.
