### ISSUE TITLE
`BMFI low` error on Windows 10 but not macOS

### ISSUE THREAD

**Issue by mkiang** [stan-dev/rstan#377]
Just wondering if this is expected behavior. Details below.

#### Summary:
Inconsistent error message (specifically, `low BFMI`) across Windows 10 and macOS 10.12.2 implementations of RStan.

#### Description:
Windows 10 throws a `BMFI low` error on an identical model (with identical data) when macOS does not. This happens across two different sets of data, each with two different sets of runs, but not on every dataset (and not on every run). The runs take a relatively long time so I don't have a huge sample size. Can find a reproducible dataset with public data if necessary but unable to share actual data.

When comparing results (just mean and 2.5th%ile and 97.5%ile), they are the same. ESS was smaller on two Windows 10 runs, but didn't use same seed across operation systems so could have just been a bad start.

#### Reproducible Steps:
Ran identical code on identical data in macOS and Windows 10.

#### Current Output:
Didn't save exact output (and model takes quite a while to run), but it was the standard `BFMI low` error.

#### Expected Output:
Either `BFMI low` error in macOS or no error in Windows 10.

#### RStan Version:
On both Windows 10 and macOS 10.12.2: `2.14.1`

#### R Version:
Both macOS and Windows 10 are running `R version 3.3.2 (2016-10-31)`

#### Operating System:
macOS is version `10.12.2` and Windows 10 is version `1607` (specifically, build `14393.576`).

**Comment by bgoodri** [comment]
The model output is not going to be the same across operating systems (although it should be similar), so there is some chance that it could trigger the low BFMI threshold on one but not the other. I don't think this is a bug because the actual BFMI calculation is simple and not platform specific, but if you are close to the BFMI threshold, you probably want to think about reparameterizations of the model.

**Comment by mkiang** [comment]
@bgoodri thanks for the reply. If you don't mind, can you clarify a couple things. 

- From limited testing, it seems I cannot get identical results across platforms even when setting the same `set.seed()`, `stan(..., seed)`, and `stan(..., init = 0)`. (Obviously, all other model parameters are also identical). Is it possible to do so?
- The BFMI error seems to be very consistent for my model on the PC and not so on the Mac -- dozens of different models with different (but similar) datasets. In fact, I've never gotten it on my Mac, but almost always do on the PC. Diagnostics on the PC seem to indicate I'm hitting the max tree depth (again, not on the Mac). Where would you suggest I start in terms of getting more consistent (or Mac-like) results?

**Comment by bgoodri** [comment]
On Thu, Jan 12, 2017 at 11:48 PM, Mathew Kiang <notifications@github.com>
wrote:

> @bgoodri <https://github.com/bgoodri> thanks for the reply. If you don't
> mind, can you clarify a couple things.
>
>    - From limited testing, it seems I cannot get identical results across
>    platforms even when setting the same set.seed(), stan(..., seed), and
>    stan(..., init = 0)`. (Obviously, all other model parameters are also
>    identical). Is it possible to do so?
>
> It is not possible, mostly due to the C++ compilers not generating
identical code. Also, set.seed() only affects the R seed. To make the
results exactly replicatable _on the same machine_ you need to pass a seed
to the seed argument of stan() or sampling().

>
>    - The BFMI error seems to be very consistent for my model on the PC
>    and not so on the Mac -- dozens of different models with different (but
>    similar) datasets. In fact, I've never gotten it on my Mac, but almost
>    always do on the PC. Diagnostics on the PC seem to indicate I'm hitting the
>    max tree depth (again, not on the Mac). Where would you suggest I start in
>    terms of getting more consistent (or Mac-like) results?
>
> It is going to be hard for me to say anything without being able to
replicate it. If you can share the model and data, I could take a look.
Otherwise, we can try to coach you through some stuff but it will probably
take a lot of back and forth.

**Comment by mkiang** [comment]
Thanks for the reply. Regarding BFMI, let me make a find a replicable example with a smaller (shareable) dataset and get back to you. Would be helpful to understand why the error doesn't occur on my Macbook and given how many models I need to run and how long they go for, I'd rather be able to run it on my office computer.

**Comment by bgoodri** [comment]
You might call

debug(rstan:::throw_sampler_warnings)
rstan:::throw_sampler_warnings(stanfit)

on both computers to see if the BFMI estimates (toward the end) are really
that different.
