### ISSUE TITLE
Error saving PDF when Arial font not found

### ISSUE THREAD

**Issue by infotroph** [stan-dev/rstan#381]
#### Summary:
Current Rstan plotting theme causes plot failure when saving to PDF on systems not configured to include "Arial" in pdfFonts().

#### Description:
While trying to rerun a script that worked in November on Rstan 2.12.1, I found that saving a traceplot to PDF now fails with "Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :  invalid font type.” After some digging, it seems the rstan plotting theme now sets family=“Arial” but on my machine R only knows Arial by the name “ArialMT”. 

#### Reproducible Steps:

```
library("ggplot2")
plt = ggplot(mtcars, aes(wt,mpg))+geom_point()
thm = get("theme", envir=rstan:::.rstanvis_defaults)

# Works as expected, plot uses Helvetica
ggsave("fontdemo_1.pdf", plt)

# Fails ("invalid font type"), leaves PDF with plot half-drawn
ggsave("fontdemo_2.pdf", plt + thm) 

# Works, plot uses Arial
ggsave("fontdemo_3.pdf", plt + thm + theme(text=element_text(family="ArialMT")))

# Works iff you have extrafont correctly installed and set up
# and Arial present on your machine
library("extrafont")
loadfonts()
ggsave("fontdemo_4.pdf", plt + thm)
```

#### RStan Version:
2.14.1

#### R Version:
Tested with both 3.2.2 and 3.3.2

#### Operating System:
Tested with both OS X 10.11.6 running R 3.3.2 and Amazon Linux 4.4.41-35 running R 3.2.2. Same result in both, except that plot 4 succeeds on OS X and fails on Linux (because my Amazon image has no Arial font for extrafont to find).

**Comment by jgabry** [comment]
Thanks for reporting the problem. That's interesting. We haven't touched
the font stuff in a long time and never used to have any issues with it,
but I think there have been several recently. I wonder if something changed
in one of the packages we're calling internally (either directly or
indirectly via another package). If not then I'm not sure why we wouldn't
have run into this problem until now. I'll look into this a bit and then
we'll either change the font settings for everyone or at a minimum try to
check for available fonts if that's possible.

**Comment by infotroph** [comment]
If it helps the search, looks like the Arial specification was introduced in ad8eae537ef887df4f7744718ae981ae0cca5c17

**Comment by jgabry** [comment]
Great, thanks for the pointer.

**Comment by jgabry** [comment]
Just so I'm 100% clear on when this is happening, does this error only
occur when saving a plot or anytime the ggplot object is printed/plotted?

**Comment by infotroph** [comment]
Any time the object is plotted:

```
> pdf("fontdemo_multi.pdf")
> plt+thm
Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid font type
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> plt+thm+theme(text=element_text(family="ArialMT"))
> plt+thm
Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid font type
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> dev.off()
```

**Comment by infotroph** [comment]
Belated clarification: Any time the object is plotted *to a PDF device.* Onscreen plotting and saving in raster formats all seem to work as expected for me, though I haven't tested that very deeply.

**Comment by jgabry** [comment]
Ok thanks, that last clarification is very helpful.

**Comment by wds15** [comment]
I was the one suggesting the fix with the base_family as a workaround to ggplot2 issue. As far as I recall, the need to specify explicitly the base_family is not anymore needed once ggplot2 2.2.1 came out. So in short: I think we can take away the base_family default, but require ggplot2 2.2.1 at least and then it should work.

**Comment by jgabry** [comment]
Thanks Sebastian. I think that's the best solution. I'll make the change
tonight or tomorrow and then we can test it out.

**Comment by jgabry** [comment]
Ok I made that change in d822f223f4098385fe021feaad2e9d8317924596. 

@infotroph If you install from GitHub do you still get the error when using the PDF device? I think to install the right version from GitHub you need
```r
devtools::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")
```

**Comment by infotroph** [comment]
Yep, that appears to fix it. Thanks!
What's the convention re closing -- do I close this now or leave it open until merged?

**Comment by jgabry** [comment]
Ok great! We can close it since I already put it into the develop branch.
