### ISSUE TITLE
Passing data as a list of matrix

### ISSUE THREAD

**Issue by skoyama427** [stan-dev/rstan#384]
I can not give a list of matrix from rstan to stan.

#### Description:

I want to give many matrices as a list. Compile was done. However, data would not be passed to stan. Rstan manual says, we can pass a list of matrix as " matrix[N,M] MS[L] ". 

#### Reproducible Steps:

```
library(rstan)

MA <- matrix(c(2,4,7, 1,3,4), byrow=T, 2, 3)
MB <- matrix(c(4,3,9, 4,2,5), byrow=T, 2, 3)
MC <- matrix(c(1,2,4, 1,2,4), byrow=T, 2, 3)

MS <- list(MA, MB, MC)

data <- list(MS=MS)

stancode <- "

  data {
    matrix[2, 3] MS[3];
  }

  parameters {
    real<lower=0> s;
    real a[3];
    real b[3];
  }

  model {
    for(i in 1:3) {
      MS[i][][2] ~ normal(a[i] + b[i]*MS[i][][1], s);
    }
  }

"

stan(model_code=stancode, data=data, verbose=T, cores=1)

```

#### Current Output:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  variable does not exist; processing stage=data initialization; variable name=MS; base type=matrix_d
In addition: Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In FUN(X[[i]], ...) : data with name MS is not numeric and not used
failed to create the sampler; sampling not done

#### RStan Version:
2.14.1

#### R Version:
R 3.3.2

#### Operating System:
Ubuntu 16.04.1

**Comment by jgabry** [comment]
It looks like passing a list of matrices is either broken or was never actually allowed. Either @bgoodri or @maverickg will know. Until that's sorted out it will work if you use an array. 

On another note, the matrices you're creating in R are 2x3 but in your Stan program you've declared them as 3x3.

**Comment by skoyama427** [comment]
Dear jgabry

Thank you for appropriate suggestion.
I can pass an array to stan like below.
However, this coding style looks like inefficient. 
I am looking forward to updating!

\> On another note, the matrices you're creating in R are 2x3 but in your Stan program you've declared them as 3x3.

Forgive me my careless. I corrected my original post.

```
library(rstan)

MA <- matrix(c(1,3,8,12,15, 2,6,18,24,30), byrow=T, 2, 5)
MB <- matrix(c(3,4,6,6,14, 6,8,0,12,14), byrow=T, 2, 5)
MC <- matrix(c(1,2,4,4,5, -1,-2,-3,-4,-5), byrow=T, 2, 5)

MS <- cbind(MA, MB, MC)
dim(MS) <- c(2,5,3)
data <- list(MS=MS)
MS

stancode <- "

  data {
    real MS[2, 5, 3];
  }

  parameters {
    real<lower=0> s[3];
    real a[3];
    real b[3];
  }

  model {
    for(i in 1:3) {
      for(j in 1:5){
        MS[1,j,i] ~ normal(a[i] + b[i]*MS[2,j,i], s[i]);
      }
    }
  }

"

OUT <- stan(model_code=stancode, data=data)
```
