### ISSUE TITLE
Model with _rng function implemented in C++ generates broken C++ code

### ISSUE THREAD

**Issue by torsti** [stan-dev/rstan#385]
#### Summary:

Stan model with externally (C++) implemented random number generator fails to build due to include statement inserted within template definition.

#### Description:

When you try to build a model with `allow_undefined = TRUE` with a user declared _rng function in the `functions` block, the generated C++ code is invalid as the `#include` statement ends up in the middle of the function declaration.

#### Reproducible Steps:

I can reproduce the problem with this minimal example:

```R
library(rstan)

cpp = "
	template <class RNG>
	int
	my_rng(RNG& base_rng__, std::ostream* pstream__) {
		return 1;
	}
"

cat(cpp, file = 'rng.hpp')

model_code = "
functions {
	int my_rng();
}

model {

}
"

model = stan_model(
	model_code = model_code,
	allow_undefined = TRUE,
	includes = paste0('\n#include "', file.path(getwd(), 'rng.hpp'), '"\n')
)
```

#### Current Output:

```C++
 27: template <
 28: #include "/tmp/rng/rng.hpp"
 29:  class RNG>
 30: int
 31: my_rng(RNG& base_rng__, std::ostream* pstream__);

```

#### RStan Version:

2.14.1

#### R Version:

R version 3.3.2 (2016-10-31)

#### Operating System:

Debian GNU/Linux 9 (stretch)

**Comment by bob-carpenter** [comment]
Thanks for reporting.  Not sure if this is a Stan or RStan issue at heart.  Do you know, @bgoodri?  If it's Stan, you can use the handy issue mover to move it or I can:  https://github-issue-mover.appspot.com

**Comment by torsti** [comment]
@bob-carpenter After looking at the code of `stan_model`, it seems to me that the issue is with RStan. I think that on line 134 in rstan.R the call to `sub` matches the `class RNG` part inside the template and ends up inserting the `#include` statement there.

```R
sub("(class.*: public prob_grad \\{)", paste(includes, "\\1"), stanc_ret$cppcode)
```

**Comment by torsti** [comment]
If the model class name in the Rstan generated C++ code always starts with `model`, a simple fix would be to replace `class.*: public prob_grad` with `class model.*: public prob_grad`, but is that assumption correct?

**Comment by bgoodri** [comment]
Yeah, I think it is an rstan issue. CmdStan inserts at the top.
