### ISSUE TITLE
Determining constrained and unconstrained parameters

### ISSUE THREAD

**Issue by stuntman723** [stan-dev/rstan#391]
Looking at the documentation and #344 , I am very confused about the functions unconstrain_pars and constrain_pars. Is there any way to get a list of the parameters that are constrained or unconstrained?

**Comment by stuntman723** [comment]
This should be labelled a question, but I don't have the ability to do so.

**Comment by bgoodri** [comment]
All parameters in the parameters block of the Stan program are constrained,
although by default they are only constrained to be between negative
infinity and positive infinity. The unconstrain_pars() function maps these
constrained parameters to the real numbers.

**Comment by davidmanheim** [comment]
This should be closed.
(The question is answered, and discussion belongs on a different forum.)

**Comment by bob-carpenter** [comment]
Thanks for sweeping out the issues, @davidmanheim
