### ISSUE TITLE
Rstan model will not compile

### ISSUE THREAD

**Issue by padpadpadpad** [stan-dev/rstan#395]
#### Summary:
Get error when compiling big stan model:

```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file6b842cc125c.cpp:8:
```

#### Description:
I am trying to compile a model for rayan in which I hard code a distribution into model which works for small datasets and a small number of hard coded distributions... [https://groups.google.com/forum/#!searchin/stan-users/daniel$20padfield/stan-users/XvixdZIeHqw/pCa6HtmPAQAJ](url)

However my distributions are actually ~700 individuals for 60 samples and when this is compiled I get the error:

`Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file6b84e5ea497.cpp:8:`

Interestingly if I massively truncate the file does compile so I think it is something to do with the size of the file but I may be mistaken.

#### Reproducible Steps:

I have attached the two model files. `lnc_size_dependence_EcoNorm_examp.stan` is the massively smaller file that does compile whereas the much larger `lnc_size_dependence_EcoNorm.stan` gives the above error.

```
sm <- stan_model('~/Desktop/lnc_size_dependence_EcoNorm_examp.stan')
sm <- stan_model('~/Desktop/lnc_size_dependence_EcoNorm.stan')
```

#### RStan Version:
rstan 2.14.1

#### R Version:
R 3.3.2

#### Operating System:
Sierra OS X 10.12.3

[Archive.zip](https://github.com/stan-dev/rstan/files/790777/Archive.zip)

**Comment by bob-carpenter** [comment]
That's a 1.4 MB `.stan` file that produced a 1.9 MB `.hpp` file (C++).  Trying to compile that huge file blew out clang in CmdStan:

```
~/cmdstan(develop)$ mk ~/Downloads/Archive/lnc_size_dependence_EcoNorm

--- Translating Stan model to C++ code ---
bin/stanc  /Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.stan --o=/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp
Model name=lnc_size_dependence_EcoNorm_model
Input file=/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.stan
Output file=/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp

--- Linking C++ model ---
clang++ -I src -I stan/src -isystem stan/lib/stan_math/ -isystem stan/lib/stan_math/lib/eigen_3.2.9 -isystem stan/lib/stan_math/lib/boost_1.62.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -Wall -DEIGEN_NO_DEBUG  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long -ftemplate-depth=256    -O0 -o /Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm src/cmdstan/main.cpp -include /Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a 
In file included from <built-in>:332:
In file included from <command line>:7:
/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp:241:338: fatal error: bracket nesting level exceeded maximum of 256
/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp:241:338: note: use -fbracket-depth=N to increase maximum nesting level
1 error generated.
make: *** [/Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm] Error 1
```

I was able to compile after upping the max nesting level to 2048 at optimization level 1 (I figured 3 migh t take too long and 0 generate too much debug info):

```
~/cmdstan(develop)$ mk CC="clang++ -O1 -fbracket-depth=2048" ~/Downloads/Archive/lnc_size_dependence_EcoNorm

--- Linking C++ model ---
clang++ -O1 -fbracket-depth=2048 -I src -I stan/src -isystem stan/lib/stan_math/ -isystem stan/lib/stan_math/lib/eigen_3.2.9 -isystem stan/lib/stan_math/lib/boost_1.62.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -Wall -DEIGEN_NO_DEBUG  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long -ftemplate-depth=256    -O0 -o /Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm src/cmdstan/main.cpp -include /Users/carp/Downloads/Archive/lnc_size_dependence_EcoNorm.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a 
```

The resulting executable is only about 20MB.  I didn't try to run it.

**Comment by padpadpadpad** [comment]
Thanks.

Will try to reduce the size of the model. is there anyway to change nesting level in rstan or would I have to download and compile models in CmdStan if they are much larger.

**Comment by bgoodri** [comment]
The compilation aspect should be about the same whether you are using RStan
or CmdStan. For RStan, you can change the compilation settings by editing
the ~/.R/Makevars file

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation

**Comment by padpadpadpad** [comment]
Thanks have a had a play with the Makevars file but have not had any success.

I changed my `~/.R/Makevars` file to:

```
CXX=clang++
#CC=clang
CC=clang++ -O1 -fbracket-depth=2048
```
 
which I think should implement the same thing as above but the stan file still does not compile.

Any ideas?

**Comment by maverickg** [comment]
CC is the compiler for c code.  Modify CXX instead for c++ code.

**Comment by padpadpadpad** [comment]
Hi

So this gets over the error but it never finishes compiling it just hangs for eternity and never completes compilation now. Am using a a significantly smaller model file now too (only 446 kB). I have got the model to work in Jags but would like to try it in Stan if possible.

**Comment by bob-carpenter** [comment]
What platform are you on?  We've had a lot of trouble with Windows blowing out memory or hanging on us because its C++ toolchain doesn't seem to be as scalable as on Linux or Mac OS X.

**Comment by padpadpadpad** [comment]
I am on MacOS Sierra. 8 GB RAM.

**Comment by bgoodri** [comment]
I don't think this is a bug. The C++ file may or may not compile in a finite amount of time depending on the hardware, the compiler, and its settings but even if it is compilable, you don't want your script to generate Stan code like
```
log(
(50000*pow(1.39581543953231e-05,a)) +
(50000*pow(5.18891487045055e-05,a)) +
...
(50000*pow(2.39496635704626e-05,a)));
```
First, you want to use the `log_sum_exp(vector)` function rather than doing the logarithm of a sum of `50000 * pow(base, a)` for various positive base values. This is equal to `log(50000) + log_sum_exp(a * log_base);` where `log_base` is a vector that contains the natural logarithms of 1.39581543953231e-05, 5.18891487045055e-05, ..., 2.39496635704626e-05. If those vectors all have size `K`, you can do this in the `data` and `transformed data` blocks of your Stan program:
```
data{
  int<lower=0> N;             // number of samples
  vector[N] ln_c;               // rate
  int<lower=0> K;
  vector<lower=0>[K] log_base[N];
}
transformed data {
  real log_50000 = log(50000);
}
```
and then in your `model` block, you can do
```
model {
  vector[N] mu;
  vector[N] ln_biomass;
  ln_r0_eco ~ normal(0,10);
  a ~ normal(0,10);
  sigma ~ cauchy(0,2);
  for (n in 1:N) ln_biomass[n] = log_50000 + log_sum_exp(a * log_base[n]);
  // likelihood regression for size dependence of rate
  mu = ln_r0_eco + ln_biomass;
  ln_c ~ normal(mu, sigma);
}
```

**Comment by padpadpadpad** [comment]
So after months of having other things to do (finishing thesis) I have rewritten this using the suggestions of @bgoodri.

I actually used `segment()` and accounted for having different sized vectors for each observation.

Reproducible code for anyone interested:

https://gist.github.com/padpadpadpad/e5fa95373217af6586e2fdc173e6c4b9

Will close this now.
Thanks

**Comment by bob-carpenter** [comment]
Thanks for coming back and closing the issue.

We've introduced cleaner notation since then, so you can write `segment(mass, pos, mass_n[n])` as `mass[pos:mass_n[n]]`.

**Comment by padpadpadpad** [comment]
Thanks @bob-carpenter will implement this.
