### ISSUE TITLE
expose_stan_functions:  array returned as list of vectors and functions with integer arguments not exported

### ISSUE THREAD

**Issue by pboesu** [stan-dev/rstan#400]
#### Summary:
I have two issues with expose_stan_function: (i) arrays are returned as lists of vectors in R - which is unexpected; (ii) functions with integer arguments only are not exposed.

#214 and #370 
#### Description:
(This is a problem I discovered when troubleshooting an ODE system in, so please excuse that the example appears overly simplistic) 
(i) I have a stan function that returns a real array, when calling this function from R a list of (row) vectors is returned, rather than a matrix or array. This behaviour doesn't really matter for my application, but it is unexpected.
(ii) In the process of creating a reproducible example, I noticed that functions with only integer arguments were not exposed to R. I guess this is the same issue as reported in #214, #370, and #375 

#### Reproducible Steps:
Stan functions:
```
/* array creator with dummy real argument*/
  real[,] make_an_array_wreal(int Nrow, int Ncol, real element) {
    
    real output_array[Nrow, Ncol];
    
    for (i in 1:Nrow){
      for (j in 1:Ncol) 
       output_array[i,j] = element + i;
    }
    return output_array;
  }
  
  /* array creator */
  real[,] make_an_array(int Nrow, int Ncol) {
    
    real output_array[Nrow, Ncol];
    
    for (i in 1:Nrow){
      for (j in 1:Ncol) 
       output_array[i,j] = 1.5 + i;
    }
    return output_array;
  }
```

R call
```
make_an_array_wreal(2, 2, 3.5)
```

#### Current Output:

`make_an_array` is not exported, further 
```
> make_an_array_wreal(2,2,3.5)
[[1]]
[1] 4.5 4.5

[[2]]
[1] 5.5 5.5
```
#### Expected Output:
```
     [,1] [,2]
[1,]  4.5  4.5
[2,]  5.5  5.5
```

#### RStan Version:
```
> packageVersion("rstan")
[1] ‘2.14.1’
```
#### R Version:
```
> R.version.string
[1] "R version 3.3.2 (2016-10-31)"
```

#### Operating System:
OS X 10.10.5

**Comment by bgoodri** [comment]
(ii) was fixed in rstan 2.14.2
(i) I don't know how to change; it is a Rcpp thing

**Comment by pboesu** [comment]
Thanks for the speedy reply!

Upgrading to rstan 2.14.2 (still using R 3.3.2) did **not** resolve (ii).

However, I dug into the generated C++ code and the stan manual, and now realize that (i) is logically consistent with arrays in stan being represented as nested std::vectors.

**Comment by bgoodri** [comment]
Can you try the GitHub version? I think it was actually the first commit or
two after 2.14.2 that fixed the problems with returning real arrays; 2.14.2
only fixed problems with integer arrays.

**Comment by bgoodri** [comment]
Actually, you just need to do

source("
https://raw.githubusercontent.com/stan-dev/rstan/develop/rstan/rstan/R/expose_stan_functions.R
")

You don't have to install the full rstan from GitHub.

**Comment by pboesu** [comment]
That did the job. Thank you!
