### ISSUE TITLE
The meaning of "eta" parameter in 8 school example

### ISSUE THREAD

**Issue by caprice-j** [stan-dev/rstan#401]
What is "eta" parameter in 8 school example in the following example?
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

I checked the Gelman's textbook (3rd Edition) but could not find eta.

**Comment by andrewgelman** [comment]
eta is the thing that is distributed normal(0,1) so that theta is distributed normal(mu,tau).

**Comment by caprice-j** [comment]
Thank you for your quick reply. Then, why don't we write just `theta ~ normal(mu, tau^2)`? Is there some advantage?

**Comment by avehtari** [comment]
@caprice-j see http://mc-stan.org/documentation/case-studies/divergences_and_bias.html

Also notice that normal() in Stan takes standard deviation not variance as the second argument.

**Comment by caprice-j** [comment]
Thank you!
