### ISSUE TITLE
stan_model fails on stan code that uses array expressions

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#402]
#### Summary:
Running stan_model on my model fails with a C++ compilation error. (stanc runs just fine.) The problem only seems to occur when I have array expressions in my code.

#### Description:
When running stan_model on the attached file foo.stan
[foo.stan.txt](https://github.com/stan-dev/rstan/files/926668/foo.stan.txt)
, I get a whole lot of error output, ending with this:

    Error in compileCode(f, code, language = language, verbose = verbose) : 
      Compilation ERROR, function(s)/method(s) not created! In file included from filec9651ce71bbe.cpp:8:
    ....

If I replace the line "vector[2] z = ..." (in the function gamma_from, in the function block) with the commented-out line above it, the errors disappear. 

If I replace "omega_gamma" with "rep_vector(0.1, 2)" in the lines
    vector[2] gamma[2] =
      gamma_from(rep_vector(0.1, 2), omega_gamma, Lprime_gamma);
in the transformed parameters block, the errors disappear.

#### Reproducible Steps:
sm <- rstan::stan_model(file = 'some_directory/foo.stan')

#### Current Output:
[output.txt](https://github.com/stan-dev/rstan/files/926659/output.txt)

See attached file output.txt.

#### RStan Version:
2.14.2

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.3.0

#### Operating System:
Mac OS X 10.12.4 (Sierra)

**Comment by ksvanhorn** [comment]
This may be a dup of issue #395; I'm not sure.

**Comment by bgoodri** [comment]
I think the array expressions may not have been incorporated until 2.15.x.

**Comment by bob-carpenter** [comment]
Array expressions were in the Stan language in 2.14, vector and matrix operations in 2.15.

**Comment by bgoodri** [comment]
I think this was fixed in 2.16.x
