### ISSUE TITLE
generic syntax errors after R (and Rstan?) update

### ISSUE THREAD

**Issue by stijnmasschelein** [stan-dev/rstan#405]
#### Summary:
The syntax errors are no longer informative

#### Description:
When I use the rstudio_stanc() function or stan_model() with a stan file with syntax errors, the only information I got was "c++ exception (unknown reason)".

#### Reproducible Steps:
The following stan file gives `~/Desktop/test.stan is syntactically correct.`

```
parameters{
  vector[10] alpha;
}
model{
  alpha ~ normal(0, 1);
}
```
while this one gives `Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  c++ exception (unknown reason)`

```
parameters{
  vector[10] alpha;
}
model{
  alpha ~ normal(0, 1)
}
```
The only difference is that I dropped the ; in the message block.

#### Current Output:
See above.

#### Expected Output:
I think in previous versions I got more informative error messages.

#### RStan Version:
2.15.1

#### R Version:
3.4.0 with Rstudio 1.0.143

#### Operating System:
OsX 10.12.4

**Comment by bgoodri** [comment]
I get the same behavior. Someone with OSX will have to try to replicate
this.

**Comment by jgabry** [comment]
I can check on Mac later today.

**Comment by jgabry** [comment]
@bgoodri This does appear to be an issue on Mac as I'm seeing the same unexpected behavior (with the latest versions of RStan, R, and RStudio).

**Comment by jrnold** [comment]
I also ran into this today after upgrading to R 3.4.0. Downgrading back to R 3.3.3 fixed the problem - and the syntax error messages reappeared. I am also using MacOS.

**Comment by maverickg** [comment]
No problem with me using R 3.4.0 for Mac GUI released by official R folks.   The problem is with RStudio?

**Comment by stijnmasschelein** [comment]
It's not just an RStudio issue I can replicate it with R in the terminal.

```
stan_string = "
parameters{
  vector[10] alpha;
}
model{
  alpha ~ normal(0, 1)
}"
stanc(model_code = stan_string)
```

The R3.4 for mac installation guide does mention that there are changes in the Clang version. 
"Important: this release uses Clang 4.0.0 and GNU Fortran 6.1, neither of which is supplied by Apple. If you wish to compile R packages from sources, you will need to download and install those tools - see the tools directory."
[https://cran.r-project.org/bin/macosx/](https://cran.r-project.org/bin/macosx/)

Maybe the R Mac GUI installation has some additional elements?

**Comment by maverickg** [comment]
see [the discusson on stan-user mailing list](https://groups.google.com/forum/#!category-topic/stan-users/Yp7ieQNnJXM).  This might be an issue with pre-built binary package from CRAN is somehow not compatible with local environment.  **Building from source** might address the problem.

**Comment by stijnmasschelein** [comment]
Building from source did the trick for me. Thanks.
