### ISSUE TITLE
Print statements in generated quantities block produce no output if there is a subsequent error

### ISSUE THREAD

**Issue by glenngoldsmith** [stan-dev/rstan#407]
#### Summary:
If an error occurs in the generated quantities block, print statements preceding the error do not produce any output.

#### Description:
Appears to be similar to [stan-dev/rstan#274](https://github.com/stan-dev/rstan/issues/274)  and [stan-dev/stan#1789](https://github.com/stan-dev/stan/issues/1789) but with the generated quantities block rather than the model block.

It's (mostly) possible to work around this while print-debugging, by inserting print statements and then commenting out the subsequent problematic code, but it would be great if that weren't necessary!

#### Reproducible Steps:
The following code illustrates the problem.

```
model.code = ' 
data {
  int N;
  vector[N] y;
}

parameters {
  real mu;
  real<lower=0> sigma;
}

model {
  print("Model block");
  y ~ normal(mu,sigma);
}

generated quantities {
  vector[N-1] too_short_for_y;
  print("Generated quantities block");
  // Next line is designed to throw an exception
  too_short_for_y = y;
}
'

noprint = stan_model(model_code = model.code)
set.seed(1234)
noprint.data = list(N = 100,y = rnorm(100))
sampling(noprint,data=noprint.data,chains=1)
```

#### Current Output:
Print statement from the model block is printed, but print statement from the generated quantities block is not.

> ...
> Iteration:    1 / 2000 [  0%]  (Warmup)
> Model block
> Model block
> [1] "Error in sampler$call_sampler(args_list[[i]]) : "                                                                       
> [2] "  Exception thrown at line 21: assign: Rows of left-hand-side (99) and rows of right-hand-side (100) must match in size"
> error occurred during calling the sampler; sampling not done

#### Expected Output:
Expected to see the print statement from the generated quantities block before error message: 

> ...
> Iteration:    1 / 2000 [  0%]  (Warmup)
> Model block
> Model block
> Generated quantities block
> [1] "Error in sampler$call_sampler(args_list[[i]]) : "                                                                       
> [2] "  Exception thrown at line 21: assign: Rows of left-hand-side (99) and rows of right-hand-side (100) must match in size"
> error occurred during calling the sampler; sampling not done

#### RStan Version:
2.15.1

#### R Version:
R version 3.3.3 (2017-03-06)

#### Operating System:
OS X 10.12.3

**Comment by bob-carpenter** [comment]
This will be solved as part of https://github.com/stan-dev/stan/issues/2294

**Comment by syclik** [comment]
Bob, I'm not sure if my original fix will also handle generated quantities. I'll double check later.

**Comment by cdriveraus** [comment]
Sorry if this has been fixed for 2.18, but so far as I can see this is still an issue for 2.17, and I would have expected given the timestamps on the posts above that it would be fixed...

**Comment by bob-carpenter** [comment]
@cdriveraus --- Have you checked the develop branch?  Some of the intermediate outputs were cherry picked for the latest 2.17.x release---I don't think it was up to the develop branch at the point of its release.  

We're working on a new release now.

**Comment by karchjd** [comment]
The problem still persists if optimizing is used. So the following code

```
model.code = '
data {
int N;
vector[N] y;
}

parameters {
real mu;
real<lower=0> sigma;
}

model {
print("Model block");
y ~ normal(mu,sigma);
}

generated quantities {
vector[N-1] too_short_for_y;
print("Generated quantities block");
// Next line is designed to throw an exception
too_short_for_y = y;
}
'
library(rstan)
noprint = stan_model(model_code = model.code)
set.seed(1234)
noprint.data = list(N = 100,y = rnorm(100))
optimizing(noprint,data=noprint.data)
```

returns

```
Error in sampler$call_sampler(c(args, dotlist)) : 
  Exception: assign: Rows of left-hand-side (99) and rows of right-hand-side (100) must match in size  (in 'model349a7849f1d0_d5d154b3282e1a6180dbfdc6db17fcae' at line 21)
```

Instead of
```
Generated quantities block
Error in sampler$call_sampler(c(args, dotlist)) : 
  Exception: assign: Rows of left-hand-side (99) and rows of right-hand-side (100) must match in size  (in 'model349a7849f1d0_d5d154b3282e1a6180dbfdc6db17fcae' at line 21)
```

Any advice on how to debug models that use optimizing without print?

**RStan Version:**
2.18.2

**R Version:**
R version 3.5.0  

**Operating System:**
OS X 10.12.6
