### ISSUE TITLE
Suggestion to optimize as.matrix.stanfit(..)

### ISSUE THREAD

**Issue by fanyi1029** [stan-dev/rstan#411]
#### Summary:
Suggest code to improve as.matrix.stanfit(..) computing efficiency

#### Description:
This is an issue directed from {brms} issue [224](https://github.com/paul-buerkner/brms/issues/224)
I have a big stanfit object (~800MB) and I find it inefficient and memory heavy to run the predict.brmsfit(..) function which is caused by as.matrix.stanfit(..). The insane memory consumed by as.matrix.stanfit(..) is probably harder to tackle while we can easily optimize one line of code to improve at least the computing time.
The profile analysis on as.matrix.stanfit(..) is attached below:
![screen shot 2017-05-11 at 10 26 54 am](https://cloud.githubusercontent.com/assets/12900885/25963523/9140fa56-364f-11e7-840c-0fd891ac6049.png)

Also attach the function definition here for reference:
>as.matrix.stanfit <- function(x, ...) {
if (x@mode != 0) return(numeric(0))
e <- extract(x, permuted = FALSE, inc_warmup = FALSE, ...)
out <- apply(e, 3, FUN = function(y) y)
if (length(dim(out)) < 2L) out <- t(as.matrix(out))
dimnames(out) <- dimnames(e)[-2]
return(out)
}

If I understand it correctly, apply(...) is an expensive way to flatten the object 'e' from 3 dimensions into 2.  The following code should accomplish the same task with much less overhead (suggested by  @warnes )

>as.matrix.stanfit <- function(x, ...) {
  if (x@mode != 0) return(numeric(0)) 
  e <- extract(x, permuted = FALSE, inc_warmup = FALSE, ...) 
  dim(e) <- c( dim(e)[1] * dim(e)[2], dim(e)[3])
  dimnames(e) <- dimnames(e)[-2]
  return(e)
}

Testing benchmarked results:
One model:
Before improved (current rstan code): 
![screen shot 2017-05-11 at 2 07 07 pm](https://cloud.githubusercontent.com/assets/12900885/25964727/d30c8bfe-3653-11e7-8531-e99d0e17414e.png)
After improved (suggested here):
![screen shot 2017-05-11 at 2 07 23 pm](https://cloud.githubusercontent.com/assets/12900885/25964765/eaf0d766-3653-11e7-8d5f-1dec7d4d6864.png)

The total processing time is 44.9s vs 12.2s

The other model:
Before improved (current rstan code): 
![screen shot 2017-05-11 at 2 11 03 pm](https://cloud.githubusercontent.com/assets/12900885/25964874/61edde86-3654-11e7-8590-dd457d961653.png)
After improved (suggested here):
![screen shot 2017-05-11 at 2 17 50 pm](https://cloud.githubusercontent.com/assets/12900885/25965001/af9b1464-3654-11e7-8553-cb859adcb0d9.png)

The total processing time is 5.2s vs 1.9s.

#### Reproducible Steps:
I need permission and extra work to fake the stanfit data object, and given the suggested change here will have minimal impact on the other functions, I would not share any data at this point unless it's required or highly preferred. 

#### RStan Version:
rstan 2.14.1

#### R Version:
R version 3.2.3

#### Operating System:
OS X 10.10.3

**Comment by bob-carpenter** [comment]
Thanks!  Can we just call out to C++ to do these expensive operations, or is there a marshal/unmarshal cost in doing that?

**Comment by jgabry** [comment]
Cool, thanks for the suggestion. I haven't run your new as.matrix.stanfit
function yet but it does indeed look like it should return the same output
as before while avoiding the apply step.

Bob, as for doing this in C++, I think the additional cost is pretty low,
but getting rid of the call to apply() probably already removes the most
obvious place to do that (at least in this particular case).

**Comment by maverickg** [comment]
Thanks for the suggestion with a lot of details.  Regarding to your code 
```
e <- extract(x, permuted = FALSE, inc_warmup = FALSE, ...)
dim(e) <- c( dim(e)[1] * dim(e)[2], dim(e)[3])
dimnames(e) <- dimnames(e)[-2]
```

I think the dimnames of `e` is lost after change its `dim` on the above line 2.  So we might need a tiny bit modification.  

Since you are on it, can you please test if the current code and your new code give identical results (use function `idential`)?  thanks!!

**Comment by fanyi1029** [comment]
@maverickg Yes, the dimnames of e is lost. 
So I tested on adding on more line of code: 

 `a <- as.array.stanfit(..)`
`dimnames(e) <- dimnames(a)` 
then it will produce the same output, i.e. `identical(e, as.matrix.stanfit(..))` is `TRUE` .

**Comment by maverickg** [comment]
@fanyi1029 thanks.  If you would have a PR with this suggestion, we would definitely take another look and get it merged?  Or we would change the code following the suggestion.  Let us know your thought.

**Comment by fanyi1029** [comment]
Either is fine, although I do prefer you make the code changes!

On Sat, May 13, 2017 at 10:13 PM, maverickg <notifications@github.com>
wrote:

> @fanyi1029
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fanyi1029&d=DwMCaQ&c=fi2D4-9xMzmjyjREwHYlAw&r=DqKfKXLUq--vnW76p2eHnQ&m=2nDp2p9kVXUCK68yr_JTP8Mck5OI7KjGuDlvx_fIP74&s=WdrZcl3SSi4ipa5SpsBBS3TrWLInH1xS6CTXmqMOfIc&e=>
> thanks. If you would have a PR with this suggestion, we would definitely
> take another look and get it merged? Or we would change the code following
> the suggestion. Let us know your thought.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stan-2Ddev_rstan_issues_411-23issuecomment-2D301286273&d=DwMCaQ&c=fi2D4-9xMzmjyjREwHYlAw&r=DqKfKXLUq--vnW76p2eHnQ&m=2nDp2p9kVXUCK68yr_JTP8Mck5OI7KjGuDlvx_fIP74&s=x5wcdZ5suEXjEtcrRpCNwXoVBxtWlNhsO9SxzaUVQJQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMTaFewhpRin-2DgmlRqOUNsD7JENf-2D3cmks5r5mNXgaJpZM4NYcyg&d=DwMCaQ&c=fi2D4-9xMzmjyjREwHYlAw&r=DqKfKXLUq--vnW76p2eHnQ&m=2nDp2p9kVXUCK68yr_JTP8Mck5OI7KjGuDlvx_fIP74&s=CRq6wWQiUNztGcByhSYT8gnsQn3I3Ft_AjXC0SSiQlc&e=>
> .
>



-- 
*Fanyi Zhang*| Statistical Analyst, Data Science | Medidata Solutions
Worldwide <http://www.mdsol.com/>®
8F/350 Hudson Street, NYC, NY
fzhang@mdsol.com <jhartman@mdsol.com> | direct: +1 917-834-2012

**Comment by maverickg** [comment]
no problem.  i will make the change.  thanks!

**Comment by maverickg** [comment]
done in https://github.com/stan-dev/rstan/commit/5c3d41a46ee18e16da02a7075840d40c5632154a
