### ISSUE TITLE
 RNG in the transformed data block is insensitive to seed

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/rstan#413]
#### Summary:
The RNG in the transformed data block is insensitive to seed. It should use the overall seed, but not the chain ID.

See https://github.com/stan-dev/stan/issues/2241  for details.

**Comment by mitzimorris** [comment]
see https://github.com/stan-dev/cmdstan/issues/551

generated cpp code now has 3-arg constructor that takes a random seed, not an RNG

**Comment by bgoodri** [comment]
How is this intended to work in the RStan case? Currently, we use the two-argument constructor
https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/inst/include/rstan/stan_fit.hpp#L983
and then initialize the `base_rng` on the next line. But the seed that the user specifies (if any) is not being passed until the `call_sampler` method is called from
https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/inst/include/rstan/stan_fit.hpp#L1169

**Comment by mitzimorris** [comment]
you will have to check whether or not the user has specified a seed before you initialize the model.

there's PR for cmdstan - cf changes to `command.hpp`:  https://github.com/stan-dev/cmdstan/pull/552/files
