### ISSUE TITLE
expose_stan_functions() fails with an Rcpp error

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#415]
#### Summary:
Calling expose_stan_functions() fails with an error from from Rcpp::sourceCpp that says "No function return type found for Rcpp::export attribute"

#### Description:
See error output below.

#### Reproducible Steps:

1. Clone the Git repo https://github.com/jrnold/ssmodels-in-stan . (Commit efc9b5098185c5387e6ff3f0c635829a60aed6d3 of 2017-03-07.) Let ssmodels-in-stan be the root directory.

2. Save the following Stan code to example.stan:

    functions {
      #include ssm.stan
    }
    data {
      int<lower=1> N;
      real y[N];
    }
    transformed data {
    }
    parameters {
      real<lower=0> sigma_y;
    }
    transformed parameters {
    }
    model {
      y ~ normal(0, sigma_y);
    }

3. Issue the following commands in R:

    ssm_path <- "ssmodels-in-stan/StanStateSpace/inst/stan/include"
    b <- rstan::stanc_builder("example.stan", isystem=ssm_path)
    model <- rstan::stan_model(model_code = b$model_code)
    e <- new.env(parent=baseenv())
    errout <- capture.output(expose_stan_functions(model, e))

capture.output() is necessary because a huge amount of output gets written to the console, and we just want to see what's written to stderr.

Note that the call to stan_model() succeeds, so the code is correct. (This problem originally arose in the context of a model I had successfully run.)

#### Current Output:
The following "message" output:

    recompiling to avoid crashing R session
    In file included from filec21f7331b596.cpp:5:
    In file included from /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rstan/include/boost_not_in_BH/boost/fusion/support/unused.hpp:10:
    In file included from /Library/Frameworks/R.framework/Versions/3.3/Resources/library/BH/include/boost/fusion/support/config.hpp:11:
    In file included from /Library/Frameworks/R.framework/Versions/3.3/Resources/library/BH/include/boost/config.hpp:39:
    /Library/Frameworks/R.framework/Versions/3.3/Resources/library/BH/include/boost/config/compiler/clang.hpp:196:11: warning: 'BOOST_NO_CXX11_RVALUE_REFERENCES' macro redefined [-Wmacro-redefined]
    #  define BOOST_NO_CXX11_RVALUE_REFERENCES
              ^
    <command line>:6:9: note: previous definition is here
    #define BOOST_NO_CXX11_RVALUE_REFERENCES 1
            ^
    filec21f7331b596.cpp:4935:1: error: expected unqualified-id
    RcppExport SEXP sourceCpp_6_matrix_diff(SEXP ASEXP, SEXP BSEXP) {
    ^
    /Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include/RcppCommon.h:129:27: note: expanded from macro 'RcppExport'
    #define RcppExport extern "C"
                              ^
    1 warning and 1 error generated.
    make: *** [filec21f7331b596.o] Error 1
     Show Traceback
     
     Rerun with Debug
     Error in Rcpp::sourceCpp(code = paste(lines, collapse = "\n"), env = env) : 
      Error 1 occurred building shared library. In addition: Warning message:
    No function return type found for Rcpp::export attribute at filec21f7331b596.cpp:2911 
    Here is the C++ code that does not compile. Please report bug.

#### RStan Version:
2.15.1

#### R Version:
3.3.0

#### Operating System:
OS X 10.12.4

**Comment by ksvanhorn** [comment]
I've done some more experimentation, and it turns out that you can remove everything from ssm.stan except the definition of matrix_diff(), and you still get the error.

**Comment by ksvanhorn** [comment]
Might this be the problem? This is from what appears to be the generated C++ code:

    // [[Rcpp::export]]
    
    double
    
    // [[Rcpp::export]]
    
    matrix_diff(const matrix_d& A, 
                      ...

**Comment by bgoodri** [comment]
Fixed by 6b15df1d760e01fb84ccda6fd2cbf6375ea546b2. You can `source` expose_stan_functions.R from its raw github file to get it to compile without having to reinstall all of rstan from GitHub.
