### ISSUE TITLE
get_inits fails when iter is specified

### ISSUE THREAD

**Issue by rgiordan** [stan-dev/rstan#417]
#### Summary:
The ```get_inits``` function does not provide a usable list when the ```iter``` argument is specified.

#### Description:
One purpose of ```get_inits``` is to provide a list of variables that can be passed to ```unconstrain_pars``` or to initialize an MCMC chain.  It works for this purpose when the argument ```iter``` is not specified, but when it is specified, ```get_inits``` can populate a field with an data frame rather than a numeric type, rendering it unusable by ```stan```.

#### Reproducible Steps:
Using the model and data ```normal_censored.stan``` from ```stan-dev/example-models```, run the following code:

```
library(rstan)
model_name <- "basic_estimators/normal_censored"
model <- stan_model(paste(model_name, "stan", sep="."))

stan_data <- new.env()
source(paste(model_name, "data.R", sep="."), local=stan_data)
result <- sampling(model, data=stan_data, chains=1)

# Works fine:
par_list <- get_inits(result)[[1]]
unconstrain_pars(result, par_list)
print(par_list)
class(par_list$mu)

# Produces an error:
par_list <- get_inits(result, iter=1)[[1]]
unconstrain_pars(result, par_list)
print(par_list)
class(par_list$mu)
```

#### Current Output:
```
> par_list <- get_inits(result)[[1]]
> unconstrain_pars(result, par_list)
[1] 0.7042813
> print(par_list)
$mu
[1] 0.7042813

> class(par_list$mu)
[1] "numeric"
> 
> par_list <- get_inits(result, iter=1)[[1]]
> unconstrain_pars(result, par_list)
Error in object@.MISC$stan_fit_instance$unconstrain_pars(pars) : 
  variable mu missing
> print(par_list)
$mu
         NA
1 0.7042813

> class(par_list$mu)
[1] "data.frame"
```

#### Expected Output:
I expect the output from ```get_inits(result, iter=1)``` to be the same as from ```get_inits(result)```.

#### RStan Version:
2.15.1

#### R Version:
R version 3.2.3 (2015-12-10)

#### Operating System:
Ubuntu 16.04

**Comment by jgabry** [comment]
Thanks, I hadn't noticed this. Indeed, I would also expect 

```r
get_inits(result, iter=1) 
```

to return the same thing as 

```
get_inits(result)
```

@bgoodri is this intentional? It looks like you added the `iter` argument in https://github.com/stan-dev/rstan/commit/4dabb39067f270b001eb92944aa0f12fcbde1900, but I can't tell from the code if there was a particular reason for returning a different kind of object when `iter` is specified.

**Comment by bgoodri** [comment]
I think I meant to do that but didn't mean for it to be incompatible.

**Comment by rgiordan** [comment]
Any progress on this?  This makes ```git_inits``` hard to use because you cannot pass it to ```unconstrain_pars``` for any but the first draw.

**Comment by rgiordan** [comment]
It's actually even worse than this.  When it parses matrices, it returns a matrix of one-element lists.  Consider the schools example, below.

Perhaps you could tag this as a bug?  Should I re-post on ```http://discourse.mc-stan.org/```?

```
examples_loc <- "/home/rgiordan/Documents/git_repos/example-models/bugs_examples/vol2"
stan_data <- new.env()
source(file.path(examples_loc, "schools/schools.data.R"), local=stan_data)
stan_data <- as.list(stan_data)

school_model <- stan_model(file.path(examples_loc, "schools/schools-1.stan"))
sampling_result <- sampling(school_model, data=stan_data, chains=1, iter=200)

par_list <- get_inits(sampling_result, iter=1)[[1]]
pars_free <- unconstrain_pars(sampling_result, par_list) # Fails
# Fails:
# Error in object@.MISC$stan_fit_instance$unconstrain_pars(pars) :
# variable beta missing

# It fails for every variable since they're all malformed.
# But the matrix parameter is especially strange:

class(par_list$alpha)
# [1] "matrix"
dim(par_list$alpha)
# [1] 38  3
class(par_list$alpha[1])
# [1] "list"
par_list$alpha[1, 1]
# [[1]]
# [1] 0.7710187
```
