### ISSUE TITLE
Description syntax problem on r-hub

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstan#432]
I tried to compile on r-hub, and got an error probably related to a line break in DESCRIPTION

https://github.com/r-hub/rhub/issues/85#issuecomment-314395550

As mentioned by @gaborcsardi, this might be a problem in the remotes package, but is easy to correct.

**Comment by bgoodri** [comment]
We don't have linebreaks within sections of RStan's DESCRIPTION file. The r-hub must be wrapping the lines after some number of characters.

**Comment by dmenne** [comment]
This is from your gz:
```
Imports: methods, stats4, inline, gridExtra (>= 2.0.0), Rcpp (>=
        0.12.0)
```

**Comment by bgoodri** [comment]
Ah: tar or gzip must wrap the lines because they are unwrapped on GitHub. I
will put a line break after each comma.

**Comment by gaborcsardi** [comment]
I think it was probably `devtools::build` if you used `devtools`.
