### ISSUE TITLE
optimizing doc wrong for inits

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#434]
#### Summary:

Fix doc for inits in optimizing functions to indicate it's a single list, not a list of lists. 

#### Description 

From http://discourse.mc-stan.org/t/initializing-values-for-the-optimizing-function-using-rstan/1241

which says:

<blockquote>
The manual points to the "stan" function and suggests that the init parameter should be a list of lists.

In fact, if you have, for example, parameters a, b, then init should be specified as just
`init = list (a=a, b=b)` and not `init = list(list(a=list(a), b=list(b)) )` as suggested by the manual.
</blockquote>

Describe the issue as clearly as possible.

**Comment by jgabry** [comment]
Yeah that doc is wrong. Thanks for opening the issue. Just fixed it.
