### ISSUE TITLE
Suggested change to  parallel::detectCores()

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstan#435]
Under Windows 10, `parallel::detectCores()` return the number of cores including hyperthreading cores. With my i7, it return 8, but only 4 are physical cores. Using 8 cores/chains is slightly slower than using 4 due to overhead.

Suggested changes to documentation and to startup message:

`parallel::detectCores(logical = FALSE)`

**Comment by bgoodri** [comment]
Whether eight chains with 4 physical cores and 4 virtual cores is faster or
slower than eight chains with 4 physical cores twice depends on a lot of
stuff.

**Comment by aaronjg** [comment]
Potentially even depends on the model:

http://discourse.mc-stan.org/t/multicore-speedups-are-different-between-models/1219/19
