### ISSUE TITLE
missing final line in parser error report

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#436]
#### Summary:

With program

```
data {
  foo bar; } model { }
```

CmdStan outputs:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in '/Users/carp/temp2/foo.stan' at line 2, column 3
  -------------------------------------------------
     1: data {
     2:   foo bar; } model { }
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

whereas RStan (on my Mac, RStudio and R GUI), I get:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'model10239103581_foo' at line 2, column 3
  -------------------------------------------------
     1: data {
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

What's odd is that it's only partway through the output from the parser.

#### RStan Version:

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.16.2         StanHeaders_2.16.0-1 ggplot2_2.2.1       

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.4.1     assertthat_0.1   lazyeval_0.2.0   plyr_1.8.4       tools_3.3.2     
 [7] inline_0.3.14    gtable_0.2.0     tibble_1.2       gridExtra_2.2.1  Rcpp_0.12.8      grid_3.3.2      
[13] stats4_3.3.2     munsell_0.4.3   
```

**Comment by sakrejda** [comment]
Did you guys figure out where this came from? Mostly nosy but I did look at the associate Rcpp code and could figure this out.

**Comment by bob-carpenter** [comment]
Not that I know of.  If you could take a look, that'd be great.

**Comment by sakrejda** [comment]
It doesn't reproduce in R 2.15.2 on my Mac but I'll update and see if it does then.

**Comment by bgoodri** [comment]
And to clarify, this is only with the CRAN binary rstan or is it also with
a source install, e.g. `devtools::install_github("stan-dev/rstan", ref =
"v2.16.2", subdir = "rstan/rstan")`?

**Comment by sakrejda** [comment]
Seems like also happens with source install, I'm suspicious that a stream
isn't getting flushed on line 71 or so of parser.hpp but I haven't
reinstalled yet to check. Either way it's odd.

**Comment by bob-carpenter** [comment]
I tried that magic to install from GitHub and it spit out a lot of lines about git and then did the same thing---missing a line.

And yes, @sakrejda, there should be a `<< std::endl` after diagnostics --- it will automatically flush that way.  I'd have thought the message and everything else would do the right thing with the string stream, but apparently not.

**Comment by bob-carpenter** [comment]
Or maybe it's a problem with string scope in exceptions?  This also looks suspicious on line 90:

```
throw std::invalid_argument(msg.str());
```

I think we should be setting that to a local std::string (which copies), then call that.  Even though it seems like that's also going to go out of scope, I seem to remember having problems with something like this before.

**Comment by maverickg** [comment]
I will take a look.

**Comment by maverickg** [comment]
It's weird.  If I added a new line (\n) to the end so it look like
```
$ od -c test.stan
0000000    d   a   t   a       {  \n           f   o   o       b   a   r
0000020    ;       }       m   o   d   e   l       {       }  \n  \n
0000037
```

Then it seems to be fine.  So I am thinking the issue lies in something other than wrongly processing the error message. 

```
$ R -q -e "library(rstan); stanc('test.stan')"
> library(rstan); stanc('test.stan')
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.16.3, packaged: 2017-07-21 02:04:11 UTC, GitRev: 901101506c4f)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
Warning message:
package ‘StanHeaders’ was built under R version 3.4.1

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'model14a1521ca7bda_test' at line 2, column 3
  -------------------------------------------------
     1: data {
     2:   foo bar; } model { }
          ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
Error in stanc("test.stan") :
  failed to parse Stan model 'test' due to the above error.
Execution halted
```

**Comment by maverickg** [comment]
ok, I guess now stanc requires an '\n' at the end of line.  Currently `stanc` function in rstan removes the last \n when reading code from a file and I guess this is how it behaves since the first version of rstan.   The bug can be sort of replicated with cmdstan if there is no \n at the end of the stan file. 

```
$ od -c test.stan
0000000    d   a   t   a       {      \n               f   o   o       b
0000020    a   r   ;       }       m   o   d   e   l       {   }
0000037
mmac2:cmdstan-2.16.0 jq$ ./bin/stanc test.stan
Model name=test_model
Input file=test.stan
Output file=test_model.cpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'test.stan' at line 2, column 4
  -------------------------------------------------
     1: data {
           ^
  -------------------------------------------------

PARSER EXPECTED: <one of the following:
  a variable declaration, beginning with type,
      (int, real, vector, row_vector, matrix, unit_vector,
       simplex, ordered, positive_ordered,
       corr_matrix, cov_matrix,
       cholesky_corr, cholesky_cov
  or '}' to close variable declarations>
```

**Comment by sakrejda** [comment]
We might just want to decide what it is that stanc is supposed to take (text file or just string) and be consistent about this.  It's silly to be adding/deleting newlines.
```
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
```

**Comment by bob-carpenter** [comment]
stanc shouldn't care if there's a final newline.  As far as I can tell, it's OK and CmdStan is OK on the output, even with a single line.

It's generally good practice to have a newline at the end, but it shouldn't disrupt any of our output or prevent having error messages for the last line.

If there's something not handling this correctly in stan-dev/stan, it should be fixed there.

**Comment by maverickg** [comment]
This issue was moved to stan-dev/stan#2359
