### ISSUE TITLE
Error in readRDS(file.rds) : unknown input format

### ISSUE THREAD

**Issue by AliGhanbari26** [stan-dev/rstan#437]
#### Summary:
Hi. I install rstan package and faced with this error:

_**Error in readRDS(file.rds) : unknown input format**_

please help me, 
#### Description:
`> traceback()`
5: readRDS(file.rds)
4: is(obj <- readRDS(file.rds), "stanmodel")
3: stan_model(file, model_name = model_name, model_code = model_code, 
       stanc_ret = NULL, boost_lib = boost_lib, eigen_lib = eigen_lib, 
       save_dso = save_dso, verbose = verbose)
2: stan(file = fName, data = datalist, init = list(inlist), chains = 1, 
       iter = n.it, pars = c("f", "tau"), warmup = n.warm, seed = computerID + 
           1000) at functions.r#131
1: RunModel(11, myT, nu, lambda, rho, BDRi, Pars, computerID, n.it, 
       n.warm, getwd())

#### RStan Version:
2.16.2

#### R Version:
R version 3.4.1 (2017-06-30)

#### Operating System:
windows 10

**Comment by bgoodri** [comment]
I would try deleting the file ending with .rds whose prefix is the same as
the prefix of the .stan file in the same directory.

**Comment by AliGhanbari26** [comment]
My problem is solved. I use **_writeLines_** command.

```
library(rstan)
scode <- "
     parameters {
       real y[2]; 
     } 
     model {
       y[1] ~ normal(0, 1);
       y[2] ~ double_exponential(0, 2);
     } 
     "
writeLines(scode, "mymodel.stan")

mymodel <- stan("mymodel.stan", iter = 10, verbose = FALSE) 
```
