### ISSUE TITLE
Old version RStan objects in memory break Rstan

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/rstan#443]
#### Summary:
If I have a model from 2.12 in memory, you cannot run a new model, because it detects an incompatible version.

#### Description:
With a previous analysis loaded in memory, attempting to run a model gives the following error;
Error in prep_call_sampler(object) : 
  the compiled object from C++ code for this model is invalid, possible reasons:
  - compiled with save_dso=FALSE;
  - compiled on a different platform;
  - does not exist (created from reading csv files).

This is somewhat low-priority, and has a simple fix, but makes some types of manipulation of earlier results and comparing results between versions painful.

#### Reproducible Steps:
Load a stanfit object from a previous stan version into memory, then run another stan model.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.16.2

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.4.0

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Windows 10

**Comment by bgoodri** [comment]
If you have a model from 2.12 in memory, then you have biased draws. Even if you have something from 2.15, you would probably still run into this problem though. It might fix itself in rstan3.
