### ISSUE TITLE
Unconstrain_pars does not work after restarting / reloading stanfit object.

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/rstan#445]
#### Summary:
Instead it returns "Error in .local(object, ...) : 
  the model object is not created or not valid"

#### Reproducible Steps:
Fit a model, restart R and reload the stanfit object, then try unconstrain_pars on it.

#### RStan Version:
2.16.2

#### R Version:
3.4.0

#### Operating System:
Windows 7

**Comment by bgoodri** [comment]
That is not intended to work. All of the functions that take a stanfit object have a slot for a stanmodel object and the stanmodel object has to be compiled and in memory for those functions to work.

**Comment by cdriveraus** [comment]
Ok. Doesn't sound ideal, but I assume there is good cause. The stanfit help could mention this aspect somehow.
