### ISSUE TITLE
rstan compilation error with Boost 1.62

### ISSUE THREAD

**Issue by boryspaulewicz** [stan-dev/rstan#450]
#### Summary:

rstan does not compile under Debian 9 (stable), error comes up when including one of the Boost headers

#### Current Output:

from lang__grammars__expression_grammar_inst.cpp:18:
/home/borys/R/library/BH/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp: In instantiation of ‘const typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2, A3, A4>::type boost::phoenix::function<F>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&) const [with A0 = boost::phoenix::actor<boost::spirit::attribute<0> >; A1 = boost::phoenix::actor<boost::spirit::argument<0> >; A2 = char [3]; A3 = char [11]; A4 = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<std::__cxx11::basic_stringstream<char> > >, 0l> >; F = stan::lang::binary_op_expr; typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2, A3, A4>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval, boost::proto::argsns_::list6<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<stan::lang::binary_op_expr>, 0l>, boost::phoenix::actor<boost::spirit::attribute<0> >, boost::phoenix::actor<boost::spirit::argument<0> >, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l>, boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<std::__cxx11::basic_stringstream<char> > >, 0l> > >, 6l> >]’:
/home/borys/R/library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_def.hpp:57:27:   required from ‘stan::lang::expression_grammar<Iterator>::expression_grammar(stan::lang::variable_map&, std::stringstream&) [with Iterator = boost::spirit::line_pos_iterator<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > >; std::stringstream = std::__cxx11::basic_stringstream<char>]’
/home/borys/R/library/StanHeaders/include/src/stan/lang/grammars/expression_grammar_inst.cpp:6:21:   required from here
/home/borys/R/library/BH/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp:91:86: error: invalid conversion from ‘const char*’ to ‘param_type {aka char*}’ [-fpermissive]
 n detail::expression::function_eval<F, A0 , A1 , A2 , A3 , A4>::make(f, a0 , a1 , a2 , a3 , a4);
   
#### RStan Version:
2.16.2

#### R Version:
3.4.1

#### Operating System:
Debian 9

**Comment by bgoodri** [comment]
The solution is the same as in 
https://github.com/stan-dev/rstan/issues/447#issuecomment-325172186

**Comment by boryspaulewicz** [comment]
Thanks, that worked
