### ISSUE TITLE
How to reset BINPREF

### ISSUE THREAD

**Issue by RafaRafa** [stan-dev/rstan#451]
When restarting R I get the error message: 

````
Error: 2:24: unexpected '/'
2: Sys.setenv(BINPREF = C:/
                           ^
````
When I call ````Sys.getenv()````, ````BINPREF```` is set to ````C:/Rtools/mingw_$(WIN)/bin/````
(Which I believe was set with: 
````
   cat('Sys.setenv(BINPREF = "C:\\Rtools\\mingw_$(WIN)\\bin\\")',
    file = file.path(Sys.getenv("HOME"), ".Rprofile"), 
    sep = "\n", append = TRUE)
````
)

**Comment by bgoodri** [comment]
You just need to call 
```
cat('Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")',
    file = file.path(Sys.getenv("HOME"), ".Rprofile"), 
    sep = "\n", append = TRUE)
```
making sure to include the quotation marks around C:/Rtools/mingw_$(WIN)/bin/ .

**Comment by RafaRafa** [comment]
I ran it (again) and then restarted R, still see the same error. I tried editing the Makeconf file in /R/R.x.x/etc, but nothing changed.

**Comment by bgoodri** [comment]
What version of Windows is this?

**Comment by RafaRafa** [comment]
Windows 7

**Comment by bgoodri** [comment]
What happens if you do
```

Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")
```

inside R?

**Comment by RafaRafa** [comment]
I can change ````BINPREF```` if I run it in R, however upon restarting R, it still prints the error. 

I wanted to note that if I change ````BINPREF```` inside R with a different value it appears with that new value when I call ````Sys.getenv()````. For example if I set it to ````Sys.setenv(BINPREF = "X:/Rtools/mingw_$(WIN)/bin/")```` it will show up as ````"X:/Rtools/mingw_$(WIN)/bin/"````, but if I run 
````
cat('Sys.setenv(BINPREF = "X:/Rtools/mingw_$(WIN)/bin/")',
    file = file.path(Sys.getenv("HOME"), ".Rprofile"), 
    sep = "\n", append = TRUE)
````
then call ````Sys.getenv()````, the value of ````BINREF```` is still ````C:/Rtools/mingw_$(WIN)/bin/````

**Comment by bgoodri** [comment]
Ah, I see what the problem is. Do that with append = FALSE to erase the old
.Rprofile and replace it with the new one.
