### ISSUE TITLE
cpp_object_initializer importFrom is commented out

### ISSUE THREAD

**Issue by danielmcauley** [stan-dev/rstan#453]
https://github.com/stan-dev/rstan/blob/d84eb5ebd9bcfc0f3bfe6455402678b04a740485/rstan/rstan/NAMESPACE#L11

#importFrom("Rcpp", cpp_object_initializer)

This appears to be causing issues in other packages. For example:

https://github.com/facebook/prophet/issues/285

**Comment by bgoodri** [comment]
Duplicate of https://github.com/stan-dev/rstan/issues/353
