### ISSUE TITLE
MacOS High Sierra time issue during compilation

### ISSUE THREAD

**Issue by acgetchell** [stan-dev/rstan#455]
#### Summary:
Please provide a short summary (no more than a sentence or two).
Error in default timezone on macOS 10.13

#### Description:
Describe the issue as clearly as possible.

Apple moved location of tz data. Howard Hinnant found this issue in his date library also:

https://github.com/HowardHinnant/date/issues/213

Note the fix:

https://github.com/HowardHinnant/date/commit/1df9453d915e37988ac7e9b0abef233b35cecd86

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

> install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'default/America/Los_Angeles'

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

> packageVersion("rstan")
[1] ‘2.16.2’

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

> R.version.string
[1] "R version 3.4.2 (2017-09-28)"

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

OS X 10.13

**Comment by bgoodri** [comment]
Can you call

traceback()

after the error?

**Comment by acgetchell** [comment]
It happens during installation of rstan or packages depending on it, like rethinking.

**Comment by bgoodri** [comment]
Right. I was hoping that calling traceback() after the installation error
would tell me more about what function in RStan is causing the problem.

**Comment by acgetchell** [comment]
Okay, I uninstalled and reinstalled. I get:

> install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
trying URL 'https://cloud.r-project.org/src/contrib/rstan_2.16.2.tar.gz'
Content type 'application/x-gzip' length 733666 bytes (716 KB)
==================================================
downloaded 716 KB

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'default/America/Los_Angeles'
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** libs

And then:

/usr/local/Cellar/r/3.4.2/lib/R/library/StanHeaders/include/src/stan/lang/ast/node/conditional_op.hpp:40:21: warning: 
      in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
      bool has_var_ = false;
                    ^
1 warning generated.
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.4.2/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o rstan.so chains.o init.o lang__ast_def.o lang__grammars__bare_type_grammar_inst.o lang__grammars__expression07_grammar_inst.o lang__grammars__expression_grammar_inst.o lang__grammars__functions_grammar_inst.o lang__grammars__indexes_grammar_inst.o lang__grammars__program_grammar_inst.o lang__grammars__semantic_actions.o lang__grammars__statement_2_grammar_inst.o lang__grammars__statement_grammar_inst.o lang__grammars__term_grammar_inst.o lang__grammars__var_deccls_grammar_inst.o lang__grammars__whitespace_grammar_inst.o misc.o sparse_extractors.o stanc.o -L/usr/local/Cellar/r/3.4.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /usr/local/Cellar/r/3.4.2/lib/R/library/rstan/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rstan)

The downloaded source packages are in
	‘/private/var/folders/s6/_mkn5zzx6n7f7c_q0_j2zg6m0000gn/T/RtmpeBsv3V/downloaded_packages’
Updating HTML index of packages in '.Library'
Warning messages:
1: In file.create(f.tg) :
  cannot create file '/usr/local/Cellar/r/3.4.2/lib/R/doc/html/packages.html', reason 'Permission denied'
2: In make.packages.html(.Library) : cannot update HTML package index
> traceback()
No traceback available

**Comment by bgoodri** [comment]
OK. It looks as if the installation was actually successful, but there are
some warning messages. Does packageVersion("rstan") yield "2.16.2"?

**Comment by acgetchell** [comment]
Yes.

> packageVersion("rstan")
[1] ‘2.16.2’

Just from experience using https://howardhinnant.github.io/date/date.html, any compilations requiring timezones won't on MacOS 10.13.

**Comment by bgoodri** [comment]
Okay. Maybe @jgabry can figure out how to get rid of the warnings, but I
think it should work fine.

**Comment by hadley** [comment]
This warning generated from R CMD check, not stan. See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17355 for details, and for https://cran.rstudio.com/doc/manuals/R-admin.html#High-Sierra a work around until 3.4.3 is released.
