### ISSUE TITLE
Row major vs column major parameter ordering

### ISSUE THREAD

**Issue by ecmerkle** [stan-dev/rstan#470]
#### Summary:
Multidimensional parameters are ordered differently in summary() vs in extracted posterior draws, which can be confusing.

#### Description:
For models with multidimensional parameters, parameter ordering is row major in summary() and column major when extracting mcmc draws (via, say, as.matrix()). This can be confusing if the user is trying to do extra posterior predictive checks in R, following model estimation. Not a major issue, but would still be nice if it were consistent. Or it might be nice if the user could easily switch between the two orderings.

Example below. Looking at the summary method (arpund line 500 of stanfit-class.R), it seems like there has already been some consideration here.

#### Reproducible Steps:
A model related to kidiq, with a 2-dimensional parameter:

```
data {
  int<lower=0> N;
  int g[N];
  vector<lower=0, upper=200>[N] kid_score;
  vector<lower=0, upper=200>[N] mom_iq;
  vector<lower=0, upper=1>[N] mom_hs;}
transformed data {           // interaction
  vector[N] inter;
  inter = mom_hs .* mom_iq;
}
parameters {
  real betamat[4,2];
  real<lower=0> sigma;
}
model {
  sigma ~ cauchy(0, 2.5);
  for(i in 1:N){
    kid_score[i] ~ normal(betamat[1,g[i]] + betamat[2,g[i]] * mom_hs[i] 
                          + betamat[3,g[i]] * mom_iq[i]
                          + betamat[4,g[i]] * inter[i], sigma);
  }
}
```

R code to run the model and compare parameter ordering in "draws" vs "summ":

```
library(rstan)

set.seed(101)
N <- 100
mom_hs <- sample(0:1, N, replace=TRUE)
mom_iq <- rnorm(N, 100, 15)
kid_score <- rnorm(N, 5 + 10*mom_hs + .85*mom_iq + .1*mom_iq*mom_hs, 10)
g <- rep(1:2, each=50)
dat <- list(N=N, mom_hs=mom_hs, mom_iq=mom_iq,kid_score=kid_score,g=g)

m1 <- stan(file="kidiq_group.stan", data=dat, iter=400)

## posterior draws
draws <- as.matrix(m1)

## summary
summ <- summary(m1)$summary

## matrix parameters ordered differently
cbind(colnames(draws), rownames(summ))

```

#### RStan Version:
2.16.2

#### R Version:
3.4.2

#### Operating System:
ubuntu

**Comment by bob-carpenter** [comment]
Thanks for the issue report.  I think this one may be hard to change without breaking backward compatbility.  I don't know how many people rely on the orderings, but their code would all break if we changed ordering.  I'm also leery of supporting multiple flags to produce different styles of output---it turns into a doc, testing, and maintenance nightmare.

**Comment by ecmerkle** [comment]
That seems reasonable. In case somebody else has the same problem, the parameter indexing can be manually changed in R via

```
match(colnames(draws), rownames(summ))
```

or vice versa.
