### ISSUE TITLE
Cannot fit stan models. Compiler error status 127

### ISSUE THREAD

**Issue by JoaquinIglesiasTurina** [stan-dev/rstan#482]
#### Summary:
Fitting a model in stan on windows 7 professional 64. The stan file is not properly compiled, returning 127 status

#### Description:
When fitting stan model, the compiler throws the following error. I believe the issue to be with my PATH setting, but the error dump states to make a bug report. RBuildTools is installed (but the folder structure differs from the windows installation package) as well as a c++ compiler. Rcpp works without issue. rstanarm works fine too. The error appears with stan and R codes that I wrote and fitted in a linux machine without issue.
```
 Warning message:
    running command 'make -f "C:/Users/e048366/DOCUME~1/R/R-34~1.3/etc/x64/Makeconf" -f "C:/Users/e048366/DOCUME~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2b846af33b8d.dll" WIN=64 TCLBIN=64 OBJECTS="file2b846af33b8d.o"' had status 127 

    ERROR(s) during compilation: source code errors or compiler configuration errors!
```

#### Reproducible Steps:
whenever I run stan(), R command, I do not believe the issue to be reproducible.

#### Current Output:
The error message is attached as a .txt file
[stanError.txt](https://github.com/stan-dev/rstan/files/1646330/stanError.txt)

#### Expected Output:
a fitted stan model

#### RStan Version:
2.17.2

#### R Version:
3.4.3

#### Operating System:
windows 7 professional 64.

**Comment by JoaquinIglesiasTurina** [comment]
Indeed the issue was with my path.

**Comment by syclik** [comment]
Thanks for following up!
