### ISSUE TITLE
brm_Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  :    failed to parse Stan model 'file112848ad88c0

### ISSUE THREAD

**Issue by potamus2017** [stan-dev/rstan#488]
#### Summary:
I am (trying to) run Bayesian regression analyses but am struggling with the prior component of my analyses and keep getting the error message mentioned in the title.

My command:
fit1 <- brm(IL8 ~ 1 + tx8, data=a8c,
            family = "gaussian"(link = "identity"),
            prior = c(set_prior("gaussian(0,1000)", class = "b"), set_prior("student_t(3,0,100)", class = "sigma")),
            inits = "random", chains = 4,iter = 10000, warmup = 2000, thin = 1,cores = getOption("mc.cores", 1L),control = NULL, silent = TRUE, seed = 12345, save_model = NULL,save_dso = TRUE)

The following error message keeps popping up.

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  gaussian_lpdf(vector, int, int)

Function gaussian_lpdf not found.
  error in 'model112878ed1a86_file112848ad88c0' at line 30, column 38
  -------------------------------------------------
    28:   vector[N] mu = Xc * b + temp_Intercept; 
    29:   // priors including all constants 
    30:   target += gaussian_lpdf(b | 0,1000); 
                                             ^
    31:   target += student_t_lpdf(temp_Intercept | 3, 1, 10); 
  -------------------------------------------------

Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file112848ad88c0' due to the above error.

#### RStan Version:
RStudio
Version 1.1.419 – © 2009-2018 RStudio, Inc.
#### Operating System:
Mozilla/5.0 (Windows NT 6.1; WOW64)

**Comment by bob-carpenter** [comment]
The error message is correct.  Stan has a `normal_lpdf` but no `gaussian_lpdf`.  The complete list of functions is availabe in the back of the manual.
