### ISSUE TITLE
Cannot use multiple cores

### ISSUE THREAD

**Issue by lleemann** [stan-dev/rstan#491]
#### Summary:
I can detect four cores but when I try to run the four chains on four different cores I get an error message. I checked that 

#### Description:
I can run all my code when only using "..., cores=1,.." but as soon as I change that it throws an error message:

starting worker pid=1865 on localhost:11283 at 16:17:48.458
Error in socketConnection(master, port = port, blocking = TRUE, open = "a+b",  : 
  cannot open the connection
Calls: <Anonymous> ... doTryCatch -> recvData -> makeSOCKmaster -> socketConnection
In addition: Warning message:
In socketConnection(master, port = port, blocking = TRUE, open = "a+b",  :
  localhost:11283 cannot be opened
Execution halted

#### Reproducible Steps:
See example below.

#### Current Output:

> library(rstan)
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.17.3, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
> rstan_options(auto_write = TRUE)
> options(mc.cores = parallel::detectCores())
> schools_code <- '
+ data {
+ int<lower=0> J; // number of schools 
+ real y[J]; // estimated treatment effects
+ real<lower=0> sigma[J]; // s.e. of effect estimates 
+ } 
+ parameters {
+ real theta[J]; 
+ real mu; 
+ real<lower=0> tau; 
+ } 
+ model {
+ theta ~ normal(mu, tau); 
+ y ~ normal(theta, sigma);
+ } 
+ '
> schools_dat <- list(J = 8, 
+                     y = c(28,  8, -3,  7, -1,  1, 18, 12),
+                     sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
> fit1 <- stan(model_code = schools_code, data = schools_dat, 
+              iter = 1000, chains = 4, cores=4)
starting worker pid=1865 on localhost:11283 at 16:17:48.458
Error in socketConnection(master, port = port, blocking = TRUE, open = "a+b",  : 
  cannot open the connection
Calls: <Anonymous> ... doTryCatch -> recvData -> makeSOCKmaster -> socketConnection
In addition: Warning message:
In socketConnection(master, port = port, blocking = TRUE, open = "a+b",  :
  localhost:11283 cannot be opened
Execution halted

> fit1 <- stan(model_code = schools_code, data = schools_dat, 
+              iter = 1000, chains = 4, cores=1)
Error in (function (x)  : attempt to apply non-function
recompiling to avoid crashing R session

SAMPLING FOR MODEL '1c69172c71911435e4c822059138f8ca' NOW (CHAIN 1).

Gradient evaluation took 4.4e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.44 seconds.
Adjust your expectations accordingly!

Iteration:   1 / 1000 [  0%]  (Warmup)

...and this second model runs through although only using one core.

#### RStan Version:
‘2.17.3’

#### R Version:
3.4.3

#### Operating System:
Mac OSX 10.13.3

**Comment by bgoodri** [comment]
I imagine it is some security setting. Does

example(mclapply)

run?

**Comment by lleemann** [comment]
Thank you very much for the quick reply.

I ran the code and it provides this output:

mclppl> ## No test: 
mclppl> simplify2array(mclapply(rep(4, 5), rnorm))
           [,1]       [,2]       [,3]        [,4]        [,5]
[1,]  0.2363011  2.1202877  0.8032543  0.54667975  0.03102281
[2,] -0.1103319 -1.6978280  0.1697744  0.09987921  0.69749983
[3,]  0.5400914 -0.8864408  0.5124162  0.84857738  0.67840622
[4,]  0.9459083 -2.8737096 -0.6867566 -0.64673399 -1.91738797

mclppl> # use the same random numbers for all values
mclppl> set.seed(1)

mclppl> simplify2array(mclapply(rep(4, 5), rnorm, mc.preschedule = FALSE,
mclppl+                 mc.set.seed = FALSE))
           [,1]       [,2]       [,3]       [,4]       [,5]
[1,] -0.6264538 -0.6264538 -0.6264538 -0.6264538 -0.6264538
[2,]  0.1836433  0.1836433  0.1836433  0.1836433  0.1836433
[3,] -0.8356286 -0.8356286 -0.8356286 -0.8356286 -0.8356286
[4,]  1.5952808  1.5952808  1.5952808  1.5952808  1.5952808

mclppl> ## Contrast this with the examples for clusterCall
mclppl> library(boot)

mclppl> cd4.rg <- function(data, mle) MASS::mvrnorm(nrow(data), mle$m, mle$v)

mclppl> cd4.mle <- list(m = colMeans(cd4), v = var(cd4))

mclppl> mc <- getOption("mc.cores", 2)

mclppl> run1 <- function(...) boot(cd4, corr, R = 500, sim = "parametric",
mclppl+                            ran.gen = cd4.rg, mle = cd4.mle)

mclppl> ## To make this reproducible:
mclppl> set.seed(123, "L'Ecuyer")

mclppl> res <- mclapply(seq_len(mc), run1)

mclppl> cd4.boot <- do.call(c, res)

mclppl> boot.ci(cd4.boot,  type = c("norm", "basic", "perc"),
mclppl+         conf = 0.9, h = atanh, hinv = tanh)
BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 1000 bootstrap replicates

CALL : 
boot.ci(boot.out = cd4.boot, conf = 0.9, type = c("norm", "basic", 
    "perc"), h = atanh, hinv = tanh)

Intervals : 
Level      Normal              Basic              Percentile     
90%   ( 0.4575,  0.8547 )   ( 0.4703,  0.8575 )   ( 0.4964,  0.8663 )  
Calculations on Transformed Scale;  Intervals on Original Scale

mclppl> ## End(No test)
mclppl> 
mclppl>

**Comment by bgoodri** [comment]
Does it work if you run your Stan model with only 2 cores?

**Comment by lleemann** [comment]
No, it provides the same error message as before:

starting worker pid=2349 on localhost:11729 at 17:13:03.095
Error in socketConnection(master, port = port, blocking = TRUE, open = "a+b",  : 
  cannot open the connection
Calls: <Anonymous> ... doTryCatch -> recvData -> makeSOCKmaster -> socketConnection
In addition: Warning message:
In socketConnection(master, port = port, blocking = TRUE, open = "a+b",  :
  localhost:11729 cannot be opened
Execution halted

I also tried it with changing a prior line to "options(mc.cores = 2)" before running the model. But it provides the same error message. 

I re-installed RStudio, updated all packages, installed RStan, re-created the ~/.R/Makevars file. But all this did not change anything.

**Comment by bgoodri** [comment]
What about

example(parLapplyLB)

?

**Comment by lleemann** [comment]
This seems to not work - the red "stop" symbol is on and it shows:

> example(parLapplyLB)

prLpLB> ## No test: 
prLpLB> ## Use option cl.cores to choose an appropriate cluster size.
prLpLB> cl <- makeCluster(getOption("cl.cores", 2))

**Comment by bgoodri** [comment]
OK. I don't know why that is, but it isn't a Stan problem. To run in
parallel, it will probably work if you run R in the Terminal app (under
Applications -> Utilities). The reason is that
https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/stanmodel-class.R#L535
only uses mclapply when it is absolutely safe to do so.

**Comment by tfjaeger** [comment]
I have the same problem, it seems. But I've tried to use the R terminal (R --vanilla). I can't even run:

library(parallel)

# Calculate the number of cores
no_cores <- detectCores() - 1

# Initiate cluster
cl <- makeCluster(no_cores)

# R hangs  on last command.

I'm running MacOS High Sierra 10.13.3 (17D47) on a MacbookPro 2017 laptop with 4 cores.

platform       x86_64-apple-darwin15.6.0
arch           x86_64
os             darwin15.6.0
system         x86_64, darwin15.6.0
status
major          3
minor          4.3
year           2017
month          11
day            30
svn rev        73796
language       R
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree

**Comment by jgabry** [comment]
This is definitely relevant to RStan but not an issue stemming from RStan. If the examples in the parallel package that comes with R aren't even successfully running then I don't think this is anything we can address in RStan unfortunately. It also doesn't seem to be a general issue on Mac since I can't reproduce it on my machine. So I'm really not sure what's going. I wish I had a better answer since this must be frustrating.

**Comment by tfjaeger** [comment]
Thank you for the quick answer.


On 2/10/18 11:18 PM, Jonah Gabry wrote:
>
> This is definitely relevant to RStan but not an issue stemming from 
> RStan. If the examples in the parallel package that comes with R 
> aren't even successfully running then I don't think this is anything 
> we can address in RStan unfortunately. It also doesn't seem to be a 
> general issue on Mac since I can't reproduce it on my machine. So I'm 
> really not sure what's going. I wish I had a better answer since this 
> must be frustrating.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stan-2Ddev_rstan_issues_491-23issuecomment-2D364719584&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=KqX4l1Lu3QzfIvJp0sHrobSlEFoIdlzKdoygn5qf9q0&m=lxZpanusvABH7z55Wcvsn18LpuqUq5JTo8BO3mu00FE&s=jAVvO1Eb6dVYb8qRRB-6tqYC1rlbNf1EN-mM8QW08ck&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANGZgX3zlEyUaf6y0p3eSzQbiKxGcfWPks5tTmn7gaJpZM4R4NDD&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=KqX4l1Lu3QzfIvJp0sHrobSlEFoIdlzKdoygn5qf9q0&m=lxZpanusvABH7z55Wcvsn18LpuqUq5JTo8BO3mu00FE&s=9SQ38vWc4ie6siVt3bxf8IEUBJ7AF8pdFxs0cJKguU4&e=>.
>

-- 
T. Florian Jaeger
Professor of the Brain and Cognitive Sciences,
Computer Science
Alfred P. Sloan Research Fellow
University of Rochester,
Meliora Hall, Box 270268,
Rochester, NY 14627-0268
USA
P: +1 (585) 276 3611
F: +1 (585) 442 9216
E: fjaeger@ur.rochester.edu
B: http://www.hlplab.wordpress.com/
T: https://twitter.com/_hlplab_

To schedule an appointment, please visit 
http://www.bcs.rochester.edu/people/fjaeger/appointments.html

**Comment by jgabry** [comment]
If you figure out what’s going on please let us know since this seems to be
affecting multiple people. If I find out anything about this I’ll also post
back here so you’ll see it.

**Comment by dm13450** [comment]
I had this issue. It turns out my /etc/hosts file was empty. 
Add 127.0.0.1 localhost in the /etc/hosts file and everything should work again.

**Comment by lleemann** [comment]
Thank you very much - that did the trick for me!
