### ISSUE TITLE
Allow easy programmatic access to HMC diagnostics

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/rstan#494]
#### Summary:
Currently the only way to get diagnostics is via ```check_hmc_diagnostics``` which is itended for human use. I propose a set of functions to access those programmatically. 

#### Description:
In my work I often fit hundreds of small models and want to check that all of them converged. However, except for divergence, which can be somewhat easily extracted from ```nuts_params``` the diagnostics require additional manipulation to be useful (e.g., actual treedepth is not stored directly and BFMI ahs to be computed.)

**Comment by jgabry** [comment]
Closed by #495

**Comment by jgabry** [comment]
@martinmodrak Thanks again for this!
