### ISSUE TITLE
Effective sample size calculation in Stan output (rstan)

### ISSUE THREAD

**Issue by mariadzul-usgs** [stan-dev/rstan#499]
#### Summary:
I am trying to reproduce the effective sample size calculation given by RStan and described in the Stan manual, but I cannot seem to replicate the results.

#### Description:
Describe the issue as clearly as possible.
Hello,

I had a question about the effective sample size calculation in Stan.  I am trying to re-create the same equation used in Stan for computing n_eff, as I am trying to compare effective sample sizes of a few different methods run under different programs.  I can’t seem to reproduce the n_eff estimates, however.  Not sure where I’m going wrong.  Here is what I have so far (this is R code): [N_eff_calc/N_eff_calc.R](https://github.com/mariadzul-usgs/N_eff_calc)

Essentially, I tried calculating effective sample size using two different methods.  These methods are identical except for which autocorrelations are used in the effective sample size calculation.  With the method described in Gelman et al. (2013), the sum of the autocorrelation is for all lags until the sum of the autocorrelation of two successive lags is less than zero (though in the Gelman book they mention the first odd positive integer… which I don’t understand).  In the Stan manual, you only use the autocorrelations before the first lag where the autocorrelation is negative.  Both methods produce answers that are fairly close to the Stan output, but not exactly.

On a similar but different note, I also was trying to use the coda package to calculate effective sample size (using effectiveSize() function), but did not like the fact that it would produce a higher number of effective samples than actual samples (similar to the post by https://groups.google.com/forum/#!topic/stan-users/mfdeTS322hQ)

I am fairly new to Stan and very new to GitHub.  Any help would be appreciated!

Thanks,

Maria Dzul

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

https://github.com/mariadzul-usgs/N_eff_calc

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.17.3

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.4.0

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Windows 10

**Comment by bob-carpenter** [comment]
I'm closing this because the calculation and doc are all being updated for the next release (2.18).

Coda doesn't take cross-chain information into account.  Stan's n_eff is much more conservative.  However, one of the changes for 2.18 is to allow n_eff estimates higher than the number of draws.  This is actually correct and has been calibrated by Aki, who made the changes.

The reference right now is the version in `stan-dev/stan`, and the doc is in the manual there, which can be built with LaTeX.

**Comment by bob-carpenter** [comment]
I should've added some references:

My summary on Andrew's blog of what Aki was telling me:
http://andrewgelman.com/2018/01/18/measuring-speed-stan-incorrectly-faster-thought-cases-due-antithetical-sampling/

Aki's calibration runs:
http://discourse.mc-stan.org/t/n-eff-bda3-vs-stan/2608/14

Paper to follow!
