### ISSUE TITLE
Typo manual 2.17 section 20.2

### ISSUE THREAD

**Issue by garyappleseed** [stan-dev/rstan#500]
#### Summary:
Please provide a short summary (no more than a sentence or two).

real[] x_i should be int[] x_i
#### Description:
Describe the issue as clearly as possible.
There is a typo showing code that won't work. This would be obvious to anyone who knew anything about these issues, but I didn't and it took me a lot of work and some guessing to get it. This was complicated by the fact that the error message wasn't very clear. Anyway, the manual has two lines in a row starting with real[], and the second one should be int[]. 

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.
Copied the code exactly, just changing the function for z to the one I wanted. Kept getting an error message about the signature. Wasn't sure what to make of it. Finally guessed that this was a typo, made the change I suggest above, and it worked,
If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.17.3
#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Mac High Sierra 10.13.3

**Comment by bob-carpenter** [comment]
We track issues with the manual here:

https://github.com/stan-dev/stan/issues/2437#issuecomment-371829107

I copied your issue over to a comment with a citation and am closing this issue.
