### ISSUE TITLE
stanc gives useless error message when model source has non-ASCII characters

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#501]
#### Summary:
If you have a file that contains a non-ASCII character, then running stanc on the file just tells you that there was a C++ exception, and nothing else.

#### Description:
If your Stan source contains a non-ASCII character, then stanc just dies with "c++ exception (unknown reason)", which doesn't help in tracking down the cause of the problem, and makes it look like some sort of system instability.

#### Reproducible Steps:
Write out the "Eight Schools" model to a file schools.stan, then replace all occurrences of the identifier "mu" with the unicode character "μ". Save the results as UTF-8. Then run 

    stanc("schools.stan")

#### Current Output:
The following error message:

    Error in stanc("~/Tmp/foo.stan") : c++ exception (unknown reason)

#### Expected Output:
Something telling me that I have illegal, non-ASCII characters in my Stan source.

#### RStan Version:
2.17.2

#### R Version:
R version 3.4.3 (2017-11-30)

#### Operating System:
OS X 10.13.3

**Comment by maverickg** [comment]
What is the error message for other problematic Stan model code in your
current rstan?

What is the error message if you use stanc in cmdstan?

**Comment by bob-carpenter** [comment]
That's not what happens for me.  I'm on Mac OS X 10.10.5 and RStan 2.17.3 (one beyond where you're at).  Is this still an issue for you in 2.17.3?

```
parameters {
  real μ;
}
model {
  μ ~ normal(0, 1);
}
```

Here's what I see:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'modelbdbe5bf695ec_pe' at line 2, column 10
  -------------------------------------------------
     1: parameters {
     2:   real μ;
                 ^
     3: }
  -------------------------------------------------

PARSER EXPECTED: <identifier>
```

I agree that could be a much clearer message as to why there's a problem.

**Comment by ksvanhorn** [comment]
I think this is related to issue #431; when I reinstalled rstan by compiling from source as recommended [here](https://github.com/stan-dev/rstan/wiki) under "Troubleshooting," this problem went away.

BTW, in response to Bob's comment, the really nasty problem here was not having any idea what line contained the error; even the minimal message "PARSER EXPECTED: <identifier>", with a specific line indicated, is hugely more helpful than "c++ exception (unknown reason)".

**Comment by bob-carpenter** [comment]
Thanks for reporting back.  I'll close the issue, then.  We really do need to be more proactive in the parser about non-ASCII characters and catch the problems right away.  I'm going to open an issue to do just that in Stan.:

https://github.com/stan-dev/stan/issues/2485

There's already an issue to allow unicode with UTF-8 encodings;  I link to that issue from the issue above.
