### ISSUE TITLE
Compilation error-missing plugins

### ISSUE THREAD

**Issue by rspsbits** [stan-dev/rstan#508]
#### Summary:
While testing the installation with the code provided with installation instructions, compilation error occurred stating that plugin needed to handle lto object. 

#### Description:
Below is the output stating that a plugin is missing. 
> fx <- inline::cxxfunction( signature(x = "integer", y = "numeric" ) , '
+ 	return ScalarReal( INTEGER(x)[0] * REAL(y)[0] ) ;
+ ' )
C:\RBuildTools\3.3\mingw_64\bin\nm.exe: file11c4447dccd.o: plugin needed to handle lto object
Cannot export __gnu_lto_slim: symbol not defined
Cannot export __gnu_lto_v1: symbol not defined
collect2.exe: error: ld returned 1 exit status

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: 
  2: // includes from the plugin
  3: #include <R.h>
  4: #include <Rdefines.h>
  5: #include <R_ext/Error.h>
  6: 
  7: 
  8: // user includes
  9: 
 10: 
 11: // declarations
 12: extern "C" {
 13: SEXP file11c4447dccd( SEXP x, SEXP y) ;
 14: }
 15: 
 16: // definition
 17: 
 18: SEXP file11c4447dccd( SEXP x, SEXP y ){
 19: 
 20: 	return ScalarReal( INTEGER(x)[0] * REAL(y)[0] ) ;
 21:  
 22: Rf_warning("your C++ program does not return anything"); 
 23:  return R_NilValue ; 
 24: }
 25: 
 26: 
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:\RBuildTools\3.3\mingw_64\bin\nm.exe: file11c4447dccd.o: plugin needed to handle lto object
Cannot export __gnu_lto_slim: symbol not defined
Cannot export __gnu_lto_v1: symbol not defined
collect2.exe: error: ld returned 1 exit status
> fx( 2L, 5 )
Error: could not find function "fx"
> 

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by bgoodri** [comment]
http://discourse.mc-stan.org/t/error-during-compilation/3557/2?u=bgoodri
