### ISSUE TITLE
summary function no longer returns summary statistics

### ISSUE THREAD

**Issue by timydaley** [stan-dev/rstan#511]
I used to obtain summary statistics with the function summary, as outlined in the vignette.  Is there a new function that has taken its place?

?rstan::summary
No documentation for ‘summary’ in specified packages and libraries:
you could try ‘??summary’
summary(neuron.gene.mix.stan)
 Length   Class    Mode 
      1 stanfit      S4

**Comment by jgabry** [comment]
The summary method should still be there in rstan, but rstan just defines a
method so the underlying summary generic function isn’t in rstan.
