### ISSUE TITLE
enhancements to output analysis

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#52]
It would be nice if we could reproduce all the Coda functionality in RStan.
1.  Ideally, the posterior analysis functionality should be able to operate on an object that just contains the relevant information about variable names, dimensions, and draws with order and chain ID.   (This could be a stanfit object w/o a model, but I think a better approach would be to refactor the relevant parts of the stanfit object into a standalone object that the stanfit object holds on to.)
2.  Some way to read the output of WinBUGS, OpenBUGS, and JAGS into such an object.  We need this capability in order to do the kinds of evaluations both Andrew and our users have been asking for.
3.  Add all the functionality from Coda that's missing from Stan.  That would include the Geweke diagnostics, autocorrelation plots (if we don't have them), running mean plots, etc.  We'd have to do a sweep of the Coda doc to specify this further.

**Comment by jgabry** [comment]
Closing this old issue because I think all of the useful coda functionality is now implemented in our R packages and that functionality is compatible with output from jags, etc.
