### ISSUE TITLE
out of memory?

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/rstan#528]
#### Summary:
Please provide a short summary (no more than a sentence or two).

At the end of sampling, I get:

Error in FUN(X[[i]], ...) : 
  trying to get slot "mode" from an object of a basic class ("NULL") with no slots
Calls: stan ... sampling -> sampling -> .local -> sapply -> lapply -> FUN
Execution halted

My model doesn't have that many parameters, but I do want to include per datum log_lik for loo and sample data sets for posterior predicted checks. So each sample has 21216 columns. I used stan(..., sample_file=tempdir()) and I can see each chain only used about 122M. I use 6 chains. That should easily fit in RAM on my machine.

Is there an easy work-around? Can I use cmdstan and then incorporate the results back into an rstan object?

#### Description:
Describe the issue as clearly as possible.

I read some similar reports on the forums that suggest that this problem might be caused by running out of memory. My computer has 10GiB RAM available, but maybe there is something really inefficient going on.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

I can include a complete example, but first tell me that it would be useful.

#### RStan Version:

Session info -----------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.447)           
 language en_US:en                    
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-05-18                  

Packages ---------------------------------------------------------
 package      * version   date       source        
 assertthat     0.2.0     2017-04-11 CRAN (R 3.5.0)
 BH             1.66.0-1  2018-02-13 CRAN (R 3.5.0)
 cli            1.0.0     2017-11-05 CRAN (R 3.5.0)
 colorspace     1.3-2     2016-12-14 CRAN (R 3.5.0)
 crayon         1.3.4     2017-09-16 CRAN (R 3.5.0)
 dichromat      2.0-0     2013-01-24 CRAN (R 3.5.0)
 digest         0.6.15    2018-01-28 CRAN (R 3.5.0)
 ggplot2        2.2.1     2016-12-30 CRAN (R 3.5.0)
 glue           1.2.0     2017-10-29 CRAN (R 3.5.0)
 graphics     * 3.5.0     2018-04-24 local         
 grDevices    * 3.5.0     2018-04-24 local         
 grid           3.5.0     2018-04-24 local         
 gridExtra      2.3       2017-09-09 CRAN (R 3.5.0)
 gtable         0.2.0     2016-02-26 CRAN (R 3.5.0)
 inline         0.3.14    2015-04-13 CRAN (R 3.5.0)
 labeling       0.3       2014-08-23 CRAN (R 3.5.0)
 lattice        0.20-35   2017-03-25 CRAN (R 3.5.0)
 lazyeval       0.2.1     2017-10-29 CRAN (R 3.5.0)
 magrittr       1.5       2014-11-22 CRAN (R 3.5.0)
 MASS           7.3-50    2018-04-30 CRAN (R 3.5.0)
 Matrix         1.2-14    2018-04-09 CRAN (R 3.5.0)
 methods      * 3.5.0     2018-04-24 local         
 munsell        0.4.3     2016-02-13 CRAN (R 3.5.0)
 pillar         1.2.2     2018-04-26 CRAN (R 3.5.0)
 plyr           1.8.4     2016-06-08 CRAN (R 3.5.0)
 R6             2.2.2     2017-06-17 CRAN (R 3.5.0)
 RColorBrewer   1.1-2     2014-12-07 CRAN (R 3.5.0)
 Rcpp           0.12.16   2018-03-13 CRAN (R 3.5.0)
 RcppEigen      0.3.3.4.0 2018-02-07 CRAN (R 3.5.0)
 reshape2       1.4.3     2017-12-11 CRAN (R 3.5.0)
 rlang          0.2.0     2018-02-20 CRAN (R 3.5.0)
 rstan          2.17.3    2018-01-20 CRAN (R 3.5.0)
 scales         0.5.0     2017-08-24 CRAN (R 3.5.0)
 StanHeaders    2.17.2    2018-01-20 CRAN (R 3.5.0)
 stats        * 3.5.0     2018-04-24 local         
 stats4         3.5.0     2018-04-24 local         
 stringi        1.1.7     2018-03-12 CRAN (R 3.5.0)
 stringr        1.3.0     2018-02-19 CRAN (R 3.5.0)
 tibble         1.4.2     2018-01-22 CRAN (R 3.5.0)
 tools          3.5.0     2018-04-24 local         
 utf8           1.1.3     2018-01-03 CRAN (R 3.5.0)
 utils        * 3.5.0     2018-04-24 local         
 viridisLite    0.3.0     2018-02-01 CRAN (R 3.5.0)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

R version 3.5.0 (2018-04-23)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

Ubuntu bionic

**Comment by bgoodri** [comment]
Besides memory, the other thing to check for is that none of the things in
generated quantities are undefined, but if that is the case there should
have been a warning message above.

You can try rstan::read_stan_csv to read CmdStan output into a stanfit
object.

**Comment by jpritikin** [comment]
Ugh. I'm not keen on rewriting my scripts to use cmdstan, but it's a huge waste of compute resources when rstan fails at the end of sampling so I guess I have no choice? Or can I use `rstan::read_stan_csv` to read the files produced by `stan(..., sample_file)`? Is there any diagnostic that I will skip in my workflow by using `rstan::read_stan_csv`?

**Comment by bgoodri** [comment]
If you specify the sample_file option and pars = "", then it is basically
equivalent to running CmdStan.

**Comment by jpritikin** [comment]
Is there any way to get the same effect as include and pars,

```
               include=TRUE,
               pars=c('alpha', 'sigma', paste0('threshold',1:2), 'theta',
                 'flow', 'flowLoadings', 'log_lik'),  # , 'rcat_sim'
```

There are tons of parameters that I prefer to exclude to reduce memory usage.

**Comment by bgoodri** [comment]
If you specify sample_file, it writes everything to the disk irrespective
of what pars is (which is why you might as well put pars = "").

But if you want to exclude a bunch of stuff from the output, why don't you
just define them in the model block or a local block within transformed
parameters or generated quantities?

**Comment by jpritikin** [comment]
Suppose I have parameter `rawTheta` but I only care about generated quantity `theta` which is a simple function of `rawTheta`. How can I exclude `rawTheta`?

**Comment by bgoodri** [comment]
pars = "rawTheta", include = FALSE

**Comment by jpritikin** [comment]
But `rstan::read_stan_csv` doesn't accept `pars` or `include` options, does it?

**Comment by bgoodri** [comment]
Correct, but if you exclude rawTheta you may not encounter the memory
problem when it comes back to the main process

**Comment by jpritikin** [comment]
Ah, yes, if I use `stan(..., sample_file)`. Are there similar `pars` and `include` options for `cmdstan`? I didn't see anything plausible in help-all.

**Comment by jpritikin** [comment]
I think I'd prefer to use cmdstan because there won't be any surprise failures. I'll write a perl script to strip out the columns I don't want from the raw csv files. Too bad R memory management is so unpredictable.
