### ISSUE TITLE
CPP_stanc280 not resolved from current namespace (rstan)

### ISSUE THREAD

**Issue by kaskr** [stan-dev/rstan#535]
#### Summary:

I'm often experiencing this error (or similar) *at random* :

> Error in .Call("CPP_stanc280", ...)
>   "CPP_stanc280" not resolved from current namespace (rstan)

#### Description:

`rstan` looks up native routines by character rather than using its registered symbols (e.g. `rstan:::CPP_stanc280` ). This is not allowed when you have `R_forceSymbols(dll, TRUE);` in `init.cpp`.

You can sort out the issue by removing quotes from `.Call("...")`:

```shell
cd stan/R
sed -i 's/.Call("\(.*\)"/.Call(\1/g' *.R
```

#### Reproducible Steps:

From a *clean R session* run:

```r
library(Matrix)
library(rstan)
detach("package:Matrix", unload=TRUE)
example(rstan, run.dontrun=TRUE)
```

#### RStan Version:
`2.17.3`

#### R Version:

`R version 3.2.3 (2015-12-10)` and
`R Under development (unstable) (2018-03-14 r74402)`

#### Operating System:

`Ubuntu 16.04`

**Comment by maverickg** [comment]
@kaskr Can you please tell me why it works for now in general and why your code triggers this problem?  Thanks.

**Comment by kaskr** [comment]
@maverickg 
With the current `rstan` code (`.Call` lookup by character with `PACKAGE` argument missing) R tries to automatically find the `rstan` namespace and registered routines by evaluating `getCallingDLLe()` inside the `.GlobalEnv`. Try e.g.:

```r
getCallingDLLe <- function(e) { stop("Better not do this") }
library(rstan)
example(rstan, run.dontrun=TRUE)
```

and you'll see it stops.

In contrast `.Call(CPP_stanc280)` directly passes `rstan:::CPP_stanc280` to `.Call`. It avoids the DLL search (`getCallingDLLe()`) and guaranties that the correct routine is being used. This is the approach recommended in [WRE](https://cran.r-project.org/doc/manuals/r-release/R-exts.html):

> The R_useDynamicSymbols call says the DLL is not to be searched for entry points specified by character strings so .C etc calls will only find registered symbols: the R_forceSymbols call only allows .C etc calls which specify entry points by R objects such as C_pansari (and not by character strings).

My example demonstrates that `getCallingDLLe()` easily gets confused if the table of loaded DLLs changes. There is no reason to rely on this code when it can be avoided.

**Comment by maverickg** [comment]
@kaskr thanks for the detailed explanation

I fixed this with https://github.com/stan-dev/rstan/commit/3489574bd1fbd0c2980dd46f9a95e11ea04f2be0  

Everything seems to be fine.
