### ISSUE TITLE
Segfault in optimizing for simple exponential model

### ISSUE THREAD

**Issue by NathanWycoff** [stan-dev/rstan#545]
This issue ported over from [here](http://discourse.mc-stan.org/t/segfault-in-simple-exponential-model/4776).

Hello everyone,

I want to first thank the developers for an awesome software package that has helped me extensively in several projects.

This bug doesn't really affect me, but I felt like I should report it anyways. With a specific model/data combination and a specific random seed, I observe a segfault when invoking the optimizing function. The model is rather simple.

Steps to reproduce:
1) Please find the model attached [exp_model.txt](https://github.com/stan-dev/rstan/files/2177192/exp_model.txt)
2) Please find an R script attached [breaks_stan.txt](https://github.com/stan-dev/rstan/files/2177185/breaks_stan.txt). Rename these if necessary (not sure why github won't accept R/stan files).
3) Modify line 36 of the R file to point to where exp_model.stan lives on disk.
4) Run the R file in its entirety. This is important to advance PRNG to the point of failure. This involves sampling from the posterior, but it terminates in less than half a second on my machine. 

Bug Description:
Posterior sampling from the model works fine. Afterwards, when trying to find the optimum, it will print the initial loglikelihood, then R will freeze for about half a minute before this message appears (the shrug emoji is just my replacement for the standard prompt):

```

    ¯\_(ツ)_/¯ optimizing(mod, data = stan_dat)
    Initial log joint probability = -8.18984

     *** caught segfault ***
    address 0x256b38fff, cause 'memory not mapped'

    Traceback:
     1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x7fdbf945fd70>,     dll = list(name = "Rcpp", path = "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x7fdbf9708d90>,         info = <pointer: 0x7fdbf986aa20>), numParameters = -1L),     <pointer: 0x7fdbf97fb9b0>, <pointer: 0x7fdbf9739640>, .pointer,     ...)
     2: sampler$call_sampler(c(args, dotlist))
     3: .local(object, ...)
     4: optimizing(mod, data = stan_dat)
     5: optimizing(mod, data = stan_dat)

    Possible actions:
    1: abort (with core dump, if enabled)
    2: normal R exit
    3: exit R without saving workspace
    4: exit R saving workspace
```

This only seems to occur for a specific PRNG state.

Facts about the platform this was discovered on:

OS: Mac OS High Sierra 10.13.2

R: R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

rstan (Version 2.17.3, GitRev: 2e1f913d3ca3)

R was executed directly from a bash terminal.

**Comment by bob-carpenter** [comment]
Thanks much for the reproducible example.

I verified this is indeed a bug and segfaults for me also on the Mac with the latest RStan.

I also verified that it does not segfault on the develop version of CmdStan.

**Comment by maverickg** [comment]
Well, I tried on the last released version of CmdStan and had segfault for some particular seed too.  So I don't think it's a RStan issue. 

This is the seed I used:
```
./exp_model optimize data file=exp.rdump random seed=12345
```

And exp.rdump file has 
```
$ more exp.rdump
alpha_l1_0 <- 0.2
alpha_l2_0 <- 0.2
beta_l1_0 <- 1
beta_l2_0 <- 1
t1 <- 0.281152420352801
t2 <- 0.164745791682175
```

**Comment by bob-carpenter** [comment]
Thanks for following up.  I'll move this to a Stan issue.  

With that seed, it prints 20 or 30 repetitions of:

  Error evaluating model log probability: Non-finite gradient.

then goes into a busy infinite loop where it takes 100% of the CPU, but doesn't produce any output on the terminal.

**Comment by bob-carpenter** [comment]
This issue was moved to stan-dev/stan#2576
