### ISSUE TITLE
Compilation ERROR, function(s)/method(s) not created!

### ISSUE THREAD

**Issue by JvSlooten88** [stan-dev/rstan#548]
Dear STAN Forum, 
I am new to R and Rstan, and would be very happy if someone could help me with solving the following problem. 

#### Summary:
Cannot compile stan model in R/Rstudio  

#### Description:
After installing RStan, I was able to correctly compile and fit the 8schools.stan model. However, when trying to compile another model [pvl_d.stan.zip](https://github.com/stan-dev/rstan/files/2210329/pvl_d.stan.zip), I get an compilation error.

#### Reproducible Steps:

- I followed the [instructions](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux) for downloading RStan. 

- My **Makevars** file contains the following: 
LDFLAGS=  -L/usr/local/clang4/lib
  The following statement changes the Fortran linking path
  FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0
  End Fortran linking path statement
  The following statement changes the Fortran linking path
  FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0
  End Fortran linking path statement
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
CXX98=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
  The following statement changes the Fortran linking path
  FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0
  End Fortran linking path statement
CXXFLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined -Wno-unknown-pragmas
CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256
CXXFLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined -Wno-unknown-pragmas
CC=clang
CXX=clang++ -arch x86_64 -ftemplate-depth-256

- My Rstan installation seems fine, as `fx( 2L, 5 )` returns 0

- to run the model I used the following code: 
library(rstan) 
set_cppo('fast') 
load("Data_paper_deliberate.rdata")
n_s <- nrow(wi)  # Number of subjects
n_t <- ncol(wi)  # Number of trials
net <- wi + lo   # Net gains of each subject on each trial
dat <- list(choice=choice, n_s=n_s, n_t=n_t, net=net)      
model.file <- "pvl_d.stan"
parameters <- c(  
                "A_ind", "mu_A", "la_A",
                "w_ind", "mu_w", "la_w",
                "a_ind", "mu_a", "la_a",
                "c_ind", "mu_c", "la_c")          
samples <- stan(file=model.file, data=dat, verbose=FALSE,
                warmup=500, iter=2200, thin=5, chains=2, 
                init='random', pars=parameters)
 
#### Current Output:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from fileb7a2de3212c.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/stan/math.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:36:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/stan/math/rev/core/operator_unary_plus.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/stan/math/prim/scal/fun/constants.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Res
In addition: Warning messages:
1: In readLines(file, warn = TRUE) :
  incomplete final line found on '/Users/Joanne/Dropbox/Articles/RL_EBR/Website_Pvl_d_bayes/pvl_d.stan'
2: In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB fileb7a2de3212c.cpp 2> fileb7a2de3212c.cpp.err.txt' had status 1
> 

#### RStan Version:
` ‘2.17.3’`

#### R Version:
`"R version 3.5.1 (2018-07-02)"`

#### Operating System:
 OS X 10.13.5

**Comment by bgoodri** [comment]
For the moment, you need to use the fabs() function rather than the abs()
function, which was suggested by the parser message.

**Comment by JvSlooten88** [comment]
Thanks a lot!! That did the trick.

**Comment by bob-carpenter** [comment]
@JvSlooten88:  This is not the Stan forums.  Thisis the issue tracker for bugs in RStan.  If you'd like to ask further questions, please ask them on our forums:

http://discourse.mc-stan.org
