### ISSUE TITLE
vectors of length 1 and matrices with only 1 column

### ISSUE THREAD

**Issue by andrewgelman** [stan-dev/rstan#56]
I was playing around with doing regressions in Stan and came up with a problem.

Here’s my Stan code:

data {
 int N;
 int K;
 int<lower=0,upper=1> y[N];
 matrix[N,K] X;
}
parameters {
 vector[K] b;
}
model {
 y ~ bernoulli_logit(X*b);
}

And here’s my R code:

y <- rep (c(1,0),c(10,5))
N <- length (y)
K <- 1
X <- array (1, c(N,K))
data <- c("N","K","X","y”)

This all worked fine with K=2, but this is what happened with K=1:

model <- stan(file=model_name, data=data, chains = 0)

TRANSLATING MODEL 'logistic_0' FROM Stan CODE TO C++ CODE NOW.
COMPILING THE C++ CODE FOR MODEL 'logistic_0' NOW.
the number of chains is less than 1; sampling not done

OK, that’s fine.  But then I tried to fit the model:

fit <- optimizing(object=get_stanmodel(model), data, hessian = TRUE)
STAN OPTIMIZATION COMMAND (BFGS)
init = random
save_iterations = 1
init_alpha = 0.001
tol_obj = 1e-08
tol_grad = 1e-08
tol_param = 1e-08
seed = 287624105
initial log joint probability = -16.1761
   Iter      log prob        ||dx||      ||grad||       alpha  # evals  Notes 
      0      -12.4353      0.661911       4.59045         0.1        4  
      4      -9.54771   4.27152e-05    1.7734e-07           1        8  
Optimization terminated normally: Convergence detected: change in objective function was below tolerance
Error: mismatch in number dimensions declared and found in context; processing stage=initialization; variable name=b; dims declared=(1); dims found=()

—

Bob and Ben say this bug stems from R's conflation of scalars and 1-dimensional arrays.

**Comment by elchorro** [comment]
I came across the same problem:

My Stan data block:

```
data {
  int T; // number of time periods
  int S; //number of states
  int N; // number of members
  int K; // number of topics
  matrix[T,N*K] Y; // observations
  vector[2] initial_states_prior;
}
```
And my R call:

```
stan.data = list(N = 1, K = 39, T = 179, Y = Y, S = 1, initial_states_prior = vector(1,1))
model <- stan("influence.stan", data = stan.data, iter = 20, chains = 1)
```

Result in the following error:

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=initial_states_prior; dims declared=(1); dims found=()  (in 'model2d40577169f2_influence' at line 7)
```

Has this been resolved yet?

**Comment by bob-carpenter** [comment]
The issue being closed indicates it's fixed.  We leave open bug issues open.

You just need to pass in a size-2 vector.  For example,

```
fit <-
  stan(model_code = "data { vector[2] x; } parameters { real<lower = 0, upper = 1> theta; }", 
       data = list(x = c(1.3, -2.7)))
```

I'm not sure what `vector(1, 1)` is supposed to do, but I get:

```
> vector(1, 1)
Error in vector(1, 1) : vector: cannot make a vector of mode '1'.
```

**Comment by elchorro** [comment]
Bob, thanks for the reply (and all the amazing work you are doing). I apologize, I discovered this thread later and pasted the wrong code.

Reproducible example is here:

```
fit <-
+     stan(model_code = "data{int S; vector[S] x;} parameters { vector[S] theta; }", 
+          data = list(S = 1, x = c(1)))
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=x; dims declared=(1); dims found=()  (in 'model36a077c2e30_d31792206c66bcb33dac9268215b4da7' at line 1)

failed to create the sampler; sampling not done
```
I know that if S=1 then x should be declared as real but in  my code I would like to accommodate various dimensions.

**Comment by bob-carpenter** [comment]
If it's size 1, you need x = as.array(1) or x = as.array(c(1)).

> fit <-
    stan(model_code = "data { real y[1]; } parameters { real<lower = 0, upper = 1> theta; }", 
         data = list(y = as.array(c(3.2))))

I don't understand R's underlying type system, but as.vector(1) doesn't work.
