### ISSUE TITLE
Compilation ERROR for Example 1: Eight Schools

### ISSUE THREAD

**Issue by chisha78** [stan-dev/rstan#567]
#### Summary:
After successfully installing "rstan" by following https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#how-to-use-rstan
Every step gave the same outputs, however once I started trying out the Example 1: Eight Schools in https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#how-to-use-rstan 
I got an error message: "Compilation ERROR, function(s)/method(s) not created!..."
#### Description:
Here is the code I run and the error message: 
> `library("rstan")`
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.17.4, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
> `rstan_options(auto_write = TRUE)`
> `options(mc.cores = parallel::detectCores())`
> `schools_dat <- list(J = 8, y = c(28,  8, -3,  7, -1,  1, 18, 12), sigma = c(15, 10, 16, 11,  9, 11, 10, 18))`
> `file.edit('/Documents/Stan/Test/8schools.stan')`
>` fit <- stan(file = "Documents/Stan/Test/8schools.stan", data = schools_dat, iter = 1000, chains = 4, cores=2)`
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/Program Files/R/R-3.5.1/library/StanHeaders/include/stan/math/rev/core/gevv_vvv_vari.hpp:5:0,
                 from C:/Program Files/R/R-3.5.1/library/StanHeaders/include/stan/math/rev/core.hpp:12,
                 from C:/Program Files/R/R-3.5.1/library/StanHeaders/include/stan/math/rev/mat.hpp:4,
                 from C:/Program Files/R/R-3.5.1/library/StanHeaders/include/stan/math.hpp:4,
                 from C:/Program Files/R/R-3.5.1/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file10781b3c2469.cpp:8:
C:/Program Files/R/R-3.5.1/library/StanHeaders/include/stan/math/rev/core/var.hpp:7:39: fatal error: boost/math/tools/config.hpp: No such file or directory
 #include <boost/math/tools/config.hpp>
                                       ^
compilation terminated.
make: *** [file10781b3c2469.o] Error 1
In addition: Warning messages:
1: In readLines(file, warn = TRUE) :
  incomplete final line found on '\\ads.bris.ac.uk\filestore\MyFiles\Staff2\ew18103\Documents\Stan\Test\8schools.stan'
2: In stan_model(file, model_name = model_name, model_code = model_code,  :
  StanHeaders version is ahead of rstan version; update to latest rstan
3: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-35~1.1/bin/x64/R CMD SHLIB file10781b3c2469.cpp 2> file10781b3c2469.cpp.err.txt' had status 1

In addition, from examining previous posts, I have uninstall and reinstall "StanHeaders". However that still gave the same errors...

#### RStan Version:
> `packageVersion("rstan")`
[1] ‘2.17.4’
> `packageVersion("StanHeaders")`
[1] ‘2.18.0’

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
> `R.version.string`
[1] "R version 3.5.1 (2018-07-02)"

I have installed Rtools34.exe

#### Operating System:
Windows 7

I will be so grateful for any help or advice you can give me!

**Comment by Rdataflow** [comment]
Please retry with StanHeaders 2.17.*

**Comment by chisha78** [comment]
Hi,
Thanks for this @Rdataflow , I have now tried install StanHeader 2.17.2 and now it works!
