### ISSUE TITLE
number of comment lines in read_stan_csv too limited

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#57]
Reported to me off list:

I just discovered a nasty bug in rstan which prevents read_stan_csv to work properly for the case of a full mass matrix. The function refuses to import the csv files generated in this case. The reason is simple: In my case I have a lot of variables and hence the the mass matrix becomes large. Now read_stan_csv reads all the comments from the stan run which it parses. If it does not find the “Elapsed Time” line in the comments the function aborts. However, the number of comments to import is limited to 50. This limit is hard coded in the function and it is by far to small in my case due to the many variables for which the mass matrix is identified after adaptation.

[Hopefully this will be easy to verify and fix.]

**Comment by jgabry** [comment]
Closing since this was fixed but issue was never closed
