### ISSUE TITLE
cannot find -lR: 2.18.1 fails when building rstan on windows 10

### ISSUE THREAD

**Issue by thorvall** [stan-dev/rstan#570]
#### Summary:
When installing rstan on windows if fails with cannot find -lR, but R.exe is in the folder it searches in. 

#### Description:
Using the [guide:](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows) 
Have reinstalled rtools and additionally added 'C:\Rtools\mingw_64\bin' to path, which the guide does not mention.
It now fails with an error message that it cant find R. 

#### Reproducible Steps:
[](install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE))

#### Current Output:
```
g++ -std=c++1y -shared -s -static-libgcc -o rstan.dll tmp.def chains.o init.o lang__ast_def.o lang__grammars__bare_type_grammar_inst.o lang__grammars__expression07_grammar_inst.o lang__grammars__expression_grammar_inst.o lang__grammars__functions_grammar_inst.o lang__grammars__indexes_grammar_inst.o lang__grammars__program_grammar_inst.o lang__grammars__semantic_actions.o lang__grammars__statement_2_grammar_inst.o lang__grammars__statement_grammar_inst.o lang__grammars__term_grammar_inst.o lang__grammars__var_deccls_grammar_inst.o lang__grammars__whitespace_grammar_inst.o misc.o pointer-tools.o sparse_extractors.o stanc.o -LC:/PROGRA~1/R/R-35~1.1/bin/i386 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-35~1.1/bin/i386/R.dll when searching for -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-35~1.1/bin/i386/R.dll when searching for -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lR
collect2.exe: error: ld returned 1 exit status
```

In addition, but this might disappear when rstan compiles:
```
Warning messages:
1: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
2: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
3: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
4: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
5: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
6: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’, ‘loo.stanfit’ were declared in NAMESPACE but not found 
```

#### RStan Version:
trying to install 2.18.1 from source

#### R Version:
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray  

#### Operating System:
   sysname            release        version            machine        
     "Windows"       "10 x64"  "build 17134"          "x86-64"

**Comment by paul-buerkner** [comment]
This is a problem related to installing rstan 2.18 on 32-bit and 64-bit R at the same time with current Rtools versions, which we have not been able to resolve so far.  If you use 64-bit R, you can install rstan for 64-bit R only via 

```
install.packages("rstan", type = "source", INSTALL_opts = "--no-multiarch")
```

If you use 32-bit R, you should change the info in PATH to  `C:\Rtools\mingw_32\bin` and then run the same install command as above. 

See also https://discourse.mc-stan.org/t/failing-to-install-rstan-2-18-on-win10-x64/6044/28 for some discussion about current problems to build rstan 2.18 on windows. As soon as rstan 2.18 has binary versions on CRAN, you shouldn't have to worry about this anymore.

**Comment by thorvall** [comment]
Thanks for your very quick reply. 
It now compiles, and after loading rstan, stan code does compile.
Thanks,
