### ISSUE TITLE
c++ exception (unknown reason) with OSX+clang4 (on CRAN)

### ISSUE THREAD

**Issue by helske** [stan-dev/rstan#572]
#### Summary:
CRAN tests for package [walker](https://cran.r-project.org/web/packages/walker/index.html) fail on OSX using clang4 when calling `stan` with error `c++ exception (unknown reason)`.

#### Description:
Sampling works fine locally on my Linux and Windows machines, and with `rhub::check_for_cran()`, but on CRAN's OSX flavors using clang4 I get following ([full log here](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/walker-00check.html)):
```
> rw2_fit <- walker(Nile ~ -1 +
+ rw2(~ 1,
+ beta_prior = c(1000, 100),
+ sigma_prior = c(0, 100),
+ slope_prior = c(0, 100)),
+ sigma_y_prior = c(0, 100),
+ iter = 200, chains = 1)

SAMPLING FOR MODEL 'walker_lm' NOW (CHAIN 1).
Chain 1: Gradient evaluation took 0.001545 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 15.45 seconds.
Chain 1: init_buffer = 15
Chain 1: adapt_window = 75
Chain 1: term_buffer = 10
[1] "Error in sampler$call_sampler(args_list[[i]]) : "
[2] " c++ exception (unknown reason)"
error occurred during calling the sampler; sampling not done
> 
```
Note that the example in question contains two sampling calls, and first one works just fine.

I noticed some [older questions](https://discourse.mc-stan.org/t/strange-error-message/2050/3) relating to clang4 at Discourse, but based on those I got the impression the issue is solved. Any hints?
Here is the `Makevars` of from `walker`:
```
STANHEADERS_SRC = `"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`
PKG_CPPFLAGS = -I"$(STANHEADERS_SRC)" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG
PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
CXX_STD = CXX14
``` 

#### Reproducible Steps:
I haven't been able to reproduce the result myself. Here are the codes for the examples:
```
 library("walker")
 rw1_fit <- walker(Nile ~ -1 + 
   rw1(~ 1, 
     beta_prior = c(1000, 100), 
     sigma_prior = c(0, 100)), 
   sigma_y_prior = c(0, 100), 
   iter = 200, chains = 1)
   
 rw2_fit <- walker(Nile ~ -1 + 
   rw2(~ 1,
     beta_prior = c(1000, 100), 
     sigma_prior = c(0, 100), 
     slope_prior = c(0, 100)), 
   sigma_y_prior = c(0, 100), 
   iter = 200, chains = 1)
```
I just noticed that I have not set seed before the example, not sure if the error occurs independently of that.

#### System Information:
`Rstan` 2.18.1, happened also with previous  `rstan`/`walker`version combination in CRAN as well.

CRAN flavor `r-release-osx-x86_64 | r-release | OS X | x86_64 | OS X 10.11.6 | Mac Pro, Quad-Core Intel Xeon 2.93 GHz | Xcode 8.2.1, clang 4.0.0, GNU Fortran 6.1`. Also with `r-oldrel`.

**Comment by bgoodri** [comment]
I made a PR for this in the walker repo.
