### ISSUE TITLE
rstan package is not found

### ISSUE THREAD

**Issue by aminathshausan** [stan-dev/rstan#574]
#### Summary:
Please provide a short summary (no more than a sentence or two).

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by aminathshausan** [comment]
Hi 
I followed all instructions but when I get to the step where I had to type library("rstan") I get an error saying that there is no package called 'rstan'. the installed package has the name "rstan_2.18.1.tar.gz". Why is this so? Any help is appreciated

**Comment by bgoodri** [comment]
Probably just a lag in whatever CRAN mirror you were using. It definitely exists
https://cran.r-project.org/web/packages/rstan/

**Comment by davidmanheim** [comment]
Any reason not to close this?
