### ISSUE TITLE
Subscript out of bounds when using `read_stan_csv`

### ISSUE THREAD

**Issue by jburos** [stan-dev/rstan#578]
#### Summary:

I recently updated rstan to v 2.18.1 and found that I was unable to read in chains fit with an earlier version of cmdstan (v2.17.1-35, specifically stan-dev/cmdstan@c1d9b01) using `rstan::read_stan_csv`.

I just tested with the latest version of cmdstan (v2.18.0, specifically stan-dev/cmdstan@dd69572) and found the same behavior.

#### Description:
The error I get when running `read_stan_csv(csvfiles)` is:

```{r}
Error in `[<-`(`*tmp*`, buffer.pointer, , value = scan(con, nlines = 1,  :
  subscript out of bounds
```

When debugging `read_stan_csv`, i see that the value of `buffer.pointer` is 0 because the num.iter read from the header info is 0.

#### Reproducible Steps:

The issue can be illustrated by using `read_stan_csv` on chains fit to the [bernoulli.stan](https://github.com/stan-dev/cmdstan/blob/develop/examples/bernoulli/bernoulli.stan) example provided in the cmdstan repo.

After updating [stan-dev/cmdstan@dd69572]:

```{sh}
HEAD is now at dd69572... release/v2.18.0: updating version numbers
```

and updating submodules, doing `make clean-all`, & `make build -j4`:

```{sh}
--- CmdStan v2.18.0 built ---
```

I find I am unable to read these fitted chains using `read_stan_csv`.

Specifically, on the command line (after compiling `bernoulli` from `bernoulli.stan`):

```{sh}
./bernoulli sample data file=bernoulli.data.R
```

Then trying to read the file into R using `rstan::read_stan_csv`:

```{r}
> fit <- read_stan_csv('cmdstan/examples/bernoulli/output.csv')
Error in `[<-`(`*tmp*`, buffer.pointer, , value = scan(con, nlines = 1,  :
  subscript out of bounds
```

#### RStan Version:
```{r}
> packageVersion("rstan")
[1] ‘2.18.1’
```

#### R Version:
```{r}
> R.version.string
[1] "R version 3.5.1 (2018-07-02)"
```

#### Operating System:
```{r}
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
```

**Comment by bob-carpenter** [comment]
Thanks for reporting.  This may not be fixable.  The CSV readers are very hard coded for a bunch of comments, etc.  We'll be replacing all of this going forward in Stan 3, but that's not going to help anyone any time soon.

**Comment by bob-carpenter** [comment]
I initially misread the direction of the problem.  If 2.18 can't read earlier versions, that's something we can probably fix.

**Comment by bgoodri** [comment]
@aaronjg Is `iter.count` supposed to be `sample.count` in
https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/misc.R#L1527

**Comment by aaronjg** [comment]
Yes, it should be:
"iter.count <- sample.count"

**Comment by bgoodri** [comment]
@jburos Thanks. You can install from GitHub to get the fixed version with
```
devtools::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")
```
but we have to fix https://github.com/stan-dev/rstan/issues/577 before I can try to upload rstan 2.18.2 to CRAN.

**Comment by bgoodri** [comment]
@aaronjg What should it use when sample.count never gets defined?

**Comment by aaronjg** [comment]
Do you have a test case for an output where this happens? I can go back to the old code to see how it was handled there.

**Comment by bgoodri** [comment]
It is the unit test where it does rstan:::read_stan_csv_header("cc2.stan")
which only has like 3 lines. I am initializing sample.count to NA_integer_
now and it seems fine.
