### ISSUE TITLE
Initialization fails as parameters get impossibile values

### ISSUE THREAD

**Issue by slaweks17** [stan-dev/rstan#583]
Hi,
I am debugging problems in my time series models, and created a very much simplified demo.
The issue is that initialization fails, when an unconstrained value(initSu) is assigned to a positively constrained one (initSuPositiveConstrained). However the way this unconstrained parameter is defined and initialized make it impossible for it to get negative values.
It appears that my initial values are ignored. Why?

Here is the code:

library(rstan)

SEASONALITY=12

modelS='
data {  
	int<lower=2> SEASONALITY;
}
parameters {
	vector[SEASONALITY] initSu; 
} 
transformed parameters {
	vector<lower=0>[SEASONALITY] initSuPositiveConstrained;

	for (i in 1:SEASONALITY) {
		initSuPositiveConstrained[i]=initSu[i];
	} 
}
model {
	for (t in 1:SEASONALITY) {
		 initSu[t] ~ normal (1, 0.3) T[0.01,];
	}
}
'

stanModel = stan_model(model_code=modelS)

nChains=1
initializations <- list()
for (irr in 1:nChains) {
	initializations[[irr]]=list( 
		initSu = rnorm(SEASONALITY, 1, 0.05)
	)
}

data <- list(SEASONALITY=SEASONALITY)
parameters="initSu"

samples1 <-
		rstan::sampling(
				object = stanModel,   
				data = data, 
				init = initializations,
				pars = parameters,
				iter = 2,
				chains = 1,
				cores = 1,
				open_progress = F,
				verbose = T,
				refresh = - 1)

**Comment by slaweks17** [comment]
Hi,
Sorry, I forgot to add: it is Windows 10 and rstan 2.18.2

Thanks

**Comment by bgoodri** [comment]
I'm not sure what you are expecting to happen. Since `initSu` can be any
real vector of size 12 and it gets assigned to `initSuPositiveConstrained`
which is constrained to be positive, even if you start with positive values
you are basically guaranteed to cross zero on the first Hamiltonian
transition.

**Comment by slaweks17** [comment]
Hi,
Thanks for looking into it. But there are two issues:
1. initSu should never get negative because its sampling statement is
initSu[t] ~ normal (1, 0.3) T[0.01,];
2. The failure happens during the initialization phase, so do we even touch the model?

**Comment by bgoodri** [comment]
Having a sampling statement that says

initSu[t] ~ normal(1, 0.3) T[0.01,];

does not guarantee that all proposals for initSu are positive. It just
means evaluate

target += normal_lpdf(initSu | 1, 0.3) - SEASONALITY * normal_lccdf(0.01 |
1, 0.3);

which can be evaluated for any initSu, including ones that wander into
negative territory in the first Hamiltonian transition.

**Comment by slaweks17** [comment]
Hi,
Thank you for your help. But I am confused: the Stan manual says (page 84) that
y ~ normal(0, 1) T[-0.5, ];
is equivalent to:
y ~ normal(0, 1);
if (y < -0.5)
target += negative_infinity();
else
target += -normal_lccdf(-0.5 | 0, 1);

So anything out of bounds gets zero probability. How can it wander into the negative territory with zero probability?
I also do not understand why you use SEASONALITY in your formula.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bgoodri** [comment]
The SEASONALITY is just there because the truncation happens for each of
the 12 values, so we can multiply that by the scalar normal_lccdf(0.1 | 1,
0.3). It is true that a negative value for initSu will never be accepted at
the end of a Hamiltonian transition, but that does not imply that no
negative values are proposed for initSu during the (first) Hamiltonian
transition.

**Comment by slaweks17** [comment]
Thank you very much!
