### ISSUE TITLE
Feature: monitor parallel chains while sampling

### ISSUE THREAD

**Issue by lindeloev** [stan-dev/rstan#591]
I am currently debugging a complex model with convergence issues. I run multiple chains in parallel and often the first chain completes several hours before the last chain. It would be great to be able to inspect the results from the "quick" chain immeditately so that I can shut down the other chains if the first chain is bad.

I have an idea about an API for this. However, [when I raised this idea for brms](https://github.com/paul-buerkner/brms/issues/561) Paul Buerkner suggested that I raised the idea here so that there would be a general solution rather than a brms-hack. Unfortunately, I am using `brms`, so I am not too familiar with `rstan` directly, so other solutions may be better. 

* Completed chains will be saved as `filename_chain1.rds` if a `file` is specified. If `file` is not specified, there is no change in behavior.
* If you want to, you can load that in a separate R session and explore it while the sampling continues.
* When all chains have completed, the "chain-files" are deleted, and the full `filename.rds` file is saved.

**Comment by sakrejda** [comment]
Does the write.csv option not work when used in parallel?

**Comment by lindeloev** [comment]
I just learned that the `sample_file` argument already does this in `rstan::stan`. Actually, it's even better because it updates the csv files after each iteration. So just do

    brms::brm(formula, data, sample_file='chain_data')

... and it will save `chain_data_1.csv`, `chain_data_2.csv`, etc. These will stay when sampling has finished.

They have a somewhat strange format. Use the function below to convert them into a normal data.frame of MCMC samples:
```
samples_from_chain = function(filename) {
  stanfit = rstan::read_stan_csv(filename)
  samples = data.frame(stanfit@sim$samples)
  samples %>% 
    filter(lp__ != 0) %>%  # Remove non-sampled iterations
    mutate(
      iter = 1:nrow(.),
      chain = gsub('.csv', '', last(strsplit(filename, '_')[[1]]))  # Get chain number [filename_1.csv]
    )
}
```

Here's one way you would draw traceplots as the sampling progresses:

```
# Load some data
chains = rbind(
  samples_from_chain('chain_data_1csv'),
  samples_from_chain('chain_data_2.csv')
)

# Visualize it
chains %>%
  select(chain, iter, b_Intercept, sigma) %>%
  gather(key, value, -chain, -iter) %>%
  ggplot(aes(x=iter, y=value, color=factor(chain))) + 
  facet_wrap(~key, scales = 'free_y') +
  geom_line()
```

Here's a plot from a model that's still sampling as of writing this:

![image](https://user-images.githubusercontent.com/1439417/49411266-8a139a00-f768-11e8-9623-59680618878f.png)


Closing this issue.
