### ISSUE TITLE
Programmatically check diagnostics

### ISSUE THREAD

**Issue by vkehayas** [stan-dev/rstan#594]
#### Summary:
Provide a wrapper function to evaluate several model diagnostics.

#### Description:
Although `rstan` provides functions to diagnose models in `check_hmc_diagnostics.R`, it would be useful to have a single utility function that provides a list containing the outcome for all relevant diagnostics on a per-model basis. Such a wrapper function would make programmatic model fit evaluation a bit easier, for example in unit tests.
A template of how it might look is provided by @betanalpha here:
https://github.com/betanalpha/knitr_case_studies/blob/master/rstan_workflow/stan_utility.R

The way I imagine the output of this function would be to 
1) print messages or warnings depending on if something is found for each diagnostic, similarly to what is done after sampling is completed
2) return a list of booleans corresponding to each of the diagnostics used 
3) perhaps also return an additional item in the list for whether all diagnostics are cleared.

Suggested diagnostics are:
```r
CheckDivergence
CheckTreeDepth
CheckEnergy
CheckNEffective
CheckRHat
```

Since this is something I feel I can contribute to, please let me know if you would like a PR.

([Initially posted](https://github.com/paul-buerkner/brms/issues/568) on @paul-buerkner 's `brms` project, reposted here on the suggestion of @bgoodri)
cc @avehtari, @jgabry

**Comment by bgoodri** [comment]
OK, we're talking about the rhat thing tomorrow, so we'll see what comes of that.

**Comment by vkehayas** [comment]
See https://github.com/paul-buerkner/brms/issues/568.
