### ISSUE TITLE
temporary file leak (in cxxfun_from_dso_bin?)

### ISSUE THREAD

**Issue by madeleineth** [stan-dev/rstan#597]
#### Summary:

There appears to be a temporary file leak when building models in parallel.

#### Description:

If you look in `/tmp/Rtmp....`, it fills up with `.so` files when building and sampling from many models in parallel.

This is also discussed here: https://discourse.mc-stan.org/t/looping-over-many-fits-fills-hard-drive/5523/6

I suspect the `cxxfun_from_dso_bin` function is responsible.

#### Reproducible Steps:

Here's `placeholder.stan`:
```
parameters {
  real x;
}

model {
  x ~ normal(0, 1);
}
```

Here's an R script that fills up my disk with temporary files if you let it run for a few minutes:
```
library("rstan")
library("parallel")

fit_once <- function(x) {
  model <- stan_model("placeholder.stan")
  sampling(model)
}

repeat {
  mclapply(1:3, fit_once, mc.cores = 3)
}
```

#### RStan Version:

2.18.2 (custom built at `85c9b00a`, though the one on CRAN also seems to have the issue)

#### R Version:

R version 3.5.1 (2018-07-02)

#### Operating System:

Ubuntu Linux 18.10 on an EC2 m5a.xlarge (4 AMD vCPUs, 16GiB RAM)

**Comment by madeleineth** [comment]
Also, I confirmed that it happens on R-devel 2018-12-30 r75928 with rstan 2.18.2 (also on Ubuntu 18.10 on an m5a.xlarge).

**Comment by bgoodri** [comment]
This is a known limitation of the fact that we can't reliably find a previously compiled `stanmodel` object in local scopes. You should do something like
```
model <- stan_model("placeholder.stan")
repeat {
  mclapply(1:3, sampling, mc.cores = 3, object = model)
}
```
