### ISSUE TITLE
pairs() function doesn't seem to colour the right points

### ISSUE THREAD

**Issue by ShaunMcDonald1021** [stan-dev/rstan#599]
#### Summary:
The pairs() function is supposed to colour divergent points red, but the red points don't seem to correspond to the actual indices with divergences. This appears to be related to the source code of the smoothScatter() function.

#### Description:
In theory, the pairs() method in rstan is supposed to assign colours to certain points for diagnostic reasons - red for divergences, and yellow for hitting the max treedepth (I will only focus on the former here, since the example in which I discovered this behaviour had no instances of the latter).  However, in practice I found that parameter values at divergent steps (either found directly or alternatively shown with the stan.par() function) didn't correspond to the red points in the pairs() scatterplots. As far as I can tell after digging through source code, the problem seems to be that the `smoothScatter` function rstan calls from the 'graphics' re-orders the points before colouring them. Thus, I'm not sure if there's a viable fix on the rstan side, but I wanted to note it anyways.

#### Reproducible Steps:
For simplicity, assume only one chain and parameter `theta` (the actual model is irrelevant here). Of course, we can first look at the pairs plot
`pairs(stan_runs, pars = c('theta', 'lp__'))`

To recover the values of theta at divergent transitions with below-median acceptance probability (which, in theory, should be the red points on the lower diagonal plot of `pairs`), we can do the following:

`divergent__ = get_sampler_params(stan_runs)[[1]][,'divergent__']`
`accept_stat__= get_sampler_params(stan_runs)[[1]][,'accept_stat__']`
`theta = extract(stan_runs, permuted = FALSE, pars = 'theta')`
`theta[divergent__ == 1 & accept_stat__ < median(accept_stat__)]`

In my application, I found that there were values of theta printed in the last step with values that obviously didn't correspond to the red points in the `pairs` plot. However, calling

`stan_par(stan_runs, pars = 'theta')`

puts markers at the "correct" points printed above, in contrast to the `pairs()` scatterplot. When I run the code below,

`lp = extract(stan_runs, permuted = FALSE, pars = 'lp__')`
`smoothScatter(theta[accept_stat__ < median(accept_stat__)], lp[accept_stat__ < median(accept_stat__)], col = ifelse(divergent__[accept_stat__ < median(accept_stat__)]== 1, 'red', NA_character_))`

I recover the bottom left plot from `pairs()` ("wrong" divergent points and all), suggesting that the problem is with `smoothScatter` itself (a glance at the source code confirmed this - for some reason it re-orders the points).

#### RStan Version:
Using rstan version 2.18.2.

#### R Version:
Using R version 3.5.1, with graphics package v3.5.1

#### Operating System:
Windows 10.

**Comment by bgoodri** [comment]
That is ... annoying. @jgabry can we work around this by setting `nrpoints = 0` and specifying a `postPlotHook` function that colors the points that are supposed to be red or yellow?

**Comment by jgabry** [comment]
I tried this last week and thought I posted this, but I guess not. I think replacing the `lower.panel` function (and analogously the `upper.panel` function using `mark` instead of `!mark`) with the code below would work. I'll open a PR.

```r
lower.panel <- function(x,y, ...) {
        dots <- list(...)
        x_tmp <- x[!mark]
        y_tmp <- y[!mark]
        div_tmp <- divergent__[!mark]
        hit_tmp <- hit[!mark]

        dots$x <- x_tmp
        dots$y <- y_tmp
        dots$nrpoints <- 0
        dots$postPlotHook <- function() {
          if (!identical(condition, "divergent__")) {
            points(x_tmp[div_tmp==1], y_tmp[div_tmp == 1], col = "red", pch = ".")
            points(x_tmp[hit_tmp == 1], y_tmp[hit_tmp == 1], col = "yellow", pch = ".")
          }
        }
        dots$add <- TRUE
        do.call(smoothScatter, args = dots)
      }
```
