### ISSUE TITLE
error during untar v2.18.1.tar.gz in untar2() function from the GitHub release

### ISSUE THREAD

**Issue by murfreesboro** [stan-dev/rstan#605]
#### Summary:
Please provide a short summary (no more than a sentence or two).

error in untar of v2.18.1.tar.gz in untar2() function, error message is 
skipping pax global extended headers

#### Description:
Describe the issue as clearly as possible.

We use Easybuild to maintain the cluster software. In the installation of RStan we meet the following error during the unstar of v2.18.1.tar.gz, the tarball is downloaded from the link: https://github.com/stan-dev/rstan/archive/v2.18.1.tar.gz. Can you double check this tar.gz file? Thank you!

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

The following command returns the error:

R CMD INSTALL v2.18.1.tar.gz   --library=/accre/arch/easybuild/software/MPI/GCC/6.4.0-2.28/OpenMPI/2.1.1/RStan/2.18.1/ --no-clean-on-error

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

R CMD INSTALL v2.18.1.tar.gz   --library=/accre/arch/easybuild/software/MPI/GCC/6.4.0-2.28/OpenMPI/2.1.1/RStan/2.18.1/ --no-clean-on-error " exited with exit code 1 and output:
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from ‘v2.18.1.tar.gz’
 (at easybuild/EB-develop/easybuild-framework/easybuild/tools/run.py:501 in parse_cmd_output)

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

2.18.1

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

3.4.3

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core

**Comment by bob-carpenter** [comment]
It untarred fine for me in the Finder in Mac OS X (10.13.6 --- High Sierra).

**Comment by murfreesboro** [comment]
I can download it and untar it, too. However it seems when I do "R CMD INSTALL v2.18.1.tar.gz --library=/accre/arch/easybuild/software/MPI/GCC/6.4.0-2.28/OpenMPI/2.1.1/RStan/2.18.1/ --no-clean-on-error" it gives me error.  The untar2() function is a R function.

**Comment by bgoodri** [comment]
You have to untar it first and then `R CMD INSTALL` the rstan/rstan subdirectory, as in
```
tar -xzf rstan-2.18.1.tar.gz
R CMD INSTALL rstan-2.18.1/rstan/rstan
```
