### ISSUE TITLE
"External" vignette missing `sinc` code in CRAN 

### ISSUE THREAD

**Issue by maxbiostat** [stan-dev/rstan#607]
https://cran.r-project.org/web/packages/rstan/vignettes/external.html

"the sinc.hpp file reads as
  [BLANK]
"

From the source code it seems that the `sinc.hpp` was not in the right directory so the relevant chunk does not render properly.

**Comment by bgoodri** [comment]
Yeah, I need to fix that. -- Thanks

**Comment by bgoodri** [comment]
I think I have this fixed locally. Thanks!
