### ISSUE TITLE
Include GPL 2 in license

### ISSUE THREAD

**Issue by mm3509** [stan-dev/rstan#628]
#### Summary:

I would like RStan to include GPL2 as a license.

#### Description:

I am writing a package that depends on `ggplot2` and `e1071`, which are GPL 2, and `rstan`, which is GPL 3.

On choosing a license, I realised that [I cannot use packages that depend on GPL 2 and 3](https://www.gnu.org/licenses/license-list.en.html#GPLv2):

> Please note that GPLv2 is, by itself, not compatible with GPLv3. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well.

Following [this thread on StackExchange](https://opensource.stackexchange.com/questions/4414/if-my-r-package-uses-gpl-packages-does-mine-automatically-inherit-gpl):

> these two versions [(GPL 2 and 3)] are mutually incompatible so you cannot distribute a program that would depend on libraries under both licenses. To solve this hurdle, the best way is probably to write to the authors of the "GPL 2.0 only" packages and ask them to license their libraries under "GPL 2.0 or later" instead.

I request that `rstan` include GPL 2, so one can create packages that depend on `rstan` and other GPL 2 packages.

#### Reproducible Steps:

Not relevant.

#### Current Output:

Not relevant.

#### Expected Output:

Not relevant.

#### RStan Version:

2.18.2

#### R Version:

R version 3.5.2 (2018-12-20)

#### Operating System:

OS X 10.14.4

**Comment by avehtari** [comment]
> To solve this hurdle, the best way is probably to write to the authors of the "GPL 2.0 only" packages and ask them to license their libraries under "GPL 2.0 or later" instead.

As in your quote, the recommendation is to contact the authors of "GPL 2.0 only" package, and not the authors of the "GPL 3" package. btw ggplot2 is part of tidyverse, which is using mix of GPL 2 and 3 (and MIT).

**Comment by mm3509** [comment]
You're right. As I am using several package with GPL 3 and only one with GPL 2, one other way was to ask the GPL3 package to also include GPL2.

But in fact, `rstan` uses `ggplot2`, which is GPL 2. So if `rstan` can use a license other than GPL 2, I believe I can do the same.

**Comment by bob-carpenter** [comment]
You could also just release your package under BSD-3-clause (aka new BSD), which is compatible with GPL.

For all the gory details, see:  https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

and:  https://directory.fsf.org/wiki/License:BSD-3-Clause

This is how the core Stan C++ code is licensed and probably how we should've licensed RStan and PyStan.

**Comment by bgoodri** [comment]
@miguelmorin From a quick glance at your package, my understanding is that CRAN's and the FSF's position is that having **rstan** (or **ggplot**, etc.) in the Imports field does not create a derived work of **rstan** in a functional language such as R. Therefore, your choice of a license for your package has nothing to do with that of **rstan**.

However, compiling a Stan model at runtime is not how we would recommend writing an R package that uses the Stan algorithms. It is generally much better to compile the model at installation time or to download a binary CRAN package whose Stan model has already been compiled. At that point, my understanding is that CRAN's and the FSF's position is that the generated C++ is a derived work of Rcpp (which is licensed  under GPL 2+) and your package would need to be licensed in a way that consistent with that.

**Comment by mm3509** [comment]
@bgoodri Thanks for the suggestion and the inspection of my package. I understand that if I compile the Stan model at runtime from a `.stan` file, as I do now, then the compiled Stan program is a derived work of Rcpp and requires GPL 2+. But if I compile it on my machine first and upload it to CRAN along with the source code, can I stay with the MIT license?

Incidentally, when I pre-compile an RStan model with:

```r
rstan::rstan_options(auto_write = TRUE)
rstan_model <- rstan::stan_model(file = source_file)
```

I see no `.rds` file in the directory of `source_file` (I checked that my user can write to the directory and that `RScript` is running with my user), nor in the current `tempdir()` of an interactive R session. How should I compile an RStan model for distribution in a package?

**Comment by bgoodri** [comment]
For general guidelines on creating a package using Stan, see

https://cran.r-project.org/web/packages/rstantools/vignettes/developer-guidelines.html

and for the step-by-step version see

https://cran.r-project.org/web/packages/rstantools/vignettes/minimal-rstan-package.html

But I think you have it reversed. If you just provide the .stan files in
your package, then it isn't necessarily a derived work of anything. But it
has to be compiled at run-time, which is bad. If you provide the C++ files
to pre-compile the Stan models on CRAN, they have the `#include <Rcpp.h>`
lines that copies in all of the GPL'd headers from Rcpp, making it a
derived work of Rcpp.

**Comment by mm3509** [comment]
Yes, that makes sense: if I distribute the source `.stan` model, I am not creating a derived work of Rcpp or Rstan (the user will at runtime and that seems OK with the MIT license for my package). If I do compile the Stan model and distribute it, then I am creating and distributing derived work of Rcpp, which requires a license compatible with GPL.

I see on [the step-by-step tutorial](https://cran.r-project.org/web/packages/rstantools/vignettes/minimal-rstan-package.html) that to compile a model, I have to follow the RStan package skeleton, which creates the right structure:

```
library("rstantools")
rstan_package_skeleton(path = 'rstanlm')
```

and the code that compiles the model into C++ is in `tools/make_cc.R`:

```
make_cc <- function(file) {
  file <- sub("\\.cc$", ".stan", file)
  cppcode <- rstan::stanc(file, allow_undefined = TRUE,
                          obfuscate_model_name = FALSE)$cppcode
	...
}
```

For better or worse, my employer decided to not compile the Stan model and to stay with the MIT license. This has the advantage of the code allowing users to provide their own Stan models, and the disadvantage that our project is de-prioritised in the RStan community support.

Thanks for your help and the great clarifications. I hope that this discussion helps someone in the future.
