### ISSUE TITLE
produce option for covariance and scatterplotting posterior

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#63]
It would be nice to have the option of printing covariance for pairs of parameters.  Ideally, a subset of parameters could be chosen using a string vector as input.

I'd also love to have the kinds of pairwise parameter scatterplots that Ben produces with summaries for parameters on the diagonal.

**Comment by jgabry** [comment]
Closing this old issue since it's all either been implemented or was already possible at the time.
