### ISSUE TITLE
Rstan CXX14 compile fail for 'Getting started' tutorial on windows 10

### ISSUE THREAD

**Issue by nickschurch** [stan-dev/rstan#633]
I am completely new to Rstan. I worked my way through the 'getting started' instructions but when I come to fir the model, I get the following error:

```
> fit <- stan(file = '8schools.stan', data = schools_dat)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Error in .shlib_internal(commandArgs(TRUE)) : 
  C++14 standard requested but CXX14 is not defined
Calls: <Anonymous> -> .shlib_internal
Execution halted
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file177c4fad1bac.cpp 2> file177c4fad1bac.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

#### Description:
This is a fresh install of R, Rstan, and Rstudio under windows. The versions are:

```
> Sys.info()
       sysname        release        version       nodename        machine 
     "Windows"       "10 x64"  "build 17763"       "xxxxxx"       "x86-64" 

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.18.2       StanHeaders_2.18.1 ggplot2_3.1.1     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         pillar_1.3.1       compiler_3.6.0    
 [4] plyr_1.8.4         prettyunits_1.0.2  tools_3.6.0       
 [7] pkgbuild_1.0.3     tibble_2.1.1       gtable_0.3.0      
[10] pkgconfig_2.0.2    rlang_0.3.4        cli_1.1.0         
[13] rstudioapi_0.10    parallel_3.6.0     loo_2.1.0         
[16] gridExtra_2.3      withr_2.1.2        dplyr_0.8.0.1     
[19] stats4_3.6.0       grid_3.6.0         tidyselect_0.2.5  
[22] glue_1.3.1         inline_0.3.15      R6_2.4.0          
[25] processx_3.3.0     callr_3.2.0        purrr_0.3.2       
[28] magrittr_1.5       scales_1.0.0       ps_1.3.0          
[31] matrixStats_0.54.0 assertthat_0.2.1   colorspace_1.4-1  
[34] lazyeval_0.2.2     munsell_0.5.0      crayon_1.3.4 
```

I have made sure that I correctly ran the section for making `Makevars.win` and I have also tried the flag solutions suggested [here](https://github.com/stan-dev/rstantools/issues/40) and [here](https://github.com/stan-dev/rstan/issues/569) to no avail.

Inserting `CXX14 = g++` into `Makevars.win` results is the error:

```
> fit <- stan(file = '8schools.stan', data = schools_dat)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! sh: g++: command not found
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/x64/Makeconf:215: file177c347912c2.o] Error 127
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file177c347912c2.cpp 2> file177c347912c2.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

while inserting the flags 
```
CXX14="$(BINPREF)g++ $(M_ARCH)"
CXX14FLAGS="-O2 -Wall"
CXX14STD=-std=gnu1y
```

results in the error

```
> fit <- stan(file = '8schools.stan', data = schools_dat)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! sh: C:/RBuildTools/3.5/mingw_64/bin/g++ : No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/x64/Makeconf:215: file177c3ee13a32.o] Error 127
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file177c3ee13a32.cpp 2> file177c3ee13a32.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
```

The output of `pkgbuild::has_build_tools(debug = TRUE)` is true and `C:/RBuildTools/3.5/mingw_64/bin/g++` does exist on the filesystem.

#### Reproducible Steps:
Step by step instructions on the 'getting started' page.

**Comment by tsharaf** [comment]
I have the same issue on windows 10 with R 3.6, any recommendations

**Comment by ode33** [comment]
One recommendation is to install a VM and build the latest Ubuntu on it if you can't wait for real help to arrive.

**Comment by foogee** [comment]
Same exact issue here

**Comment by foogee** [comment]
I finally fixed it by changing my Makevars.win file to the below
CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native

**Comment by tsharaf** [comment]
I can't do this on Windows, can you explain how did you change it. 
Thanks in advance

**Comment by foogee** [comment]
I used emacs, which makes it pretty easy to get to the document. The Stan getting started page also has instructions for modifying Makevars.win. One last point: the original poster had the directory RbuildTools in C; I did not. Instead I had Rtools. I created .Rprofile in my home directory with the below to fix that
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")

**Comment by tsharaf** [comment]
Thanks, I got it to work by following the instructions on Stan quick guide page

**Comment by nickschurch** [comment]
This worked for me too. Thanks.

**Comment by janhannig** [comment]
This did not work for me on a mac. I am getting
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from file1096b88c599.cpp:8:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core/matrix_vari.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat/fun/Eigen_NumTraits.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resourc
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB file1096b88c599.cpp 2> file1096b88c599.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

**Comment by ghost** [comment]
This is the Windows 10 thread. Look here instead: https://github.com/stan-dev/rstan/issues/637

**Comment by mpapenfus** [comment]
I am having the same issue on Windows 10, RStudio1.2.1335, R 3.6.0.  Did a fresh 'rstan' install following guidance on the RStan-Getting Started Guide.

pkgbuild::has_build_tools(debug = TRUE)
[1] TRUE

Now I try to run 8 schools example:
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)


schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit <- stan(file = 'D:/home/stan_example/8schools.stan', data = schools_dat)

with the following error.

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Error in .shlib_internal(commandArgs(TRUE)) : 
  C++14 standard requested but CXX14 is not defined.
Calls: <Anonymous> -> .shlib_internal
Execution halted
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file5790166c2eb7.cpp 2> file5790166c2eb7.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

Even after reading the thread above, I am at a lose as to how to proceed.
Any suggestions would be welcome.
thanks.

**Comment by schwa021** [comment]
> I finally fixed it by changing my Makevars.win file to the below
> CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native

Thanks. This worked. If you have a few seconds for a non-compsci/developer type - can you please explain what this means and why it worked?

**Comment by ghost** [comment]
I'm not an experienced Windows dude but I can tell you that CXX14 is the system flag for finding the needed compiler, I presume that the $(BINPREF) follows a convention for expanding another system environment variable likely the path of the compiler, g++ is the compiler we a targeting, -O2 is the optimization level, you can read about march and mtune here: https://lemire.me/blog/2018/07/25/it-is-more-complicated-than-i-thought-mtune-march-in-gcc/. Why it works is because of a difference between your operating system software updates which created the bug and `rstan` developer lag time required to identify and patch the issue.

**Comment by sgb86** [comment]
Hi, thanks to nickschurch for bringing up this issue. I have had an identical error message when following the installation instructions for rstan trying to compile a model and it sounds like the following solution worked at least for Windows users like myself. 

> I finally fixed it by changing my Makevars.win file to the below
CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native

I have no idea how to do this however. Can it be done from the R-Studio console? If not, then how do you locate the Makevars.win file in Windows?

**Comment by Kruti2017** [comment]
Thanks, changing Makevars file helped !

**Comment by philophthalmus** [comment]
I have the same problem on a linux server. 

I have tried the suggestion to change the Makrvar file, but it didn't work on my system.

Are there known solutions for linux servers?

**Comment by mlan1** [comment]
Solved in my Win10.

1. Locate the "Makevars.win". It's "Home\.R\Makevars.win" in my laptop.
2. Add the following to the Makevars.win
```
CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native
```

My Makevars.win looks like this now:
```
CXX14=$(BINPREF)g++ -O2 -march=native -mtune=native
CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=native -mtune=native
```

**Comment by philophthalmus** [comment]
Dear mlan1,

Thank you for the solution for Windows 10.  However, the solution does not apply to my Linux sever.

**Comment by tahia** [comment]
I have similar issue on my RH7 server. Any suggestion?

Thanks!

E  creating vignettes (4m 5.8s)
   Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
   Creating a 'stanmodel' object beta_binomial
   Warning in system(cmd, intern = !verbose) :
     running command '/usr/lib64/R/bin/R CMD SHLIB file386f627b8ce39.cpp 2> file386f627b8ce39.cpp.err.txt' had status 1
   Quitting from lines 20-45 (SBC.Rmd) 
   Quitting from lines 20-45 (SBC.Rmd) 
   Error: processing vignette 'SBC.Rmd' failed with diagnostics:
   invalid connection
   Execution halted
Error: Failed to install 'rstan' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):


> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.25

loaded via a namespace (and not attached):
 [1] ps_1.3.0          prettyunits_1.0.2 crayon_1.3.4      withr_2.1.2      
 [5] rprojroot_1.3-2   assertthat_0.2.1  R6_2.4.0          backports_1.1.5  
 [9] magrittr_1.5      cli_1.1.0         curl_3.3          remotes_2.1.0    
[13] callr_3.3.2       tools_3.5.1       xfun_0.8          compiler_3.5.1   
[17] processx_3.4.1    pkgbuild_1.0.6

**Comment by SamuelDonnelly** [comment]
I'm getting a similar error - everything started working fine after installing rstan and rtools, then when trying in a RMD (rather than rscript), I received the following error: 

Input:
```
library(rstan)
options(mc.cores=4)
fit <- stan(file = "linearmodel.stan", data = data)
```
Output:
```
'C:/rtools40/usr/mingw_/bin/g++' not foundmake cmd is
  make -f "C:/PROGRA~1/R/R-40~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-40~1.3/share/make/winshlib.mk" CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB="file28dc5bb722de.dll" WIN=64 TCLBIN=64 OBJECTS="file28dc5bb722de.o"

make would use
C:/rtools40/usr/mingw_64/bin/g++  -std=gnu++14 -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG   -I"C:/Users/donne/Documents/R/win-library/4.0/Rcpp/include/"  -I"C:/Users/donne/Documents/R/win-library/4.0/RcppEigen/include/"  -I"C:/Users/donne/Documents/R/win-library/4.0/RcppEigen/include/unsupported"  -I"C:/Users/donne/Documents/R/win-library/4.0/BH/include" -I"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/include/src/"  -I"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/include/"  -I"C:/Users/donne/Documents/R/win-library/4.0/RcppParallel/include/"  -I"C:/Users/donne/Documents/R/win-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DBOOST_NO_AUTO_PTR  -include "C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp"  -std=c++1y         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c file28dc5bb722de.cpp -o file28dc5bb722de.o
if test "zfile28dc5bb722de.o" != "z"; then \
  if test -e "file28dc5bb722de-win.def"; then \
    echo C:/rtools40/usr/mingw_64/bin/g++  -shared -s -static-libgcc -o file28dc5bb722de.dll file28dc5bb722de-win.def file28dc5bb722de.o   "C:/Users/donne/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/donne/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    C:/rtools40/usr/mingw_64/bin/g++  -shared -s -static-libgcc -o file28dc5bb722de.dll file28dc5bb722de-win.def file28dc5bb722de.o   "C:/Users/donne/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/donne/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
  else \
    echo EXPORTS > tmp.def; \
    C:/rtools40/usr/mingw_64/bin/nm file28dc5bb722de.o | sed -n 's/^.* [BCDRT] / /p' | sed -e '/[.]refptr[.]/d' -e '/[.]weak[.]/d' | sed 's/[^ ][^ ]*/"&"/g'  >> tmp.def; \
    echo C:/rtools40/usr/mingw_64/bin/g++  -shared -s -static-libgcc -o file28dc5bb722de.dll tmp.def file28dc5bb722de.o   "C:/Users/donne/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/donne/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    C:/rtools40/usr/mingw_64/bin/g++  -shared -s -static-libgcc -o file28dc5bb722de.dll tmp.def file28dc5bb722de.o   "C:/Users/donne/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/donne/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/donne/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    rm -f tmp.def; \
  fi \
fi
```
```
Error in compileCode(f, code, language = language, verbose = verbose) : sh: line 1: C:/rtools40/usr/mingw_64/bin/g++: No such file or directorymake: *** [C:/PROGRA~1/R/R-40~1.3/etc/x64/Makeconf:229: file28dc5bb722de.o] Error 127
Error in sink(type = "output") : invalid connection
```

Thank you in advanced,
Sam
