### ISSUE TITLE
Installing RStan on Linux

### ISSUE THREAD

**Issue by paulsendavidjay** [stan-dev/rstan#642]
#### Summary:
Please provide a short summary (no more than a sentence or two).
Following instructions to add
    rsession-ld-library-path=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
to 
    /etc/rstudio/rsession.conf
causes RStudio to crash on restart.

#### Description:
Describe the issue as clearly as possible.
RStan runs fine in terminal on linux server, but in RStudio produces error on loading

Error: package or namespace load failed for ‘rstan’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so': /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so)

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.
Error: package or namespace load failed for ‘rstan’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so': /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so)

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
Version 2.18.2
#### R Version:
The version of R you are running (e.g., from `R.version.string`)
"R version 3.5.2 (2018-12-20)"

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Centos 7

**Comment by ode33** [comment]
https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by ghost** [comment]
I'm seeing a lot of suggestions online but in your case the compiler is already working. What have you tried so far?

**Comment by paulsendavidjay** [comment]
@ode33 
So far I've tried pasting:
`rsession-ld-library-path=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64`
into `/etc/rstudio/rsession.conf`, which prevents RStudio from starting up.

And I've tried the suggestion at https://discourse.mc-stan.org/t/rstan-wont-load-in-rstudio-server-linux/7701/4 

```
(base) [dpaulsen@risk02 ~]$ sudo find / -name "libstdc++.so.6"
/home/dpaulsen/anaconda3/pkgs/libstdcxx-ng-8.2.0-hdf63c60_1/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so.6
/home/dpaulsen/anaconda3/pkgs/libstdcxx-ng-8.2.0-hdf63c60_1/lib/libstdc++.so.6
/home/dpaulsen/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so.6
/home/dpaulsen/anaconda3/lib/libstdc++.so.6
/home/dpaulsen/gcc-4.9.3/x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6
/home/dpaulsen/gcc-4.9.3/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6
/home/dpaulsen/gcc-4.9.3/stage1-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6
/usr/lib64/libstdc++.so.6
/usr/local/lib64/libstdc++.so.6
```

dirs<-c("/home/dpaulsen/gcc-4.9.3/x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs",
        "/home/dpaulsen/gcc-4.9.3/prev-x86_64-unknown-linux-gnu/libgcc/")
for ( dir in dirs ) {
  libs<-list.files(dir,pattern="*.so")
  for ( lib in libs ) {
    print(lib)
    dyn.load(paste(dir,lib,sep="/"))
  }
}

which returns 
[1] "libstdc++.so"
[1] "libstdc++.so.6"
[1] "libstdc++.so.6.0.20"
[1] "libgcc_s.so"
[1] "libgcc_s.so.1"
and the same error.

Error: package or namespace load failed for ‘rstan’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so':
  /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/dpaulsen/R/x86_64-redhat-linux-gnu-library/3.5/rstan/libs/rstan.so)

**Comment by paulsendavidjay** [comment]
Following the suggestion for a "one-time fix" at this [git page](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux)  I need to paste `export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64` into shell before running R. Otherwise I get the same result as RStudio when trying `library(rstan)`

**Comment by ghost** [comment]
Is the R version the same for R and RStudio? Both are 3.5?

**Comment by paulsendavidjay** [comment]
Yes. 3.5.2

**Comment by ghost** [comment]
And you've reinstalled `rstan` since encountering the error?

**Comment by paulsendavidjay** [comment]
I've also tried to load the dynamic libraries specified in the search paths by `export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64` 

```
dirs<-c("/usr/lib64",
        "usr/local/lib64", 
        "/usr/local/lib",
          "/usr/lib")
for ( dir in dirs ) {
  libs<-list.files(dir,pattern="*.so")
  for ( lib in libs ) {
    print(lib)
    dyn.load(paste(dir,lib,sep="/"))
  }
}
```

and get the following:

```[1] "ld-2.17.so"
[1] "ld-linux-x86-64.so.2"
[1] "libacl.so.1"
[1] "libacl.so.1.1.0"
[1] "libaio.so.1"
[1] "libaio.so.1.0.0"
[1] "libaio.so.1.0.1"
[1] "libanl-2.17.so"
[1] "libanl.so"
[1] "libanl.so.1"
[1] "libapol.so.4"
[1] "libapol.so.4.4"
[1] "libasm-0.172.so"
[1] "libasm.so.1"
[1] "libasound.so.2"
[1] "libasound.so.2.0.0"
[1] "libasprintf.so.0"
[1] "libasprintf.so.0.0.0"
[1] "libassuan.so.0"
[1] "libassuan.so.0.4.0"
[1] "libatk-1.0.so.0"
[1] "libatk-1.0.so.0.22810.1"
[1] "libattr.so.1"
[1] "libattr.so.1.1.0"
[1] "libaudit.so.1"
[1] "libaudit.so.1.0.0"
[1] "libauparse.so.0"
[1] "libauparse.so.0.0.0"
[1] "libavahi-client.so.3"
[1] "libavahi-client.so.3.2.9"
[1] "libavahi-common.so.3"
[1] "libavahi-common.so.3.5.3"
[1] "libavahi-glib.so.1"
[1] "libavahi-glib.so.1.0.2"
[1] "libbfd-2.27-34.base.el7.so"
[1] "libbind9.so.90"
[1] "libbind9.so.90.0.8"
[1] "libblkid.so.1"
[1] "libblkid.so.1.1.0"
[1] "libBrokenLocale-2.17.so"
[1] "libBrokenLocale.so"
[1] "libBrokenLocale.so.1"
[1] "libbtrfs.so.0"
[1] "libbtrfs.so.0.1"
[1] "libbz2.so"
[1] "libbz2.so.1"
[1] "libbz2.so.1.0.6"
[1] "libc-2.17.so"
[1] "libc.so"
Error in dyn.load(paste(dir, lib, sep = "/")) : 
  unable to load shared object '/usr/lib64/libc.so':
  /usr/lib64/libc.so: invalid ELF header
```

**Comment by paulsendavidjay** [comment]
> And you've reinstalled `rstan` since encountering the error?

Negative. I installed rstan once and had success in terminal invocation _ONLY AFTER EXPORTING DYN_LIB PATHS_. I've tried new sessions without the export and have same error as in RStudio.

I'm wondering why the bash export for dyn_lib works before running R, but neither the R nor RStudio (via session-conf file) do.

**Comment by paulsendavidjay** [comment]
I'm not sure if this is useful, but it's something. I try searching for specific version text

```
> for f in `sudo find /usr -name "libstdc++.so.6"`; do echo $f; grep -c GLIBCXX $f; done
/usr/lib64/libstdc++.so.6
2
/usr/local/lib64/libstdc++.so.6
3
> for f in `sudo find /usr -name "libstdc++.so.6"`; do echo $f; grep -c GLIBCXX_3.4.20 $f; done
/usr/lib64/libstdc++.so.6
0
/usr/local/lib64/libstdc++.so.6
2
```
showing that this version is not in `/usr/lib64/libstdc++.so.6` but is in `/usr/local/lib64/libstdc++.so.6`

**Comment by paulsendavidjay** [comment]
@ode33 please let me know your thoughts

I did the following based on the string search for GLIBCXX & GLIBCXX_3.4.20 in the preceding comment.

```
# copy file on which we will make changes just in case
cp /lib64/libstdc++.so.6 ~/lib64_libstdc++.so.6 

# rename current lib - 
sudo mv /lib64/libstdc++.so.6 /lib64/libstdc++.so.6_orig

# create sym link in the dir where 'GLIBCXX_3.4.20' was not found in libstdc++.so.6 file 
# (location that RStudio seems to be using) 
# to the libstdc++.so.6 file in which it was 
sudo ln -s /usr/local/lib64/libstdc++.so.6 /lib64/libstdc++.so.6

# undo if necessary
# not run 
# rm /lib64/libstdc++.so.6
# not run 
# mv /lib64/libstdc++.so.6_orig /lib64/libstdc++.so.6
```
and got the following results in RStudio
```{r}
Restarting R session...

> library(rstan)
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.18.2, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
```

**Comment by ghost** [comment]
Hooray?

**Comment by paulsendavidjay** [comment]
I guess? I don't what other impacts this change might have. These kinds of issues are not my bag.

**Comment by ghost** [comment]
There may be a more elegant approach, I create symlinks all the time for these kinds of linkages, so this seems fine to me. Others may disagree.
