### ISSUE TITLE
sampling() throws MCMC ESS warnings even when algorithm="Fixed_param"

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#658]
These warnings shouldn't be thrown when just simulating data using `algorithm="Fixed_param"`.

**Comment by bob-carpenter** [comment]
Do the errors arise because the parameters don't vary across iterations?  If so, I agree they should be suppressed.

**Comment by jgabry** [comment]
Yeah I think so. Since “Fixed_param” turns off MCMC, I think the diagnostics that expect Markov chains would indicate problems that aren’t actually problems.
