### ISSUE TITLE
clarify exceptions in interfacing with external C++ code doc

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#663]
#### Summary:

Based on [discussion on Discourse](https://discourse.mc-stan.org/t/lu-decomposition-determinant-of-sparse-asymmetric-matrix/9088/11), the [vignette on external C++ code](https://mc-stan.org/rstan/articles/external.html) should have this text added somewhere:

> The way the MCMC samplers are configured, if there is an exception thrown and it is std::domain_error, it will treat that iteration as a rejection but as a recoverable error: set that iteration’s log probability value to 0 and move to the next iteration. If there’s an std::invalid_argument thrown, MCMC terminates. We treat these as non-recoverable, user programming errors.

**Comment by bgoodri** [comment]
added
