### ISSUE TITLE
how to suppress all output?

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/rstan#665]
#### Description:
When I run `sampling(...)` then I always get something like,

```
SAMPLING FOR MODEL 'unidim_ll' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 0.000205 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 2.05 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 

```

I've tried all the sampling arguments suggested in the man page with no success.

#### Expected Output:
I'm running `sampling()` inside of testthat. Is there any way to suppress all output?

**Comment by jgabry** [comment]
Does setting `refresh=0` work? We need to make that more prominent in the doc. It's hiding in the doc for the `...` arguments to the `stan()` function, so it can be hard to find.

**Comment by jpritikin** [comment]
Yeah, works great! Thanks.

**Comment by jpritikin** [comment]
Oops, no, that option only works in interactive mode. Is there a way to suppress output when the script runs noninteractively?

**Comment by jgabry** [comment]
Interesting, I didn’t realize that wouldn’t work in non-interactive settings, will look into that. If refresh=0 doesn’t work then maybe you can wrap the call to Stan inside of capture.output?

**Comment by jpritikin** [comment]
Yeah, I guess. It's not a big deal, just cosmetic. I guess you can close this issue, or leave it open. Up to you.
