### ISSUE TITLE
Error in compile code following Rethinking textbook

### ISSUE THREAD

**Issue by Seanlove89** [stan-dev/rstan#668]
library(rethinking)
data("reedfrogs")
d <- reedfrogs

make the tank cluster variable
d$tank <- 1:nrow(d)

fit
m12.2 <- map2stan(
alist(
surv ~ dbinom( density , p ) ,
logit(p) <- a_tank[tank] ,
a_tank[tank] ~ dnorm( a , sigma ) ,
a ~ dnorm(0,1) ,
sigma ~ dcauchy(0,1)
), data=d , iter=200 , chains=4 )

I am getting an error below

Error in sink(type = "output") : invalid connection
In addition: Warning message:
In system(cmd, intern = !verbose) :
running command 'C:/PROGRA1/R/R-361.0/bin/x64/R CMD SHLIB file1a90554e2a28.cpp 2> file1a90554e2a28.cpp.err.txt' had status 1
Error in map2stan(alist(surv ~ dbinom(density, p), logit(p) <- a_tank[tank], :
Something went wrong, when calling Stan. Check any debug messages for clues, detective.
invalid connection

R version 3.6

#######################################################
The computer is a Lenovo make core i7, v510 series. operating system windows 10 64 bits

I tried to follow comments above but failing because mine has
Makevars.win.gcc3

**Comment by mcol** [comment]
Shouldn't this be reported to https://github.com/rmcelreath/rethinking?
