### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by SebAtWork** [stan-dev/rstan#673]
#### Summary:
Please provide a short summary (no more than a sentence or two).
I am running into a bunch of errors when trying to run the basic rstan example from the quick start guide.

#### Description:
Describe the issue as clearly as possible.
I receive the error:
```
Error in Compile Code(f, code, language = language, verbose = verbose): 
Compilation ERROR, function(s)/method(s) not created! Error in .shlib _internal(commandArgs(TRUE)):
c++14 standard requested but CXX14 is not defined
Calls: <Anonymous> -> .shlib_internal
Execution halted
In addition: warning message:
In system(cmd, intern =! Verbose) :
                Running command ‘C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file16c449079df.cpp 2> file16c449079df.cpp.
Err.txt’ had status 1
Error in sink(type = “output”) : invalid connection
```

I have checked many forums, such as [569](https://github.com/stan-dev/rstan/issues/569), [633](https://github.com/stan-dev/rstan/issues/633) and [this forum](https://discourse.mc-stan.org/t/compilation-error-please-help/9095), but none of these solutions have been working.

When I run `Sys.getenv("BINPREF")` and `Sys.getenc("R_MAKEVARS_USER")`, they return as empty quotation marks, but I can get the first command to temporarily return `C:/Rtools/mingw_$(WIN)/bin/` until I close Rstudio by running 
```
Sys.setenv(PATH = paste("C:/Rtools/bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")
```
I have also tried to change the Makevars and Makevars.win files with various lines, but it didn't do anything. I was just opening the makevar files in the notes application, so maybe I wasn't editing them properly? This is also all on a laptop that isn't connected to the internet, so all of the packages were installed via USB, if that makes a difference.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.
```
// saved as 8schools.stan
data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
```

```
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))

fit <- stan(file = '8schools.stan', data = schools_dat)
```

This is just the first example from the rstan start guide.
#### Current Output:
If applicable, any relevant output from RStan.

NA

#### Expected Output:
If applicable, the output you expected from RStan.

It should return an object called 'fit' instead of a bunch of errors.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.18.2
#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.6.0
#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Windows 7 (it's a work computer)

**Comment by mehrdadfr** [comment]
Hi,
You may remove rstan and follow this page. I did and it worked.

https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows

Except, install.packages("rstan", type = "source") didn't work so I installed without the option: install.packages("rstan")

**Comment by bgoodri** [comment]
If you are going to install RStan from source on Windows (not recommended) you have to configure R to know what compiler to use under the C++14 standard by executing
https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows#configuration
