### ISSUE TITLE
web documentation still at 2.17.3

### ISSUE THREAD

**Issue by mcol** [stan-dev/rstan#674]
#### Summary:
The `rstan` webpage still reports 2.17.3 as the current version (top left corner):
http://mc-stan.org/rstan/index.html

#### Expected output:

The whole site should be rebuilt for 2.19.2, as for example under http://mc-stan.org/rstan/articles/index.html I can't find the new SBC vignette, which is instead available on the CRAN page.

**Comment by bob-carpenter** [comment]
Should we instead just get rid of all links to doc and versions?  

We've never been able to keep the links up to date with our releases because the releases are so ad hoc and disconnected from the web site.

**Comment by mcol** [comment]
This has been updated at some point, so this can be closed.

**Comment by jgabry** [comment]
Thanks for closing. That was my fault for not updating the website until somewhat recently. Updating the R package websites is actually something that we could probably automate and have it triggered by a release. I’ve been meaning to try to set that up for a while.
