### ISSUE TITLE
Rstan 2.19.2 slower than 2.18.1

### ISSUE THREAD

**Issue by JustinCCYap** [stan-dev/rstan#676]
I have recently noticed that my tests take longer to run and it appears to be due to the latest version of rstan (2.19.2). To verify this, I ran some of our Stan code with versions 2.18.1 and 2.19.2 for 10 different seeds, and observed that the latest version was consistently running around 10% slower than the previous version with 2 chains and 200 iterations. To minimise measurement noise I ran the calculations from safe mode in Windows 10. My R code is below along with two CSV attachments containing data, which should provide a runnable example. I assume this is something that would concern stan developers and users who care about performance, as the difference in run time could be hours with larger examples?

```
data <- list(C = 3L, R = 380L, RS = 3040L, V = 13,
             prior_mean = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
             prior_sd = c(5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5))

data$X <- array(c(as.matrix(read.csv("xdata.txt"))), dim = c(3040, 3, 13))
data$Y <- read.csv("ydata.txt")[[1]]
data$S <- rep(8, 380)

options(mc.cores=parallel::detectCores())

library(rstan)
stan.model <- stan_model("hb.txt")
result <- sampling(stan.model, data = data,
                      chains = 2, iter = 200,
                      control = list(max_treedepth = 10,
                                     adapt_delta = 0.8),
                      init = function () list(L_omega = diag(13)))
```

[ydata.txt](https://github.com/stan-dev/rstan/files/3429043/ydata.txt)
[hb.txt](https://github.com/stan-dev/rstan/files/3429044/hb.txt)
[xdata.txt](https://github.com/stan-dev/rstan/files/3429045/xdata.txt)

**Comment by bob-carpenter** [comment]
Thanks for reporting.  We definitely care about 10% performance regressions. 

When comparing performance, we recommend using the same seeds and initializations and running long enough to ensure we've converged to the right answer in both cases (which typically requires more than 200 iterations total).  [edit: I misread the model initially---there isn't a hierarchical component here, so it should be OK to fit if the transform of `beta` is OK.]

I'm including the model (`hb.txt`) inline here for convenience:

```
data {
    int<lower=2> C;
    int<lower=1> R;
    int<lower=1> S[R];
    int<lower=1> RS;
    int<lower=1> V;
    int<lower=1,upper=C> Y[RS];
    matrix[C, V] X[RS];
    vector[V] prior_mean;
    vector[V] prior_sd;
}

parameters {
    vector<lower=0>[V] sigma;
    row_vector[V] theta;
    cholesky_factor_corr[V] L_omega;
    matrix[V, R] standard_normal;
}

transformed parameters {
    matrix[V, V] L_sigma;
    matrix[R, V] beta;

    L_sigma = diag_pre_multiply(sigma, L_omega);
    beta = rep_matrix(theta, R) + (L_sigma * standard_normal)';
}

model {
    int rs = 1;
    vector[V * R] vector_normal;

    sigma ~ gamma(1, 1);

    theta ~ normal(prior_mean, prior_sd);
    L_omega ~ lkj_corr_cholesky(4);

    vector_normal = to_vector(standard_normal);
    vector_normal ~ normal(0, 1);

    for (r in 1:R)
    {
        for (s in 1:S[r])
        {
            Y[rs] ~ categorical_logit(X[rs] * to_vector(beta[r]));
            rs += 1;
        }
    }
}
```

You can move calculation of `L_sigma` and `

**Comment by JustinCCYap** [comment]
Thanks @bob-carpenter, it looks like your last line "You can move calculation of L_sigma and `" is incomplete?

Why do you say there isn't a hierarchical component? I consider `beta` to be on a "lower level" to `theta`, `sigma`, which are higher up the hierarchy? Note that I include a variable called `standard_normal` in the calculation of `beta`.

I will run with more iterations until convergence and report back on the results.

**Comment by bob-carpenter** [comment]
Very poor editing on my part.

> Why do you say there isn't a hierarchical component?

I should've said there wasn't a centered hierarchical component.  

> it looks like your last line "You can move calculation of L_sigma and `" is incomplete?

I was going to say to generated quantities, but then I noticed that `beta` is used in the model.   I don't want to go edit again now or the comments will be out of context.

**Comment by JustinCCYap** [comment]
This issue has been confirmed by others on the Stan forum and it appears there is a pull request that will fix this:

https://discourse.mc-stan.org/t/rstan-2-19-2-slower-than-2-18-1/9841/7
https://github.com/stan-dev/math/pull/1255

**Comment by bgoodri** [comment]
This is fixed in Stan Math.
