### ISSUE TITLE
rstan windows installation wiki - proposed edit

### ISSUE THREAD

**Issue by stemangiola** [stan-dev/rstan#679]
#### Summary:
rstan windows installation wiki - proposed edit

#### Description:
On windows 10 the Configuration commands should be changed to

dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars.win")
if (!file.exists(M)) file.create(M)
cat("\nCXX14FLAGS=-O3 -march=native",
    "CXX14=$(BINPREF)g++ -m$(WIN) -std=c++1y -march=native -mtune=native",
    "CXX11FLAGS=-O3 -march=native",
    file = M, sep = "\n", append = TRUE)

Considering [this issue](https://github.com/stan-dev/rstan/issues/633)

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
Same error in the issue

#### Expected Output:
No error in installing

**Dependencies**
install.packages("BiocManager")
BiocManager::install("edgeR")
BiocManager::install("sva")
devtools::install_github('stemangiola/tidyTranscriptomics')

**Install package**
devtools::install_github('stemangiola/ppcSeq')

#### RStan Version:
2.19.2

#### R Version:
3.6.0

#### Operating System:
Windows 10

**Comment by bgoodri** [comment]
I changed the wiki and we'll just have to see whether that causes more problems than it fixes.
