### ISSUE TITLE
Segfault using log_sum_exp function in v2.19.2

### ISSUE THREAD

**Issue by mwmclean** [stan-dev/rstan#689]
#### Summary:
Code that uses the log_sum_exp function inside a user-defined lpmf function now segfaults for `rstan v2.19.2`, but runs successfully for earlier versions of `rstan`.

#### Description:
The stan code in the attached zip file used to fit a rank-ordered logit model with ties (briefly described [here](https://www.displayr.com/tricked-vs-rank-ordered-logit/)). Since upgrading to `rstan v2.19.2`, the code now segfaults. I attempted to debug with gdb which says the segfault occurred in ` Eigen::internal::redux_impl<Eigen::internal::scalar_max_op<double, double>, Eigen::internal::redux_evaluator<Eigen::Matrix<double, -1, 1, 0, -1, 1> >, 3, 0>::run(Eigen::internal::redux_evaluator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > const&, Eigen::internal::scalar_max_op<double, double> const&) ()` 
or 
`stan::math::log_sum_exp<-1,1>` 
depending on which OS I use.

I have confirmed the issue occurs with other data (not attached) that worked with older `rstan` versions. I additionally tried to define my own log-sum-exp function (`logSumExp` in `rol.stan`), but when I switch to that, I get
```
Chain 1: Unrecoverable error evaluating the log probability at the initial value.
Chain 1: Exception: Exception: Exception: []: accessing element out of range. index 1 out of range; expecting index to be between 1 and 0; index position = 1x  (in 'model950417a7916_rol' at line 15)
  (in 'model950417a7916_rol' at line 39)
  (in 'model950417a7916_rol' at line 178)
```
[rol.zip](https://github.com/stan-dev/rstan/files/3553835/rol.zip)

#### Reproducible Steps:
```
library(rstan)
tdir <- tempdir()
unzip("/path/to/rol.zip", exdir = tdir)
sm <- stan_model(file.path(tdir, "rol.stan"))
load(file.path(tdir, "mdSegfault.RData"))
sampling(sm, stan.dat, chains = 1)
```

#### Current Output:
If applicable, any relevant output from RStan.
```
SAMPLING FOR MODEL 'rol' NOW (CHAIN 1).

Process R exited abnormally with code 5
```

#### Expected Output:
Sampling occurs without a segfault.

#### RStan Version:
2.19.2

#### R Version:
1) R Under development (unstable) (2019-03-26 r76272)
2) R version 3.5.1 (2018-07-02)
3) R version 3.6.1 (2017-01-27)

#### Operating System:
1) Windows 10
2) Debian buster
3) Ubuntu 14.04.5 LTS trusty

**Comment by rok-cesnovar** [comment]
This needs to be handled in Stan Math, opened an issue there https://github.com/stan-dev/math/issues/1416

**Comment by bgoodri** [comment]
Thanks @rok-cesnovar
