### ISSUE TITLE
Inconsisent and odd optimizing results with Nesterov

### ISSUE THREAD

**Issue by ariddell** [stan-dev/rstan#71]
I'm getting some strange results using ``optimizing`` with the Nesterov algorithm.

The following code, run with ``Rscript`` yields some odd results. The two issues are (1) fixed random seed not yielding same results and (2) huge point estimate for sigma, should be ~ 1 but is 278.27842.

```
library(rstan)
stdnorm <- '
data {
  int N;
  real y[N];
}

parameters {
  real mu;
  real<lower=0> sigma;
}

model {
  y ~ normal(mu, sigma);
}
'

N <- 30
y <- rnorm(N)
sm <- stan_model(model_code = stdnorm)

results = c()
for (i in 1:100) {
    optim <- rstan:::optimizing(sm, data = list(N=N, y=y), algorithm = 'Nesterov', stepsize = 0.5, seed=12)
    results = c(results, optim)
}
print(results)
```
For example, buried in the results I get
```
$par
       mu     sigma 
 34.36915 278.27842 

$value
[1] -169.0886

$par
       mu     sigma 
 1.802399 60.074890 

$value
[1] -122.886

$par
         mu       sigma 
-0.07302237  0.92984243 
```

I'm using RStan 2.1.0 but I'm encountering a similar error in PyStan using stan-dev tip (or near tip).

**Comment by maverickg** [comment]
close this as this optimizer is not in stan.
