### ISSUE TITLE
Compilation error despite pkgbuild::has_build_tools(debug = TRUE) returns TRUE

### ISSUE THREAD

**Issue by schwa021** [stan-dev/rstan#710]
#### Summary:
New PC (Windows 10), new installation of Rstan (2.9.12) and R (3.6.1).

Install seemed to go smoothly, but...

Compile error for a model that was running on my old PC (win 7, Rstan 2.18.12, R3.6.0).

#### Description:
New install of Rstan on a new computer. 

Followed all isntructions on Rstan getting started page, including installing Rtools. 

I then confirmed C++ toolchain (disclaimer - I don't even know what that is) using pkgbuild::has_build_tools(debug = TRUE) which returned TRUE

I then tried to run a model that had been successfully running on my old computer, and received the compile error shown below.

I tried the solution proposed here: https://github.com/stan-dev/rstan/issues/633, which worked before. But, this time it did not work.

I found a similar report from July, but the solution there was to install old versions of R, Rstan. I'm hoping to actually figure out what's going wrong rather than backpedaling.

#### Reproducible Steps:
Running a model using the "rethinking" package. As noted above, model runs fine in 3.6.0 on my old computer.

#### Current Output:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/Users/mschwartz/Documents/R/win-library/3.6/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/BH/include/boost/random/detail/int_float_pair.hpp:26,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/BH/include/boost/random/exponential_distribution.hpp:27,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/BH/include/boost/random/gamma_distribution.hpp:25,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/StanHeaders/include/stan/math/prim/mat.hpp:292,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/StanHeaders/include/stan/math/rev/mat.hpp:12,
                 from C:/Users/mschwartz/Documents/R/win-library/3.6/StanHeade
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.1/bin/x64/R CMD SHLIB file721c4146600a.cpp 2> file721c4146600a.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

#### RStan Version:
2.19.12

(rethinking version 1.91)

#### R Version:
3.61

#### Operating System:
Windows 10

**Comment by schwa021** [comment]
Sometimes the solutions are simple, and staring right at you.

After trying all the "fancy" changes to my Makevars file that were suggested in countless other similar threads, I started from scratch and followed *ALL* RStan getting started instructions. This included paying close attention to the warning:

"_However, be advised that setting the optimization level to O3 may cause problems for packages besides RStan and that, in rare cases, specifying -march=native -mtune=native may cause Stan programs to not work_"

I went into my Makevars file and deleted the -march=native and -mtune=native and things worked.

I hope this helps someone. I have to say that while I *LOVE* RStan, I am constantly baffled at how complicated it is to get it to simply install and run on a windows machine. For non-linux/non-developer/simple-scientist folks like me, this is a bit of a barrier to use.

**Comment by jgabry** [comment]
> I hope this helps someone. I have to say that while I _LOVE_ RStan, I am constantly baffled at how complicated it is to get it to simply install and run on a windows machine. For non-linux/non-developer/simple-scientist folks like me, this is a bit of a barrier to use.

Thanks for sharing and sorry for the hassle. I agree it can be complicated. We're definitely looking for ways to make it easier!
