### ISSUE TITLE
10x performance drop in R/3.6.1 compiled with gcc 9.2.0 vs R/3.6.0 compiled with gcc 7.3.0

### ISSUE THREAD

**Issue by wresch** [stan-dev/rstan#726]
#### Summary:
rstan models run considerably slower in our new R/3.6.1 install compiled with gcc/9.2.0 vs the previous R/3.6.0 compiled with gcc/7.3.0

#### Description:
I maintain R on our cluster. I recently compiled a new version of R (3.6.1) that also uses a newer compiler (gcc 9.2.0 vs 7.3.0 in the previous installs). A user reported that a package using rstan ran considerably slower (see https://github.com/CCS-Lab/hBayesDM/issues/115). I verified that this was due to rstan by running the hepatitis and rats examples with 3000 iterations:

```
            R 3.6.0 / gcc 7.3.0     R 3.6.1 / gcc 9.2.0
hepatitis:        7.4s                   103.3s              14x
rats:             1.7s                    19.6s              11x
```

The attached tarball contains code and output (including `sessionInfo()` calls).

BLAS in both cases is intel MKL.

Not sure if this is an issue with rstan, stan, or our current install. Generic R benchmarks are within normal range.  Have you guys noticed any similar issues? Do you have any suggestions on how we could fix this?

#### Reproducible Steps:
Code run is attached, along with output.

#### RStan Version:
rstan version is 2.19.2 in both installs

#### R Version:
3.6.0 and 3.6.1

#### Operating System:
CentOS 7.5

[rstan_tests.tar.gz](https://github.com/stan-dev/rstan/files/4003136/rstan_tests.tar.gz)

**Comment by bob-carpenter** [comment]
Thanks for reporting. I can conform this is not a problem for CmdStan on the develop branch (at least using Mac OSX Homebrew installs of gcc).

Using the latest CmdStan from develop with -O3 optimization, using seed=1234 for each run, I get

Compiler                                               |   Rats timing
-------------------------------------|----------
g++ 7.5.0 (Homebrew GCC 7.5.0)       | 0.48s
g++-9.2.0 (Homebrew GCC 9.2.0_2)  |    0.41s

Performance varies by .02s across runs.

I don't think BLAS is being used in Stan unless you somehow customized Eigen to use BLAS.

Are you sure the new version is being compiled using `-O3` optimization (`O=3` in our makefiles), as that's about the performance gap we'd expect between `-O0` and `-O3`?

**Comment by wresch** [comment]
🤦‍♂ 

It's not you - it's me.  We use environment modules for the different compilers we have. the module for the new gcc sets `CXXFLAGS` to fix the c++ abi version. the previous gcc module did not set `CXXFLAGS`. when compiling R autoconf picked up CXXFLAGS and used it wholesale thus overriding the default of `-O2 -g` - hence i compiled a lot of stuff with default optimization instead of `-O2`. I modified the `R/etc/Makeconf` file to add `-O2` back in and the runtimes for rstan are back where they should be.

Thanks for pointing me in the right direction.
