### ISSUE TITLE
segfault: 'memory not mapped'

### ISSUE THREAD

**Issue by jszhao** [stan-dev/rstan#728]
#### Summary:
I run the eight schools example, and got error:

 *** caught segfault ***
address 0x30, cause 'memory not mapped'

#### Description:
I run R 3.6.2 on a FreeBSD workstation. I install rstan package through `install.packages("rstan")`. when I test the installed rstan using the eight schools example. It threw the above error.

#### Reproducible Steps:
The steps are following:

https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

#### Current Output:
 *** caught segfault ***
address 0x30, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE)
 2: .getModulePointer(x)
 3: new("Module", .xData = <environment>)$stan_fit4modelc994e050949_8schools
 4: new("Module", .xData = <environment>)$stan_fit4modelc994e050949_8schools
 5: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
 6: eval(call("$", mod, paste("stan_fit4", model_cppname, sep = "")))
 7: object@mk_cppmodule(object)
 8: .local(object, ...)
 9: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
10: sampling(sm, data, pars, chains, iter, warmup, thin, seed, init,     check_data = TRUE, sample_file = sample_file, diagnostic_file = diagnostic_file,     verbose = verbose, algorithm = match.arg(algorithm), control = control,     check_unknown_args = FALSE, cores = cores, open_progress = open_progress,     include = include, ...)
11: stan(file = "8schools.stan", data = schools_dat)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

#### RStan Version:
> packageVersion("rstan")
[1] '2.19.2'

#### R Version:
> R.version.string
[1] "R version 3.6.2 (2019-12-12)"

#### Operating System:
# uname -a
FreeBSD xw6600 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: amd64-portbld-freebsd12.0 (64-bit)
Running under: FreeBSD xw6600 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

Matrix products: default
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.2

**Comment by bgoodri** [comment]
This is usually due to conflicting compilers and / or compilation flags between Rcpp (or possibly RcppEigen) and rstan.

**Comment by jszhao** [comment]
> This is usually due to conflicting compilers and / or compilation flags between Rcpp (or possibly RcppEigen) and rstan.

I have installed the R, and the only package I installed is rstan, which also install all dependencies. So, I don't know what's the problem. 

The default compiler for C/C++ in FreeBSD is clang compiler, however, I set CC and CXX in Makevars to gcc9 and g++9.

**Comment by bgoodri** [comment]
I think you will be fine if you (re)install Rcpp with g++-9.

**Comment by jszhao** [comment]
> 
> I think you will be fine if you (re)install Rcpp with g++-9.

How to do that? In R, I just install Rcpp with `install.packages("Rcpp")， then Rcpp would be installed. How to specify the compiler?

Thanks!

**Comment by bgoodri** [comment]
It should be based on whatever you have for CXX or CXX11 in ~/.R/Makevars .

**Comment by jszhao** [comment]
> 
> It should be based on whatever you have for CXX or CXX11 in ~/.R/Makevars .

I have the ~/.R/Makevars as following:
```
CXX=g++9
CC=gcc9
CXX14FLAGS=-O3 -march=native -mtune=native
CXX14FLAGS += -fPIC
```
And the I installed the rstan, and it also installed Rcpp and all other dependencies.

**Comment by bgoodri** [comment]
Possibly need the same CXXFLAGS as CXX14FLAGS.

**Comment by jszhao** [comment]
> 
> Possibly need the same CXXFLAGS as CXX14FLAGS.

I tried the following Makevars, the same error:
```
CXX=g++9
CC=gcc9
CXX14FLAGS=-O3 -march=native -mtune=native
CXX14FLAGS += -fPIC
CXXFLAGS=-O3 -march=native -mtune=native
CXXFLAGS += -fPIC
```

**Comment by jszhao** [comment]
> 
> 
> This is usually due to conflicting compilers and / or compilation flags between Rcpp (or possibly RcppEigen) and rstan.

You are right.

I think I get the reason of the error. I set CXX to g++9 in Makevars, and install `Rcpp` and `rstan` and others. However, function `stan()` seems to compile the model using the variables in Makeconf located at /usr/local/lib/R/etc/ on my FreeBSD. In the file, the CXX is set to c++, i.e., clang++. I don't know why `stan()` dose not use the setting in `.R/Makevars`.

**Comment by jszhao** [comment]
After removing the .R/Makevars, and reinstalled rstan and its dependencies, now rstan works.

**Comment by t-pollington** [comment]
> After removing the .R/Makevars, and reinstalled rstan and its dependencies, now rstan works.

Unfortunately that followed by `install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")), dependencies = TRUE)` didn't work for me. So I'm going to try `cmdstanr` instead as mentioned [here](https://discourse.mc-stan.org/t/persistent-error-message-error-in-unserialize-socklist-n-error-reading-from-connection/24184/2)

**Comment by andrjohns** [comment]
Which part didn't work? Was there a particular error? Happy to help debug if you want

**Comment by t-pollington** [comment]
Hi @andrjohns, really sorry but realised I got a different fault (`Error in unserialize(socklist[[n]]) : error reading from connection`) so this isn't related.
