### ISSUE TITLE
No Error messages When Compiling Stan Model OSX Catalina

### ISSUE THREAD

**Issue by severianovillarruel** [stan-dev/rstan#735]
#### Summary:
When I try to compile a STAN model I get no error messages or any output at all.

#### Description:
Running the following code 
```
x <- stan_model(model_code='xyz')
```
produces no errors at all even though the code is nonsense.
Also there is no output: `x` is `NULL`.

#### Expected Output:
An error, eg
```
PARSER EXPECTED: whitespace to end of file
```

#### RStan Version:
The version of RStan you are running: 2.19.2

#### R Version:
R version 3.6.1

#### Operating System:
Your operating system (e.g., OS X 10.15.1)

**Comment by petrelharp** [comment]
There are several people in the class I am teaching with this same problem, btw.

**Comment by petrelharp** [comment]
ps. Stan will correctly compile models if they do not have errors - the problem is that errors are not shown.  This might be related to #721 .

**Comment by petrelharp** [comment]
pps. The code above was run with `R --vanilla` in the terminal.

**Comment by petrelharp** [comment]
Perhaps this is fixed by installing from source, as described here:
 https://discourse.mc-stan.org/t/rstudio-rstan-not-showing-errors-warnings-on-macos-catalina/12732
... ?

**Comment by severianovillarruel** [comment]
Nice! This advice helped me out a lot! I am getting error messages now. Thanks

**Comment by petrelharp** [comment]
Thanks - confirmed that doing `install.packages("rstan", type="source")` cleared this up.
