### ISSUE TITLE
Error after updating to R to version 3.6.2

### ISSUE THREAD

**Issue by mfeddern** [stan-dev/rstan#736]
#### Summary:

Since the latest r upgrade (see version below) rstan is no longer able to initialize my sampler. My code ran fine as of November, I have since upgraded my r and it no longer functions. Appears the r data list is no longer the correct configuration for feeding variables to stan, but cannot identify what the problem is

I have tried: installing rstan from the source, updating my xcode, reinstalling r, downgrading r and rstan

#### Description:
Describe the issue as clearly as possible.

I am now receiving the following error, with what formerly functioned: 

Leads to the following error: 

Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int  (in 'model8d351eaea491_gpdfa' at line 2)

failed to create the sampler; sampling not done

#### Reproducible Steps:
I get the error everytime I run my code:

num_ts = max(df$ts) # time series
num_years = max(df$Year) # number of years
nKnots = 15 # number of knots for smooths
num_trends = 2# number of DFA trends
varIndx = NULL# variance equal or not
zscore = TRUE # yes, we should
iter = 4000 # mcmc iterations
chains = 1 # mcmc chains
control = list(adapt_delta = 0.99)

df = dplyr::group_by(df, ts) %>%
  dplyr::mutate(z = (y - mean(y,na.rm=T))/sd(y,na.rm=T)) %>%
  dplyr::select(-y)

y = df$z
yr = df$Year
ts = df$ts

knots = sort(pamk(yr, nKnots)$pamobject$medoids)
distKnots = as.matrix(dist(knots))
distAll = as.matrix(dist(c(1:num_years,knots)))
distKnots21 <- t(distAll[-seq_len(num_years), -seq(num_years + 1, ncol(distAll))])

model = "Src/Analysis/gpdfa.stan"

N = num_years
P = num_ts
K = num_trends # number of dfa trends
nZ = P * K - sum(1:K) + K

mat_indx = matrix(0, P, K)
start = 1
for (k in 1:K) {
  if (k == 1)
    mat_indx[, k] = (1:nZ)[start:(start + P - k)]
  if (k > 1)
    mat_indx[-c(0:(k - 1)), k] = (1:nZ)[start:(start + P - k)]
  start = start + (P - k + 1)
}

row_indx = matrix((rep(1:P, K)), P, K)[which(mat_indx > 0)]
col_indx = rep(1:K, times = P:(P - K + 1))
row_indx_z = matrix((rep(1:P, K)), P, K)[which(mat_indx == 0)]
col_indx_z = matrix(sort(rep(1:K, P)), P, K)[which(mat_indx == 0)]
row_indx_z = c(row_indx_z, 0, 0)# +2 zeros for making stan ok with data types
col_indx_z = c(col_indx_z, 0, 0)# +2 zeros for making stan ok with data types
nZero = length(row_indx_z)

if (is.null(varIndx))
  varIndx = rep(1, P)
nVariances = length(unique(varIndx))

row_indx_pos = matrix((rep(1:P, N)), P, N)[which(!is.na(y))]
col_indx_pos = matrix(sort(rep(1:N, P)), P, N)[which(!is.na(y))]
row_indx_pos = ts
col_indx_pos = yr
n_pos = length(y)

data_list = list(
  N,
  P,
  K,
  nZ,
  y,
  row_indx,
  col_indx,
  nZero,
  row_indx_z,
  col_indx_z,
  row_indx_pos,
  col_indx_pos,
  n_pos,
  nKnots,
  distKnots,
  distKnots21
)
pars <- c("x", "Z", "sigma", "pred", "log_lik")

mod = rstan::stan(
  data = data_list,
  pars = pars,
  file = model[[1]],
  chains = chains,
  iter = iter,
  control = control
)

#### Current Output:
If applicable, any relevant output from RStan.
Leads to the following error: 

Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int  (in 'model8d351eaea491_gpdfa' at line 2)

failed to create the sampler; sampling not done

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
rstan version 2.19.2

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
rversion: 3.6.2

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
mac OS 10.13.6 (high sierra)

**Comment by mfeddern** [comment]
Finally found success with the r 3.5 binary branch to downgrade (I overshot the first time and accidentally installed 3.3). That being said this problem still stands that there is something not compatible between the new upgrade of r!

**Comment by bob-carpenter** [comment]
@bgoodri --- I have my old Mac notebook if that'd help debugging.  I think it may still be on High Sierra---I never upgraded it to Catalina.

**Comment by bob-carpenter** [comment]
@mfeddern : thanks for reporting back about success with 3.5.  I'm not sure how many configs of Macs we have to test.  There was a huge mess with Catalina when Apple shut down our RTools installer, which made it easier for users to install a compatible C++ toolchain.

**Comment by mfeddern** [comment]
@bob-carpenter I came across some mentions of the Catalina issues when I was trying to find a solution. I am realizing now that this happened to me both on High Sierra and on Catalina -- as I tried both my desktop and lap top for that reason (both macs). Just figured I would mention it in case its helpful.  I found success with r 3.5 on my lap top with Catalina!

**Comment by bgoodri** [comment]
For anyone who might be reading this, the installer at

https://github.com/rmacoslib/r-macos-rtools/releases/

can apparently be run if you download it and then

> CTRL+right click on the file, then clicking “Open” will get the installer going

**Comment by SteveBronder** [comment]
Oddly I have R 3.6.1 and mac os sierra with everything running fine

Did you try reinstalling BH, Rcpp, RcppEigen etc? Those usually need to be recompiled after an update to R

**Comment by mfeddern** [comment]
Yes, everything was recompiled -- I had no issues with R 3.6.1 the issue arose when I installed 3.6.2. only reason I downgraded to 3.5 was because I was having a hard time finding the binary for 3.6.1 for mac
