### ISSUE TITLE
Error trying to run model file written on other computer

### ISSUE THREAD

**Issue by SchollJ** [stan-dev/rstan#737]
#### Summary:
Stan code written on other Mac does not run, but runs when copied to new file.

#### Description:
I have been trying to run stan code that worked on another mac on a new mac that I've just set up. I keep getting the error: 
Error in dyn.load(libLFile) : 
  unable to load shared object '/var/folders/dx/wzlxnswn4_560w3k4272_m200000gn/T//RtmpxF1RR5/filea1a636307a0e.so':
  dlopen(/var/folders/dx/wzlxnswn4_560w3k4272_m200000gn/T//RtmpxF1RR5/filea1a636307a0e.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /var/folders/dx/wzlxnswn4_560w3k4272_m200000gn/T//RtmpxF1RR5/filea1a636307a0e.so
  Reason: image not found

I installed RStan again, but this did not help. What fixed the problem was copying the text of the Stan file into a new document and saving it again. 

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.19.2

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.6.2

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
OS X 10.14.6

**Comment by bob-carpenter** [comment]
Compiled Stan models will only work on binary compatible platforms, so it's usually best to recompile.  That's probably what a new copy of the Stan program caused to happen.

I'm going to close this issue, but feel free to reopen if you can provide a way for us to reproduce the problem.
