### ISSUE TITLE
Compilation Error with StanHeaders: no such file or directory

### ISSUE THREAD

**Issue by smonto2** [stan-dev/rstan#738]
#### Summary:
Compilation error when running the main `stan` function. I receive an error that several files used by StanHeaders cannot be found (even when they exist).

#### Description:
I am a new Stan user and had no problem with installation of all dependencies. However, when I try to run a simple "Hello, world" type example ([found here](https://mc-stan.org/workshops/halifax2017/exercise_2.html)), I receive a compilation error that I put under the current output section.

I have messed with changing the `Makevars.win` file and tried several others alternatives I found within the issues requests, but to no avail. From the output, I believe the issue to be related somehow to the file name having a space, but Program Files should be the standard in all of Windows file naming, how would this be an issue?

#### Reproducible Steps:
```
remove(list = ls())
library(rstan)

hello.stan <- 'data {
  int<lower=0> N;
  vector[N] y;
}
parameters {
  real mu;
  real<lower=0> sigma;
}
model {
  y ~ normal(mu, sigma);
}
'

N <- 100
y <- rnorm(N, mean = 5, sd = 10)
stanfit <- stan(model_name = hello.stan, data = list(N, y))
```

#### Current Output:
`Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created!`
`g++.exe: error: Files/R/R-3.6.2/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory`
`g++.exe: error: Files/R/R-3.6.2/library/StanHeaders/include: No such file or directory`
`g++.exe: error: Files/R/R-3.6.2/library/RcppEigen/include: No such file or directory`
`make: *** [C:/PROGRA~1/R/R-3.6.2/etc/x64/Makeconf:215: file4f647a08385b.o] Error 1`

#### RStan Version:
2.19.2

#### R Version:
R version 3.6.2 (2019-12-12)

#### Operating System:
Windows 10 Pro, 64 Bit, Version 1809

**Comment by bgoodri** [comment]
At the moment, you need to do
```
install.packages(c(
"https://win-builder.r-project.org/DZFx7zc08XoW/StanHeaders_2.19.1.zip", 
"https://win-builder.r-project.org/z7YZVs4x6LAX/rstan_2.19.3.zip"),
repos = NULL)
```

**Comment by johnsonrd58** [comment]
i upgraded rstan yesterday and get this error

Error in compileCode(f, code, language = language, verbose = verbose) : Compilation ERROR, function(s)/method(s) not created! g++.exe: error: Files/R/R-3.6.2/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory g++.exe: error: Files/R/R-3.6.2/library/StanHeaders/include: No such file or directory g++.exe: error: Files/R/R-3.6.2/library/RcppEigen/include: No such file or directory make: *** [C:/PROGRA~1/R/R-3.6.2/etc/x64/Makeconf:215: file15445ae679f.o] Error 1

**Comment by bgoodri** [comment]
I think you just need to get StanHeaders and rstan back in sync with

remove.packages(c("StanHeaders", "rstan"))
file.remove(".RData")
# restart R
install.packages(c("StanHeaders", "rstan"))

**Comment by matiasandina** [comment]
I am still facing this issue, doing the install together as suggested does not solve this.
I get

```
Compilation ERROR, function(s)/method(s) not created! 
g++.exe: error: 
Files/R/R-3.6.3/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
g++.exe: error: 
Files/R/R-3.6.3/library/StanHeaders/include: No such file or directory
g++.exe: error: Files/R/R-3.6.3/library/RcppEigen/include: No such file or directory
```

All files exist StanHeaders and RcppEigen seem to have correct folder structure.

Info about my session/packages

If I do pkgbuild::check_compiler(TRUE) *before* trying rstan, I get

```
Trying to compile a simple C file
Running \
  "c:/PROGRA~1/R/R-36~1.3/bin/x64/Rcmd.exe" \
  SHLIB foo.c
c:/Rtools/mingw_64/bin/gcc  -I"c:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=core2 -c foo.c -o foo.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o foo.dll tmp.def foo.o -Lc:/PROGRA~1/R/R-36~1.3/bin/x64 -lR
 
[1] TRUE
```
If I try to do a simple model with rstan, I get 

```
Trying to compile a simple C file
Running \
  "c:/PROGRA~1/R/R-36~1.3/bin/x64/Rcmd.exe" \
  SHLIB foo.c
C:/Rtools/mingw_64/bin/gcc  -I"c:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG   -I"c:/Program Files/R/R-3.6.3/library/Rcpp/include/"  -I"c:/Program Files/R/R-3.6.3/library/RcppEigen/include/"  -I"c:/Program Files/R/R-3.6.3/library/RcppEigen/include/unsupported"  -I"c:/Program Files/R/R-3.6.3/library/BH/include" -I"c:/Program Files/R/R-3.6.3/library/StanHeaders/include/src/"  -I"c:/Program Files/R/R-3.6.3/library/StanHeaders/include/"  -I"c:/Program Files/R/R-3.6.3/library/rstan/include" -DEIGEN_NO_DEBUG  -D_REENTRANT  -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp  -std=c++1y         -O2 -Wall  -std=gnu99 -mtune=core2 -c foo.c -o foo.o
cc1.exe: warning: command line option '-std=c++1y' is valid for C++/ObjC++ but not for C
In file included from c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/Core:88:0,
                 from c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/Dense:1,
                 from c:/Program Files/R/R-3.6.3/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from <command-line>:0:
c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name 'namespace'
 namespace Eigen {
 ^
c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 namespace Eigen {
                 ^
In file included from c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/Dense:1:0,
                 from c:/Program Files/R/R-3.6.3/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from <command-line>:0:
c:/Program Files/R/R-3.6.3/library/RcppEigen/include/Eigen/Core:96:19: fatal error: complex: No such file or directory
 #include <complex>
                   ^
compilation terminated.
make: *** [c:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:208: foo.o] Error 1
Error: Failed to compile C code
```

Any advice ?


---

```
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics 
[3] grDevices utils    
[5] datasets  methods  
[7] base     

other attached packages:
[1] rstan_2.19.3        
[2] ggplot2_3.3.0       
[3] StanHeaders_2.21.0-1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        
 [2] rstudioapi_0.11   
 [3] magrittr_1.5      
 [4] tidyselect_1.0.0  
 [5] munsell_0.5.0     
 [6] colorspace_1.4-1  
 [7] R6_2.4.1          
 [8] rlang_0.4.5       
 [9] fansi_0.4.1       
[10] dplyr_0.8.5       
[11] tools_3.6.3       
[12] parallel_3.6.3    
[13] pkgbuild_1.0.6    
[14] grid_3.6.3        
[15] gtable_0.3.0      
[16] loo_2.2.0         
[17] cli_2.0.2         
[18] withr_2.1.2       
[19] matrixStats_0.56.0
[20] assertthat_0.2.1  
[21] tibble_2.1.3      
[22] lifecycle_0.2.0   
[23] crayon_1.3.4      
[24] processx_3.4.2    
[25] gridExtra_2.3     
[26] purrr_0.3.3       
[27] callr_3.4.2       
[28] ps_1.3.2          
[29] inline_0.3.15     
[30] glue_1.3.2        
[31] compiler_3.6.3    
[32] pillar_1.4.3      
[33] prettyunits_1.1.1 
[34] scales_1.1.0      
[35] stats4_3.6.3      
[36] pkgconfig_2.0.3   
```

**Comment by matiasandina** [comment]
I have tried the suggested steps here

https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows#configuration

Although issues are closed, errors keep popping in every OS. It seems like we should keep them open if no definitive solution exists yet

**Comment by matiasandina** [comment]
I am posting this here for the record because people keep having issues.
The way I manage to solve it was to install specific StanHeaders version, which "magically" solves the issue for now.

if you already installed the packages, do:

```
remove.packages("rstan")
remove.packages("StanHeaders")
```
Close Rstudio and open it again. Run this install.

```
devtools::install_version("StanHeaders", version = "2.19.0", repos = "http://cran.us.r-project.org")
install.package("rstan")
```
```
```

**Comment by djb17** [comment]
> I am posting this here for the record because people keep having issues. The way I manage to solve it was to install specific StanHeaders version, which "magically" solves the issue for now.
> 
> if you already installed the packages, do:
> 
> ```
> remove.packages("rstan")
> remove.packages("StanHeaders")
> ```
> 
> Close Rstudio and open it again. Run this install.
> 
> ```
> devtools::install_version("StanHeaders", version = "2.19.0", repos = "http://cran.us.r-project.org")
> install.package("rstan")
> ```

I can confirm my issue with Eigen mentioned above was resolved with this approach. Hope we can get an actual fix soon.
