### ISSUE TITLE
update the NEWS file

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/rstan#746]
#### Summary:

The [NEWS file](https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/inst/NEWS) has the most recent version dated as `Sun July 7 2019`. There is no version listed next to the date. Every CRAN release should be included in the NEWS, with the version, and how or why the package is being updating.

**Comment by jgabry** [comment]
Going through old issues and just found this. I'm going to close since there are now 2020 entries to the NEWs file but I just opened a related issue #848 about improving the quality of the contents of the NEWS file.
