### ISSUE TITLE
Error in CompileCode. Not possible to compile Stan model.

### ISSUE THREAD

**Issue by LucasLoerch** [stan-dev/rstan#760]
#### Summary:
There were various problems with the installation due to a space in the path to the directory in which rstan was installed. Now I installed it in a new directory without spaces in the path. But now there are other errors. Rtools is also installed.

#### Description:
The compilation of a stan model returns an error . All packages are loaded without errors and pkgbuild::has_build_tools(debug = TRUE) returns TRUE.

#### Reproducible Steps:
I installed the packages in a directory without space in the path as this was producing errors before

install.packages("rstan", lib="C:/R_library", repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("BayesFactor", lib="C:/R_library")
install.packages("StanHeaders", lib="C:/R_library")
install.packages("RcppEigen", lib="C:/R_library")

I loaded all the packages with reference to this directory

library(StanHeaders, lib.loc="C:/R_library")
library(ggplot2, lib.loc="C:/R_library")
library(RcppEigen, lib.loc="C:/R_library")
library(rstan, lib.loc = "C:/R_library")
library(BayesFactor,  lib.loc = "C:/R_library")

I tried to fit a test model

m <- 
'parameters {real y;} 
 model {y ~ normal(0,1);}'
model<- stan_model(model_code = m)

this returns the output below

#### Current Output:
Fehler in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file2aa8144f62fd.cpp:6:36: warning: ISO C99 requires whitespace after the macro name
 #define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>
                                    ^
C:/RBuildTools/3.5/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/as.exe: file2aa8144f62fd.o: too many sections (36616)
C:\Users\LUCASL1\AppData\Local\Temp\ccUiJN6A.s: Assembler messages:
C:\Users\LUCASL1\AppData\Local\Temp\ccUiJN6A.s: Fatal error: can't write file2aa8144f62fd.o: File too big
C:/RBuildTools/3.5/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/as.exe: file2aa8144f62fd.o: too many sections (36616)
C:\Users\LUCASL1\AppData\Local\Temp\ccUiJN6A.s: Fatal error: can't close file2aa8144f62fd.o: File too big
make: *** [C:/PROGRA1/R/R-361.3/etc/x64/Makeconf:215: file2aa8144f62fd.o] Error 1
Zusätzlich: Warnmeldung:
In system(cmd, intern = !verbose) :
  Ausführung von Kommando 'C:/PROGRA1/R/R-361.3/bin/x64/R CMD SHLIB file2aa8144f62fd.cpp 2> file2aa8144f62fd.cpp.err.txt' ergab Status 1
Fehler in sink(type = "output") : ungültige Verbindung

#### RStan Version:
rstan Version 2.19.3

#### R Version:
R Version 3.6.3

#### Operating System:
Windows 10 Version 1903

**Comment by willfurnass** [comment]
@LucasLoerch What was the issue here?  I've encountered the same problem

**Comment by LucasLoerch** [comment]
@willfurnass , I could not finally figure it out as the problem disappeared after I downloaded the new Version of R (4.0) and then the new versions of Rtools and all packages. 
My guess is that the system could not find Rtools, as the new version was automatically installed in another directory in the new version. Try uninstalling Rtools and install it directly in C:/
