### ISSUE TITLE
RStan Influenced By R Environment RNG Seed

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/rstan#761]
#### Description:

Contrary to the documentation the `stan` command is influenced by the global `R` seed and returns results inconsistent with the other interfaces.

#### Reproducible Steps:

Consider the short Stan program
```
generated quantities {
  real theta = normal_rng(0, 1);
}
```

In CmdStan 2.21.0 the seed 4838282 results in 

```
> ./simu_test sample algorithm=fixed_param num_warmup=0 num_samples=10 random seed=4838282

-1.32118,0.636464,-0.887328,-0.714188,0.705271,1.96361,-0.249596,-0.969753,0.182282,-0.497738
```

In RStan 2.19.2 (R 3.5.1), however, it gives
```
> fit <- stan(file='simu_test.stan',
              iter=10, warmup=0, chains=1, refresh=10,
              seed=4838282, algorithm="Fixed_param")
> extract(fit)$theta

[1]  0.34899964  0.04996515 -0.78890771 -0.55016985  0.30426112 -1.31350839
[7]  1.11651093  0.19455556  0.45362133  0.39525325
```
Not only is this inconsistent with the CmdStan output which is supposed to use the same PRNG it's also inconsistent with itself.  Running again gives
```
> fit <- stan(file='simu_test.stan',
              iter=10, warmup=0, chains=1, refresh=10,
              seed=4838282, algorithm="Fixed_param")
> extract(fit)$theta

[1]  0.19455556  1.11651093 -0.78890771 -1.31350839  0.04996515  0.45362133
[7]  0.39525325  0.34899964 -0.55016985  0.30426112
```

If we set the `R` global seed, however, we do get consistent results which implies that `RStan` is being influenced by the `R` environment despite an explicit seed being set,
```
> set.seed(4838282)
> fit <- stan(file='simu_test.stan',
              iter=10, warmup=0, chains=1, refresh=10,
              seed=4838282, algorithm="Fixed_param")
> extract(fit)$theta

[1] -0.78890771 -1.31350839  0.45362133  0.34899964  0.30426112  0.39525325
[7]  0.19455556  1.11651093 -0.55016985  0.04996515

> set.seed(4838282)
> fit <- stan(file='simu_test.stan',
              iter=10, warmup=0, chains=1, refresh=10,
              seed=4838282, algorithm="Fixed_param")
> extract(fit)$theta

[1] -0.78890771 -1.31350839  0.45362133  0.34899964  0.30426112  0.39525325 [7]  0.19455556  1.11651093 -0.55016985  0.04996515
```

To double check the seed is valid,
```
> as.integer(4838282)
4838282
```

#### Current Output:

Inconsistent results with a fixed seed within `RStan` and with CmdStan.

#### Expected Output:

Consistent results with a fixed seed within `RStan` at least and ideally compatibility with the other interfaces.

#### RStan Version:

2.19.2

#### R Version:

3.5.1

#### Operating System:

OS X 10.14.6

**Comment by jgabry** [comment]
That's weird. I was also under the impression that setting the global seed in R wasn't necessary. I'm not particularly familiar with the way rstan is handling seeds. @bgoodri or @maverickg any idea why this is happening? If not I can try to do some digging around. 

Also, sorry for the slow response! I've been swamped for months and on the interfaces side I've been mostly focusing on getting CmdStanR off the ground.

**Comment by maverickg** [comment]
I took a look.  The reason of the seemingly difference is there a `chain_id` argument used in the random number generation in the c++ code.  `chain_id` is set to 1 by default in R while it is 0 in CmdStan.  Also we need to use `refresh=1` to match to CmdStan. I did the following in rstan:

```
> fit <- stan(file='simu_test.stan',
              iter=10, warmup=0, chains=1, refresh=1,
              seed=4838282, algorithm="Fixed_param", chain_id=0)
```

And I got the following result that is the same as that from CmdStan.  

```
> fit@sim$samples[[1]]$theta
 [1] -1.3211750  0.6364637 -0.8873277 -0.7141877  0.7052710  1.9636059 -0.2495965
 [8] -0.9697525  0.1822816 -0.4977385
```

It seems that R's random seed makes a difference in the issue report.  This is only because `extract` function by default does a permutation, which I believe can be seen from those number if we looked at carefully.  

So other than the oddity that default chain_id is used, this is not a bug.

**Comment by jgabry** [comment]
Thanks @maverickg!

**Comment by betanalpha** [comment]
Thanks, Mav.  I can confirm that explicitly specifying `chain_id=0` unifies the results between interfaces when the RStan output is accessed with `extract(fit, permute=FALSE)`.

Before I close the issue can I get confirmation that the permutation of the samples is set when the fit object is created and so multiple calls to `extract` on the same fit object are guaranteed to have the same order?  In other words
```
samples <- extract(fit)
samples$param1
samples$param2
```
and
```
extract(fit)$param1
extract(fit)$param2
```
will always be the same?  Empirically this appears to be true but I just want to make sure that it's guaranteed by the code.

Thanks!

**Comment by maverickg** [comment]
Yes, the way to permute the iterations in each chains is randomly generated when the sampling is done. As a result, `extract` with `permute=TRUE` always produces the same results.

**Comment by betanalpha** [comment]
Great, thanks!
