### ISSUE TITLE
Warning when compiled with R  4.0

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstan#762]
After upgrading to R 4.0 and rtools 4.0, I get a warning both in rstan and in brms:

```
Compiling the C++ model
file45c227e6c7b.cpp:6:36: warning: ISO C++11 requires whitespace after the macro name
 #define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>
```

Results looks ok though, so did not spend the time to track is down.

**Comment by bob-carpenter** [comment]
Thanks for reporting.   I'm not sure where that `#define` is coming from.  Given our naming conventions, this should be a Stan repo file named `stan/services/command.hpp`, but it's not.  So I'm guessing it comes from rstan.

**Comment by dmenne** [comment]
I suspect tom CR vs. CRLF problem.

**Comment by jgabry** [comment]
Is this warning still an issue for windows users with the latest RStan? I don't have Windows but maybe @dmenne you could check again, or @andrjohns or someone else with Windows could try this and check? If it's still there maybe we can get rid of it. If not then we should close this.

**Comment by dmenne** [comment]
No problem for me (R 2.21.2)
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
