### ISSUE TITLE
Bug in stan_model()

### ISSUE THREAD

**Issue by cetp** [stan-dev/rstan#764]
#### Summary:
All models fail to be constructed using stan_model. 

#### Description:
No model can be constructed using rstan.  Every attempt ends with a compilation error in compileCode(). I have freshly installed rstan and all associated libraries. 

#### Reproducible Steps:
`
library(rstan)
scode <- "
parameters {
  real y[2]; 
} 
model {
  y[1] ~ normal(0, 1);
  y[2] ~ double_exponential(0, 2);
}"
fit1 <- stan(model_code = scode, iter = 10, verbose = T) 
`

#### Current Output:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file65965c8c977a.cpp:6:36: warning: ISO C99 requires whitespace after the macro name [enabled by default]
 #define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>
                                    ^
In file included from /homes/une/cpaine2/R/x86_64-redhat-linux-gnu-library/3.6/StanHeaders/include/stan/math/rev/mat/fun/ordered_constrain.hpp:6:0,
                 from /homes/une/cpaine2/R/x86_64-redhat-linux-gnu-library/3.6/StanHeaders/include/stan/math/rev/mat.hpp:41,
                 from /homes/une/cpaine2/R/x86_64-redhat-linux-gnu-library/3.6/StanHeaders/include/src/stan/model/log_prob_grad.hpp:4,
                 from /homes/une/cpaine2/R/x86_64-redhat-linux-gnu-library/3.6/StanHeaders/include/src/stan/model/test_gradients.hpp:7,
                 from /homes/une/cpaine2/R/x86_64-redhat-linux-gnu-library/3.6/StanHeaders/include/src/stan/services/diagnose/diagnose.hpp:10,
                 from /home

These lines are generated on line 92 in stan_model(), which is 
 `
 inc <- paste("#define STAN__SERVICES__COMMAND_HPP", "#include <boost/integer/integer_log2.hpp>\n", 
               "#include <rstan/rstaninc.hpp>\n", if (is.null(includes)) 
                 model_cppcode
               else sub("(class[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*)", 
                        paste(includes, "\\1"), model_cppcode), get_Rcpp_module_def_code(model_cppname), 
               sep = "")
`

I think that the problem is that the first two arguments to paste are pasted together with no space between them. I think that re-wriiting this would solve the problem: 
`
 inc <- paste("#define STAN__SERVICES__COMMAND_HPP\n#include <boost/integer/integer_log2.hpp>\n", 
               "#include <rstan/rstaninc.hpp>\n", if (is.null(includes)) 
                 model_cppcode
               else sub("(class[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*)", 
                        paste(includes, "\\1"), model_cppcode), get_Rcpp_module_def_code(model_cppname), 
               sep = "")
`
Perhaps, however, this would only fix the warning, and the error is deeper-rooted. 

#### RStan Version:
2.19.3

#### R Version:
3.6.0 (2019-04-26)

#### Operating System:
This is running on one of my university's virtual machines. It runs Linux, version 3.10.0-1127.el7.x86_64.

**Comment by jgabry** [comment]
I'm going through issues and just noticed nobody ever responded to this, sorry! Are you still running into this error or were you able to get it working? (There are more recent versions of R and RStan now too that might help)

**Comment by cetp** [comment]
Dear Jonah,
Thanks for reaching out. I did eventually find a way around that issue. It was not, in he end, a bug at all, but an error in how the virtual machine I was using had been set up. Please mark this as closed.
Thanks, and best wishes, --Tim




On 5 Sep 2020, at 6:28 am, Jonah Gabry <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm going through issues and just noticed nobody ever responded to this, sorry! Are you still running into this error or were you able to get it working? (There are more recent versions of R and RStan now too that might help)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstan-dev%2Frstan%2Fissues%2F764%23issuecomment-687366346&data=02%7C01%7Ctimothy.paine%40une.edu.au%7C05d6cdcbf0b94b4def0208d85111173f%7C3e104c4f8ef24d1483d8bd7d3b46b8db%7C0%7C0%7C637348481132207016&sdata=%2B%2Fa747DJTTv2RVhoD4nD54Mq2FwvNtZ9eswlqO9iK0U%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFJLVZWZ5GNTEVGULHCOK43SEFEWVANCNFSM4M5TDSZA&data=02%7C01%7Ctimothy.paine%40une.edu.au%7C05d6cdcbf0b94b4def0208d85111173f%7C3e104c4f8ef24d1483d8bd7d3b46b8db%7C0%7C0%7C637348481132207016&sdata=pQu1xOZ0qdWOY5Q0feOXLuPqmLaI1%2Fh7RwA1ePQSPj8%3D&reserved=0>.

_____________________
Dr. C. E. Timothy Paine

[cid:C0C39BDE-B3AC-45C4-AB1E-DD98853DA24E@une.edu.au]
Lecturer
School of Environmental and Rural Science
Faculty of Science, Agriculture, Business and Law
University of New England
Armidale NSW 2351 Australia
The University of New England (UNE)
CRICOS Provider Code 00003G

**Comment by jgabry** [comment]
Ok great, glad it’s working now!
