### ISSUE TITLE
`stan_ac` returns a warning message.

### ISSUE THREAD

**Issue by tellnnn** [stan-dev/rstan#766]
#### Summary:

`stan_ac` function returns a warning message, saying "Ignoring unknown parameters: fun.y". I think it is due to an update in ggplot2 (3.3.0).

#### Description:

When I call `stan_ac` like `stan_ac(object = fit, pars = "lp__")`, it returns:

> No summary function supplied, defaulting to 'mean_se()'
>  Warning message:
> Ignoring unknown parameters: fun.y 

Although `stan_ac` returns these messages, `stan_ac` works well for now. However, this might lead to an error in future.

The 1st message can be suppressed by adding option 'fun.data = "mean_se"' explicitly. 

On the other hand, the 2nd one might need some modification in `stan_ac` fuction. I took a look at [source on GitHub](https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/stan_plot.R) (line 156), and I found the `stan_ac` called `geom_bar` in it and passed three options `position = "dodge", stat = "summary", fun.y = "mean"`. However, in [`stat_summary` in `ggplot2-3.3.0`](https://ggplot2.tidyverse.org/reference/stat_summary.html), `fun.ymin`, `fun.y`, and `fun.ymax` are deprecated. To modify this problem, `fun.y = "mean"` should be replaced by `fun = "mean"`.

For example, `geom_bar` works as follows in `ggplot2-3.3.0`.

With iris dataset, 

> ggplot(iris, aes(x = Species, y = Sepal.Length)) +
>     geom_bar(position = "dodge",
>                       stat = "summary",
>                       fun.data = "mean_se",
>                       fun.y = "mean")

returns:

>  Warning message:
> Ignoring unknown parameters: fun.y 

When I replace `fun.y` with `fun`,

> ggplot(iris, aes(x = Species, y = Sepal.Length)) +
>     geom_bar(position = "dodge",
>                       stat = "summary",
>                       fun.data = "mean_se",
>                       fun = "mean")

returns no warning message.

#### Reproducible Steps:

- Example 1

code:

`fit <- stan_demo("eight_schools")`
`stan_ac(object = fit, pars = "lp__")`

return:

> No summary function supplied, defaulting to 'mean_se()'
>  Warning message:
> Ignoring unknown parameters: fun.y 

- Example 2

code: 

`fit <- stan_demo("eight_schools")`
`stan_ac(object = fit, pars = "lp__", fun.data = "mean_se")`

return:

>  Warning message:
> Ignoring unknown parameters: fun.y 

#### RStan Version:

2.19.2

#### ggplot2 Version:

3.3.0

#### R Version:

R version 3.6.0 (2019-04-26)

#### Operating System:

OS X 10.13.6

**Comment by jgabry** [comment]
Thanks for reporting this. Just fixed it based on your recommendations and that does indeed remove the warning messages. Thanks!
