### ISSUE TITLE
R4.0 / rtools40: vector allocation error in any (e.g. schools.stan) model

### ISSUE THREAD

**Issue by cord-otten** [stan-dev/rstan#767]
#### Summary:
After uninstalling/ reinstalling/ setting up rstan and rtools40, I get an error message when trying to fit any model like:
Error: cannot allocate vector of size 14174.3 Gb

#### Description:
I went through all steps as described in the 'RStan Getting Started' section. When I reach the point to actually fit the model, I get the following error:
Error: cannot allocate vector of size 14174.3 Gb
The size varies from attempt to attempt. I tried different (super simple example) models, with the same effect.

#### RStan Version:
‘2.19.3’

#### R Version:
R version 4.0.0 (2020-04-24)

#### Operating System:
Windows 10 Education, 64-bit

**Comment by andrjohns** [comment]
Can you try the steps listed in this forum post: https://discourse.mc-stan.org/t/r-4-0-rstan-and-you/15271

And see if that fixes it?

**Comment by cord-otten** [comment]
I did. Unfortunately it doesn't.
I tried various proposals from the forum without success. Maybe I have overlooked something so far.

**Comment by andrjohns** [comment]
So you've moved/deleted your Rprofile.site, Makevars.win, and .Renviron files? Then after re/moving .Renviron you've run:
```
writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
```


Can you post the output from:
```
Sys.which("g++")
Sys.getenv("BINPREF")
Sys.getenv("PATH")
```

We basically need to check whether R is finding the right compiler (from Rtools 4), and if not, why not

**Comment by cord-otten** [comment]
> So you've ...  

Yes.

Probably the forum would have been more appropriate for my problem(s) : /
The first two commants return empty, so there clearly is an issue.
Thank you very much for taking the time!
Anyhow - here are the ouputs:

`
> Sys.which("g++")
g++ 
 "" 
> Sys.getenv("BINPREF")
[1] ""
> Sys.getenv("PATH")
[1] "C:\\rtools40\\usr\\bin;C:\\Program Files\\R\\R-4.0.0\\bin\\x64;C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Python37\\Scripts\\;C:\\Program Files\\Python37\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\SysWOW64\\Empirum;C:\\Program Files (x86)\\Pandoc\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Git\\cmd;C:\\Users\\BAR8214\\AppData\\Local\\Microsoft\\WindowsApps;"
`

**Comment by andrjohns** [comment]
The PATH looks good, but the empty string for ```g++``` means that it's not finding the compiler, which is odd.

Can you run: ```devtools::find_rtools(debug = TRUE)```?

**Comment by andrjohns** [comment]
Also, can you check your RStudio version (if you're using it)? Since 1.2.5042 is recommended with rtools4

**Comment by cord-otten** [comment]
` > devtools::find_rtools(debug = TRUE)`
`[1] TRUE`

RStudio
Version 1.2.1335

--> I did not see the RStudio version requirement before. That might fix it (I cannot update currently, since my machine is administered by my organization). I did try to run the schools example from plain R, though. It just closes when trying to sample the example model.

**Comment by andrjohns** [comment]
Hm, so it's finding RTools but not the compiler. Have you uninstalled the old versions of rtools?

Can you try running:
```
cat('Sys.setenv(BINPREF = "C:/rtools40/mingw$(WIN)/bin/")',
    file = file.path(Sys.getenv("HOME"), ".Rprofile"), 
    sep = "\n", append = FALSE)
```

Then restarting R and running ```Sys.which("g++")``` again?

**Comment by cord-otten** [comment]
> Have you uninstalled the old versions of rtools?

Yes. I also made sure that they were removed from the PATH.

`Sys.which("g++")` is still empty after running the command.

**Comment by andrjohns** [comment]
What does ```Sys.which("make")``` return?

Something else to try is the ```find_rtools``` function from the development version of ```pkgbuild```:
```
devtools::install_github("r-lib/pkgbuild")
pkgbuild::check_rtools(debug=TRUE)
```

**Comment by cord-otten** [comment]
- `> Sys.which("make")`
`                              make` 
`"C:\\rtools40\\usr\\bin\\make.exe" `

- `> pkgbuild::check_rtools(debug=TRUE)`
`[1] TRUE`

Looks fine to me.
: /

**Comment by andrjohns** [comment]
It is a bit weird. If you use the R GUI and run:
```
library(rstan)
example(stan_model,run.dontrun = TRUE,verbose=TRUE)
```
What is the section that starts with ```Compilation argument```?

**Comment by andrjohns** [comment]
Actually, are you able to install any packages from source?
Like:
```
install.packages("jsonlite", type="source")
```

That's probably a better test of the compiler

**Comment by cord-otten** [comment]
- I can install packages from source.

Stranger things:
- I just tried to run the `example(stan_model,run.dontrun = TRUE,verbose=TRUE)` first from within RStudio, then from R GUI:
  - From Rstudio it works, but I get a warning:
`Warning message:`
`In find.package(package, lib.loc, verbose = verbose) :`
`  package ‘base’ found more than once, using the first from`
`  “C:/PROGRA~1/R/R-40~1.0/library/base”,`
`  “C:/Program Files/R/R-4.0.0/library/base”`

  - From R GUI I get:
`...`
`Compilation argument:`
` C:/PROGRA~1/R/R-40~1.0/bin/x64/R CMD SHLIB file2ac834a66c94.cpp 2>` `file2ac834a66c94.cpp.err.txt `
`make: \ad.uni-hamburg.de\basis\mit\bm01\BAR8214\Documents/.R/Makevars.win: No such file or directory`
`make: *** No rule to make target '\ad.uni-hamburg.de\basis\mit\bm01\BAR8214\Documents/.R/Makevars.win'.  Stop.`
`Fehler in file(con, "r") : kann Verbindung nicht öffnen`
`Zusätzlich: Warnmeldungen:`
`1: In find.package(package, lib.loc, verbose = verbose) :`
`  package ‘base’ found more than once, using the first from`
`  “C:/PROGRA~1/R/R-40~1.0/library/base”,`
`  “C:/Program Files/R/R-4.0.0/library/base”`
`2: In file(con, "r") :`
`  kann Datei 'file2ac834a66c94.cpp.err.txt' nicht öffnen: No such file or directory`

**Comment by andrjohns** [comment]
Oh you've got a networked home directory? Are the R packages installed locally or on the networked drive? You can check quickly with: ```.libPaths()```

**Comment by cord-otten** [comment]
So as far as I understand, my home directory is mirrored to a network drive. I work at a university, so the general machine setup is administered by the IT department. The home directory is always available (whether online or offline, that is).

`.libPaths()`
`"C:/Program Files/R/R-4.0.0/library"`

**Comment by andrjohns** [comment]
But the example model compiled and ran fine under RStudio? So your stan installation is working? Make sure you delete any existing .rds files for the models, or omit the call to ```rstan_options(auto_write = TRUE)```, so that the model gets re-compiled

**Comment by andrjohns** [comment]
If the models are working under RStudio, that's great! If not, or if you have issues again, networked drives have caused issues in the past with RStan and model compilation. This is mainly caused by having the R packages installed on a networked-drive, while the compiler is on the local drive, you can check this by running:
```
system.file("include", "stan", "math", "prim", "mat", "fun", "Eigen.hpp", 
            package = "StanHeaders")
```
If the directory starts with ```\ad.uni-hamburg.de\...```, then you should try uninstalling Rcpp, RcppEigen, BH, StanHeaders, and rstan, and reinstalling to a directory on your local machine (i.e., not mirrored).

**Comment by cord-otten** [comment]
- The package example does compile from RStudio.
- networked drive:
  - The system.file command returns `"C:/Program Files/R/R-4.0.0/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp"`  
  - The issue is/ would be a little strange, because I did have rstan running on this machine prior to the R4.0 / rtools upgrade
  - I removed and installed the packages as suggested, unfortunately it did not solve the issue.

**Comment by andrjohns** [comment]
So the example model works but your own model(s) give the vector allocation error? The next thing to try is to see if it's the location of the stan model itself that's causing the issue. Can you try passing your stan model as a string to RStan (rather than the stan file itself)? For example:
```
stancode <- 'data {real y_mean;} parameters {real y;} model {y ~ normal(y_mean,1);}'
mod_string = stan(model_code=stancode, data=list(y_mean=0))

writeLines(stancode,file("~/test.stan"))
tmod = stan("~/test.stan",data=list(y_mean=0))
```

If the first method works, but the second doesn't, try putting your stan code (just the .stan file) in a local directory, like 'C:/stan' or something, and see if that also works

**Comment by andrjohns** [comment]
If none of them work, can you run the model with ```verbose=TRUE```, and post the section that starts with ```Compilation argument:```

For example, on my machine, this looks like:
```
Compilation argument:
 C:/PROGRA~1/R/R-40~1.0/bin/x64/R CMD SHLIB filebb82f5a2ce.cpp 2> filebb82f5a2ce.cpp.err.txt 
"C:/rtools40/mingw64/bin/"g++  -std=gnu++14 -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG   -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/Rcpp/include/"  -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/RcppEigen/include/"  -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/RcppEigen/include/unsupported"  -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/BH/include" -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/StanHeaders/include/src/"  -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/StanHeaders/include/"  -I"C:/Users/Andrew Johnson/Documents/R/win-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -D_REENTRANT  -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp  -std=c++1y    -march=core2     -O3 -Wno-unused-variable -Wno-unused-function -std=c++14 -march=native -mtune=native -Wno-deprecated-declarations -Wno-ignored-attributes -c filebb82f5a2ce.cpp -o filebb82f5a2ce.o
```

**Comment by cord-otten** [comment]
> So the example model works but your own model(s) give the vector allocation error?  

For example, the 'schools' example does not work (with the vector allocation error).


> ...if it's the location of the stan model itself...  

Both mentioned approaches work, so that doesn't seem to be the problem.

I did try the schools model with `verbose = TRUE` resulting in:

```
TRANSLATING MODEL 'schools' FROM Stan CODE TO C++ CODE NOW.
successful in parsing the Stan model 'schools'.
CHECKING DATA AND PREPROCESSING FOR MODEL 'schools' NOW.
COMPILING MODEL 'schools' NOW.
Error: cannot allocate vector of size 15452.6 Gb
```

**Comment by andrjohns** [comment]
And what happens if you try the same approach with the schools model:
```
stancode = "data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"
writeLines(stancode,"~/test_schools.stan")
school_test = stan("~/test_schools.stan",data=list(J = 8, 
                                                 y = c(28,  8, -3,  7, -1,  1, 18, 12),
                                                 sigma = c(15, 10, 16, 11,  9, 11, 10, 18)))
```

**Comment by cord-otten** [comment]
Alas! It worked.
I find it surprising, since the model file is now under my 'Documents' folder, which is on a networked drive. Anyhow, thank you so much for your help!
