### ISSUE TITLE
Rstan - cannot get started/installation issue

### ISSUE THREAD

**Issue by Swronski** [stan-dev/rstan#772]
#### Summary:
Please provide a short summary (no more than a sentence or two).
Followed STAN online tutorial for "schools" example but getting compilation issue

#### Description:
Describe the issue as clearly as possible.
Hello - I am following the tutorial here (https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started).  I installed R-Studio 1.3.959 and am using R 3.4.3.

I followed the steps and in doing so I executed pkgbuild::has_build_tools(debug = TRUE) and it returned TRUE. I omitted the part about Configuration of the C++ Toolchain as it was optional.  Trying to run schools.stan gives the following error in R-Studio (it seems to be the same error in R).

> fit <- stan(file = 'schools.stan', data = schools_dat)
DIAGNOSTIC(S) FROM PARSER:
Info (non-fatal): assignment operator <- deprecated in the Stan language; use = instead.

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/Users/HuaH/Documents/R/win-library/3.4/Rcpp/include/RcppCommon.h:187:0,
                 from C:/Users/HuaH/Documents/R/win-library/3.4/Rcpp/include/Rcpp.h:27,
                 from C:/Users/HuaH/Documents/R/win-library/3.4/rstan/include/rstan/io/rlist_ref_var_context.hpp:16,
                 from C:/Users/HuaH/Documents/R/win-library/3.4/rstan/include/rstan/stan_fit.hpp:18,
                 from C:/Users/HuaH/Documents/R/win-library/3.4/rstan/include/rstan/rstaninc.hpp:3,
                 from fileeb07c19473f.cpp:478:
C:/Users/HuaH/Documents/R/win-library/3.4/Rcpp/include/Rcpp/internal/wrap.h: In function 'SEXPREC* Rcpp::internal::primitive_range_wrap__impl(InputIterator, InputIterator, Rcpp::traits::true_type)':
C:/Users/HuaH/Documents/R/win-library/3.4/Rcpp/include/Rcpp/internal/wrap.h:108:20: error: 'wrap_extra_steps' was not declared in this scope
             retur
In addition: Warning message:
running command 'C:/PROGRA~1/R/R-34~1.3/bin/x64/R CMD SHLIB fileeb07c19473f.cpp 2> fileeb07c19473f.cpp.err.txt' had status 1 
Error in sink(type = "output") : invalid connection

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

I issued "fit <- stan(file = 'schools.stan', data = schools_dat)" at the command prompt in R (and R-Studio) after following the tutorial instructions.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

I expected to see the output described here (https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) which indicates an object called "fit" would be available.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.18.2
#### R Version:
The version of R you are running (e.g., from `R.version.string`)
"R version 3.4.3 (2017-11-30)"

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Windows 7 64-bit

**Comment by jgabry** [comment]
Sorry you've having compilation issues. I don't know Windows well enough to know what's going on here. I would suggest posting to the Stan forums (https://discourse.mc-stan.org/) because many more people (including windows users) will see your question there than here on Github.
