### ISSUE TITLE
still haunted by "Error in unserialize(socklist[[n]])"

### ISSUE THREAD

**Issue by DLeBlond** [stan-dev/rstan#780]
#### Summary:
This is not a new issue but has not been given the attention it deserves. 

The unhelpful message re-appears every so often just to enforce humility. It has caught me 3 times over the past 4 years - once at a 2019 Stan course where at least 20% of attendees experienced this famous message using instructor supplied code. Typing this error into the Web will bring up pages of links dating back years and filled with desperate debugging discussions (most far over my head). The cause is never found. No resolution. No fix. In my case I give up, resort to BUGS or JAGS for the project. The issue magically disappears with the next project, then a year or so later comes back. Usually after I have upgraded my Stan, R, rstan, RStudio, and even my Windows.

So - please help me. I am not alone here. There must be a way to avoid this that has been discovered by now. 

#### Description:
Here is the full Error message that appears in my RStudio console:

> StanFit <- sampling(comp_PLA, data=dataList,iter=200, chains=2, cores=2,
+                     verbose=TRUE )
CHECKING DATA AND PREPROCESSING FOR MODEL 'PLA' NOW.
COMPILING MODEL 'PLA' NOW.
STARTING SAMPLER FOR MODEL 'PLA' NOW.
**Error in unserialize(socklist[[n]]) : error reading from connection
Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection**

With cores = 1 or chains = 1, RStudio simply crashes.

#### Reproducible Steps:
This is absolutely reproducible with this data/model/Rcode. My data (428 obs, set and about 7 variables) code (simple mixed linear model) are really very trivial compared with many analyses I have made in Stan in the past. I am using the most recent versions of R, rstan, Stan, RStudio, Windows 10. I have lots of disk storage and memory. There is nothing else (I can identify) running on my computer to interfere. Reboot doesn't help. Recompiling doesn't help. Tall glass of beer doesn't help. Harsh language doesn't help. A 1:1 with my rubber ducky feels good but ... doesn't help.

I can provide the code and data that causes this but I fear that will just end (as so many other instances of this problem I have seen on line) with a rabbit hole run and a waste of some kind person's time. With the popularity of this strange behavior, I would think by now the cause/solution would be well known. I'm hoping someone out there knows it. If not, I am happy to run down the rabbit hole with anyone kind enough to help me.

#### Current Output:
The error above (or the RStudio crash which is also fun to see) appears in my RStudio console just prior to when I expect sampling to start.

#### Expected Output:
I expect it to sample (or at least try).

#### RStan Version:
rstan (Version 2.19.3, GitRev: 2e1f913d3ca3)

#### R Version:
R 3.6.3 
RStudio Version 1.2.1335

#### Operating System:
Windows 10 Pro v 1909

**Comment by betanalpha** [comment]
I used to have similar problems in my courses when students would be running on their 
own Windows machines.  I can’t guarantee that this will solve the problem, but it got rid
of all of the issues for me.

The unserialize/serialize messages are RStudio communicating that the processes on
which it was running the Stan chains crashed and couldn’t be recovered.  By setting 
chains = 1 (or cores = 1) RStan will not run with parallelization so you won’t get the 
error.

Instead RStudio itself just crashes; this indicates that something bad is happening 
deep in the execution of the code.  On Windows this often happens when 

 -march=native -mtune=native

is set in the Makevars file.  The problem is that the C++ compiler thinks it knows 
the native architecture and how to optimize it but it actually generates code that 
clashes with your particular processor.  More advanced functions, like the ODE 
solver and algebraic solver, were particularly likely to generate these clashes,
but it could also occur with seemingly innocuous code.

Check your Makevars file and if -march and -mtune are being set remove them and
try again.

**Comment by DLeBlond** [comment]
Thank you Michael!! Especially thank you for explaining in a way I can understand. I will follow your suggestion. But I will need some hand-holding. First question, which of the 16 "Makevars.*" files on My Windows machine is the one I need to change? (the second question will be how specifically to make the change as this is apparently a learned skill):
![List of makevars files](https://user-images.githubusercontent.com/67350797/85577545-f251f700-b5fe-11ea-80ae-b4c4bdc063fb.png)

**Comment by DLeBlond** [comment]
Some additional info
1. My processor is an Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz. My machine (HP ZBook 15u G2) has 15.9GB usable RAM.
2. None of the more recent Markvars "type" files (associated with R 3.6) have anything like "-march=native -mtune=native" in them as far as I can tell bringing these files up in NOTEPAD:

#### Here's one (/rstantools/include/):
STANHEADERS_SRC = $(shell "$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" -e "message()" -e "cat(system.file('include', 'src', package = 'StanHeaders', mustWork = TRUE))" -e "message()" | grep "StanHeaders")

PKG_CPPFLAGS = -I"../inst/include" -I"$(STANHEADERS_SRC)" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG

CXX_STD = CXX14

all: $(SHLIB)

clean:
		RM -rf *.so *.o

.phony: all clean

#### Here's another one (/rcppEigen/):
## With Rcpp 0.11.0 and later, we no longer need to set PKG_LIBS as there is
## no user-facing library. The include path to headers is already set by R.
#PKG_LIBS = 

## With R 3.1.0 or later, you can uncomment the following line to tell R to 
## enable compilation with C++11 (or even C++14) where available
#CXX_STD = CXX11

**Comment by betanalpha** [comment]
Keep in mind that what I suggested was just one possibility and may not 
work for any particular windows system.

In R you can find the Makevars file currently being used by running 
```
file.path(Sys.getenv("HOME"), ".R", ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))

```
you can edit it by running
```
M <- file.path(Sys.getenv("HOME"), ".R", ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"
))
file.edit(M)
```

**Comment by DLeBlond** [comment]
Thanks again Michael. Appreciate the support. 
Is it possible to see such an error message due to a cockpit error (i.e, I have been known to write dumb model code).
Stan is an amazing tool. I hope I can figure this out. I'll try your suggestions (a bit scary but...) and report back soon.

**Comment by DLeBlond** [comment]
Thank you Michael again for helping me through this. I learned allot about this error and how to resolve it from your suggestions. The issue has been resolved. With my tail between my legs I will describe how it was resolved:
1. My Makevars file did not contain the offending statements Michael asked me to remove so that was not the cause (this time).
2. In frustration, I reluctantly went back to WinBUGS to finish my project
3. My habit, when using WinBUGS, is always to first draw my model out as a DAG - a habit I had abandoned with Stan.
4. In drawing out my model as a DAG, I identified an error. I had failed to include one parameter in my likelihood. It was a loose end.
5. On reprogramming, the model ran perfectly in Stan and much faster than in WinBUGS, with better convergence.
So I learned 2 important lessons: Always do the DAG - even with Stan!! and This horrid and not very descriptive error message can result also from stupid coding.

**Comment by betanalpha** [comment]
I’m glad that you were able to find a modeling problem, but Stan 
should still be giving you an informative error message and not 
crashing silently, which indicates that something is corrupting 
the executables being built.  A clean install is always a good idea
to ensure that old files aren’t introducing problematic settings.

**Comment by aflor017** [comment]
I too am having this problem (all of a sudden). I inspected the Makevars files and do not see anything referencing -march or -mtune. This happened out of the blue (things were running fine a little over a week ago). Perhaps this is something with a new release (Windows update)? Just curious if others are having this problem all of a sudden.

I'll add that I also ran the same model using cmdstanr. In that situation, the model runs - 4 chains, 2000 iterations. Then, RStudio crashes after the chains finish.

**Comment by DLeBlond** [comment]
Sorry to hear about this aflor017. I have not had the issue again for over 1 year. I felt at the time that the cause might have been a cockpit (modeling) error on my part (always scratch out a DAG on paper!!), though I think the Stan experts felt it was more likely a version problem or some incompatibility. But it disappeared when I looked more closely at my model. However, I have had this error using perfectly good models provided by Stan instructors at a Stan course a couple years ago, so...

I know how frustrating it can be when you depend on the tool to meet a deadline and it breaks. I hope that you are able to get this miserable bug resolved. If so, please post the resolution. I quake in fear that the issue will return. Windows updates terrify me. I am strongly considering a Mac.

**Comment by mguzmann** [comment]
I'm actually getting this error in Ubuntu server. The Makevars thing seems to fix it... for now.

**Comment by DLeBlond** [comment]
Thanks Matias. I have found (after many such errors) that it is very important to continuously update versions of Stan, rstan, R, Rstudio, and all the dependent apps in order to avoid these kinds of frustrating hang-ups. It is indeed a pain to update constantly, but it appears to be the price we pay for freeware. I have not used Ubuntu but I can understand the attraction. Best Regards, Dave
