### ISSUE TITLE
error compiling Rstan using R 3.6.3 on Mac

### ISSUE THREAD

**Issue by swenk238** [stan-dev/rstan#783]
Hi there, 

I tried running **schools.stan** on my laptop and it compiled (it's the only model I could run), but it was prompting me with this error:

>_The NEXT version of Stan will not be able to pre-process your Stan program.
>Please open an issue at ...[this website]_ 

I have tried other examples and none of it worked, earlier I'm getting 

>_hash mismatch so recompiling; make sure Stan code ends with a blank line_ or

>_Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : no valid constructor available for the argument list_

And after reinstalling Rstan (and all necessary tools), I get this error when running the '**rats**' examples

>_Error in compileCode(f, code, language = language, verbose = verbose)_ 

My running R version (had to downgrade for another package) is:

> version            _                           
platform       x86_64-apple-darwin15.6.0   
arch             x86_64                      
os                darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major           3                           
minor           6.3                         
year             2020                        
month          02                          
day              29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock      

And ideas or directions to point me towards for this problem? Appreciate it.

**Comment by jgabry** [comment]
@statsy238 Sorry for the slow response. Can you share the output from calling `devtools::session_info()` after loading rstan?

**Comment by SteveBronder** [comment]
@statsy238 does your error message reference `clang++ -mmacosx-version-min=10.13`? If so this may be related to #774

**Comment by jgabry** [comment]
@statsy238 Were you able to get RStan installed?

**Comment by swenk238** [comment]
Hi, 

Thank you for following up and sorry for the slow response. My error message is as below:

`clang: error: no such file or directory: '/lib/libc++abi.1.dylib'
make: *** [rstan.so] Error 1
ERROR: compilation failed for package ‘rstan’` 

Am I just making a rookie mistake here? I am now running:

 `version  R version 4.0.2 (2020-06-22) 
os       macOS Mojave 10.14.6        
 system   x86_64, darwin17.0 ` 

Thanks in advance.

**Comment by jgabry** [comment]
No I don't think you're making a rookie mistake, I think this is just confusing. I'm not sure if this is something related to Mojave (as opposed to newer Mac OS) or if there's something else going on. @bgoodri or @SteveBronder any ideas? 

What are the contents of your Makevars file? You can view it by running `file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars"))`.

**Comment by jgabry** [comment]
Also, do you have an `~/.Renviron` file with anything in it? For that you can check `file.edit(file.path(Sys.getenv("HOME"), ".Renviron"))`

**Comment by liebscher** [comment]
Of all the issues on installation, this seems perhaps like the best one to add to. I'm experiencing a similar issue with installation and compilation. From a bird's eye view: either I cannot get rstan to install, or I can get it to install from the binaries (rstan 2.21.1) but then it won't compile any model, either from a model file or from model code.

Running `sessionInfo()` gives:

> R version 4.0.2 (2020-06-22)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Catalina 10.15.5

Also relevant:

> Apple clang version 11.0.3 (clang-1103.0.32.62)
> Target: x86_64-apple-darwin19.5.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

My `Makevars` and `.Renvirons` files are empty. I just updated R and RStudio to the latest: 4.0.2 and 1.3.1073, respectively. Here's what I've tried:

1. Install from `cloud.r-project.org` as recommended in the Getting Started. This fails to install.

Specifically, first I've run: `install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)`. Given the option to install from the source, version 2.21.2, I install from here. This immediately fails to install:

> * installing *source* package ‘rstan’ ...
> ** package ‘rstan’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS   -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c Module.cpp -o Module.o
> In file included from Module.cpp:1:

This led me to #816 and #774, where I read through all the comments and tried to act based on those. I subsequently removed all traces of rstan and tried to reinstall from Github.

2. Install from Github. This fails to install.

I ran: `remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan", build_opts = "")`, which led to:

> Error: Failed to install 'rstan' from GitHub:
>   System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:646:17: error: no template named 'numeric_limits'
> E>   static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
> E>                 ^
> E> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> E> 20 errors generated.
> E> make: *** [Module.o] Error 1
> E> ERROR: compilation failed for package ‘rstan’
> E> * removing ‘/private/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T/RtmpH8Wmjr/Rinst242872afceb1/rstan’
> E>       -----------------------------------
> E> ERROR: package installation failed

So, I removed all traces of rstan and `.Rdata` and tried again from the repository...

3. Install from `cloud.r-project.org` but from the binaries. This installs, but eventually leads to a clang++ error and does not fit any model.

Lastly, I ran attempt (1) above but chose to install from the binaries, version 2.21.1. This installs without issues! However, fitting the simplest of models, the 8-schools example and a basic normal model from #774, fails. I get:

> sh: clang++ -mmacosx-version-min=10.13: command not found
> error in running commandThe NEXT version of Stan will not be able to pre-process your Stan program.
> Please open an issue at
>  https://github.com/stan-dev/stanc3/issues 
> if you can share or at least describe your Stan program. This will help ensure that Stan
> continues to work on your Stan programs in the future. Thank you!
> This message can be avoided by wrapping your function call inside suppressMessages().

Plus a few other errors, with `traceback()` giving:

> 7: stop(paste("Compilation ERROR, function(s)/method(s) not created!", 
>        paste(errmsg, collapse = "\n")))
> 6: compileCode(f, code, language = language, verbose = verbose)
> 5: cxxfunction(sig = sig, body = body, plugin = plugin, includes = includes, 
>        settings = settings, ..., verbose = verbose)
> 4: pkgbuild::with_build_tools(cxxfunction(sig = sig, body = body, 
>        plugin = plugin, includes = includes, settings = settings, 
>        ..., verbose = verbose), required = rstan_options("required") && 
>        !identical(Sys.getenv("WINDOWS"), "TRUE") && !identical(Sys.getenv("R_PACKAGE_SOURCE"), 
>        ""))
> 3: cxxfunctionplus(signature(), body = paste(" return Rcpp::wrap(\"", 
>        model_name, "\");", sep = ""), includes = inc, plugin = "rstan", 
>        save_dso = save_dso | auto_write, module_name = paste("stan_fit4", 
>            model_cppname, "_mod", sep = ""), verbose = verbose)
> 2: stan_model(file, model_name = model_name, model_code = model_code, 
>        stanc_ret = NULL, boost_lib = boost_lib, eigen_lib = eigen_lib, 
>        save_dso = save_dso, verbose = verbose)
> 1: stan(model_code = scode, iter = 10, verbose = TRUE)

----

Overall, through three different attempts I am unable to install a working rstan. I have a feeling it might be related to updating R and RStudio this afternoon, although with so many other similar issues from previous versions I'm not so sure. I wouldn't know what version to revert to anyways. Any thoughts?

**Comment by liebscher** [comment]
@jgabry @SteveBronder Any ideas? I'd love to get started with rstan but I'm at a standstill! I really appreciate any help I can get.

**Comment by bgoodri** [comment]
Try first doing
```
remotes::install_github("bgoodri/inline")
```
and then see if there is more to the error message.

**Comment by liebscher** [comment]
Thanks @bgoodri for the suggestion. I installed your fork there no problem. It's hard to tell what changes you anticipated, although I don't see anything significantly different. Two installs (from CRAN and from GH) both failed with seemingly identical errors as to what I had before. See:

1. First, I `remove.packages("rstan")`. Then deleted `.Rdata`. Then installed `inline`. Then restarted the R session from inside RStudio. Then ran `install.packages(“rstan”, type = “source”)`. And lastly, was handed this error:

```
> install.packages("rstan", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/rstan_2.21.2.tar.gz'
Content type 'application/x-gzip' length 1152008 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS   -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c Module.cpp -o Module.o
In file included from Module.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from Module.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:335:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
using ::abs;
      ~~^
/usr/local/include/math.h:417:15: note: 'fabs' declared here
extern double fabs(double);
              ^
In file included from Module.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:640:26: error: no template named 'numeric_limits'
    bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:640:60: error: no template named 'numeric_limits'
    bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                                                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:641:18: error: no template named 'numeric_limits'
    int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:641:50: error: no template named 'numeric_limits'
    int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                                                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:646:17: error: no template named 'numeric_limits'
  static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Module.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan’
Warning in install.packages :
  installation of package ‘rstan’ had non-zero exit status
```

Potentially this might be related to clang, although I don't know whether that's true or how to debug that. Could it be related to me installing Rcpp not from `drat` but from CRAN?

2. Second, I removed `rstan`. Then, restarted the R session from within RStudio. Then ran `remotes::install_github(“stan-dev/rstan”, ref = “develop”, subdir = “rstan/rstan”, build_opts = “”)`. After a lengthly cloning period (which on the first try ended in a bad pack header error from curl), gave:

```
> remotes::install_github("stan-dev/rstan", ref = "develop", 
+                         subdir = "rstan/rstan", build_opts = "")
Downloading GitHub repo stan-dev/rstan@develop
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git /var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T//RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/rstan/rstan/../../StanHeaders/inst/include/upstream
Cloning into '/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T//RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/rstan/rstan/../../StanHeaders/inst/include/upstream'...
Submodule 'lib/stan_math' (https://github.com/stan-dev/math.git) registered for path 'lib/stan_math'
Cloning into '/private/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T/RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/StanHeaders/inst/include/upstream/lib/stan_math'...
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/math.git /var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T//RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/rstan/rstan/../../StanHeaders/inst/include/mathlib
Cloning into '/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T//RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/rstan/rstan/../../StanHeaders/inst/include/mathlib'...
Updating files: 100% (26321/26321), done.
✓  checking for file ‘/private/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T/RtmpgFpf02/remotes4dace499b6b/stan-dev-rstan-a9a44bb/rstan/rstan/DESCRIPTION’ ...
─  preparing ‘rstan’: (720ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘rstan’ ...
   ** using staged installation
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS   -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c Module.cpp -o Module.o
   In file included from Module.cpp:1:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
   using ::signbit;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
   using ::fpclassify;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
   using ::isfinite;
         ~~^
   /usr/local/include/math.h:749:12: note: 'finite' declared here
   extern int finite(double)
              ^
   In file included from Module.cpp:1:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
   using ::isinf;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
   using ::isnan;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
   using ::isnormal;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'isgreater' in the global namespace
   using ::isgreater;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'isgreaterequal' in the global namespace
   using ::isgreaterequal;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
   using ::isless;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
   using ::islessequal;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
   using ::islessgreater;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
   using ::isunordered;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
   using ::isunordered;
         ~~^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:335:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
   using ::abs;
         ~~^
   /usr/local/include/math.h:417:15: note: 'fabs' declared here
   extern double fabs(double);
                 ^
   In file included from Module.cpp:1:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:640:26: error: no template named 'numeric_limits'
       bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                            ^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:640:60: error: no template named 'numeric_limits'
       bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                                                              ^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:641:18: error: no template named 'numeric_limits'
       int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                    ^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:641:50: error: no template named 'numeric_limits'
       int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                                                    ^
   /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:646:17: error: no template named 'numeric_limits'
     static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
                   ^
   fatal error: too many errors emitted, stopping now [-ferror-limit=]
   20 errors generated.
   make: *** [Module.o] Error 1
   ERROR: compilation failed for package ‘rstan’
─  removing ‘/private/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T/RtmpaIh4eG/Rinst4e5d523133c8/rstan’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'rstan' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:646:17: error: no template named 'numeric_limits'
E>   static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
E>                 ^
E> fatal error: too many errors emitted, stopping now [-ferror-limit=]
E> 20 errors generated.
E> make: *** [Module.o] Error 1
E> ERROR: compilation failed for package ‘rstan’
E> * removing ‘/private/var/folders/w3/69wbznbs1yz9_0xm7_wsj07r0000gp/T/RtmpaIh4eG/Rinst4e5d523133c8/rstan’
E>       -----------------------------------
E> ERROR: package installation failed
```

I'm not a fan of copying huge errors like this but out of clarity I feel compelled. Again, I see a clang error. Not sure how relevant that it is.

Thank you for volunteering your time to help out a stranger.

**Comment by bgoodri** [comment]
Yeah, it is way easier to get Stan-related stuff working with R 4.x so that it uses the Xcode clang++ rather than the LLVM clang++. It is still possible to get it to work with R 3.x, but you have to compile all the relevant packages from source with just the right stuff in ~/.R/Makevars .

**Comment by jgabry** [comment]
@liebscher Were you able to get RStan installed? If not definitely follow up and we'll try to help more

**Comment by liebscher** [comment]
@jgabry @bgoodri Thanks both for the input, the issue for me was unrelated to `rstan`. I wrote my complete solution on SO: <https://stackoverflow.com/questions/63865695/rcpp-fails-to-compile-c-code-after-series-of-updates>

**Comment by jgabry** [comment]
Ok great, thanks for following up!
