### ISSUE TITLE
Missing sinc.hpp code in vignette: Interfacing with External C++ code

### ISSUE THREAD

**Issue by ssp3nc3r** [stan-dev/rstan#787]
The vignette for interfacing with external c++ code refers to the file `sinc.hpp` but its contents are missing in the documentation.

**Comment by bgoodri** [comment]
it's in the directory https://cran.r-project.org/web/packages/rstan/vignettes/sinc.hpp

**Comment by jgabry** [comment]
@ssp3nc3r Are you happy if we close this or do think we need to do more to help people find that file?

**Comment by ssp3nc3r** [comment]
I think you just need to change `echo = FALSE` to `TRUE`. 

The vignette has code to insert the contents of the file, but doesn't actually insert it:

> The sinc.hpp file reads as
> ```
> ```{r, echo = FALSE, comment=""}
> cat(readLines("sinc.hpp"), sep = "\n")

**Comment by jgabry** [comment]
Ah ok. Want to make a PR? If not I'll try to get to it soon.

**Comment by ssp3nc3r** [comment]
Actually it needed `eval = TRUE`. Done.

**Comment by jgabry** [comment]
Thanks! just merged it
