### ISSUE TITLE
Compilation error with Rstan

### ISSUE THREAD

**Issue by Erandi02** [stan-dev/rstan#798]
Hi, Does any one have idea for this compilation error Rstan ? I would like to have some help to solve it.

Error in file(con, “r”) : cannot open the connection
In addition: Warning message:
In file(con, “r”) :
cannot open file ‘file2c581a232c8d.cpp.err.txt’: No such file or directory

Compilation argument:
C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file2c5817d021ca.cpp 2> file2c5817d021ca.cpp.err.txt
“C:/rtools40/mingw64/bin/“g++ -std=gnu++14 -I"C:/PROGRA~1/R/R-40~1.2/include” -DNDEBUG -I"C:/Users/erandi/Documents/R/win-library/4.0/Rcpp/include/” -I"C:/Users/erandi/Documents/R/win-library/4.0/RcppEigen/include/" -I"C:/Users/erandi/Documents/R/win-library/4.0/RcppEigen/include/unsupported" -I"C:/Users/erandi/Documents/R/win-library/4.0/BH/include" -I"C:/Users/erandi/Documents/R/win-library/4.0/StanHeaders/include/src/" -I"C:/Users/erandi/Documents/R/win-library/4.0/StanHeaders/include/" -I"C:/Users/erandi/Documents/R/win-library/4.0/rstan/include" -DEIGEN_NO_DEBUG -D_REENTRANT -DBOOST_DISABLE_ASSERTS -DBOOST_PENDING_INTEGER_LOG2_HPP -include stan/math/prim/mat/fun/Eigen.hpp -std=c++1y -march=core2 -include C:/Users/erandi/Documents/R/win-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I “C:/Users/erandi/Documents/R/win-library/4.0/StanHeaders/include” -I “C:/Users/erandi/Documents/R/win-library/4.0/RcppEigen/include” -O2 -Wall -mfpmath=sse -msse2 -mstackrealign -c file2c5817d021ca.cpp -o file2c5817d021ca.o
file2c5817d021ca.cpp:6:36: warning: ISO C++11 requires whitespace after the macro name
#define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>

Thanks

**Comment by jgabry** [comment]
Sorry you're getting an error. Does this thread from the Stan forums help? https://discourse.mc-stan.org/t/rstan-on-windows/16673

**Comment by jgabry** [comment]
@Erandi02 Were you able to successfully get RStan installed?

**Comment by Erandi02** [comment]
@jgabry I have already installed Rstan 2.19.3 with R version 4.0.2.
For my case, I am still having compilation errors. I have no luck with Rstan 2.21.1

**Comment by Erandi02** [comment]
@jgabry Hello Jonah,
 Rstan version 2.21.1 still gives me the same error as earlier

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2ae4337f71b7.o:file2ae4337f71b7.cpp:(.text+0x76c): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2ae4337f71b7.o:file2ae4337f71b7.cpp:(.text+0x14f7): undefined reference to `rstan::stan_fit::stan_fit(SEXPREC*, int)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2ae4337f71b7.o:file2ae4337f71b7.cpp:(.text+0x7ae): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2ae4337f71b7.o:file2ae4337f71b7.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D1Ev[_ZN3tbb8internal26task_scheduler
In addition: Warning message:
In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\erandi\AppData\Local\Temp\RtmpiE0Lhe\file2ae4498d1a03.stan', reason 'No such file or directory'
Error in sink(type = "output") : invalid connection

Are there any solution with you? Thanks.

**Comment by jgabry** [comment]
@Erandi02 so you installed RStan from the links at 

https://discourse.mc-stan.org/t/rstan-on-windows/16673

but it still gives you this error? If that's the case then I'm out of ideas (I don't know much about Windows). @bgoodri or @SteveBronder any ideas?

**Comment by jgabry** [comment]
Going to close this due to inactivity but if there's still a problem let us know and we'll reopen it
