### ISSUE TITLE
Fixing Windows Compilation Errors

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/rstan#801]
#### Summary:

I'm trying to sort out which Makevars flags we need to check / set for windows users.

#### Description:

In [this thread](https://discourse.mc-stan.org/t/error-running-stan-model-with-rstan-2-21-in-windows/16499/18?u=stevebronder) it was found that `-march=native` can cause compilation errors and crashes on windows because of a bug in msys's `g++` which does not allow for AVX instruction sets.

In order to make sure _windows_ users don't include `-march=native` I think what we want to do is

1. On startup scan through the `CXX*FLAGS` from all the makevars returned from `get_all_makefile_paths()`
2. If `-march=native` exists in one of these, suggest the user calls the function `rstan:::setup_makevar_files(overwrite = TRUE)` which will make a backup of the Makevar files, then remove `-march=native` from the file.

`setup_makevar_flags` can look like

```R
setup_makevar_flags <- function(overwrite = FALSE, optimized = FALSE) {
   if (overwrite) {
    # write Makevars.bak files, then remove -march=native if it exists for windows users
    if (optimized) {
      # add performance flags like O3, -mtune=native, the -m* flags for windows
    }
   } else {
     # read the Makevars and print a makevar with changes
    if (optimized) {
      # add performance flags like O3, -mtune=native, the -m* flags for windows
    }
   }
}
```

If we want to detect the CPU type for setting the windows `-m*` flags we could detect the CPU type with something like the below from `benchmarkme`

https://www.rdocumentation.org/packages/benchmarkme/versions/1.0.4/source

Reading through the flags, I thought we would just need to change `CXX14FLAGS` but looking at the compilation code it looks like rstan actually [uses `CXXFLAGS`](https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/cxxfunplus.R#L209). Should that change to 

```R
cxxflags <- try(get_makefile_flags("CXX14FLAGS"))
```

**Comment by jgabry** [comment]
> Reading through the flags, I thought we would just need to change `CXX14FLAGS` but looking at the compilation code it looks like rstan actually [uses `CXXFLAGS`](https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/cxxfunplus.R#L209). Should that change to
> 
> ```r
> cxxflags <- try(get_makefile_flags("CXX14FLAGS"))
> ```

Not sure, good question. @bgoodri?

**Comment by bgoodri** [comment]
If there is a CXXFLAGS in ~/.R/Makevars{.win} it will get picked up, but
that code in cxxfunplus() doesn't actually do anything except store what
CXXFLAGS was.

**Comment by jgabry** [comment]
By the way, the withr package from rstudio people has a function for temporarily changing makevars contents:

```r
withr::with_makevars()
```

https://www.rdocumentation.org/packages/withr/versions/2.1.2/topics/with_makevars

**Comment by SteveBronder** [comment]
Oh that's awesome! I think what we want then is just a check if any of the `CXXFLAGS` has `-march=native` (for windows) and if so replace each with the same `CXXFLAGS` but without the `-march=native` using `with_makevars` in the `stan()` function. That plus we can add something like the `get_cpu` function from `benchmarkme` and add the `-m*` stuff if we want it for performance

**Comment by SteveBronder** [comment]
@bgoodri should we also put something in the rstan makevar.win that looks for `march=native` in `CXXFLAGS` on windows and throws a meaningful error?

**Comment by bgoodri** [comment]
Yeah, couldn't hurt.

**Comment by SteveBronder** [comment]
Aight I'll try to get something running tonight

**Comment by bgoodri** [comment]
The Windows computer in my office is rebooted if you want to test on that

**Comment by SteveBronder** [comment]
Didn't get around to this last night. Is there an easy way to read in someones `CXXFLAGS` from the packages `Makevars`? I tried putting 

```
  @echo $(error CXXFLAGS= $(CXXFLAGS))
```

under `all:` but it just turns up empty

**Comment by jgabry** [comment]
By the way `withr` also has `withr::with_path()`, which looks like it could potentially be useful
