### ISSUE TITLE
rstan fails to be installed on FreeBSD

### ISSUE THREAD

**Issue by jszhao** [stan-dev/rstan#805]
#### Summary:
rstan package fails to be installed on FreeBSD

#### Description:
When I try to install rstan package in R 4.0.2 on FreeBSD 12.1. However, it gives errors

#### Reproducible Steps:
install.packages("rstan")

#### Current Output:
Error: package or namespace load failed for 'rstan' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/00LOCK-rstan/00new/rstan/libs/rstan.so':
  /usr/local/lib/R/library/00LOCK-rstan/00new/rstan/libs/rstan.so: Undefined symbol "_ZN3tbb8internal26task_scheduler_observer_v37observeEb"
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/usr/local/lib/R/library/rstan'

#### Expected Output:
* DONE (rstan)

#### RStan Version:
rstan_2.21.1.tar.gz

#### R Version:
"R version 4.0.2 (2020-06-22)"

#### Operating System:
FreeBSD 12.1-RELEASE-p6 GENERIC  amd64

**Comment by jgabry** [comment]
Sorry you're getting an error. I don't have FreeBSD so I can't reproduce this myself, but the closest thing to this error message that I've seen recently was on the Stan forums

https://discourse.mc-stan.org/t/rstan-fails-to-install-on-centos-7/15957

but I'm not sure it's the same issue. Perhaps the same path @bbbales2 goes through to debug might work though. For starters, what are the contents of your `~/.R/Makevars` file? 

@bgoodri or @bbbales2 Any other ideas?

**Comment by bgoodri** [comment]
What does the call to the linker look like?

**Comment by jszhao** [comment]
> 
> 
> Sorry you're getting an error. I don't have FreeBSD so I can't reproduce this myself, but the closest thing to this error message that I've seen recently was on the Stan forums
> 
> https://discourse.mc-stan.org/t/rstan-fails-to-install-on-centos-7/15957
> 
> but I'm not sure it's the same issue. Perhaps the same path @bbbales2 goes through to debug might work though. For starters, what are the contents of your `~/.R/Makevars` file?
> 
> @bgoodri or @bbbales2 Any other ideas?

Thanks for the suggestions. I will try after I install a new virtual  new FreeBSD system.

Because of the experience in #728, I don't have `~/.R/Makevars`.

**Comment by jszhao** [comment]
> What does the call to the linker look like?

I don't know, `ldconfig -p` does not work on FreeBSD. The only thing that I know is the compilers for C/C++ are cc and c++, not the gcc and g++.

**Comment by bgoodri** [comment]
When you do

./R CMD INSTALL rstan_2.21.1.tar.gz

there should be something toward the end like

g++-8 -std=gnu++14 -shared -O3 -g0 -Wno-ignored-attributes
-Wno-deprecated-declarations -Wno-unknown-pragmas -fpic -L/usr/local/lib -o
rstan.so chains.o stan_fit_base.o init.o pointer-tools.o stanc.o Module.o
stan_fit_rccp.o misc.o sparse_extractors.o stan/lang/ast_def.o
stan/lang/grammars/program_grammar_inst.o
stan/lang/grammars/expression_grammar_inst.o
stan/lang/grammars/statement_grammar_inst.o
stan/lang/grammars/expression07_grammar_inst.o
stan/lang/grammars/statement_2_grammar_inst.o
stan/lang/grammars/block_var_decls_grammar_inst.o
stan/lang/grammars/indexes_grammar_inst.o
stan/lang/grammars/semantic_actions_def.o
stan/lang/grammars/whitespace_grammar_inst.o
stan/lang/grammars/bare_type_grammar_inst.o
stan/lang/grammars/local_var_decls_grammar_inst.o
stan/lang/grammars/term_grammar_inst.o
stan/lang/grammars/functions_grammar_inst.o
ar -rs ../inst/lib//libStanServices.a stan_fit.o stan_fit_base.o

**Comment by jszhao** [comment]
`R CMD INSTALL rstan_2.21.1.tar.gz` output something similar at the end:

```
c++ -std=gnu++14 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -Wl,-rpath=/usr/local/lib/gcc9 -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong -o rstan.so ... -L/usr/local/lib/R/lib -lR
c++ -std=gnu++14 ... -c stand_fit.cpp -o stan_fit.o
/usr/local/bin/ar -rs ../inst/lib//libStanServices.a stan_fit.o stan_fit_bas.o
```
Since I can not copy the output from the console of FreeBSD, I omit some object names when input the above by hand.

There are lots of warnings after the second line, like:
```
In file included from stan_fit.cpp:1:
In file included from ../inst/include/rstan_next/stan_fit.hpp:5:
In file included from ../inst/include/rstan_next/stan_fit_base.hpp:8:
...
...
/usr/local/lib/R/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning:
pragma diagnostic pop could not pop, no matching push [-Wunknow-pragmas]
```
However, they may have nothing with this issue. I see them frequently during installing various packages.

> 
> When you do ./R CMD INSTALL rstan_2.21.1.tar.gz there should be something toward the end like g++-8 -std=gnu++14 -shared -O3 -g0 -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-unknown-pragmas -fpic -L/usr/local/lib -o rstan.so chains.o stan_fit_base.o init.o pointer-tools.o stanc.o Module.o stan_fit_rccp.o misc.o sparse_extractors.o stan/lang/ast_def.o stan/lang/grammars/program_grammar_inst.o stan/lang/grammars/expression_grammar_inst.o stan/lang/grammars/statement_grammar_inst.o stan/lang/grammars/expression07_grammar_inst.o stan/lang/grammars/statement_2_grammar_inst.o stan/lang/grammars/block_var_decls_grammar_inst.o stan/lang/grammars/indexes_grammar_inst.o stan/lang/grammars/semantic_actions_def.o stan/lang/grammars/whitespace_grammar_inst.o stan/lang/grammars/bare_type_grammar_inst.o stan/lang/grammars/local_var_decls_grammar_inst.o stan/lang/grammars/term_grammar_inst.o stan/lang/grammars/functions_grammar_inst.o ar -rs ../inst/lib//libStanServices.a stan_fit.o stan_fit_base.o

**Comment by jszhao** [comment]
Here, `c++` is from `clang version 8.0.1.

**Comment by jszhao** [comment]
```
c++filt _ZN3tbb8internal26task_scheduler_observer_v37observeEb
```
gives
```
tbb::internal::task_scheduler_observer_v3::observe(bool)
```

my question is which package or lib provide the above function?

**Comment by bgoodri** [comment]
RcppParallel but it needs a valid linker statement. What is the output of

RcppParallel::LdFlags()

?

**Comment by jszhao** [comment]
> 
> RcppParallel but it needs a valid linker statement. What is the output of RcppParallel::LdFlags() ?

There is no output of `RcppParallel::LdFlags()`. 

After put the following lines into `~/.R/Makevars`, I got rstan installed, but I don't know if it would work properly.
```
LDFLAGS += -L/usr/local/lib -ltbb -ltbbmalloc
```

**Comment by jszhao** [comment]
> After put the following lines into `~/.R/Makevars`, I got rstan installed, but I don't know if it would work properly.
> 
> ```
> LDFLAGS += -L/usr/local/lib -ltbb -ltbbmalloc
> ```

by the way, I have installed tbb package on FreeBSD before installing rstan.

**Comment by bgoodri** [comment]
Yeah, that probably will work. My guess is that there is a bug in
RcppParallel::LdFlags() for FreeBSD.

**Comment by jszhao** [comment]
> Yeah, that probably will work. My guess is that there is a bug in RcppParallel::LdFlags() for FreeBSD.
> […](#)

I think your guess is right.
```
  tbbSupported <- list(
      "Darwin" = paste("libtbb", suffix, ".dylib", sep = ""), 
      "Linux" = paste("libtbb", suffix, ".so.2", sep = ""), 
      "Windows" = paste("tbb", suffix, ".dll", sep = ""),
      "SunOS" = paste("libtbb", suffix, ".so", sep = "")
   )
```

**Comment by bgoodri** [comment]
You might raise an issue at

https://github.com/RcppCore/RcppParallel/issues/
