### ISSUE TITLE
the true model to calculate the Bayes factor with bridge sampling

### ISSUE THREAD

**Issue by yu-zhang-oYo** [stan-dev/rstan#813]
#### Summary:
I want to use bridge_sampler to calculate log marginal likelihood, but I get different values with different way to construct model. 

#### Description:
For regression models that include a categorical variable (e.g. ANOVA), heterogeneity manifests as vastly different variances for different levels (treatment groups) of the categorical variable. I use rstan to constrcut a model.

I want to calculate Bayes Factor, so I first use bridge_sampler to calculate log marginal likelihood. Since lp__ in rstan is the log likelihood with constants dropped if I use x ~normal(mu,sigma). While the user guide says that normal_lpdf(reals y | reals mu, reals sigma) doesn't have the problem. So I use both of them to construct the model and find that lp__ in both of them are not equal to the true lp that I calculate. I don't know the reason. 

Next, I use bridge_sampler to calculate the  log marginal likelihood of them. And I get different logml. I don't know which one is right.

Thanks very much if anyone can help me.

#### Reproducible Steps:

1. generate data:

```
set.seed(1)
ngroups <- 5  #number of populations
nsample <- 10  #number of reps in each
pop.means <- c(40, 45, 55, 40, 30)  #population mean length
sigma <- rep(c(6, 4, 2, 0.5, 1), each = nsample)  #residual standard deviation
n <- ngroups * nsample  #total sample size
eps <- rnorm(n, 0, sigma)  #residuals
x <- gl(ngroups, nsample, n, lab = LETTERS[1:5])  #factor
means <- rep(pop.means, rep(nsample, ngroups))
X <- model.matrix(~x - 1)  #create a design matrix
y <- as.numeric(X %*% pop.means + eps)
data.het1 <- data.frame(y, x)
boxplot(y ~ x, data.het1)
Xmat <- model.matrix(~x, data.het1)
data.het1.list <- with(data.het1, list(y = y, X = Xmat, n = nrow(data.het1), nX = ncol(Xmat)))

```

2.  model fit with modelString: normal(mu, sigma) and  modelString1: target += normal_lpdf( y | mu, sig );

```
library("rstan") # observe startup messages
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
modelString = "
  data {
  int<lower=1> n;
  int<lower=1> nX;
  vector [n] y;
  matrix [n,nX] X;
  }
  parameters {
  vector[nX] beta;
  vector<lower=0>[nX] sigma;
  }
  transformed parameters {
  vector[n] mu;
  vector<lower=0>[n] sig;

  mu = X*beta;
  sig = X*sigma;
  }
  model {
  //Likelihood
  y~normal(mu,sig);
  
  //Priors
  beta ~ normal(0,1000);
  sigma~cauchy(0,5);
  }
  generated quantities {
  real lpd;
  lpd = normal_lpdf(y| mu, sig);
  }
  "
```
```
modelString1 = "
  data {
  int<lower=1> n;
  int<lower=1> nX;
  vector [n] y;
  matrix [n,nX] X;
  }
  parameters {
  vector[nX] beta;
  vector<lower=0>[nX] sigma;
  }
  transformed parameters {
  vector[n] mu;
  vector<lower=0>[n] sig;

  mu = X*beta;
  sig = X*sigma;
  }
  model {
  // Likelihood
  target += normal_lpdf( y | mu, sig );
  
  //Priors
  target += normal_lpdf( beta | 0, 1000 );
  target += cauchy_lpdf( sigma | 0, 5 );

  }
  generated quantities {
  real lpd;
  lpd = normal_lpdf(y| mu, sig);
  }
  "
```

3.  output lp in rstan and true lp

```
data.het1.rstan <- stan(data = data.het1.list, model_code = modelString, chains = 3, iter = 2000, warmup = 500, thin = 3)

ex<-extract(data.het1.rstan)
tlp<-ex$lpd
lp<-ex$lp__
cons = log(1/sqrt(2 * pi))
cbind(lp,tlp)
```
```
data.het1.rstan1 <- stan(data = data.het1.list, model_code = modelString1, chains = 3, iter = 2000, warmup = 500, thin = 3)

ex<-extract(data.het1.rstan1)
tlp<-ex$lpd
lp<-ex$lp__
cons = log(1/sqrt(2 * pi))
cbind(lp,tlp)
```

4. bridge_sampler to calculate log marginal likelihood

bridgesampling::bridge_sampler(data.het1.rstan)$logml
bridgesampling::bridge_sampler(data.het1.rstan1)$logml

#### Current Output:

1. lp
![image](https://user-images.githubusercontent.com/58363119/88391017-e9b23380-cdeb-11ea-8695-3a3609e7e468.png)

![image](https://user-images.githubusercontent.com/58363119/88391050-f6368c00-cdeb-11ea-8b14-e760289a597a.png)

2. log marginal likelihood
![image](https://user-images.githubusercontent.com/58363119/88391253-66dda880-cdec-11ea-93d3-99daa441b60e.png)

**Comment by jgabry** [comment]
If I understand correctly, I think the issue here is just that  `lp__` isn't only the log-likelihood, it includes the log priors too. `lp__` is the log _posterior_ (possibly dropping constants depending on how it's coded).

**Comment by singmann** [comment]
After a few users of `bridgesampling` have reported that with the current `rstan` version the results do not match the ones in our JSS paper, I have investigated the issue and found a bug in `rstan` that is probably also responsible for the present error. 

In current `rstan`, setting `adjust_transform = TRUE` in the `log_prob` method (which is the default) does not work any more. The following is a minimal reproducible example:

```r
# Sleep data from t.test example
data(sleep)

# compute difference scores
y <- sleep$extra[sleep$group == 2] - sleep$extra[sleep$group == 1]
n <- length(y)
library(rstan)

# models
stancodeH0 <- '
data {
  int<lower=1> n; // number of observations
  vector[n] y; // observations
}
parameters {
  real<lower=0> sigma2; // variance parameter
}
model {
  target += log(1/sigma2); // Jeffreys prior on sigma2
  target += normal_lpdf(y | 0, sqrt(sigma2)); // likelihood
}
'
stanmodelH0 <- stan_model(model_code = stancodeH0, model_name="stanmodel")

stanfitH0 <- sampling(stanmodelH0, data = list(y = y, n = n),
                      iter = 20000, warmup = 1000, chains = 4, cores = 1,
                      control = list(adapt_delta = .99))
rstan::log_prob(object = stanfitH0, upars = 1, adjust_transform = TRUE)
# [1] -22.28578 
# should be: [1] -21.28578

rstan::log_prob(object = stanfitH0, upars = 1, adjust_transform = FALSE)
# [1] -22.28578
# should be: [1] -22.28578
```

This shows that `log_prob` gives the same return value in both cases which was not the case in previous version (results that "should be" are from `StanHeaders` `2.19.2` and `rstan` `2.19.3`). 

For reference:
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.21.2         ggplot2_3.3.2.9000   StanHeaders_2.21.0-6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         pillar_1.4.6       compiler_4.0.2     prettyunits_1.1.1  tools_4.0.2       
 [6] packrat_0.5.0      pkgbuild_1.1.0     jsonlite_1.7.0     lifecycle_0.2.0    tibble_3.0.3      
[11] gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.7        cli_2.0.2          rstudioapi_0.11   
[16] parallel_4.0.2     curl_4.3           loo_2.3.1          gridExtra_2.3      withr_2.2.0       
[21] dplyr_1.0.0        generics_0.0.2     vctrs_0.3.2        stats4_4.0.2       grid_4.0.2        
[26] tidyselect_1.1.0   glue_1.4.1         inline_0.3.15      R6_2.4.1           processx_3.4.3    
[31] fansi_0.4.1        purrr_0.3.4        callr_3.4.3        magrittr_1.5       codetools_0.2-16  
[36] matrixStats_0.56.0 scales_1.1.1       ps_1.3.3           ellipsis_0.3.1     assertthat_0.2.1  
[41] colorspace_1.4-1   V8_3.2.0           RcppParallel_5.0.2 munsell_0.5.0      crayon_1.3.4  
```

**Comment by avehtari** [comment]
Ouch, that's bad. This will probably affect moment matching in loo, too.

**Comment by bgoodri** [comment]
This is fixed by 901c97ae

**Comment by jgabry** [comment]
Yeah that's bad. @singmann Thanks for finding and reporting this!  @bgoodri thanks for fixing. How did this bug get introduced and can we add a test to avoid it happening again?

**Comment by bgoodri** [comment]
They changed the names of the functions in the Stan library in 2.20 for the
CRTP so now there is log_prob(), log_prob_propto(), and log_prob_jacobian()
and we were calling log_prob() like we were before when we were supposed to
be calling log_prob_jacobian() now.

**Comment by singmann** [comment]
Thanks for fixing it so quickly and pushing to CRAN. I can confirm that things work again on our end.

And I guess it could have been detected earlier, as all our `rstan` related unit tests started failing with with this bug. But of course, they are all disabled on CRAN to save checking time on the CRAN servers.

**Comment by jgabry** [comment]
> They changed the names of the functions in the Stan library in 2.20 for the CRTP so now there is log_prob(), log_prob_propto(), and log_prob_jacobian() and we were calling log_prob() like we were before when we were supposed to be calling log_prob_jacobian() now.

Are there any tests for the `rstan::log_prob()` method? It seems like this should have been caught by any test that just expects `rstan::log_prob()` to return different answers with `adjust_transform = TRUE` vs `adjust_transform = FALSE`. 

> And I guess it could have been detected earlier, as all our `rstan` related unit tests started failing with with this bug. But of course, they are all disabled on CRAN to save checking time on the CRAN servers.

@singmann no worries! Stuff like this really shouldn't break between RStan releases even if the functions in Stan change. 

@ariddell @ahartikainen Pinging you just in case this needs to be fixed in PyStan too.

**Comment by riddell-stan** [comment]
This seems like a backwards-incompatible change in Stan (log_prob). How did this happen so quietly, without a major version bump or deprecation notice?

**Comment by bob-carpenter** [comment]
> This seems like a backwards-incompatible change in Stan (log_prob). 

This was a while ago, but I thought the resulting model class was backwards compatible with the old one.  What changed that's causing problems?

> How did this happen so quietly, without a major version bump or deprecation notice?

It felt noisy while the renovation was going on!  It required basic changes to the model class and code generation and a major rewrite of the makefiles to allow independent compilation of a translation unit with the algorithms.

**Comment by bob-carpenter** [comment]
The non-template method log_prob_jacobian() is there to allow it to be virtual and thus support the CRTP.  The `log_prob()` function should work like before.  The current signature for `log_prob` in the generated model class is:

```
  template <bool propto, bool jacobian, typename T>
  inline T log_prob(std::vector<T>& params_r,
                      std::vector<int>& params_i,
                      std::ostream* pstream = nullptr) const;
```

Did that change somehow?

**Comment by bgoodri** [comment]
I could have gotten the changes right the first time but didn't. In RStan
2.19.x (without CRTP) we were doing

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/inst/include/rstan/stan_fit.hpp#L1122

but after the change to CRTP, I initially changed it to call log_prob
without a template argument in the first case and log_prob_propto in the
second case. Now, it is calling log_prob_jacobian in the first case, which
makes it equivalent to what it was returning before.
