### ISSUE TITLE
sh: clang++ -mmacosx-version-min=10.13: command not found The NEXT version of Stan will not be able to pre-process your Stan program.

### ISSUE THREAD

**Issue by RossClaytor449** [stan-dev/rstan#816]
Running on MacOS Catalina 10.15.6
Using Rethinking package to work through chapter 12 of Rethinking Statistics book by Richard McElreath. m12.1 example using ulam function

library(rethinking)
#For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores())
#To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
pbar <- 0.5
theta <- 5
curve( dbeta2(x,pbar,theta) , from=0 , to =1 ,
       xlab="probability" , ylab="Density")

## UCBadmit data example with ulam page 371
data("UCBadmit")
d <- UCBadmit
d
d$gid <- ifelse( d$applicant.gender=="male", 1L , 2L)
dat <- list( A=d$admit, N=d$applications, gid=d$gid )
dat
m12.1 <- ulam(
  alist(
    A ~ dbetabinom( N , pbar , theta ) ,
    logit(pbar) <- a[gid] ,
    a[gid] ~ dnorm( 0 , 1.5 ) ,
    transpars> theta <<- phi + 2.0 ,
    phi ~ dexp(1)
  ), data=dat, chains = 4

**Comment by jgabry** [comment]
@RossClaytor449 thanks for reporting. If you're just getting a warning I think this is a false positive. If you're getting an error that prevents the model from running then it seems similar to this issue https://github.com/stan-dev/rstan/issues/774. Over there people had success with removing rstan (`remove.packages("rstan")`), restarting R and then installing RStan from GitHub using

remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")

**Comment by RossClaytor449** [comment]
Hello Josh,
Thank you I will try that.

All the best, Ross

**Comment by jgabry** [comment]
Going to close this due to inactivity, but please let me know if there's still a problem and I'll reopen
