### ISSUE TITLE
sh: clang++ -mmacosx-version-min=10.13: command not found

### ISSUE THREAD

**Issue by DJamesWilliamson** [stan-dev/rstan#817]
The NEXT version of Stan will not be able to pre-process your Stan program.

From boarding school example
https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html
Model successfully compiled but with this warning and recommendation to raise issue on Github

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3        rstan_2.21.1         StanHeaders_2.21.0-5 forcats_0.5.0       
 [5] stringr_1.4.0        dplyr_1.0.0          purrr_0.3.4          readr_1.3.1         
 [9] tidyr_1.1.0          tibble_3.0.3         ggplot2_3.3.2        tidyverse_1.3.0     
[13] outbreaks_1.5.0     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         lubridate_1.7.9    prettyunits_1.1.1  ps_1.3.3           V8_3.2.0          
 [6] assertthat_0.2.1   digest_0.6.25      R6_2.4.1           cellranger_1.1.0   backports_1.1.8   
[11] reprex_0.3.0       stats4_4.0.2       evaluate_0.14      httr_1.4.2         pillar_1.4.6      
[16] rlang_0.4.7        curl_4.3           readxl_1.3.1       rstudioapi_0.11    callr_3.4.3       
[21] blob_1.2.1         rmarkdown_2.3      labeling_0.3       loo_2.3.1          munsell_0.5.0     
[26] broom_0.7.0        compiler_4.0.2     modelr_0.1.8       xfun_0.15          pkgconfig_2.0.3   
[31] pkgbuild_1.1.0     htmltools_0.5.0    tidyselect_1.1.0   codetools_0.2-16   matrixStats_0.56.0
[36] fansi_0.4.1        crayon_1.3.4       dbplyr_1.4.4       withr_2.2.0        grid_4.0.2        
[41] jsonlite_1.7.0     gtable_0.3.0       lifecycle_0.2.0    DBI_1.1.0          magrittr_1.5      
[46] scales_1.1.1       RcppParallel_5.0.2 cli_2.0.2          stringi_1.4.6      farver_2.0.3      
[51] fs_1.4.2           xml2_1.3.2         ellipsis_0.3.1     generics_0.0.2     vctrs_0.3.2       
[56] tools_4.0.2        glue_1.4.1         hms_0.5.3          processx_3.4.3     parallel_4.0.2    
[61] yaml_2.2.1         inline_0.3.15      colorspace_1.4-1   rvest_0.3.5        knitr_1.29        
[66] haven_2.3.1 

[epidemic_simulation.txt](https://github.com/stan-dev/stanc3/files/4966425/epidemic_simulation.txt)
[sir_negbin.txt](https://github.com/stan-dev/stanc3/files/4966428/sir_negbin.txt)

**Comment by DJamesWilliamson** [comment]
What should I do? I have latest Xtools. Would installing rstan from GH help?
remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan", build_opts = "")

**Comment by tfjaeger** [comment]
I get the exact same error message, after updating to R 4.0.2 on Mac OS High Sierra. I already uninstalled and re-installed Rstan, following the instructions at https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started (which btw contains a few broken links right in the first paragraph; and the link to " Checking the C++ Toolchain" leads to wiki edit page). Any suggestions would be welcome.

`─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-07-26                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package        * version  date       lib source        
 abind            1.4-5    2016-07-21 [1] CRAN (R 4.0.2)
 assertthat       0.2.1    2019-03-21 [1] CRAN (R 4.0.2)
 backports        1.1.8    2020-06-17 [1] CRAN (R 4.0.2)
 base64enc        0.1-3    2015-07-28 [1] CRAN (R 4.0.2)
 bayesplot        1.7.2    2020-05-28 [1] CRAN (R 4.0.2)
 blob             1.2.1    2020-01-20 [1] CRAN (R 4.0.2)
 bridgesampling   1.0-0    2020-02-26 [1] CRAN (R 4.0.2)
 brms           * 2.13.3   2020-07-13 [1] CRAN (R 4.0.2)
 Brobdingnag      1.2-6    2018-08-13 [1] CRAN (R 4.0.2)
 broom            0.7.0    2020-07-09 [1] CRAN (R 4.0.2)
 callr            3.4.3    2020-03-28 [1] CRAN (R 4.0.2)
 cellranger       1.1.0    2016-07-27 [1] CRAN (R 4.0.2)
 cli              2.0.2    2020-02-28 [1] CRAN (R 4.0.2)
 coda             0.19-3   2019-07-05 [1] CRAN (R 4.0.2)
 codetools        0.2-16   2018-12-24 [1] CRAN (R 4.0.2)
 colorspace       1.4-1    2019-03-18 [1] CRAN (R 4.0.2)
 colourpicker     1.0      2017-09-27 [1] CRAN (R 4.0.2)
 crayon           1.3.4    2017-09-16 [1] CRAN (R 4.0.2)
 crosstalk        1.1.0.1  2020-03-13 [1] CRAN (R 4.0.2)
 curl             4.3      2019-12-02 [1] CRAN (R 4.0.1)
 DBI              1.1.0    2019-12-15 [1] CRAN (R 4.0.2)
 dbplyr           1.4.4    2020-05-27 [1] CRAN (R 4.0.2)
 desc             1.2.0    2018-05-01 [1] CRAN (R 4.0.2)
 devtools       * 2.3.1    2020-07-21 [1] CRAN (R 4.0.2)
 digest           0.6.25   2020-02-23 [1] CRAN (R 4.0.2)
 dplyr          * 1.0.0    2020-05-29 [1] CRAN (R 4.0.2)
 DT               0.14     2020-06-24 [1] CRAN (R 4.0.2)
 dygraphs         1.1.1.6  2018-07-11 [1] CRAN (R 4.0.2)
 ellipsis         0.3.1    2020-05-15 [1] CRAN (R 4.0.2)
 emmeans          1.4.8    2020-06-26 [1] CRAN (R 4.0.2)
 estimability     1.3      2018-02-11 [1] CRAN (R 4.0.2)
 fansi            0.4.1    2020-01-08 [1] CRAN (R 4.0.2)
 fastmap          1.0.1    2019-10-08 [1] CRAN (R 4.0.2)
 forcats        * 0.5.0    2020-03-01 [1] CRAN (R 4.0.2)
 fs               1.4.2    2020-06-30 [1] CRAN (R 4.0.2)
 generics         0.0.2    2018-11-29 [1] CRAN (R 4.0.2)
 ggplot2        * 3.3.2    2020-06-19 [1] CRAN (R 4.0.2)
 ggridges         0.5.2    2020-01-12 [1] CRAN (R 4.0.2)
 glue             1.4.1    2020-05-13 [1] CRAN (R 4.0.2)
 gridExtra        2.3      2017-09-09 [1] CRAN (R 4.0.2)
 gtable           0.3.0    2019-03-25 [1] CRAN (R 4.0.2)
 gtools           3.8.2    2020-03-31 [1] CRAN (R 4.0.2)
 haven            2.3.1    2020-06-01 [1] CRAN (R 4.0.2)
 hms              0.5.3    2020-01-08 [1] CRAN (R 4.0.2)
 htmltools        0.5.0    2020-06-16 [1] CRAN (R 4.0.2)
 htmlwidgets      1.5.1    2019-10-08 [1] CRAN (R 4.0.2)
 httpuv           1.5.4    2020-06-06 [1] CRAN (R 4.0.2)
 httr             1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
 igraph           1.2.5    2020-03-19 [1] CRAN (R 4.0.2)
 inline           0.3.15   2018-05-18 [1] CRAN (R 4.0.2)
 jsonlite         1.7.0    2020-06-25 [1] CRAN (R 4.0.2)
 later            1.1.0.1  2020-06-05 [1] CRAN (R 4.0.2)
 lattice          0.20-41  2020-04-02 [1] CRAN (R 4.0.2)
 lifecycle        0.2.0    2020-03-06 [1] CRAN (R 4.0.2)
 loo              2.3.1    2020-07-14 [1] CRAN (R 4.0.2)
 lubridate        1.7.9    2020-06-08 [1] CRAN (R 4.0.2)
 magrittr       * 1.5      2014-11-22 [1] CRAN (R 4.0.2)
 markdown         1.1      2019-08-07 [1] CRAN (R 4.0.2)
 MASS             7.3-51.6 2020-04-26 [1] CRAN (R 4.0.2)
 Matrix           1.2-18   2019-11-27 [1] CRAN (R 4.0.2)
 matrixStats      0.56.0   2020-03-13 [1] CRAN (R 4.0.2)
 memoise          1.1.0    2017-04-21 [1] CRAN (R 4.0.2)
 mime             0.9      2020-02-04 [1] CRAN (R 4.0.2)
 miniUI           0.1.1.1  2018-05-18 [1] CRAN (R 4.0.2)
 modelr           0.1.8    2020-05-19 [1] CRAN (R 4.0.2)
 multcomp         1.4-13   2020-04-08 [1] CRAN (R 4.0.2)
 munsell          0.5.0    2018-06-12 [1] CRAN (R 4.0.2)
 mvtnorm          1.1-1    2020-06-09 [1] CRAN (R 4.0.2)
 nlme             3.1-148  2020-05-24 [1] CRAN (R 4.0.2)
 packrat          0.5.0    2018-11-14 [1] CRAN (R 4.0.2)
 pillar           1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
 pkgbuild         1.1.0    2020-07-13 [1] CRAN (R 4.0.2)
 pkgconfig        2.0.3    2019-09-22 [1] CRAN (R 4.0.2)
 pkgload          1.1.0    2020-05-29 [1] CRAN (R 4.0.2)
 plyr             1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
 prettyunits      1.1.1    2020-01-24 [1] CRAN (R 4.0.2)
 processx         3.4.3    2020-07-05 [1] CRAN (R 4.0.2)
 promises         1.1.1    2020-06-09 [1] CRAN (R 4.0.2)
 ps               1.3.3    2020-05-08 [1] CRAN (R 4.0.2)
 purrr          * 0.3.4    2020-04-17 [1] CRAN (R 4.0.2)
 R6               2.4.1    2019-11-12 [1] CRAN (R 4.0.2)
 Rcpp           * 1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
 RcppParallel     5.0.2    2020-06-24 [1] CRAN (R 4.0.2)
 readr          * 1.3.1    2018-12-21 [1] CRAN (R 4.0.2)
 readxl           1.3.1    2019-03-13 [1] CRAN (R 4.0.2)
 remotes          2.2.0    2020-07-21 [1] CRAN (R 4.0.2)
 reprex           0.3.0    2019-05-16 [1] CRAN (R 4.0.2)
 reshape2         1.4.4    2020-04-09 [1] CRAN (R 4.0.2)
 rlang            0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
 rprojroot        1.3-2    2018-01-03 [1] CRAN (R 4.0.2)
 rsconnect        0.8.16   2019-12-13 [1] CRAN (R 4.0.2)
 rstan          * 2.21.1   2020-07-08 [1] CRAN (R 4.0.2)
 rstantools       2.1.1    2020-07-06 [1] CRAN (R 4.0.2)
 rstudioapi       0.11     2020-02-07 [1] CRAN (R 4.0.2)
 rvest            0.3.6    2020-07-25 [1] CRAN (R 4.0.2)
 sandwich         2.5-1    2019-04-06 [1] CRAN (R 4.0.2)
 scales           1.1.1    2020-05-11 [1] CRAN (R 4.0.2)
 sessioninfo      1.1.1    2018-11-05 [1] CRAN (R 4.0.2)
 shiny            1.5.0    2020-06-23 [1] CRAN (R 4.0.2)
 shinyjs          1.1      2020-01-13 [1] CRAN (R 4.0.2)
 shinystan        2.5.0    2018-05-01 [1] CRAN (R 4.0.2)
 shinythemes      1.1.2    2018-11-06 [1] CRAN (R 4.0.2)
 StanHeaders    * 2.21.0-5 2020-06-09 [1] CRAN (R 4.0.2)
 stringi          1.4.6    2020-02-17 [1] CRAN (R 4.0.2)
 stringr        * 1.4.0    2019-02-10 [1] CRAN (R 4.0.2)
 survival         3.2-3    2020-06-13 [1] CRAN (R 4.0.2)
 testthat         2.3.2    2020-03-02 [1] CRAN (R 4.0.2)
 TH.data          1.0-10   2019-01-21 [1] CRAN (R 4.0.2)
 threejs          0.3.3    2020-01-21 [1] CRAN (R 4.0.2)
 tibble         * 3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
 tidyr          * 1.1.0    2020-05-20 [1] CRAN (R 4.0.2)
 tidyselect       1.1.0    2020-05-11 [1] CRAN (R 4.0.2)
 tidyverse      * 1.3.0    2019-11-21 [1] CRAN (R 4.0.2)
 usethis        * 1.6.1    2020-04-29 [1] CRAN (R 4.0.2)
 V8               3.2.0    2020-06-19 [1] CRAN (R 4.0.2)
 vctrs            0.3.2    2020-07-15 [1] CRAN (R 4.0.2)
 withr            2.2.0    2020-04-20 [1] CRAN (R 4.0.2)
 xml2             1.3.2    2020-04-23 [1] CRAN (R 4.0.2)
 xtable           1.8-4    2019-04-21 [1] CRAN (R 4.0.2)
 xts              0.12-0   2020-01-19 [1] CRAN (R 4.0.2)
 zoo              1.8-8    2020-05-02 [1] CRAN (R 4.0.2)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library`

**Comment by jgabry** [comment]
Sorry for the hassle. Yeah installing from GitHub seems to have helped for some people, e.g. in this related issue: https://github.com/stan-dev/rstan/issues/774#issuecomment-663639919

**Comment by jgabry** [comment]
Going to close this due to inactivity but if this is still a problem please let me know and I'll reopen
