### ISSUE TITLE
Fix for eigen pragma warnings

### ISSUE THREAD

**Issue by thk686** [stan-dev/rstan#820]
Compiling against Eigen generates pages of warnings like:

```
warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
```

This was happening in one of my packages, so I poked around in the Eigen code and discovered you simply need to 

```
#define EIGEN_PERMANENTLY_DISABLE_STUPID_WARNINGS
#include <Eigen/Eigen>
```

I was just installing rstan from source on my computer and noticed the stream of warnings and thought I would pass this along.

**Comment by jgabry** [comment]
Thanks for this. I agree those warnings are annoying. Tagging @bgoodri in case he hasn't seen this. 

> EIGEN_PERMANENTLY_DISABLE_STUPID_WARNINGS

Nice!

**Comment by bgoodri** [comment]
CRAN made RcppEigen insert code to reenable those stupid warnings

https://github.com/RcppCore/RcppEigen/blob/7d3183d31469135cd496e11628530ad5cf9d8bb7/inst/include/Eigen/src/Core/util/ReenableStupidWarnings.h

**Comment by jgabry** [comment]
Ugh, that’s unfortunate

**Comment by jgabry** [comment]
Closing since it seems like this nice solution isn't allowed by CRAN
