### ISSUE TITLE
rstan:::data_preprocess() drops dimensions of zero-dim arrays

### ISSUE THREAD

**Issue by mespe** [stan-dev/rstan#837]
#### Summary:
rstan:::data_preprocess() drops dimensions of zero-dim arrays

#### Description:

When called with logical arrays of zero dimensions, data_preprocess()'s step of making logical data integers drops the dimensions of the array.

The error is happening in:

```
} else if (is.logical(x)) {
                     x <- as.integer(x)
```

This can be avoided using `storage.mode(x) = "integer"`

#### Reproducible Steps:
```
x = list(a = array(logical(), dim = c(10,0)))
rstan:::data_preprocess(x)
```

#### Current Output:
$a
integer(0)

#### Expected Output:

Integer array with original dims.

#### RStan Version:

2.21.2

#### R Version:
4.0.2

#### Operating System:

Arch Linux

**Comment by jgabry** [comment]
Thanks for reporting this. Does indeed seem like a bug. I'll take a look at the PR now.

**Comment by jgabry** [comment]
closing after merging #838
