### ISSUE TITLE
Installation of development version fails on Mac Catalina 10.15.6

### ISSUE THREAD

**Issue by elinalutz** [stan-dev/rstan#840]
#### Summary:
Installation of development version using `remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")` fails on Mac Catalina 10.15.6.

#### Reproducible Steps:
`remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")`

#### Current Output:

      In file included from Module.cpp:1:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'signbit' in the global namespace
      using ::signbit;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'fpclassify' in the global namespace
      using ::fpclassify;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
        using ::isfinite;
      ~~^
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:749:12: note: 'finite' declared here
      extern int finite(double)
      ^
        In file included from Module.cpp:1:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isinf' in the global namespace
      using ::isinf;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnan' in the global namespace
      using ::isnan;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'isnormal' in the global namespace
      using ::isnormal;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'isgreater' in the global namespace
      using ::isgreater;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isgreaterequal' in the global namespace
      using ::isgreaterequal;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isless' in the global namespace
      using ::isless;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessequal' in the global namespace
      using ::islessequal;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'islessgreater' in the global namespace
      using ::islessgreater;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
      using ::isunordered;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:330:9: error: no member named 'isunordered' in the global namespace
      using ::isunordered;
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:336:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
        using ::abs;
      ~~^
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:417:15: note: 'fabs' declared here
      extern double fabs(double);
      ^
        In file included from Module.cpp:1:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
        In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:641:26: error: use of undeclared identifier 'numeric_limits'
      bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:641:41: error: '_FloatT' does not refer to a value
      bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:640:30: note: declared here
      template <class _IntT, class _FloatT,
      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:641:51: error: no member named 'digits' in the global namespace
      bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
      ~~^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:641:60: error: use of undeclared identifier 'numeric_limits'
      bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:641:75: error: '_IntT' does not refer to a value
      bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
      ^
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:640:17: note: declared here
      template <class _IntT, class _FloatT,
      ^
        fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      make: *** [Module.o] Error 1
      ERROR: compilation failed for package ‘rstan’
      * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan’
      Fehler: Failed to install 'rstan' from GitHub:
        (konvertiert von Warnung) installation of package ‘/var/folders/jn/bbxvxy8s0736mtvln57h37b40000gn/T//RtmpZ5LNdc/filef26202ea901/rstan_2.21.2.tar.gz’ had non-zero exit status

#### Expected Output:
Installation of RStan.

#### RStan Version:
Development version

#### R Version:
R4.0.2

#### Operating System:
OS Catalina 10.15.6

Any help is appreciated. Thanks!

**Comment by jgabry** [comment]
Hi, sorry you've getting an error! Can you share the contents of your Makevars file? You can check that using 

```r
file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars"))
```

**Comment by elinalutz** [comment]
I hope I did that correctly:

	# if you downloaded llvm manually above, replace with your chosen NEW_PATH/clang
	LLVM_LOC = /usr/local/opt/llvm
	CC=$(LLVM_LOC)/bin/clang -fopenmp
	CXX=$(LLVM_LOC)/bin/clang++ -fopenmp
	# -O3 should be faster than -O2 (default) level optimisation ..
	CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
	CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
	LDFLAGS=-L/usr/local/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib
	CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include

**Comment by jgabry** [comment]
Ok yeah I think some of those lines are causing a problem. I'm also on Catalina and my Makevars file looks like this: 

```
CXX14FLAGS=-O3 -march=native -mtune=native 
CXX14FLAGS += -arch x86_64 -ftemplate-depth-256
```

Just those two lines. What I recommend doing is copying the contents of your current Makevars file into some other file (so you have a backup in case you want/need to revert) and then replace all the lines in the actual Makevars file with the two lines above and see if that works.

**Comment by elinalutz** [comment]
I think that did the trick, thank you very much for your help! 
Is there an easy way to explain why it didn't work before?

**Comment by jgabry** [comment]
Glad that worked. I might be wrong, but I think it was pointing to the wrong compiler.
