### ISSUE TITLE
vb erroneously treats parameters containing double underscores as diagnostics causing error

### ISSUE THREAD

**Issue by thatchersj** [stan-dev/rstan#845]
#### Summary:
The `vb` method errors when using parameters with two underscores in their names (e.g. `my__y`) as it erroneously treats them as Stan diagnostic parameters (denoted by the suffix `__`). 

Fix available in #846 

#### Description:
The Stan Reference Manual ([6.2 Variables](https://mc-stan.org/docs/2_24/reference-manual/variables-section.html)) writes
> Variables must start with a letter (`a--z` and `A--Z`) and may not end with two underscores (`__`).

I believe that this restriction is in place as the suffix `__` is used to denote diagnostic columns used internally by Stan. However, it does not preclude the use of double underscores elsewhere in variable names.

After sampling, the `vb` function looks for the diagnostic parameters in the `samples` object with the line below, which looks for any names containing `__`, rather than names terminating in `__`.
> `diagnostic_columns <- which(grepl("__", colnames(samples)))[-1]`

The `vb` method goes on to split the diagnostic columns off from the samples dataset. However, in the case where there are variable names containing a double underscore, this step removes those columns erroneously, causing an error later in the function.

In order to detect and split off only the desired diagnostic columns the line above should read as follows:
> `diagnostic_columns <- which(grepl("__$", colnames(samples)))[-1]`

#### Reproducible Steps:
The following code (modified from the example in the documentation for `vb`) will reproduce the error
```
m <- stan_model(model_code = 'parameters {real my__y;} model {my__y ~ normal(0,1);}')
f <- vb(m, iter = 1)
```
A slightly different error is thrown with more than one parameter in the model, e.g.
```
m <- stan_model(model_code = 'parameters {real my__y; real x;} model {my__y ~ normal(0,1);}')
f <- vb(m, iter = 1)
```

#### Current Output:
With a single parameter we get an incorrect number of dimensions error as `samples` has only one column.
```
> m <- stan_model(model_code = 'parameters {real my__y;} model {my__y ~ normal(0,1);}')
> f <- vb(m, iter = 1)
Chain 1: ------------------------------------------------------------
Chain 1: EXPERIMENTAL ALGORITHM:
Chain 1:   This procedure has not been thoroughly tested and may be unstable
Chain 1:   or buggy. The interface is subject to change.
Chain 1: ------------------------------------------------------------
Chain 1: 
Chain 1: 
Chain 1: 
Chain 1: Gradient evaluation took 0 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Begin eta adaptation.
Chain 1: Iteration:   1 / 250 [  0%]  (Adaptation)
Chain 1: Iteration:  50 / 250 [ 20%]  (Adaptation)
Chain 1: Iteration: 100 / 250 [ 40%]  (Adaptation)
Chain 1: Iteration: 150 / 250 [ 60%]  (Adaptation)
Chain 1: Iteration: 200 / 250 [ 80%]  (Adaptation)
Chain 1: Success! Found best value [eta = 1] earlier than expected.
Chain 1: 
Chain 1: Begin stochastic gradient ascent.
Chain 1:   iter             ELBO   delta_ELBO_mean   delta_ELBO_med   notes 
Chain 1: Informational Message: The maximum number of iterations is reached! The algorithm may not have converged.
Chain 1: This variational approximation is not guaranteed to be meaningful.
Chain 1: 
Chain 1: Drawing a sample of size 1000 from the approximate posterior... 
Chain 1: COMPLETED.
Error in samples[1, -1] : incorrect number of dimensions
```

With more than one parameter, the error given is "undefined columns selected"
```
> m <- stan_model(model_code = 'parameters {real my__y; real x;} model {my__y ~ normal(0,1);}')
> f <- vb(m, iter = 1)
Chain 1: ------------------------------------------------------------
Chain 1: EXPERIMENTAL ALGORITHM:
Chain 1:   This procedure has not been thoroughly tested and may be unstable
Chain 1:   or buggy. The interface is subject to change.
Chain 1: ------------------------------------------------------------
Chain 1: 
Chain 1: 
Chain 1: 
Chain 1: Gradient evaluation took 0 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Begin eta adaptation.
Chain 1: Iteration:   1 / 250 [  0%]  (Adaptation)
Chain 1: Iteration:  50 / 250 [ 20%]  (Adaptation)
Chain 1: Iteration: 100 / 250 [ 40%]  (Adaptation)
Chain 1: Iteration: 150 / 250 [ 60%]  (Adaptation)
Chain 1: Iteration: 200 / 250 [ 80%]  (Adaptation)
Chain 1: Success! Found best value [eta = 1] earlier than expected.
Chain 1: 
Chain 1: Begin stochastic gradient ascent.
Chain 1:   iter             ELBO   delta_ELBO_mean   delta_ELBO_med   notes 
Chain 1: Informational Message: The maximum number of iterations is reached! The algorithm may not have converged.
Chain 1: This variational approximation is not guaranteed to be meaningful.
Chain 1: 
Chain 1: Drawing a sample of size 1000 from the approximate posterior... 
Chain 1: COMPLETED.
Error in `[.data.frame`(cbind(samples[-1, -1, drop = FALSE], lp__ = samples[-1,  : 
  undefined columns selected
```

#### RStan Version:
2.19.3

#### R Version:
R version 4.0.0 (2020-04-24)

#### Operating System:
Windows 10

**Comment by jgabry** [comment]
Thanks for reporting this! Definitely seems like a bug.
