### ISSUE TITLE
Integer division operator suggested but not available

### ISSUE THREAD

**Issue by TuomoNieminen** [stan-dev/rstan#851]
#### Summary:

Integer division operator %/% suggested but not available.

#### Description:

I am using rstan R-package version 2.21.2 and stan version 2.21.0. When compiling a model, I am getting this message

```
Info: Found int division at 'string', line 29, column 16 to column 23:
  (N - 1) / SMOOTHING_WINDOW
Values will be rounded towards zero. If rounding is not desired you can write
the division as
  (N - 1) * 1.0 / SMOOTHING_WINDOW
If rounding is intended please use the integer division operator %/%.
```

I am intentionally using integer division to construct indices. When I try to use the integer division operator %/% as suggested in the message, the parser fails:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in 'model54c11a1e72dd_seroconversion_prevalence' at line 40, column 25
  -------------------------------------------------
    38: // number of periods and indices which link each day to a period
    39: transformed data {
    40:   int PERIODS = (N - 1) %/% SMOOTHING_WINDOW + 1;
```

#### Operating System:

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by jgabry** [comment]
This is strange. I think the integer division operator was introduced too recently to be included in the RStan release (it compiles for me with CmdStanR, which uses a newer Stan version, but not with RStan), but it seems like the error message suggesting it _did_ make it in to the release. 

@bgoodri Do you know how that's possible? 

@TuomoNieminen In this case you can just use the regular division operator if you indeed want the rounding behavior. The only difference between `/` and `%/%` is whether it prints the warning message.

**Comment by bgoodri** [comment]
I didn't think it was possible with 2.21.x.

**Comment by jgabry** [comment]
@rok-cesnovar or @nhuurre this isn't a huge problem, but do either of you know how it's possible to get the suggestion to use `%/%` without having a version of Stan where it's implemented?

**Comment by rok-cesnovar** [comment]
This is printed from the stanc3 check currently running in rstan. Its not possible that this is reported by stanc2.

**Comment by jgabry** [comment]
Ah ok it’s the stanc3 check that’s printing this! That makes sense. I didn’t realize the user was seeing messages like this. I thought we were just checking if it still compiled successfully.

**Comment by jgabry** [comment]
@bgoodri Can we avoid this sort of message displaying to the user but still check their program? It's pretty confusing to get a message recommending a function they can't use.

**Comment by bgoodri** [comment]
That is unfortunate, but I think most of the warnings that they could get
are things that they should change now. Possibly I could grep for %/%
before dumping the warnings out.

**Comment by jgabry** [comment]
Ok I guess if the vast majority of messages are applicable then it's ok.
Not ideal, but this stuff rarely is!

**Comment by bgoodri** [comment]
Actually, I can't catch this warning because it is printed directly by the
stanc3 parser.

**Comment by jgabry** [comment]
Ok i guess we’ll just live with it. Thanks for thinking about it.
