### ISSUE TITLE
strange incompatibility between rmutil package and rstan 2.21.2 

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/rstan#854]
#### Summary:
After loading rmutil, I cannot longer use `as.data.frame` on a Stan object, and Rstudio says that it's an "object with null pointer".
It happens also from the commandline.

#### Reproducible Steps:
```
set.seed(42)

library(rstan)
## Save compiled models:
rstan_options(auto_write = TRUE)
rstan_options(silent = TRUE, open_progress=FALSE,show_messages=FALSE)
## Parallelize the chains using all the cores:
options(mc.cores = parallel::detectCores())

# Solves a problem with V8
rstan_options(javascript = FALSE)

library(rmutil)

Y <- rnorm(1000, mean = 3, sd = 10)
  code <- "data {
    int<lower = 1> N;  // Total number of trials
    vector[N] y;  // Score in each trial
  }
  parameters {
    real mu;
    real<lower = 0> sigma;
  }
  model {
    // Priors:
      target += normal_lpdf(mu | 0, 20); 
      target += lognormal_lpdf(sigma | 3, 1); 
      // Likelihood:
        target += normal_lpdf(y | mu, sigma); 
  }
  "
  lst_score_data <-  list(y = Y, N = length(Y))
  # Fit the model with the default values of number of
  # chains and iterations: chains = 4, iter = 2000
  fit_score <- stan(model_code = code,
                    data = lst_score_data)
d <- as.data.frame(fit_score)
# Error in as.data.frame.default(f) : 
# cannot coerce class ‘"brmsfit"’ to a data.frame

```

If I don't load `library(rmutil)` everything works fine.

#### RStan Version:
‘2.21.3’

#### R Version:
"R version 4.0.2 (2020-06-22)"

#### Operating System:
Ubuntu 20.04.1 LTS

**Comment by bgoodri** [comment]
At first glance, I would say this is rmutil's fault. It redefines the `as.data.frame` generic function from base R and tries to call the default method rather than the one defined in the rstan namespace. Anyway, you can work around it by doing `d <- base::as.data.frame(fit_score)` at the end.

**Comment by jgabry** [comment]
This is definitely strange but I agree with @bgoodri that this is an issue with rmutil and not anything related to rstan or brms. If I load rmutil I get the message 

```
The following objects are masked from ‘package:base’:

    as.data.frame, units
```

so it's definitely overriding `as.data.frame` like @bgoodri mentioned.

**Comment by bnicenboim** [comment]
yes, you're right.
 I had a ton of weird problems but it seems that newest rstan in the repo + rstan_options(javascript = FALSE) solves everything then

**Comment by jgabry** [comment]
Glad you got rid of the weird errors. I’ve been there and hate when that happens!
