### ISSUE TITLE
Cannot run Stan in R ?

### ISSUE THREAD

**Issue by vanagpau** [stan-dev/rstan#856]
HI  - I'm new to Stan and working through a course on Bayesian modelling.

When I run this code;
library(rethinking)
data(Wines2012)
d <- Wines2012

dat_list <- list(S = standardize(d$score),
jid = as.integer(d$judge),
wid = as.integer(d$wine))

m1 <- ulam(alist(
S ~ dnorm( mu , sigma ),
mu <- a[jid] + w[wid],
a[jid] ~ dnorm(0,0.5),
w[wid] ~ dnorm(0,0.5),
sigma ~ dexp(1)), data=dat_list , chains=4 , cores=4)

I get this issue;
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\BEN10~1\AppData\Local\Temp\RtmpS6E4Od\file21504f9e6cf2.stan', reason 'No such file or directory'
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file2150102d7cbc.cpp 2> file2150102d7cbc.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file2150102d7cbc.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

I'm running R Studio 
Version 1.3.959
© 2009-2020 RStudio, PBC
"Middlemist Red" (3a09be39, 2020-05-18) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.6 Chrome/69.0.3497.128 Safari/537.36

Stan version 2.21.0

UPDATE: I updated RStan to 2.21.2 latest version but it still generates an error..

Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/rtools40/usr/mingw_/bin/g++' not found
2: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file550c6614374a.cpp 2> file550c6614374a.cpp.err.txt' had status 1
3: In file(con, "r") :
  cannot open file 'file550c6614374a.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

**Comment by seantalts** [comment]
Moved to rstan; looks like an issue with your toolchain. @vanagpau I assume since you came through `rethinking` you may not have seen this page RStan has on setting up one's build environment for R: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#installation-of-rstan There are some windows specific instructions using pkgBuild and Rtools you might need to follow.

**Comment by jgabry** [comment]
Thanks @seantalts, yeah this seems like an rstan issue. @vanagpau If the instructions that @seantalts linked to don't solve the problem for you can you post on the Stan forums (https://discourse.mc-stan.org/) and we'll help get rstan setup for you?

**Comment by vanagpau** [comment]
@seantalts yes i came from using rethinking. I'll have a look at the link and see if I can resolve, many thanks

**Comment by jgabry** [comment]
Going to close this due to inactivity but @vanagpau if you're still having trouble we can reopen this
