### ISSUE TITLE
/usr/local/lib/R/etc/Makeconf:176: recipe for target 'chains.o' failed make: *** [chains.o] Error 1 ERROR: compilation failed for package ‘rstan’

### ISSUE THREAD

**Issue by hzongyao** [stan-dev/rstan#859]
#### Summary:
Please provide a short summary (no more than a sentence or two).
/usr/local/lib/R/etc/Makeconf:176: recipe for target 'chains.o' failed
make: *** [chains.o] Error 1
ERROR: compilation failed for package ‘rstan’

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.
/usr/local/lib/R/etc/Makeconf:176: recipe for target 'chains.o' failed
make: *** [chains.o] Error 1
ERROR: compilation failed for package ‘rstan’

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
3.6
#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1

**Comment by jgabry** [comment]
I'm not sure what's going on here. @bgoodri any ideas? Looks like R 3.6 with Debian. 

@hzongyao You could also try asking on the Stan forums (https://discourse.mc-stan.org/) where you'll get more eyes on your question.

**Comment by bgoodri** [comment]
We need to see more of the error message, specifically the part that starts
with "error:".

**Comment by hzongyao** [comment]
Using library: /mnt/raid/huangzongyao/lib/Rlib/R36
Using temp directory: /mnt/raid/huangzongyao/tmp/Rtmp
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS  NULL                                         CRAN  "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"  [1] "https://mirrors.tuna.tsinghua.edu.cn/bioconductor" -I"/mnt/raid/huangzongyao/lib/Rlib/R36/Rcpp/include" -I"/mnt/raid/huangzongyao/lib/Rlib/R36/RcppEigen/include" -I"/mnt/raid/huangzongyao/lib/Rlib/R36/BH/include" -I"/mnt/raid/huangzongyao/lib/Rlib/R36/StanHeaders/include" -I"/mnt/raid/huangzongyao/lib/Rlib/R36/RcppParallel/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c chains.cpp -o chains.o
g++: error: NULL: No such file or directory
g++: error: CRAN: No such file or directory
g++: error: https://mirrors.tuna.tsinghua.edu.cn/CRAN/: No such file or directory
g++: error: [1]: No such file or directory
g++: error: https://mirrors.tuna.tsinghua.edu.cn/bioconductor: No such file or directory
/usr/lib/R/etc/Makeconf:177: recipe for target 'chains.o' failed
make: *** [chains.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/mnt/raid/huangzongyao/lib/Rlib/R36/rstan’

The downloaded source packages are in
	‘/mnt/raid/huangzongyao/tmp/Rtmp/RtmpyOec3m/downloaded_packages’
Warning message:
In install.packages("rstan") :
  installation of package ‘rstan’ had non-zero exit status

**Comment by bgoodri** [comment]
Your ~/.Rprofile file seems to be printing out the mirrors that R would
use, which messes everything up. Either delete that or start R with the
--vanilla option.

**Comment by jgabry** [comment]
Going to close this but @hzongyao if this is still unresolved we can reopen
