### ISSUE TITLE
Seemingly parallel chains using only one core?

### ISSUE THREAD

**Issue by helske** [stan-dev/rstan#861]
#### Summary:

When running a simple stan model on cluster using four cores, the progress printed to screen suggests that chains are run in parallel, but the timing suggest that chains are not actually run in separate cores.

#### Description:

I am running rstan on a supercomputer where I have requested for cores for my R session. When I then run a simple stan model using the option cores = 4, the output seems to suggest that everything works, except the external timing suggest that the wall clock time is four times higher than a runtime of single chain.

#### Reproducible Steps:
```
library(rstan)

code <- "
data {
 real y[100000];
}
parameters {
  real mu;
  real<lower=0> sigma;
}
model {
  y ~ normal(mu, sigma);
}

"

print(paste("number of cores:", future::availableCores()))

set.seed(1)
y <- rnorm(1e5)
model <- stan_model(model_code = code)

a<-proc.time()
fit1 <- sampling(model, data = list(y = y), 
  iter = 10000, warmup = 1000,
  refresh = 10000, chains = 4, cores = 4)
proc.time() - a
```
#### Current Output:
Here is the output:
```
[1] "number of cores: 4"

SAMPLING FOR MODEL 'a26c54647fc55b6c089568ff2a877602' NOW (CHAIN 1).

SAMPLING FOR MODEL 'a26c54647fc55b6c089568ff2a877602' NOW (CHAIN 2).
Chain 1:
Chain 1: Gradient evaluation took 0.000382 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 3.82 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 2:
Chain 2: Gradient evaluation took 0.000415 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 4.15 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:

SAMPLING FOR MODEL 'a26c54647fc55b6c089568ff2a877602' NOW (CHAIN 4).

SAMPLING FOR MODEL 'a26c54647fc55b6c089568ff2a877602' NOW (CHAIN 3).
Chain 1: Iteration:    1 / 10000 [  0%]  (Warmup)
Chain 3:
Chain 3: Gradient evaluation took 0.000413 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 4.13 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:    1 / 10000 [  0%]  (Warmup)
Chain 4:
Chain 4: Gradient evaluation took 0.000416 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 4.16 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 10000 [  0%]  (Warmup)
Chain 2: Iteration:    1 / 10000 [  0%]  (Warmup)
Chain 1: Iteration: 1001 / 10000 [ 10%]  (Sampling)
Chain 3: Iteration: 1001 / 10000 [ 10%]  (Sampling)
Chain 4: Iteration: 1001 / 10000 [ 10%]  (Sampling)
Chain 2: Iteration: 1001 / 10000 [ 10%]  (Sampling)
Chain 2: Iteration: 10000 / 10000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 1.85203 seconds (Warm-up)
Chain 2:                13.265 seconds (Sampling)
Chain 2:                15.117 seconds (Total)
Chain 2:
Chain 4: Iteration: 10000 / 10000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 1.85596 seconds (Warm-up)
Chain 4:                18.4381 seconds (Sampling)
Chain 4:                20.294 seconds (Total)
Chain 4:
Chain 1: Iteration: 10000 / 10000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 1.75699 seconds (Warm-up)
Chain 1:                18.9451 seconds (Sampling)
Chain 1:                20.7021 seconds (Total)
Chain 1:
Chain 3: Iteration: 10000 / 10000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 1.8214 seconds (Warm-up)
Chain 3:                19.2765 seconds (Sampling)
Chain 3:                21.0979 seconds (Total)
Chain 3:
> proc.time() - a
   user  system elapsed
 79.744   1.094  80.855
```
See the discrepancy between the chain-specific elapsed times and the total time which is about 4 times higher than the runtime of a single chain.

Note that I am not able to reproduce this on my own (Windows) laptop.

#### Expected Output:
proc.time() - a should be close to runtime of slowest chain.

#### RStan Version:
2.19.3

#### R Version:
4.0.2 

#### Operating System:
Red Hat Enterprise Linux Server 7.7 (Maipo)

**Comment by jgabry** [comment]
I'm not sure if this is the issue here, but sometimes for very simple models it's faster to run them sequentially because the time it takes to get multiple cores up and running is longer than the time it takes to fit the model sequentially multiple times. But you said you weren't able to reproduce this on your laptop, so that makes me think something else is going on. Unfortunately I have no clue what that something else is! @bgoodri Any ideas?

**Comment by bgoodri** [comment]
It is going in parallel, but parallel can be slow. I would upgrade to rstan
2.21.x before worrying much about how to get more speed out of a cluster.

**Comment by helske** [comment]
Sure, I understand that for small models the speed up is not necessarily there, but this was just a minimal example. My actual model takes 8 hours to finish even though it says that each chain takes 2 hours to finish (which is also the total runtime on my laptop).

Switching to 2.21.x is unfortunately not an option at the moment. There was a segfault issue with brms using recent rstan so rstan was left behind in recent upgrade. Which suggests that there is something wrong in their setup... I have contacted the support as well and let you know if they figure it out.

**Comment by bgoodri** [comment]
Is it possible that your cluster is giving you threads on the same core
rather than distinct physical cores?

**Comment by helske** [comment]
Further testing suggests that this is not actually Stan-related, but there are other more general problems with the computing environment.
