### ISSUE TITLE
Issue with stan on Mac Catalina

### ISSUE THREAD

**Issue by laurenyatlas** [stan-dev/rstan#864]
Hi,
I am trying to use brms in Rstudio on a new Mac running Catalina, version 10.15.7. I was getting issues using my code that had worked prior to upgrade, so I installed developer tools and updated my R to version 4.0.3, and saw in a help that I should install Rstan into a fresh version of R. I downloaded Rstan package and relaunched rstudio, but got new errors:

sh: clang++ -mmacosx-version-min=10.13: command not found
error in running commandThe NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
cannot remove file '/var/folders/rr/mys624b1353gwyqzymmcngfd32lv4r/T//RtmpoWpIjX/file155ad13bff257.stan', reason 'No such file or directory'

An example of my code is:
  form0 = formula(paste(y, "~1"));
  m0_alltemps[[y]] = brm(form0, data = behavsubjs_alltrials,save_all_pars=TRUE, silent=TRUE, refresh=0);

It looks like I am using brms version 2.14.0. I'm relatively new to R so not sure what other information you might need. Thank you in advance for helping me address this!

**Comment by jgabry** [comment]
Yeah @rok-cesnovar this looks similar to https://github.com/stan-dev/rstan/issues/774, so the solutions there might work. 

@laurenyatlas and @Kreile can you check what `packageVersion("rstan")` says? And also what are the contents of the file that opens if you run `file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars"))`?

**Comment by Kreile** [comment]
file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars")) gives _CC=clang CXX=clang++_
and packageVersion("rstan") _‘2.21.1’_
Thanks a lot!

**Comment by jgabry** [comment]
@Kreile sorry for the slow response! Can you try deleting the contents of that Makevars file and replacing those lines with just this

```
CXX14FLAGS=-O3 -march=native -mtune=native 
CXX14FLAGS += -arch x86_64 -ftemplate-depth-256
```

and see if that works?

**Comment by Kreile** [comment]
Hi @jgabry I've changed the Makevars file, now I get this error:

```
Compiling Stan program...
sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
recompiling to avoid crashing R session
Start sampling

Warning messages:
1: In system2(CXX, args = ARGS) : error in running command
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/2m/jdq_zn1526lbzhmxpnm8qyrm0000gp/T//RtmpPBcSYZ/file27c252ed6e7e.stan', reason 'No such file or directory'
```

after running an brms model, had to interrupt the process. In the console it says "Start sampling" but does not get anywhere after a few minutes. It might be worthwile to add that I usually also have to do

`cl <- parallel::makeCluster(2, setup_strategy = "sequential")
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}`
(https://discourse.mc-stan.org/t/r-4-0-0-and-cran-macos-binaries/13989/19). However I also tried without, it still didnt work.

**Comment by laurenyatlas** [comment]
Sorry for my delay! I have the same version as Kreile but nothing in the Makevars file.

**Comment by laurenyatlas** [comment]
And when I make that change I get: 
```
sh: clang++ -mmacosx-version-min=10.13: command not found
error in running commandThe NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
cannot remove file '/var/folders/rr/mys624b1353gwyqzymmcngfd32lv4r/T//RtmpIVTIs0/file379c740da186.stan', reason 'No such file or directory'
```
Do these errors invalidate the output? Because the models still run and return results.

**Comment by SteveBronder** [comment]
That error is fine, that's just from testing the new compiler. The code there is erroring out but that won't change your model results

**Comment by queenbarb** [comment]
Hey. I have the same error warning (running Mac on BigSur) 

Compiling Stan program...
sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Start sampling
Warning messages:
1: In system2(CXX, args = ARGS) : error in running command
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/2s/_43kyxq500jc0kzljbg3r26c0000gn/T//RtmpbzKpTr/file3095bedc50e.stan', reason 'No such file or directory'

Each time I want to run the function bayes_factor() I get a fatal error and R shuts down. Has anyone any solutions to this?
