### ISSUE TITLE
Installing older rStan: StanHeaders R 3.4 requirements causes failure to install

### ISSUE THREAD

**Issue by bhick001** [stan-dev/rstan#865]
#### Summary:
Please provide a short summary (no more than a sentence or two).
I need to install an older version of rStan for mac, with R 3.3.3. However when installing StanHeaders I still get requires R >=  3.4.0. 

#### Description:
Describe the issue as clearly as possible.
I have been trying to install rStan on my R3.3.3 (mac OSX 10.9.5). I have been trying older version of rStan even as low as 2.13.2. I have downloaded, unpacked, and ran
source("install_StanHeaders.R")
this clones things ...

"cloning into '/var/folders/8m/gs3322bn25s8l_qznxj2mlb40000gn/T//RtmpCJq4n6/git2r-693d2d9765a6/StanHeaders/inst/include/mathlib'..."

then when it ttys to install it  fails, complaining about the R version. This package was released on Dec 18, 2016, R 3.4 was released in April 2017. Why is it requiring R 3.4 and how can I get this working?

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.
Installing StanHeaders
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8m/gs3322bn25s8l_qznxj2mlb40000gn/T/RtmpCJq4n6/git2r-693d2d9765a6/StanHeaders'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests  \
  --preclean 

ERROR: this R is version 3.3.3, package 'StanHeaders' requires R >=  3.4.0
Error: Command failed (1)

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
3.3.3
#### Operating System:
Your operating system (e.g., OS X 10.11.3)
OS X 10.9.5

**Comment by jgabry** [comment]
My guess is that the version of StanHeaders that is getting installed is too recent. If you're trying RStan 2.13.2 then you'd need StanHeaders 2.13. You should be able to download corresponding versions of RStan and StanHeaders from the CRAN source package archive: 

* https://cran.r-project.org/src/contrib/Archive/rstan
* https://cran.r-project.org/src/contrib/Archive/StanHeaders/

Does that work?

**Comment by jgabry** [comment]
Going to close this but if it's still an issue we can reopen
