### ISSUE TITLE
possible cran error on rstan

### ISSUE THREAD

**Issue by AllanKinnaird** [stan-dev/rstan#870]
#### Summary:
The cran page for rstan may be incorrect.

#### Description:
The entry for macOS binaries is as below. Is this an error? I would expect the two versions to be the other way around.

macOS binaries: | r-release: rstan_2.21.1.tgz, r-oldrel: rstan_2.21.2.tgz

**Comment by jgabry** [comment]
Hmm, I think what's going on is that the CRAN Mac binary for rstan 2.21.2 was never built for the latest R and so the info on the web page is actually correct. @bgoodri Do you know there's no Mac binary even though all the checks on Mac are passing at https://cran.r-project.org/web/checks/check_results_rstan.html?

**Comment by bgoodri** [comment]
Yeah, the Mac segfault when R is shutdown after rstan is loaded is
non-deterministic, so sometimes it passes and when it tried to build the
2.21.2 binary, it didn't. But there is no real difference between 2.21.1
and 2.21.2 for Macs, only Windows.
