### ISSUE TITLE
Question: Compilation error.

### ISSUE THREAD

**Issue by Zhuk66** [stan-dev/rstan#872]
I am trying to install rstan with Microsoft R Open 4.0.2 on Red Hat Enterprise Linux 7 and getting compile errors.
Somehow Microsoft copyright message is being appended to g++ compiler options. I modified the Makevars file by adding a --quite key to Rscript options, i.e.:
PKG_CPPFLAGS += $(shell "${R_HOME}/bin/Rscript" **--quiet** -e "RcppParallel::CxxFlags()")
It compiled after that, but this kind of solution is not acceptable. How can I compile and
install rstan without modifying Makevars?

Output:
* installing *source* package ‘rstan’ ...
** package ‘rstan’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++  -I/.../4.0.2/lib64/R/include -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"." 
-DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -DSTAN_THREADS  
**Microsoft R Open 4.0.2 The enhanced R distribution from Microsoft Microsoft packages Copyright (C)
2020 Microsoft Corporation  Using the Intel MKL for parallel mathematical computing(using 4 cores).  
Default CRAN mirror snapshot taken on . See: https://mran.microsoft.com/.** 
-I'/.../4.0/2020-10-16/cran/Rcpp/include' -I'/.../4.0/2020-10-16/cran/RcppEigen/include' 
-I'/.../4.0/2020-10-16/cran/BH/include' -I'/.../4.0/2020-10-16/cran/StanHeaders/include' 
-I'/.../4.0/2020-10-16/cran/RcppParallel/include' -DU_STATIC_IMPLEMENTATION     -O3 -fPIC 
-c chains.cpp -o chains.o
/bin/bash: -c: line 0: syntax error near unexpected token `('

**Comment by jgabry** [comment]
That's definitely strange that that the copyright message is appended to the compiler options. I don't really know anything about Microsoft R Open unfortunately, but there was a thread on the Stan forums recently about it, which may be of interest to you:

https://discourse.mc-stan.org/t/cant-get-stan-to-run-in-mro-4-0-2/19142

**Comment by andrjohns** [comment]
A user posted a fix for that error in this post: https://discourse.mc-stan.org/t/collect2-exe-error-ld-returned-1-exit-status-on-windows-10-r-4-0-2/18377/9

But note that R Open currently doesn't work with RStan on Windows, due to some issues with the TBB (RcppParallel package) that haven't been resolved, I'm not sure if there will be similar issues on RHEL

**Comment by Zhuk66** [comment]
... and it worked for me! Thank you very much!!!
