### ISSUE TITLE
LdFlags error when building package using rstantools (space in path to library)

### ISSUE THREAD

**Issue by dmphillippo** [stan-dev/rstan#873]
#### Summary:
Attempting to build a package using the latest rstantools (2.1.1) and StanHeaders (2.21.0-6) fails when there is a space in the TBB path produced by `StanHeaders:::LdFlags()`

#### Description:
Building a package ([multinma](https://github.com/dmphillippo/multinma/tree/develop)) based on the latest rstantools (2.1.1) and StanHeaders (2.21.0-6) fails to compile the Stan models. I believe this failure is at the linking stage, and happens when there is a space in the TBB path produced by `StanHeaders:::LdFlags()`. The first instance of the path (after `-L`) is quoted, but the second (after `-Wl,-rpath,`) is not.

Possible fix may be to `shQuote()` the second `TBB` path (as well as the first) in `StanHeaders:::LdFlags()`:
```r
LdFlags <- function(as_character = FALSE) {
  TBB <- system.file("lib", .Platform$r_arch, package = "RcppParallel", mustWork = TRUE)
  PKG_LIBS <- paste0("-L", shQuote(TBB), " -Wl,-rpath,", shQuote(TBB), " -ltbb -ltbbmalloc")
  if (isTRUE(as_character)) return(PKG_LIBS)
  cat(PKG_LIBS, " ")
  return(invisible(NULL))
}
```
Patching a local version of StanHeaders (building with 2.21 math and stan libraries) as above and then building the multinma package works for me - compilation completes without error.

Another possible fix may be to follow the approach used by `RcppParallel::LdFlags()`, which uses short paths on Windows (see `RcppParallel:::asBuildPath()`).

#### Reproducible Steps:
Building package [multinma](https://github.com/dmphillippo/multinma/tree/develop) based on rstantools on Windows, but likely not package specific.

#### Current Output:
The build currently errors at the linking stage:
```
C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o multinma.dll tmp.def RcppExports.o stanExports_binomial_1par.o stanExports_binomial_2par.o stanExports_normal.o stanExports_ordered_multinomial.o stanExports_poisson.o -LC:/PROGRA~1/R/WIN-LI~1/4.0/RCPPPA~1/lib/x64 -ltbb -ltbbmalloc -LC:/Program Files/R/win-library/4.0/RcppParallel/lib/x64 -Wl,-rpath,C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64 -ltbb -ltbbmalloc -LC:/PROGRA~1/R/R-40~1.3/bin/x64 -lR
g++.exe: error: Files/R/win-library/4.0/RcppParallel/lib/x64: No such file or directory
```

The output from `StanHeaders:::LdFlags()` is:
```
-L"C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64" -Wl,-rpath,C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64 -ltbb -ltbbmalloc  
```
which I think is causing the issue.

#### Expected Output:
Using the described patch (`shQuote`-ing the second TBB path in `LdFlags()`) runs the following linker command, which runs without error:
```
C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o multinma.dll tmp.def RcppExports.o stanExports_binomial_1par.o stanExports_binomial_2par.o stanExports_normal.o stanExports_ordered_multinomial.o stanExports_poisson.o -LC:/PROGRA~1/R/WIN-LI~1/4.0/RCPPPA~1/lib/x64 -ltbb -ltbbmalloc -LC:/Program Files/R/win-library/4.0/RcppParallel/lib/x64 -Wl,-rpath,C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64 -ltbb -ltbbmalloc -LC:/PROGRA~1/R/R-40~1.3/bin/x64 -lR
installing to C:/Program Files/R/win-library/4.0/00LOCK-multinma/00new/multinma/libs/x64
```

The patched `LdFlags()` output is:
```
-L"C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64" -Wl,-rpath,"C:/Program Files/R/win-library/4.0/RcppParallel/lib/x64" -ltbb -ltbbmalloc  
```

#### RStan Version:
2.21.2

#### R Version:
R version 4.0.3 (2020-10-10)

#### Operating System:
Windows 10

**Comment by jgabry** [comment]
Thanks for reporting this and for the suggestions. @bgoodri can you take a look at this?

**Comment by bgoodri** [comment]
Thanks @dmphillippo . You were right.
