### ISSUE TITLE
stan_version() 2.21.0 on fresh install but I need stan 2.24+

### ISSUE THREAD

**Issue by BayesExeter** [stan-dev/rstan#876]
#### Summary:
I want to use the multinomial_logit functionality added to stan 2.24, 2.25 (and documented in the stan reference manuals). Rstan on CRAN is at 2.21 and doesn't recognise these new features. Is Rstan behind stan, or is there an obvious way to get the latest version?

#### Description:
Certain features in the latest versions of stan looked really important. I did a fresh update of everything: R 4.0.3, RStudio 1.4.1056, Mac OS Catalina 10.15.7 (didn't dare go beyond Catalina), and installed new Rstan which works fine. But stan_version() returns 2.21.0 in R. I guess this is because the CRAN version is behind or because Rstan is behind Stan. If the former, how can I install a beta version of Rstan 2.24 or 2.25?

**Comment by breckbaldwin** [comment]
Because of issues with CRAN RStan lags behind core Stan releases. The 
easiest fix is to use CmdStanR:

https://mc-stan.org/cmdstanr/

B

**Comment by jgabry** [comment]
Going to close this since @breckbaldwin is correct that to run the latest Stan from R you can use our new CmdStanR interface which will always support the latest version of Stan. RStan is still lagging behind a few versions unfortunately.
