### ISSUE TITLE
Windows instructions are missing Makevars

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#880]
@andrjohns @bgoodri The latest instructions for Windows seem to be missing a section on setting up the Makevars[.win] file with optimizations like `-O3` and other stuff. Was it omitted intentionally?

**Comment by andrjohns** [comment]
Ah that was my mistake, I was supposed to get back to that. The issue is that the presence of a ```Makevars.win``` file (containing anything) will cause the ```argument “RMU” is missing, with no default``` error if the ```withr``` package is above version 2.2.0, so the user needs to manually install that version and not update.

I'll fix up those instructions now

**Comment by jgabry** [comment]
No worries and thanks! I only noticed because a user reported it today. And thanks for helping sort out the RMU missing error.

**Comment by jgabry** [comment]
The updated instructions look good, thanks again!
