### ISSUE TITLE
r-cran-rstan unmet dependencies for Ubuntu 20.04

### ISSUE THREAD

**Issue by moorugi98** [stan-dev/rstan#886]
#### Summary:
I cannot configure the C++ chain as ```r-cran-rstan```  has unmet dependencies.

#### Description:
Prior to installing rstan, I was trying to configure C++ chains following the instruction [here](https://github.com/stan-dev/rstan/wiki/Configuring-C-Toolchain-for-Linux).  This resulted in the error that was issued [here](https://github.com/stan-dev/rstan/issues/884), but based on the answer there I can proceed without adding any repos. However, when I run ```sudo apt install r-cran-rstan```, I get following error messages.

```
sudo apt install r-cran-rstan
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-rstan : Depends: r-api-3.5
                Depends: r-cran-stanheaders (>= 2.18.1) but it is not going to be installed
                Depends: r-cran-ggplot2 (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-inline but it is not going to be installed
                Depends: r-cran-gridextra (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-rcpp (>= 0.12.0) but it is not going to be installed
                Depends: r-cran-loo (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-pkgbuild but it is not going to be installed
                Depends: r-cran-rcppeigen (>= 0.3.3.3.0) but it is not going to be installed
                Recommends: r-cran-runit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
I tried installing ``` r-api-3.5```  separately, which returns 
```
sudo apt install r-api-3.5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package r-api-3.5 is a virtual package provided by:
  r-base-core 3.6.3-2 [Not candidate version]

E: Package 'r-api-3.5' has no installation candidate
```

#### Reproducible Steps:
1. sudo add-apt-repository -y "ppa:marutter/rrutter3.5"
2. sudo add-apt-repository -y "ppa:marutter/c2d4u3.5"
3. sudo add-apt-repository --remove "ppa:marutter/c2d4u3.5" since Ubuntu 20.04 doesn't need to add repos and this command results in error described [here](https://github.com/stan-dev/rstan/issues/884)
4. sudo apt update
5. sudo apt install r-cran-rstan

#### R Version:
 R version 4.0.3 (2020-10-10)

#### Operating System:
Ubuntu 20.04.1 LTS (Focal Fossa)

**Comment by pbrowne88** [comment]
I'm in the exact same situation, and I'm getting the exact same errors. I hope there's a simple fix!

**Comment by jgabry** [comment]
Any ideas @bgoodri?

**Comment by bgoodri** [comment]
When I do `sudo apt install r-cran-rstan -d` on Ubuntu 20.04, I get
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfprint-2-tod1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  r-cran-loo r-cran-stanheaders
Suggested packages:
  r-cran-bayesplot r-cran-brms r-cran-rstanarm r-cran-rstantools r-cran-shinystan r-cran-rcppparallel
The following NEW packages will be installed:
  r-cran-loo r-cran-rstan r-cran-stanheaders
0 upgraded, 3 newly installed, 0 to remove and 18 not upgraded.
Need to get 5,554 kB of archives.
After this operation, 17.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 r-cran-loo all 2.2.0-1 [2,743 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 r-cran-stanheaders amd64 2.21.0-1-1 [797 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 r-cran-rstan amd64 2.19.2-1build1 [2,014 kB]
Fetched 5,554 kB in 0s (39.3 MB/s)      
Download complete and in download only mode
```
Possibly you don't have the focal universe repos enabled? You should not need any other repos with 20.04.

**Comment by jgabry** [comment]
@bgoodri @andrjohns Do our [linux instructions](https://github.com/stan-dev/rstan/wiki/Configuring-C-Toolchain-for-Linux#installing-from-the-repository) need updating? They don't mention anything about "focal universe repos" and they also don't suggest using the `-d` option that you used. I don't know enough about linux installation to know if those differences matter.

**Comment by pbrowne88** [comment]
Thank you for helping us fix this!

I ensured that I had all of the focal universe repos enabled (universe, multiverse, restricted), and then tried `sudo apt install r-cran-rstan -d` both with and without the repositories recommended in the 'Configuring C Toolchain for Linux' instructions. The result was identical: 

```
sudo apt install r-cran-rstan -d
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 r-cran-rstan : Depends: r-api-3.5
                Depends: r-cran-stanheaders (>= 2.18.1) but it is not going to be installed
                Depends: r-cran-ggplot2 (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-inline but it is not going to be installed
                Depends: r-cran-gridextra (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-rcpp (>= 0.12.0) but it is not going to be installed
                Depends: r-cran-loo (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-pkgbuild but it is not going to be installed
                Depends: r-cran-rcppeigen (>= 0.3.3.3.0) but it is not going to be installed
                Recommends: r-cran-runit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.```

**Comment by bgoodri** [comment]
Try sudo apt install r-cran-rstan/focal

**Comment by pbrowne88** [comment]
I gave it a try, and it returned the same error, but with the addition of this line:

```
Selected version '2.19.2-1build1' (Ubuntu:20.04/focal [amd64]) for 'r-cran-rstan'
```

**Comment by bgoodri** [comment]
Try sudo apt install -t focal r-cran-rstan/focal

**Comment by pbrowne88** [comment]
Thank you for your perseverance!

I gave it a try, and I see no change from `sudo apt install r-cran-stan/focal`:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '2.19.2-1build1' (Ubuntu:20.04/focal [amd64]) for 'r-cran-rstan'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 r-cran-rstan : Depends: r-api-3.5
                Depends: r-cran-stanheaders (>= 2.18.1) but it is not going to be installed
                Depends: r-cran-ggplot2 (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-inline but it is not going to be installed
                Depends: r-cran-gridextra (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-rcpp (>= 0.12.0) but it is not going to be installed
                Depends: r-cran-loo (>= 2.0.0) but it is not going to be installed
                Depends: r-cran-pkgbuild but it is not going to be installed
                Depends: r-cran-rcppeigen (>= 0.3.3.3.0) but it is not going to be installed
                Recommends: r-cran-runit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by bgoodri** [comment]
What version of R do you have?

**Comment by pbrowne88** [comment]
4.0.3!

```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by bgoodri** [comment]
From where? The R version in the focal repos is 3.6.3-2

https://packages.ubuntu.com/focal/r-base-core

**Comment by pbrowne88** [comment]
I don't actually know! I just used `export R_VERSION=4.0.3` and re-installed `r-base`, and ended up with 4.0.3. Perhaps that's the root of the issue...

**Comment by bgoodri** [comment]
Then you might need to add

deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/

to your /etc/apt/sources.list file as described at

https://cran.r-project.org/bin/linux/ubuntu/

Then do

sudo apt-get update
sudo apt install r-cran-rstan

**Comment by pbrowne88** [comment]
Looks like `deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/` was already in my sources list. Just to be sure, I added it again (got duplicate warnings during `apt-get update`, but otherwise no change), and tried adding each of the other three repositories listed - one at a time - but nothing made any difference to the final `sudo apt install r-cran-rstan`.

Thank you for valiantly tilting against this strange error; my apologies for presenting something so seemingly intractable!

**Comment by bgoodri** [comment]
Maybe sudo apt install -t focal-cran40 r-cran-rstan/focal-cran40

**Comment by moorugi98** [comment]
I had the exactly the same problem as @pbrowne88 when I followed @bgoodri suggestions. I tried out `sudo apt install -t focal-cran40 r-cran-rstan/focal-cran40` . The following output was given:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Release 'focal-cran40' for 'r-cran-rstan' was not found
`

[In the focal folder](https://cran.r-project.org/bin/linux/ubuntu/focal-cran40/ ) I couldn't find anything with r stan so maybe there isn't any version available yet? Is this a possibility?

**Comment by bgoodri** [comment]
Might need to pull packages from

https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+

if you have installed R 4.x.

**Comment by pbrowne88** [comment]
THAT DID IT! IT WORKED!

Pulling packages from https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+ solved everything! 

A simple `sudo apt install r-cran-rstan` did the trick! 

Thank you so much for sticking with this issue!

**Comment by moorugi98** [comment]
@bgoodri 's suggestion also worked for me. You might want to add this information to the installation description? Thanks for solving the issue.

**Comment by quimicocesar** [comment]
I had a similar issue and I fixed it using: "sudo apt-get install cmake"

**Comment by sp4chi** [comment]
@bgoodri Thanks, it worked for me!

**Comment by ilcink** [comment]
@bgoodri @pbrowne88 
I had the same problem with install.packages("igraph") in my Jupyter notebook resulting in the error 
Warning message in install.packages("igraph"):
“installation of package ‘igraph’ had non-zero exit status”

When I opened the Ubuntu terminal and applied the commands
```
sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
sudo apt update
```
as you found, 
this “installation of package ‘igraph’ had non-zero exit status” error was finally gone.
Thank you so much for your great help!
