### ISSUE TITLE
Segfault when installing rstan 2.21.2 in R-4.0.3 on RHEL-7

### ISSUE THREAD

**Issue by mwaldron104** [stan-dev/rstan#888]
#### Summary:
Installation of rstan-2.21.2 in R-4.0.3 is failing with a segfault error.

#### Description:
During the installation of rstan, the actual compilation appears to succeed, however during the install phase where it is testing if installed package can be loaded from temporary location, it returns a segmentation fault, and so the overall installation fails.

I am using GCC 6.3.0 compiler suite, and my .R/Makevars files contains:
CXX14FLAGS=-O3 -march=native -mtune=native -fPIC    
CXX14=g++

Note that I successfully installed rstan-2.19.3 in R-4.0.1 on the same system back in June.

#### Reproducible Steps:
install.packages("rstan")

#### Current Output:
...LOTS of compiler output removed here.....

ar -rs ../inst/lib//libStanServices.a stan_fit.o stan_fit_base.o
ar: creating ../inst/lib//libStanServices.a
installing to /nas/longleaf/apps/r/4.0.3/lib64/R/library/00LOCK-rstan/00new/rstan/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1:  6345 Segmentation fault      R_TESTS= '/nas/longleaf/apps/r/4.0.3/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmphvXhIJ/file236a23f0e2c7'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: Rcpp::loadModule("class_model_base", what = TRUE)
 7: fun(libname, pkgname)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch(fun(libname, pkgname), error = identity)
12: runHook(".onLoad", env, package.lib, package)
13: loadNamespace(package, lib.loc)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
18: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
19: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
20: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
21: doTryCatch(return(expr), name, parentenv, handler)
22: tryCatchOne(expr, names, parentenv, handlers[[1L]])
23: tryCatchList(expr, classes, parentenv, handlers)
24: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
25: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
26: tools:::.test_load_package("rstan", "/nas/longleaf/apps/r/4.0.3/lib64/R/library/00LOCK-rstan/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/nas/longleaf/apps/r/4.0.3/lib64/R/library/rstan’

The downloaded source packages are in
	‘/tmp/RtmpxDPC6C/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rstan", type = "source") :
  installation of package ‘rstan’ had non-zero exit status

#### Expected Output:
DONE (rstan)

#### RStan Version:
2.21.2

#### R Version:
4.0.3

#### Operating System:
RHEL 7.8

**Comment by jgabry** [comment]
@bgoodri @andrjohns or anyone else more knowledgable about linux than I am, any idea what's causing the segfault here? 

@mwaldron104 Sorry you're running into a segfault installing RStan. If you need to use Stan from R soon and still can't get RStan working you could also try our new [CmdStanR interface](https://mc-stan.org/cmdstanr/) which a lot of people are finding easier to install.

**Comment by mwaldron104** [comment]
Thanks, I actually did install CmdStanR without any issues.

**Comment by bgoodri** [comment]
Probably need to have compiled Rcpp with the same settings.

**Comment by mwaldron104** [comment]
Thanks @bgoodri , that did it. After re-installing Rcpp with the same compiler settings, rstan installed successfully. Appreciate the help.
