### ISSUE TITLE
Windows Compile Error-multiple definition of `boost::math::detail::bessel_j0

### ISSUE THREAD

**Issue by gonghanqing-del** [stan-dev/rstan#896]
#### Summary:
The Compile for Rstan C++ is in error, it shows that multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file590071d03e99.o:file590

#### Current Output:
Compilation ERROR, function(s)/method(s) not created!
Error in compileCode(f, code, language = language, verbose = verbose) : 
  C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Junye LI/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::P1'; file590071d03e99.o:file590071d03e99.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Junye LI/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file590071d03e99.o:file590
In addition: Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/rtools40/usr/mingw_/bin/g++' not found

#### RStan Version:
2.21.2

#### R Version:
4.0.3
#### Operating System:
Win10

**Comment by andrjohns** [comment]
There was a recent update to the BH package that's causing issues.

You just need to restart R, and then reinstall the packages from source:

```
install.packages(c("StanHeaders","rstan"),type="source")
```

**Comment by gonghanqing-del** [comment]
> There was a recent update to the BH package that's causing issues.
> 
> You just need to restart R, and then reinstall the packages from source:
> 
> ```
> install.packages(c("StanHeaders","rstan"),type="source")
> ```

It works! Thank you so much! Really helpful.

**Comment by gonghanqing-del** [comment]
It works! Thanks so much! Really helpful!

-----原始邮件-----
发件人:"Andrew Johnson" <notifications@github.com>
发送时间:2021-01-17 07:11:21 (星期日)
收件人: stan-dev/rstan <rstan@noreply.github.com>
抄送: gonghanqing-del <17307100081@fudan.edu.cn>, Author <author@noreply.github.com>
主题: Re: [stan-dev/rstan] Windows Compile Error-multiple definition of `boost::math::detail::bessel_j0 (#896)



There was a recent update to the BH package that's causing issues.

You just need to restart R, and then reinstall the packages from source:

install.packages(c("StanHeaders","rstan"),type="source")
