### ISSUE TITLE
Why do we need a separate StanHeaders package?

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/rstan#900]
This might be silly question.

Is the reason we have StanHeaders separate because of the size of the rstan package or are there any other issues that require this structure?

Could we have the stan & math sources in rstan directly now that removing stanc2 has removed circa 50k lines of code?

If this could be doable, I am guessing this could simplify at least one problem with CRAN? If I remember correctly, we will need to submit StanHeaders first and that will have to be compatible with the current rstan (2.21)? If that is so, I don think that is actually doable with all the changes that have been done in Math in the last 1.5+ years. At least not trivially. 

Is StanHeaders2 an option?

cc @bgoodri @wds15 et al

**Comment by wds15** [comment]
I think the split was done for license reasons, but @bgoodri should know better. There was a desire to keep StanHeaders BSD style which you cannot do (as far as I know) once you throw in Rcpp things.

I also recall that @bgoodri did regret this decision such that maybe now is the point to reset this decision. This would mean that the license has to change most likely.

**Comment by rok-cesnovar** [comment]
> There was a desire to keep StanHeaders BSD style which you cannot do (as far as I know) once you throw in Rcpp things.

That is a valid reason though we can have both I guess. BSD StanHeaders and GPL Rstan with included Stan&Math sources?

> This would mean that the license has to change most likely.

The license of rstan is already GPL so I dont think this would matter?

**Comment by bgoodri** [comment]
The license thing would be manageable. Even the size would have been
manageable. But at the time StanHeaders was created, there was a
speculative constituency that wanted to use the Stan Math library but not
have to depend on the rest of Stan. But that only turned out to be only two
R packages that I know of.
