### ISSUE TITLE
Installer Package for macOS R toolchain Error installation

### ISSUE THREAD

**Issue by alesandel** [stan-dev/rstan#901]
#### Summary:
When I try to install macOS R toolchain I get an installation error.

#### Description:
At the end of installation process there is an error that said: "The installer has encountered an error that prevented the installation from completing. Contact the software manufacturer for assistance"   

#### Reproducible Steps:
I have followed the steps described in the guide

#### RStan Version:
The version of RStan that I try to install is 2.21.2

#### R Version:
The version of R I am running is R 4.0.3 version

#### Operating System:
My operating system is macOS Big Sur  11.1 version

**Comment by storopoli** [comment]
Try doing this as described in #904 

run R as `sudo`:

```bash
sudo R
```

then:

```r
install.packages(c("StanHeaders", "Stan"))
```

**Comment by alesandel** [comment]
Finally I got Rstan, letting him compile the installation process in R so much time but I did not solve the error that I have mentioned before.
Thank you for the help.

**Comment by storopoli** [comment]
What were your solution? Please let me know because I suspect there is something more simpler than giving sudo permission to R. But for me it's the only thing that solved.

**Comment by jojensen890** [comment]
Hey @alesandel, I have been having the same issue. I saw you closed this thread. Did you figure out how to solve it? Did @storopoli's method work? I'm afraid it didn't work for me. 
Thanks for the help!

**Comment by Jeffalltogether** [comment]
@jojensen890 @storopoli @alesandel I had probably the same issue where the installer would not complete the installation of the macOS R toolchain.  

The solution was to run through the steps that the installer does automatically.  

To do this, follow the instructions on this site:  

https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/  

**Important note:**  

I am running MacOS Big Sir version 11.4 with an Apple M1 processor. However, when I went to [download gfortran for macOS](https://github.com/fxcoudert/gfortran-for-macOS/releases), I did not install the version for ARM processors (i.e., Apple Silicon machines).    

Rather I installed the version `gfortran 10.2 for Big Sur (macOS 11), for Intel processors`. The specific file was gfortran-10.2-BigSur-Intel.dmg  

When I tried to use the gfortran version for ARM processors I was getting a `clang` error in R when running `Rcpp::sourceCpp('./helloworld.cpp')`

**Comment by daaronr** [comment]
(Note: I managed to install Rstan using the tips at https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/)

> Try doing this as described in #904
> 
> run R as `sudo`:
> 
> ```shell
> sudo R
> ```
> 
> then:
> 
> ```r
> install.packages(c("StanHeaders", "Stan"))
> ```

When I do this I get

```
Installing packages into ‘/Users/yosemite/Library/R/x86_64/4.1/library’
...
trying URL 'https://cloud.r-project.org/bin/macosx/contrib/4.1/StanHeaders_2.21.0-7.tgz'
... Warning message:
package ‘Stan’ is not available for this version of R

A version of this package for your version of R might be available elsewhere, see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

```

My version information 

```
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
...
Platform: x86_64-apple-darwin17.0 (64-bit)
```
