### ISSUE TITLE
Unable to install rstan

### ISSUE THREAD

**Issue by mbostanara** [stan-dev/rstan#902]
#### Summary:
I am not able to install Rstan on my machine. I would highly appreciate it if you would help me install it as soon as possible.

#### Description:
I am trying to install rstan by following the exact steps stated in the getting started page. Although the package installs, the example at the end of the installation guide does not run and this error occurs:

`Error in compileCode(f, code, language = language, verbose = verbose) : 
  sh: g++: command not foundmake: *** [C:/PROGRA~1/R/R-40~1.3/etc/x64/Makeconf:229: file15c039155ff.o] Error 127
In addition: Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/rtools40/usr/mingw_/bin/g++' not found`

#### Reproducible Steps:
I followed the exact steps shown on the 'getting started webpage'.

#### RStan Version:
I am trying to install the development version.

#### R Version:
r version: 4.0.3
rstudio version: 1.4.1103
rtools version: rtools40

#### Operating System:
Windows 64-bit
Ram 16

Thank you

**Comment by andrjohns** [comment]
Can you post the output from:
```
readLines("~/.Renviron")
```

**Comment by andrjohns** [comment]
Oh and:
```
Sys.getenv("PATH")
```

**Comment by mbostanara** [comment]
Yes
The output from `readLines("~/.Renviron")` is:
```
"PATH=\"${RTOOLS40_HOME}\\usr\\bin;${PATH}\""
```

The output from `Sys.getenv("PATH")` is:
```
[1] "C:\\rtools40\\usr\\bin;C:\\PROGRA~1\\R\\R-40~1.3\\bin\\x64;C:\\Rtools\\bin;C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio129\\opl\\bin\\x64_win64;C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio129\\opl\\oplide\\;C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio129\\cplex\\bin\\x64_win64;C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio129\\cpoptimizer\\bin\\x64_win64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Rtools\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\mbost\\AppData\\Local\\Microsoft\\WindowsApps;"
```

**Comment by andrjohns** [comment]
That all looks fine. As a quick possible solution, we'll try resetting your ```Makevars.win``` file. I suspect this is due to a previous edit I made to the RStan installation instructions.

Can you run:
```
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars.win")
if (!file.exists(M)) file.create(M)
cat("\n CXX14FLAGS += -mtune=native -O3 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2",
    file = M, sep = "\n", append = FALSE)
```

Then restart R and try the example model again?

**Comment by mbostanara** [comment]
Thank you for your reply.

I ran that and restarted R and then tried the example again.

Unfortunately, I got this error this time:
```
Compilation ERROR, function(s)/method(s) not created!
Error in compileCode(f, code, language = language, verbose = verbose) : 
  C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mbost/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::P1'; file4c4261c177b.o:file4c4261c177b.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mbost/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file4c4261c177b.o:file4c4261c177b.
In addition: Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/rtools40/usr/mingw_/bin/g++' not found
```

**Comment by andrjohns** [comment]
That's fixable, thankfully. A recent update to the ```BH``` package is causing issues with RStan, so you just need to reinstall RStan and StanHeaders from source. Restart R and run:
```
# Compile packages using all cores
Sys.setenv(MAKEFLAGS = paste0("-j",parallel::detectCores()))

install.packages(c("StanHeaders","rstan"),type="source")
```
Then try the example model again

**Comment by mbostanara** [comment]
Thank you very much @andrjohns!

The issue is resolved now.
