### ISSUE TITLE
rstan is installed but cannot executed

### ISSUE THREAD

**Issue by moorugi98** [stan-dev/rstan#909]
#### Summary:
Rstan is installed but I cannot use the stan function.

#### Description:
Using the stan function results in the following error message:

Error in compileCode(f, code, language = language, verbose = verbose) : g++: error: x86_64: No such file or directoryg++: error: unrecognized command line option ‘-arch’make: *** [/usr/lib/R/etc/Makeconf:181: file16781fe42d5b.o] Error 1
7.
stop(errmsg)
6.
compileCode(f, code, language = language, verbose = verbose)
5.
cxxfunction(sig = sig, body = body, plugin = plugin, includes = includes, settings = settings, ..., verbose = verbose)
4.
pkgbuild::with_build_tools(cxxfunction(sig = sig, body = body, plugin = plugin, includes = includes, settings = settings, ..., verbose = verbose), required = rstan_options("required") && !identical(Sys.getenv("WINDOWS"), "TRUE") && !identical(Sys.getenv("R_PACKAGE_SOURCE"), ...
3.
cxxfunctionplus(signature(), body = paste(" return Rcpp::wrap(\"", model_name, "\");", sep = ""), includes = inc, plugin = "rstan", save_dso = save_dso | auto_write, module_name = paste("stan_fit4", model_cppname, "_mod", sep = ""), verbose = verbose)
2.
stan_model(file, model_name = model_name, model_code = model_code, stanc_ret = NULL, boost_lib = boost_lib, eigen_lib = eigen_lib, save_dso = save_dso, verbose = verbose)
1.
stan(file = "ADA-W09-Ex1a-exam-scores.stan", data = data_exam_score, pars = c("phi", "z"))

Error in sink(type = "output") : invalid connection
4.
sink(type = "output")
3.
cxxfunctionplus(signature(), body = paste(" return Rcpp::wrap(\"", model_name, "\");", sep = ""), includes = inc, plugin = "rstan", save_dso = save_dso | auto_write, module_name = paste("stan_fit4", model_cppname, "_mod", sep = ""), verbose = verbose)
2.
stan_model(file, model_name = model_name, model_code = model_code, stanc_ret = NULL, boost_lib = boost_lib, eigen_lib = eigen_lib, save_dso = save_dso, verbose = verbose)
1.
stan(file = "ADA-W09-Ex1a-exam-scores.stan", data = data_exam_score, pars = c("phi", "z"))

#### Reproducible Steps:
execute any stan function.

#### RStan Version:
‘2.21.2’

#### R Version:
R version 4.0.3 (2020-10-10)

#### Operating System:
Ubuntu 20.04.1 LTS

**Comment by jeffreypullin** [comment]
Hi @moorugi98, 

I would suspect this is a problem with your `.R/makevars` file. Specifically that you have some options incompatible with the compiler you are using. 

You can edit your makevars with `usethis::edit_r_makevars()` or by navigating to the file at `~\.R\Makevars` and editing it as usual.

Try changing something like `-arch x86_64` to `-march x86_64`. 

All the best!

**Comment by andrjohns** [comment]
It looks like you might have accidentally followed the OSX instructions, which is causing issues. To configure your ```Makevars``` file for Linux, can you run:
```
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars")
if (!file.exists(M)) file.create(M)
cat("\nCXX14FLAGS=-O3 -march=native -mtune=native -fPIC",
    "CXX14=g++", # or clang++ but you may need a version postfix
    file = M, sep = "\n", append = FALSE)
```

Then restart R and try again?

**Comment by moorugi98** [comment]
Hi @andrjohns, I followed your instruction which resulted in the following error message:

make cmd is
  make -f '/usr/lib/R/etc/Makeconf' -f '/usr/share/R/share/make/shlib.mk' -f '/home/minseok/.R/Makevars' CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB='file2c8133d2b03a.so' OBJECTS='file2c8133d2b03a.o'

make would use
if test  "zfile2c8133d2b03a.o" != "z"; then \
  echo g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o file2c8133d2b03a.so file2c8133d2b03a.o  '/usr/lib/R/site-library/rstan/lib//libStanServices.a' -L'/home/minseok/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/lib/' -lStanHeaders -L'/home/minseok/R/x86_64-pc-linux-gnu-library/4.0/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
  g++ -std=gnu++14 -shared -L"/usr/lib/R/lib" -Wl,-Bsymbolic-functions -Wl,-z,relro -o file2c8133d2b03a.so file2c8133d2b03a.o  '/usr/lib/R/site-library/rstan/lib//libStanServices.a' -L'/home/minseok/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/lib/' -lStanHeaders -L'/home/minseok/R/x86_64-pc-linux-gnu-library/4.0/RcppParallel/lib/' -ltbb  -L"/usr/lib/R/lib" -lR; \
fi
Error in compileCode(f, code, language = language, verbose = verbose) : 
    650 |   return internal::first_aligned<int(unpacket_traits<DefaultPacketType>::alignment),Derived>(m);      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/usr/bin/ld: /usr/lib/R/site-library/rstan/lib//libStanServices.a(stan_fit.o): relocation R_X86_64_PC32 against undefined hidden symbol `_ZTCN5boost10wrapexceptINS_4math14rounding_errorEEE0_NS_16exception_detail10clone_implINS4_19error_info_injectorIS2_EEEE' can not be used when making a shared object/usr/bin/ld: final link failed: bad valuecollect2: error: ld returned 1 exit statusmake: *** [/usr/share/R/share/make/shlib.mk:10: file2c8133d2b03a.so] Error 1
Error in sink(type = "output") : invalid connection

I sadly can't understand much than that something is wrong with the makevars file...

**Comment by andrjohns** [comment]
Can you restart R and then reinstall RStan and StanHeaders from source:
```
install.packages(c("StanHeaders","rstan"),type="source")
```

Then try the example model again?

**Comment by moorugi98** [comment]
@andrjohns That did the job. Thanks. I am closing the issue.
