### ISSUE TITLE
clang: error: no such file or directory: '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a'

### ISSUE THREAD

**Issue by mspezio** [stan-dev/rstan#916]
#### Summary:
Problem with
clang: error: no such file or directory: '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a'

#### Description:
Describe the issue as clearly as possible.
Mac OS 10.15.7 Catalina. Not able to install rstan from source.

The error may be caused by an extra separator because though
'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a'
does not exist
'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib/libStanServices.a'
does exist.

How best to address this problem? What is the reason for inserting an additional file separator?

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("stan-dev/rstan", ref = "develop", subdir = "rstan/rstan")

#### Current Output:
If applicable, any relevant output from RStan.
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rstan.so Module.o chains.o init.o misc.o pointer-tools.o sparse_extractors.o stan_fit_base.o stan_fit_rccp.o stanc.o stan/lang/ast_def.o stan/lang/grammars/bare_type_grammar_inst.o stan/lang/grammars/block_var_decls_grammar_inst.o stan/lang/grammars/expression07_grammar_inst.o stan/lang/grammars/expression_grammar_inst.o stan/lang/grammars/functions_grammar_inst.o stan/lang/grammars/indexes_grammar_inst.o stan/lang/grammars/local_var_decls_grammar_inst.o stan/lang/grammars/program_grammar_inst.o stan/lang/grammars/semantic_actions_def.o stan/lang/grammars/statement_2_grammar_inst.o stan/lang/grammars/statement_grammar_inst.o stan/lang/grammars/term_grammar_inst.o stan/lang/grammars/whitespace_grammar_inst.o /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a -L/Library/Frameworks/R.framework/Versions/4.0/Resources/library/StanHeaders/lib/ -lStanHeaders -L/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/lib/ -ltbb -ltbbmalloc -ltbbmalloc_proxy -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan/lib//libStanServices.a'
make: *** [rstan.so] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rstan’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/y1/16dxljnx1cn56xlhbr_1lylh0000gn/T//Rtmpu8iyDq/file18c078181dcc/rstan_2.21.3.tar.gz’ had non-zero exit status

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
rstan_2.21.3.tar.gz

#### R Version:
The version of R you are running (e.g., from `R.version.string`)
"R version 4.0.4 (2021-02-15)"

#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Mac OS 10.15.7

**Comment by andrjohns** [comment]
Instead of the GitHub dev version, can you try the 2.26 experimental version? This will be the next version up for release, so we're trying to get it as widely tested as possible before it gets to CRAN.

Install via:
```r
remove.packages(c("StanHeaders", "rstan"))
install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

**Comment by mspezio** [comment]
Thank you Andrew, that worked. Both rstan and brms seem to be working well now.

**Comment by andrjohns** [comment]
Great to hear!
