### ISSUE TITLE
Error in stanc(file = file, model_code = model_code, model_name = model_name, : failed to parse Stan model '5981fc7d30a0e2e1b939da0d0184e522' due to the above error.

### ISSUE THREAD

**Issue by davymwax** [stan-dev/rstan#921]
#### Summary:
I am getting the above error.

#### Description:
I am not sure what is wrong with my code reproduced here below:

#### Reproducible Steps:
```{r "Model 2 Code"}
model2Code <- "
data    
        {
        int<lower=1> n;
        int<lower=1> I;
        int<lower=0,upper=I> sub[n];
        int<lower=0,upper=2> cond[n];
        vector[n] y;
        }
    
parameters 
        {
        matrix[I,2] mu;
        real<lower=0> sigma2;
        }
    
transformed parameters 
        {
        vector[I] theta;
        vector[n] center;
        sigma=sqrt(sigma2);
        for (i in 1:I){
                 theta[i]=mu[i,2]-mu[i,1];
                 }
        for (k in 1:n) {
                center[k]=mu[sub[k],cond[k]];
                }
        }
        
model {
        to_vector(mu) ~ normal(.5,.5);
        sigma2 ~ inv_gamma(1,.05);
        y ~ normal(center, sigma);
      }
"
```

```{r "This does the sampling", cache=TRUE}
model2 <- suppressMessages(stan_model(model_code = model2Code))


#### Current Output:
Error in stanc(file = file, model_code = model_code, model_name = model_name, : failed to parse Stan model '5981fc7d30a0e2e1b939da0d0184e522' due to the above error.


#### Expected Output:
I expected my stan model to compile.


#### RStan Version:
The version of RStan I am running is 2.21.1
#### R Version:
The version of R I am running is 4.0.4 (2021-02-15) -- "Lost Library Book"

#### Operating System:
My operating system is Mac OS 11.2.2 Big Sur

**Comment by 629ysf** [comment]
Hello, have you solved this problem？

**Comment by isaac-kouame** [comment]
bonjour,
j'ai un soucis avec mon model:
data 
{
  int <lower=0> N;
  vector [N] coh;
  real hill [N];
  real at [N];
  real ts [N];
  real tr [N];
  real mtw [N];
  real cwd [N];
  int <lower=0> M;
}
parameters 
{
real theta;
vector [M] theta1;
vector [M] theta2;
vector [M] theta3;
vector [M] theta4;
vector [M] theta5;
real <lower=0> sigma;
}
model 
{
  for(n in 1:N)
  hill[n] ~ lognormal(theta^0 + at***theta1** [coh[n]]+ ts*theta2[coh[n]]+tr*thet3[coh[n]]+mtw*theta4[coh[n]]+cwd*theta5[coh[n]], sigma);
}
le message d'erreur est : **container index must be integer; found type=real PARSER EXPECTED**
SVP pouvez-vous m'expliquer l'erreur et m'aider à le résoudre

**Comment by andrjohns** [comment]
The error says: `container index must be integer; found type=real PARSER EXPECTED`

Change: `vector [N] coh` to `int coh[N]`

**Comment by isaac-kouame** [comment]
ok thank you. but coh is a character variable, can i convert to integer?

**Comment by andrjohns** [comment]
You need to do this in r first and then pass the result to rstan

**Comment by isaac-kouame** [comment]
ok merci beaucoup

**Comment by isaac-kouame** [comment]
STP un autre problème:
cwd*theta5[**coh**])
message d'erreur : **no matches for : Available argument signatures for operator *;+ **
