### ISSUE TITLE
Error installing rstan on windows 10

### ISSUE THREAD

**Issue by macgbrown** [stan-dev/rstan#931]
#### Summary:
I have followed the instructions installing rstan on Windows 10 using rtools40 and rstudio 1.4.1106.  All checks work fine (I can install jsonlite from source, for example).  When I run the example code "example(stan_model, package = "rstan", run.dontrun = TRUE)" I get a successful translation of the stan model, but then, after a longish pause, the following error.

Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/MACGBR~1/AppData/Local/Temp/RtmpwdmGs9/file3180500e6a0b.dll':

#### Description:
As per the previous issue with installation on windows 10, I installed rstan using the windows binaries.
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE,
                 type="win.binary"

**Comment by andrjohns** [comment]
Can you restart R, making sure that `rstan` doesn't get loaded, and reinstall `rstan` and `StanHeaders` from source:
```r
# Compile packages using all cores
Sys.setenv(MAKEFLAGS = paste0("-j",parallel::detectCores()))

install.packages(c("StanHeaders","rstan"),type="source")
```

**Comment by macgbrown** [comment]
That seems to have worked!  Thanks.
