### ISSUE TITLE
Due to a change in the directory structure of Rtools40 on Windows, `get_CXX()` does not seem to work properly.

### ISSUE THREAD

**Issue by indenkun** [stan-dev/rstan#937]
#### Summary:
Due to a change in the directory structure of Rtools40 on Windows, `get_CXX()` does not seem to work properly.

Run the sample code of stan written in [RStan Getting Started](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started), it will get the following warning message.

Warning message:
```r
'C:/rtools40/usr/mingw_/bin/g++' not found
```

However, even with this error message, the calculation seems to be working properly, but I can't say anything about the calculation results because I don't know much about stan.

#### Description:
g++, which is referenced by `get_CXX()`, will look like `C:/rtools40/usr/mingw_/bin/g++` in Rtools40, for example, if you have installed Rtools40 in drive C with default settings. As for the directory structure, the directory that should be referenced is `C:/rtools40/mingw64/bin/g++` in the 64bit version.

In Rtools35 and earlier, `C:/Rtools/usr/mingw_64/bin/g++` is the directory to which g++ should be referenced, so I think this is due to the changes here.

By the way, under my environment (Windows 10 x64 (build 19042)), the number of bits of OST that is behaving in `Sys.getenv('WIN')` is not referenced correctly.
There are some cases on the Internet where people are having trouble with `C:/rtools40/usr/mingw_/bin/g++` being referenced, which may possibly be due to this, but I haven't investigated this far.

However, the environment variables of other (older) versions of Windows have not been examined, so it is possible that this code will behave correctly, but it is untested.

#### An idea of a solution:
```r
get_CXX <- function(CXX14 = TRUE) {
  if (.Platform$OS.type != "windows")
    return (system2(file.path(R.home(component = "bin"), "R"),
                    args = paste("CMD config", ifelse(CXX14, "CXX14", "CXX11")),
                    stdout = TRUE, stderr = FALSE))
  
  ls_path <- Sys.which("ls")
  if (ls_path == "")
    return(NULL)
  
  if(as.numeric(version$major) <4){
    install_path <- dirname(dirname(ls_path))
    file.path(install_path,
              paste0('mingw_', Sys.getenv('WIN')), 'bin', 'g++')
  }else{
    install_path <- dirname(dirname(dirname(ls_path)))
    
    R_running <- if(grepl(pattern = 64, version$arch)) 64
    else 32
    
    file.path(install_path,
              paste0('mingw', R_running), 'bin', 'g++')
  }
}
```

This way, I think you can specify and reference g++ as intended with `get_CXX()`.
However, if I recompile `{rstan}` including this code, I get other errors when I run stan.

Warning message:
```r
 'config' variable 'CPP' is deprecated
```

I think this is a similar example to #862.
This in itself, as pointed out in the said ISSUE.
`CPP < -system2(file.path(R.home(component = " bin"), " R"), args = " CMD config CPP")` "CMD config CPP"  is the problem, I think.

Since "CMD config CPP" is not defined, if I change it to "CMD config CXX14" or something like that, I can find g++, but I still get other errors.

```r
system(paste(CPP, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) is: 
  '0' not found
```

It may be due to `ARGS`, but I am not sure about the details due to my lack of understanding about R CMD, C++ and many other things.

#### RStan Version:
rstan_2.21.3

#### R Version:
R 4.1.0

#### Operating System:
Windows 10 x64 (build 19042)

**Comment by andrjohns** [comment]
Thanks for the report and looking into this! We're actually already aware of the issue and it has been patched for the next release
