### ISSUE TITLE
Error in open.connection(con, open = mode) : Timeout was reached: [github.com]

### ISSUE THREAD

**Issue by Fyedka** [stan-dev/rstan#948]
#### Summary:
I am receiving this type of error (with slight variations, as shown in Current Output, below) in the R console during the warmup portion of sampling during the execution of a `stan` function call:
```
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github.com] Operation timed out after 13129 milliseconds with 0 out of 0 bytes received
```
I get why it would have trouble connecting (I'm behind a pretty strict firewall at work), but I don't understand why it's trying to connect in the first place or whether this is affecting the sampling progress (which seems to be way too slow, relative to the estimates from the chains).

#### Description:
I coded a sizeable model in a .stan file and then called the RStan function `stan` to compile and sample from it.  After it had been attempting to sample for about an hour I got a series of error/warning messages (see Current Output, below). There is no termination of the script; it still shows as running in R.

#### Reproducible Steps:
The .stan and .r files involved are attached at the link below.  I am unfortunately not allowed to attach the input data, as it is the property of my employer and not myself.
[draft_cda2_ohi_analysis_2.zip](https://github.com/stan-dev/rstan/files/6704315/draft_cda2_ohi_analysis_2.zip)

#### Current Output:
```
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github.com] Operation timed out after 13129 milliseconds with 0 out of 0 bytes received
In addition: Warning message:
In system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'C:/rtools40/usr/mingw_/bin/g++' not found
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github.com] Operation timed out after 13328 milliseconds with 0 out of 0 bytes received
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github-releases.githubusercontent.com] Connection timed out after 38982 milliseconds
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github.com] Resolving timed out after 14366 milliseconds
Error in open.connection(con, open = mode) : 
  Timeout was reached: [github.com] Operation timed out after 14470 milliseconds with 0 out of 0 bytes received
```
The second warning is nothing new - I get that every time and it doesn't affect anything. It's the other output I'm concerned about.

#### Expected Output:
N/A

#### RStan Version:
2.21.2

#### R Version:
R version 4.1.0 (2021-05-18)

#### Operating System:
Windows 10 Enterprise, OS Build 19041.985

**Comment by RICCA-F** [comment]
Hi, I am in the same trouble as yours. The samplling progress is too slow. I wanna if you have already solve the problem? How can I speed up the sampling progress?

**Comment by andrjohns** [comment]
See this post on the forum for an explanation and fix: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/5

**Comment by RICCA-F** [comment]
> See this post on the forum for an explanation and fix: https://discourse.mc-stan.org/t/error-in-open-connection-con-open-mode-timeout-was-reached-github-com/23162/5

It's help. Thanks a lot.
