### ISSUE TITLE
Update getting started page with info about versions after 2.21

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/rstan#971]
Here's the current getting started page, which is linked from the github readme, from https://mc-stan.org/users/interfaces/rstan, and from elsewhere.
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

It says that 2.21.1 is the latest version, and provides (only) the following installation instructions:
```
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
```

A fair amount of discourse traffic now involves re-posting instructions for installing later versions of rstan for users who are confused about their inability to find newer features. I suggest editing the getting started page to explain the existence of a branch that is way ahead of CRAN and to provide the following instructions for users who want an updated `rstan`.  

```
# Uncomment the next line if you have previously installed rstan
# remove.packages(c("StanHeaders", "rstan"))
install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

I realize that everybody hopes this will be moot soon, but without an imminent end in sight I think it would be worth nudging confused users in the right direction and giving us a stable and authoritative source to link to from discourse.

**Comment by jgabry** [comment]
Yeah if a lot of users would benefit from the "experimental" branch it could be good to include that in the getting started page instead of forcing them to ask questions on the forum. I haven't been involved in the "experimental" branch development so I'll leave the decision of whether and how to mention it to  @andrjohns @hsbadr @bgoodri and anyone else who has been working on it.

**Comment by lionel68** [comment]
Was having issue reaching rstan_2.26 or above on Windows and this easy fix made my day, thx @jsocolar !

**Comment by jgabry** [comment]
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#latest-development-version-226x---unreleased (feel free to make edits)
