### ISSUE TITLE
Error in dyn.load(libLFile) (upd: issue is with RcppParallel, not with Rstan)

### ISSUE THREAD

**Issue by barracuda156** [stan-dev/rstan#979]
Could someone advise me on the following error:

> library(rstan)
Loading required package: StanHeaders
Loading required package: ggplot2
rstan (Version 2.21.2, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
Warning message:
In file(con, "r") :
  cannot open file '/var/db/timezone/zoneinfo/+VERSION': No such file or directory
> sink("bernoulli.stan")
> cat("
+ data { // data provided by the user
+ int<lower=1> N;
+ int<lower=0, upper=1> x[N];
+ }
+ parameters { // parameters to be inferred
+ real<lower=0, upper=1> theta;
+ }
+ model { // probability model
+ for (i in 1:N) {
+ x[i] ~ bernoulli(theta);
+ }
+ }
+ ",fill=T)
> sink()
> x_dat <- list(N = 10, 
+ x = c(1,1,1,0,0,1,0,0,1,0))
> fit0 <- stan(file = 'bernoulli.stan', data = x_dat, 
+ iter = 1000, chains = 4)
Error in dyn.load(libLFile) : 
  unable to load shared object '/var/folders/rD/rDeCM6SDHv8daLCecrRmrU+++TI/-Tmp-//RtmpTqVb7G/file3e7b3ef33ae3.so':
  dlopen(/var/folders/rD/rDeCM6SDHv8daLCecrRmrU+++TI/-Tmp-//RtmpTqVb7G/file3e7b3ef33ae3.so, 6): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /var/folders/rD/rDeCM6SDHv8daLCecrRmrU+++TI/-Tmp-//RtmpTqVb7G/file3e7b3ef33ae3.so
  Reason: image not found
Error in sink(type = "output") : invalid connection

RcppParallels is built and installed. From what I understand, it has its own version of TBB, however for whatever reason Rstan does not load it.
(Building standalone TBB fails on PowerPC, at least as of now, so that is not an option.)

Basic Rcpp functionality works:

> fx <- inline::cxxfunction( signature(x = "integer", y = "numeric" ) , '
+ return ScalarReal( INTEGER(x)[0] * REAL(y)[0] ) ;
+ ' )
> fx( 2L, 5 )
[1] 10

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)
Running under: OS X Snow Leopard 10.6

Matrix products: default
BLAS:   /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.utf-8/en_US.utf-8/en_US.utf-8/C/en_US.utf-8/en_US.utf-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.21.2         ggplot2_3.3.5        StanHeaders_2.21.0-7
[4] Rcpp_1.0.7.3         inline_0.3.19       

loaded via a namespace (and not attached):
 [1] pillar_1.6.4       compiler_4.1.2     prettyunits_1.1.1  tools_4.1.2       
 [5] pkgbuild_1.2.1     lifecycle_1.0.1    tibble_3.1.6       gtable_0.3.0      
 [9] pkgconfig_2.0.3    rlang_0.4.12       DBI_1.1.1          cli_3.1.0         
[13] parallel_4.1.2     loo_2.4.1          gridExtra_2.3      withr_2.4.3       
[17] dplyr_1.0.7        generics_0.1.1     vctrs_0.3.8        stats4_4.1.2      
[21] grid_4.1.2         tidyselect_1.1.1   glue_1.5.1         R6_2.5.1          
[25] processx_3.5.2     fansi_0.5.0        purrr_0.3.4        callr_3.7.0       
[29] magrittr_2.0.1     matrixStats_0.61.0 scales_1.1.1       ps_1.6.0          
[33] ellipsis_0.3.2     assertthat_0.2.1   colorspace_2.0-2   utf8_1.2.2        
[37] RcppParallel_5.1.4 munsell_0.5.0      crayon_1.4.2

**Comment by barracuda156** [comment]
@andrjohns @WardBrian Could you please help me a bit? Just with an advice, I can make a fix locally in MacPorts.
(MacPorts generally does not work well with `rpaths`, this issue is not arch-specific. Everything works robustly with absolute paths, normally.)

The issue is still relevant: https://github.com/easystats/modelbased/issues/259

P. S. To update on the initial report, now we do have OneTBB building on all relevant systems and archs (including PowerPC), so it is possible to use it instead of RcppParallel, if preferable.

**Comment by bob-carpenter** [comment]
@barracuda156.  If you need advice on Stan the best place to write in is the Stan Forums:  https://discourse.mc-stan.org

You may find it easier to use `cmdstanr`, as it doesn't have the same kind of deep binary dependency as RStan and also keeps up to date with Stan (CRAN is a serious bottleneck for RStan due to their restrictive size policy and lack of dependency management).

**Comment by barracuda156** [comment]
@bob-carpenter Well, the issue happens specifically with Rstan, so I thought it is an appropriate place to ask here.

`cmdstanr` may not be easy, since last time I looked into that it was necessary to write the build implementation for it more or less from scratch. And I have no idea how to do it from within `R`.
Outside of `R` it should be feasible, but gonna require a lot.

**Comment by bob-carpenter** [comment]
No worries. The issue tracker is for bug reports or feature requests, which is why I closed. cmdstanr is much easier to install than rstan. The package installs through github, then it has commands to install cmdstan from within cmdstanr. See the cmdstanr getting started page.

**Comment by barracuda156** [comment]
@bob-carpenter Some not working correctly fits a definition of a bug, IMO.
If it is technically impossible to link to TBB correctly, at least there should be a configure argument to do that from the user side.
I readily believe that it works correctly on a specific setup, but why not make it work robustly, on any coherent setup?

Re `cmdstanr`, though this is directly unrelated to the ticket: there are numerous reasons why a build which is not configurable may either fail or simply install in way which is not desired.

I will be happy to have `cmdstan` in MacPorts, whether via R or standalone, but I need installation instructions (assuming a build from source). If it is there, that is doable. But installing a complex OCaml software from within R sounds complicated :) 
If `cmdstanr` can be configured to use pre-installed Stanc3, OneTBB and whatever else it wants, then it easy, and I can make a port for it by tomorrow. Can it?

**Comment by andrjohns** [comment]
> If it is technically impossible to link to TBB correctly, at least there should be a configure argument to do that from the user side.\nI readily believe that it works correctly on a specific setup, but why not make it work robustly, on any coherent setup

"Technically impossible" is a bit of an exaggeration. The RcppParallel package has had instructions for [linking against system/external TBB installations](https://github.com/RcppCore/RcppParallel#intel-tbb) for several years now, which is used to distribute both `RcppParallel` and `rstan` across a wide range of Linux distros and architectures

**Comment by barracuda156** [comment]
> > If it is technically impossible to link to TBB correctly, at least there should be a configure argument to do that from the user side.\nI readily believe that it works correctly on a specific setup, but why not make it work robustly, on any coherent setup
> 
> "Technically impossible" is a bit of an exaggeration. The RcppParallel package has had instructions for [linking against system/external TBB installations](https://github.com/RcppCore/RcppParallel#intel-tbb) for several years now, which is used to distribute both `RcppParallel` and `rstan` across a wide range of Linux distros and architectures

@andrjohns Thank you, this is helpful. We were using bundled TBB, but we can certainly switch to using our standalone one (and that was already done for `quanteda`, for example, since it dropped RcppParallel support).

**Comment by andrjohns** [comment]
> @andrjohns Thank you, this is helpful. We were using bundled TBB, but we can certainly switch to using our standalone one (and that was already done for quanteda, for example, since it dropped RcppParallel support).

Also note that `rstan` isn't responsible for TBB linking, it simply [uses the flags provided by `RcppParallel`](https://github.com/stan-dev/rstan/blob/50c3c6f4e44a849b17af7e9e2b8656cd93238a18/rstan/rstan/R/plugin.R#L123).

**Comment by barracuda156** [comment]
> > @andrjohns Thank you, this is helpful. We were using bundled TBB, but we can certainly switch to using our standalone one (and that was already done for quanteda, for example, since it dropped RcppParallel support).
> 
> Also note that `rstan` isn't responsible for TBB linking, it simply [uses the flags provided by `RcppParallel`](https://github.com/stan-dev/rstan/blob/50c3c6f4e44a849b17af7e9e2b8656cd93238a18/rstan/rstan/R/plugin.R#L123).

@andrjohns You have pinpointed the exact cause of the issue:
```
macmini:~ svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/RcppParallel/lib/libtbb.dylib
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/RcppParallel/lib/libtbb.dylib:
	@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.30.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

For some reason this still works in most cases, including building `rstan` itself, but fails here. We can just use `install_name_tool` to fix the install path of `libtbb.dylib`, and that shouls solve the problem.

(This is on a different machine with the outdated `R`, but I believe, it is the same in terms of `rpath` being set.)

**Comment by bob-carpenter** [comment]
> Some not working correctly fits a definition of a bug, IMO.

Sorry if I misunderstood.  It looked like an install error to me, not a bug report.  If you think there is something specific we need to fix in the RStan code base, please re-open the issue.

**Comment by barracuda156** [comment]
@bob-carpenter Turned out that it is caused by an rpath being set in RcppParallel, so it is not Rstan bug. I don’t see anything wrong in using flags as RcppParallel reports them.

I will try fixing it today on RcppParallel port side and verify if Rstan then works as expected.

**Comment by bob-carpenter** [comment]
This is always tricky.  If we use a package that itself has a bug, it's in some sense our responsibility to take care of that.  The configuration stuff through all these packages on different platforms is really hard to stay on top of given different compute environments people have.  It's all fun and games on people's personal notebooks they can wipe, and gets increasingly difficult with more esoteric configs, IT-department managed machines, and with locked-down clusters.  

If there's some advice you have after doing this for RStan users, we can report it on the forums to try to make it indexable and also include in the docs.

Thanks for your patience.

**Comment by barracuda156** [comment]
>  If we use a package that itself has a bug

Using rpaths is not wrong in itself, it is just not guaranteed to work. I am not really sure why `rstan` (or any dependent of `RcppParallel`) do not fail to load during build (`R` verifies that a package loads, if not, build gonna fail), and apparently most of those packages can be used (at least I certainly ran tests for quite a number of them, and if nothing would even load, it could not have gone unnoticed). Maybe the issue is in how `RcppParallel` communicates its flags?

In principle I would expect that _provided_ TBB is somehow found during the build of `rstan` and build completes successfully, the same should work for models which `rstan` compiles. However it is really my mistake that I did not notice that rpath in `RcppParallel`.

From my side I would like to see transparent [non-default] options to configure everything, even if the default build does not require any manual setup and works in vanilla CRAN environment. That makes it easy to fix possible issues without burdening upstream and without local hacks (which then require ongoing rebasing of patches).

> If there's some advice you have after doing this for RStan users, we can report it on the forums to try to make it indexable and also include in the docs.

Perhaps it makes sense to add a caution somewhere in documentation, that may save both users’ and your time. Maybe just make people aware of a possible failure – I do not have a fix for it (I could not find what exactly sets rpath in that package, and its build system is a nightmarish and buggy – not from R package side, but originally, from TBB itself).

I think it is pointless to try reporting `RcppParallel` issue to CRAN, since they tend to hold a view that if something works in their environment, that is sufficient. As long as that is an official position, any failures in alternative setups are not bugs: they are defined out :) 

P. S. By the way, for some reason `install_name_tool` trick failed for me with `RcppParallel` with some odd error; so I decided it is better to switch to using an external OneTBB instead. Many hours of rebuilding 80+ dependents of `RcppParallel` ahead LOL

**Comment by andrjohns** [comment]
But is there a reason for packages installed through MacPorts to not handle `rpaths` correctly? The OS, compiler, and all programs involved should support `rpaths` without issue, it's only MacPorts that is having the problem

**Comment by barracuda156** [comment]
> But is there a reason for packages installed through MacPorts to not handle `rpaths` correctly? The OS, compiler, and all programs involved should support `rpaths` without issue, it's only MacPorts that is having the problem

AFAIK, rpaths are meant for macOS bundles (where everything gets dumped in a single location, and an app is supposed to be movable) and not for Unix-style installations (user is not supposed to pull binaries randomly around). I am sure it is possible to force them to work in any environment, but why use a setup which is known to be fragile when absolute paths work perfectly well and do not require any trickery?

P. S. I am not sure if in this particular case it is MacPorts not handling rpaths correctly (it _can_ be, but it has to be shown still). What I meant is that from experience using rpaths is prone to failures and it is not advisable for the setup we are using. However we do not do anything special to break software using rpaths, of course, and given that numerous ports were building against RcppParallel which used rpath for TBB, it did work in most or at least large number of cases.

**Comment by andrjohns** [comment]
`rpaths` are also used extensively in unix-style installations as well (the TBB and RcppParallel use the exact same flags on linux/unix).

But it's less about whether or not `rpaths` themselves are fragile - the only difference in this case between the linking working or not is whether MacPorts was used. If everything works without issue using Xcode or Homebrew compilers, but not MacPorts, shouldn't that be investigated/fixed instead of asking downstream packages to patch their builds?

**Comment by barracuda156** [comment]
> But it's less about whether or not rpaths themselves are fragile - the only difference in this case between the linking working or not is whether MacPorts was used.

To establish this, we will need at least to reproduce the same installation without MacPorts involvement, that is, build everything manually with the same directory structure. It is a bit involving.

> If everything works without issue using Xcode or Homebrew compilers

(Xcode compilers do not support OpenMP, so they won’t work neatly with R.)

It is not hugely surprising though if Homebrew works, since numerous CRAN packages explicitly rely on Homebrew, configure scripts are using brewisms etc. This is not a bug in MacPorts if CRAN decides to pick a single package manager and ignore all alternatives. Admittedly, this is not rpath-specific, but if you try to run default builds of such packages outside of Homebrew environment, things break down badly.
One the other hand, if one uses our ports in our environment, everything also gonna “just work” (at least for R, on systems which we test).

> the TBB and RcppParallel use the exact same flags on linux/unix

I do not think so: https://github.com/RcppCore/RcppParallel/blob/3756f5b5b6d6948ae6e78771a314faef5e62476c/src/Makevars.in#L115-L117
And this is perhaps working fine on Linux, but it does not work fine with Apple linker: https://github.com/RcppCore/RcppParallel/blob/3756f5b5b6d6948ae6e78771a314faef5e62476c/src/Makevars.in#L15-L17 (so it should not use the same flags in fact). Mac version will be `PKG_LIBS = -Wl,-L"$(TBB_LIB)" -Wl,-rpath,"$(TBB_LIB)" -ltbb -ltbbmalloc` – otherwise linking may fail.
