### ISSUE TITLE
Error in declaring variables by `array` in R

### ISSUE THREAD

**Issue by JinghongZeng** [stan-dev/rstan#980]
#### Summary:
R returns an error message saying that declaring a variable should not begin with `array[]`.

#### Description:
I want to fit a normal model using observed data and impute missing values from the same normal distribution with parameter estimates obtained from the observed data. I declared the observed data in the data block as a one-dimensional `array`, and the missing variables in the parameters block as a one-dimensional `array`. But after running the code, an error occurred since `array` can't be used to declare variables.

#### Reproducible Steps:
Below is R code to impute 100 missing variables. This task is the same as an [example](https://mc-stan.org/docs/2_28/stan-users-guide/missing-data.html) in the Stan manual. And an error occurred.
```
stancode <- "
data {
  int<lower=0> N_obs;
  int<lower=0> N_mis;
  array[N_obs] real y_obs;
}
parameters {
  real mu;
  real<lower=0> sigma;
  array[N_mis] real y_mis;
}
model {
  y_obs ~ normal(mu, sigma);
  y_mis ~ normal(mu, sigma);
}
"
y=rnorm(100, 2, 10)
fit <- stan(model_code = stancode, data = list(N_obs=100, N_mis=100, y_obs=y), seed = 320, chain_id = 4)
```

The error is as below:
<img width="841" alt="rstan output" src="https://user-images.githubusercontent.com/86920951/145350425-0365146e-bd74-412c-a432-3f02c2fb620d.png">

However, if I declared the variables using `vector`, the results were good.
```
stancode <- "
data {
  int<lower=0> N_obs;
  int<lower=0> N_mis;
  vector[N_obs] y_obs;
}
parameters {
  real mu;
  real<lower=0> sigma;
  vector[N_mis] y_mis;
}
model {
  y_obs ~ normal(mu, sigma);
  y_mis ~ normal(mu, sigma);
}
"
y=rnorm(100, 2, 10)
fit <- stan(model_code = stancode, data = list(N_obs=100, N_mis=100, y_obs=y), seed = 320, chain_id = 4)
```

Is this because `array` can't be used anymore?

#### RStan Version:
The version of RStan I'm running is 2.21.2.

#### R Version:
The version of R I'm running is R version 4.1.2 (2021-11-01).

#### Operating System:
My operating system is macOS Monterey, version 12.0.1.

**Comment by bob-carpenter** [comment]
Thanks for reporting, @JinghongZeng.  

The issue arises because RStan is running an older version of Stan before the `array[N]` syntax was introduced.  We're working on trying to get RStan updated, but it's a wrestling match with very restrictive CRAN policies on package size and dependency management.  I believe Rstan is up to Stan 2.16.  We just updated the user's guide to indicate when features were introduced, but we also changed all the syntax to match the latest Stan.  The easiest thing to do is to use older versions of our docs, all of which are still available.

In the meantime, you might want to check out cmdstanr, as that keeps up to date because it's just a lightweight wrapper around CmdStan.

**Comment by guemues** [comment]
As RStudio syntax checking uses Rstan package, it will be very hard to use Rstudio syntax checking for stan > 2.32.

**Comment by bob-carpenter** [comment]
We have a bunch of syntax checkers/highlighters that we struggle to keep up to date and versioned.  The RStudio syntax checker is one of those plug ins.  It's not directly tied to RStan, but there's an issue of what to do now that rstan has fallen so far behind cmdstanr and cmdstan.  The reason RStan fell behind, by the way, is restrictive CRAN policies.  

This is a particularly big issue with the new array syntax.  The old array syntax is deprecated and will be removed in a year.  We're including reformatter that will automatically let you translate older models into the new syntax.

**Comment by ssp3nc3r** [comment]
To workaround this issue, I've been using some scripts that load when `RStudio` launches that switch syntax checking from `RStan` to `cmdstanr`. I have the following, written by others, in my` .Rprofile`:

```
## WORKAROUND: https://github.com/rstudio/rstudio/issues/6692
## Revert to 'sequential' setup of PSOCK cluster in RStudio Console on macOS and R 4.0.0
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

## modified version of function initially written by Mike Lawrence
check_cmdstanr_syntax <- function (file, pedantic = FALSE) {
  if (!requireNamespace("fs", quietly = TRUE)) {
    stop("Please install the 'fs' package using 'install.packages('fs')'")
  }
  if (!requireNamespace("stringr", quietly = TRUE)) {
    stop("Please install the 'stringr' package using 'install.packages('stringr')'")
  }
  if (!requireNamespace("processx", quietly = TRUE)) {
    stop("Please install the 'processx' package using 'install.packages('processx')'")
  }
  check_wd <- fs::dir_create('syntax_check')
  code_file <- fs::path(file)
  mod_name <- fs::path_ext_remove(code_file)
  stanc_syntax_check_run = processx::run(
    command = fs::path(cmdstanr::cmdstan_path(), cmdstanr:::stanc_cmd()),
    args = c(
      code_file,
      "--include-paths",
      ".",
      if (pedantic) "--warn-pedantic",
      "--warn-uninitialized",
      "--name",
      mod_name,
      "--o",
      tempfile()
    ),
    wd = fs::path_dir(check_wd),
    error_on_status = FALSE
  )
  stderr <- stanc_syntax_check_run$stderr
  syntax_check_passed <- !((stderr != "") | (stanc_syntax_check_run$stdout != ""))
  if (!syntax_check_passed) {
    stanc_syntax_check_run$stdout = stringr::str_remove_all(stanc_syntax_check_run$stdout, stringr::fixed("./"))
    stanc_syntax_check_run$stdout = stringr::str_replace_all(stanc_syntax_check_run$stdout, "Info: ", "\nInfo:\n")
    cat(paste0("\033[34m", stanc_syntax_check_run$stdout), "\n\n", sep = "")
    cat(paste0("\033[31m", stanc_syntax_check_run$stderr), "\n",  sep = "")
  }
  else {
    cat(paste0("\033[34m","  ✓ Syntax check passed\n"))
  }
  if (sys.parent() == 0) {
    return(invisible(NULL))
  }
  else {
    return(invisible(syntax_check_passed))
  }
}

if (length(find.package("rstan", quiet = TRUE))) {
  rstan_rstudio_stanc_code = "function (filename) {return(check_cmdstanr_syntax(filename))}"
  utils::assignInNamespace("rstudio_stanc", eval(parse(text = rstan_rstudio_stanc_code)), 
                           ns = "rstan", envir = as.environment("package:rstan"))
  
  rstan_stanc_builder_code = "function (file) {return(invisible(NULL))}"
  utils::assignInNamespace("stanc_builder", eval(parse(text = rstan_stanc_builder_code)), 
                           ns = "rstan", envir = as.environment("package:rstan"))
}

```
