### ISSUE TITLE
rstan/Stanheaders 2.26.? fail with existing *.rds file

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstan#993]
I tested StanHeaders and rstan from https://mc-stan.org/r-packages/ and from StanHeaders_2.26 branch. 

If the directory has, e.g. `binom.stan` and old `binom.rds` when running `stan_mode(file='binom.stan')`, I get an error
```
> Error in if (!file.exists(file.rds) || (mtime.rds <- file.info(file.rds)$mtime) <  : 
  missing value where TRUE/FALSE needed
```
removing `binom.rds' helps (but it took a long time to figure out)

**Comment by hsbadr** [comment]
It seems that `packageDescription("rstan")$Date` returns `NULL`. So, we'd need to use `packageDate("rstan")` at
https://github.com/stan-dev/rstan/blob/f72e7d7fbdf0141ddcfb27267dd9447943ada623/rstan/rstan/R/rstan.R#L105

**Comment by hsbadr** [comment]
@avehtari Can you test the `experimental` branch at be943ac9e642ec6f466416cda31db68af550c10b?

**Comment by avehtari** [comment]
I tried, but I'm having installation issues
```
g++: error: /home/ave/R/x86_64-pc-linux-gnu-library/4.1/rstan/lib//libStanServices.a: No such file or directory
make: *** [/usr/share/R/share/make/shlib.mk:10: rstan.so] Error 1

```
I guess something got messed up, but it may take time before I get this tested

**Comment by hsbadr** [comment]
> I tried, but I'm having installation issues

Well, you may use the prebuilt packages from the artifacts at https://github.com/stan-dev/rstan/actions/runs/1962869682. It includes sources packages and binaries for common systems, including Ubuntu.

**Comment by avehtari** [comment]
It seems restarting R solved it, so probably some lock issue.
Works now, thanks!

**Comment by hsbadr** [comment]
> Works now

Great! Is it worth a new release? I'd wait for a few more fixes.
